contrib/pkg/clusterpool/clusterpool.go, contrib/pkg/createcluster/create.go
Redirect no longer exists for `openshift-release.svc.ci.openshift.org`.
=> Update default release image URL.

pkg/controller/velerobackup/helpers_test.go, pkg/controller/velerobackup/velerobackup_controller_test.go, pkg/test/clusterdeployment/clusterdeployment.go, pkg/test/syncset/syncset.go
Several tests were using DeepEquals (under testify's `assert.Equal`) to compare a runtime.Object from the (fake) kube server to a locally-constructed expected value. This is brittle, as fields such as ResourceVersion cannot be relied on to have predictable values.
Commit c7d60527612c141f58d748b8bf2e25d72f9499d5 in #1407 worked around the problem by explicitly setting the ResourceVersion to the value set by the fake kube server in controller-runtime 0.8.x. This PR has two commits:
- Revert that workaround;
- Switch to a comparison that disregards ResourceVersion and TypeMeta.
=> Fix velerobackup tests for DeepEquals

pkg/controller/remotemachineset/awsactuator.go, pkg/controller/remotemachineset/awsactuator_test.go, pkg/controller/remotemachineset/gcpactuator_test.go, pkg/controller/remotemachineset/remotemachineset_controller.go, pkg/controller/remotemachineset/remotemachineset_controller_test.go, pkg/controller/utils/conditions.go
As per kube api guidelines, conditions should be placed by the controller as soon as possible, to indicate that it has began processing the resource. If a decision cannot be made regarding the status of the condition at that time, it can be set to Unknown.
This PR initializes MachinePool conditions, and ensures conditions do not have to be "True" to be set for the first time.
xref: https://issues.redhat.com/browse/HIVE-1562
=> Initialize MachinePool conditions

apis/hive/v1/clusterdeployment_types.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/installconfigvalidation.go, pkg/controller/clusterdeployment/installconfigvalidation_test.go, pkg/test/clusterdeployment/clusterdeployment.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
In general we try not to fully validate install configs match what you
set in ClusterDeployment. In this particular case however, a region
mismatch will cause the cluster to keep provisioning machines in the
wrong region until your cloud quota is fully exhausted.
Add a minimal check to ensure the InstallConfig region matches the
cluster deployment for AWS, Azure, and GCP.
In the event of a problem, a ReadyToProvision condition on the
ClusterDeployment will go False. Hoping to use this condition to
consolidate a few others in this controller that are failing pre-flight
checks.
x-ref: https://issues.redhat.com/browse/HIVE-1337
=> Validate region in InstallConfig matches ClusterDeployment.

Dockerfile.hivebase
We stopped using this via https://github.com/openshift/release/pull/19191
=> Remove unused Dockerfile.hivebase

docs/enhancements/hivev2.md
Add a section to the Hive v2 enhancement doc proposing eliminating the VeleroBackup controller.
=> Hivev2: Get rid of VeleroBackup

.codecov.yml, Makefile, hack/codecov.sh
This commit adds
- a `coverage` make rule that runs
- a new codecov.sh script adapted from [the one OSD operators use](https://github.com/openshift/boilerplate/blob/f3c8c8d393f69f83ce9dbdbc0aa72d2e5b9e5d96/boilerplate/openshift/golang-osd-operator/codecov.sh); and
- a codecov configuration file, stolen directly from [the one OSD operators use](https://github.com/openshift/boilerplate/blob/f3c8c8d393f69f83ce9dbdbc0aa72d2e5b9e5d96/boilerplate/openshift/golang-osd-operator/.codecov.yml).
This is designed to be run in three modes: local, presubmit, and postsubmit.
- In all modes, it runs the go cover tool, scrubs out the stats for generated files, and writes the raw report to `coverage.out`.
- In local mode, that's it.
- Presubmit and postsubmit modes are intended for use in CI jobs, where …
=> Add code coverage script & make target

hack/e2e-test.sh
`IMAGE_FORMAT` is deprecated in favor of `dependencies` [1]. We have changed our CI config accordingly [2]. This commit removes it from e2e-test.sh; and adds some helpful error checking/messaging in case the script is run locally.
[1] https://docs.ci.openshift.org/docs/architecture/step-registry/#available-environment-variables
[2] https://github.com/openshift/release/pull/19300
=> e2e-test: Stop using `IMAGE_FORMAT`

pkg/controller/dnszone/dnszone_controller.go, pkg/controller/utils/errorscrub.go, pkg/controller/utils/errorscrub_test.go
While trying to get the actuator in dnszone controller, code was trying
to parse a re-assigned error variable, causing a panic
/assign @joelddiaz
=> Fix panic in dnszone controller

pkg/controller/hibernation/aws_actuator.go, pkg/controller/hibernation/aws_actuator_test.go, pkg/controller/hibernation/azure_actuator.go, pkg/controller/hibernation/azure_actuator_test.go, pkg/controller/hibernation/gcp_actuator.go, pkg/controller/hibernation/gcp_actuator_test.go, pkg/controller/hibernation/hibernation_actuator.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, pkg/controller/hibernation/mock/hibernation_actuator_generated.go
Currently when hibernation is in progress, the controller checks if all
machines for the cluster are in desired state (stopped when hibernating
and running when running). If all machines are not in that state, the
controller returns and retries after some timeout.
This means that there is no information from the controller about the
progress made and machines in mis-matched state.
With this change, when machines are in mis-matched state, we update the
Hibernating condition to include a message listing those machines.
xref: https://issues.redhat.com/browse/HIVE-1564
/cc @2uasimojo
=> hibernation: include machines in undesired state when hibernating/resuming

pkg/controller/clusterdeployment/clusterprovisions.go
x-ref: https://issues.redhat.com/browse/HIVE-1583
Per the Jira these details are not a good fit for exposing to users, and
can be removed.
=> Remove next provision details from ProvisionFailed condition.

apis/go.sum, go.sum, vendor/github.com/openshift/hive/apis/go.sum
For some reason these didn't start failing `verify` until after #1441 merged.
=> go.sum updates for go 1.16

pkg/controller/utils/errorscrub.go, pkg/controller/utils/errorscrub_test.go
When dns controller hits Invalid credentials on Azure cloud, Azure API
constantly tries to login and refresh the token. This results in
frequent update of dns condition for generic cloud errors.
While we do have rate limiter on cloud errors for dns, we can still
scrub the Azure error and bubble up only the error description. This
will make the error easier to interpret and restrict frequent status
updates.
xref: https://issues.redhat.com/browse/HIVE-1582
=> Scrub frequent Azure cloud dns errors

apis/hive/v1/clusterclaim_types.go, apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
To help consumers understand how Duration fields should be formatted, add a reference to the upstream documentation.
(This came out of a [slack conversation](https://coreos.slack.com/archives/CE3ETN3J8/p1626184245263600?thread_ts=1626144477.250800&cid=CE3ETN3J8) around the referenced card.)
[HIVE-1587](https://issues.redhat.com/browse/HIVE-1587)
=> Document Duration types better

apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/zz_generated.deepcopy.go, apis/hivecontracts/v1alpha1/zz_generated.deepcopy.go, apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml, pkg/clusterresource/builder.go, pkg/controller/argocdregister/argocdregister_controller_test.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/fakeclusterinstall/fakeclusterinstall_controller.go, pkg/controller/machinemanagement/machinemanagement_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go, vendor/github.com/openshift/hive/apis/hivecontracts/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go
Hive doesn't need this value, and we should not require users adopting
clusters to provide it.
/cc @lwan-wanglin
=> Make metadata admin password secret optional.

apis/hive/v1/clusterclaim_types.go, apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Add kubebuilder directives to validate Duration fields.
[HIVE-1587](https://issues.redhat.com/browse/HIVE-1587)
=> Enforce format of Duration fields

pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
Clusters that do not have clustersync object should be able to hibernate
xref: https://issues.redhat.com/browse/HIVE-1585
/cc @abutcher
=> Allow clusters without clustersync to hibernate

apis/hive/v1/aws/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, pkg/controller/remotemachineset/awsactuator.go, pkg/controller/remotemachineset/awsactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Per GCP support, the field is immutable for now.
x-ref: https://issues.redhat.com/browse/HIVE-1374
=> Add support for custom KMS key AWS disk encryption.

Makefile, config/operator/operator_role_binding.yaml, hack/e2e-test.sh
This commit fixes two things about our build-machinery-go includes:
- The `images.mk` include uses `ensure-imagebuilder`, which comes from `imagebuilder.mk`. We shouldn't have to include the latter explicitly. https://github.com/openshift/build-machinery-go/pull/50 is fixing that, but until that merges and we can vendor it in, include it explicitly.
- `ensure-kustomize` was working as far as it went, but it was installing kustomize into a subdirectory which is (usually) not in
`$PATH`, so things like `make deploy` were either breaking (bad) or picking up kustomize from somewhere else (potentially worse). Fix our usage of kustomize to ref the variable that `ensure-kustomize` sets up to point to the binary it installs. This is also a different version of kustomize (4.1.3) from what our e2e …
=> Fix build-machinery-go dependencies

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
i was investigating a [cluster provisioning delay](https://redhat.pagerduty.com/incidents/PP1XFXV) and this error was the cause
per [the SOP](https://github.com/openshift/hive-sops/blob/master/sop/ClusterProvisioningFailure.md#check-clusterdeployment-conditions), i opened this to add the error to the configmap
=> add a match for GCP CPU quota

apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/dnszone_types.go, config/crds/hive.openshift.io_dnszones.yaml, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/dnszone/dnszone_controller.go, pkg/controller/dnszone/dnszone_controller_test.go, pkg/controller/dnszone/test_helpers.go, pkg/test/clusterdeployment/clusterdeployment.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/dnszone_types.go
ClusterDeployment PreserveOnDelete is now being used to abandon stuck
deprovisions where a customer typically has revoked the cloud
credentials we have. It was discovered that if managed DNS was in play,
the DNS zone cleanup was still trying to use the AWS creds and getting
stuck.
CD controller will automatically transfer the clusters setting to the
DNS zone to allow it to remain independent and not require a CD to
exist.
=> Add PreserveOnDelete to DNSZones.

cmd/manager/main.go, cmd/operator/main.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
We were adding version v1beta1 of apiextensions to the scheme for the operator and manager. This is deprecated, and blows up if we try to run on OCP 4.9 where CRD v1beta1 has been removed. Cut over to version v1.
[HIVE-1598](https://issues.redhat.com/browse/HIVE-1598)
=> Add apiextensions s/v1beta1/v1/ to scheme

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
as seen in https://redhat.pagerduty.com/incidents/P6W7F8B , clusters can fail to install when the GCP service account quota is exceeded:
> iam.googleapis.com/quota/service-account-count is not available in global because
the required number of resources (5) is more than remaining quota of 0
this will catch that error in the installlog monitor
=> catch failures for iam.googleapis.com/quota/service-account-count quota

pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go
Previously, the ClusterRunning condition of ClusterClaim was being used to store the state of the assigned ClusterDeployment, *except* when the CD was deleted. We had a whole separate condition, ClusterDeleted, for that. This was particularly confusing in the summary output for ClusterClaim, which could show something like:
```
[efried@efried ~]$ oc get clusterclaim claim-gllgp
NAME          POOL                     PENDING          CLUSTERNAMESPACE               CLUSTERRUNNING   AGE
claim-gllgp   fake-ocp-4-7-amd64-aws   ClusterClaimed   fake-ocp-4-7-amd64-aws-m2kkp   Running          4m23s
```
...even when the ClusterDeployment was deleted.
The reasonable fix is to twiddling the ClusterRunning condition to:
```
{
"lastProbeTime": "2021-07-16T20:02:01Z",
"lastTransitionTime": …
```
=> claim: Consolidate ClusterDeleted into ClusterRunning

pkg/awsclient/client.go, pkg/awsclient/mock/client_generated.go, pkg/controller/hibernation/aws_actuator.go, pkg/controller/hibernation/aws_actuator_test.go, pkg/controller/hibernation/hibernation_actuator.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/mock/hibernation_actuator_generated.go
OpenShift supports running spot instances for compute. Therefore when
cluster is hibernated these instances must also be stopped and started
like the on-demand instances.
But due to the nature of the spot instances, these instances are not
guaranteed. So if these instances are started, these might not start if
the spot instance constraints are not met. Therefore aws supports
stopping and starting spot instances only when the spot instance request
are persistent (compared to one-time). see [1] for more info.
machine-api add support for spot instances in AWS detailed in [2].
Some of the things to note are,
- machine-api has decided that one spot instance in aws is tied to one
Machine object in api.
- which means, the spot instances are created as "one-time" type. Once
the backing instance …
=> hibernation: support hibernating spot instance for AWS clusters

cmd/manager/main.go, cmd/operator/main.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
We were still using v1beta1 of apiextensions. If we try to run on OCP 4.9 where CRD v1beta1 has been removed, this crashes the operator on startup while trying to add it to the scheme. This commit cuts over to apiextensions v1.
[HIVE-1598](https://issues.redhat.com/browse/HIVE-1598)
=> apiextensions s/v1beta1/v1/

hack/app_sre_create_image_catalog.sh
hack/app_sre_create_image_catalog.sh was grabbing the
hive-production v3 shard as the currently deployed hash,
and that's wrong because it's pinned to an old commit.
Use hivep01ue1's hash.
=> fix app-sre build script current hash grab

pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go
This is a UX improvement to reflect that a CD is deleting in the status of its assigned Claim: We set the ClusterRunning condition to False with Reason: ClusterDeleting.
Note that, although this triggers on both deletion timestamp and the `remove-claimed-cluster-from-pool` annotation, we are unlikely to notice in the latter case because the claim itself is deleted almost immediately in that code path. However, the code as written accounts for a future where that deletion may wait on some other finalizer.
=> Claim: Add ClusterRunning=>ClusterDeleting condition

hack/generate-operator-bundle-operatorhub.py, hack/generate-operator-bundle.py
Sort the list of CRDs when generating the CSV for the operator bundle, for easier diffing from one version to the next.
=> Make owned CRD order deterministic in CSV

pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
PR #1477 introduced a regression whereby it wouldn't start (non-fake) machines in most cases. Fix.
[HIVE-1606](https://issues.redhat.com/browse/HIVE-1606)
=> Actually start hibernated machines

apis/hive/v1/hiveconfig_types.go, config/crds/hive.openshift.io_hiveconfigs.yaml, docs/awsprivatelink.md, hack/awsprivatelink/vpc.cf.yaml, pkg/awsclient/client.go, pkg/awsclient/mock/client_generated.go, pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Currently the private link controller creates an ALIAS record in the PHZ
created for customer's cluster. This record points enables the dns
resolution of customer clsuters k8s API to the VPC endpoint, therefore
allowing hive to transparently accessing the cluster over the private
link.
In some cases the ALIAS record cannot be used. For example, in GovCloud
environments the Route53 private hosted zones do not support ALIAS
record type and therefore we have to use A records.
CNAME records would have been more suitable replacement for ALIAS
records, but
CNAME records cannot be created at the apex of a DNS zone like ALIAS
records. see https://stackoverflow.com/a/20230670
The private link architecture uses a DNS zone like
`api.<clustername>.<clusterdomain>`
so that there is no conflicts with …
=> hiveconfig: allow choosing dns record type for private link

Makefile, hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
[HIVE-1605](https://issues.redhat.com/browse/HIVE-1605)
=> Introduce e2e-pool test

pkg/controller/hibernation/hibernation_controller.go
Scrub condition message to exclude the request id:
```
- lastProbeTime: "2021-08-04T19:45:34Z"
lastTransitionTime: "2021-08-04T14:48:13Z"
message: "Failed to start machines: AuthFailure: AWS was not able to validate
the provided access credentials\n\tstatus code: 401, request id: 5cf337cf-c70d-4a8a-87e0-4a08d3cca2f0"
reason: FailedToStart
status: "True"
type: Hibernating
```
=> ErrorScrub message in setHibernatingCondition to remove AWS request_id.

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Previous attempt only tested against installing clusters, which is
bypassed if the cluster is already installed.
Move the sync of PreserveOnDelete prior to both portions of the
reconcile loop.
x-ref: https://issues.redhat.com/browse/HIVE-1594
=> Fix transfer of PreserveOnDelete to DNSZone for installed clusters.

apis/hive/v1/clusterclaim_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go
This was missed in a747efe7b / #1460, where use of this const was removed.
=> Remove obsolete ClusterClaimClusterDeletedCondition

config/templates/hive-csv-template.yaml, docs/developing.md
This commit adds the annotation to the CSV generated for OperatorHub,
that would hide the following Hive CRs from the UI
- ClusterSync
- ClusterSyncLease
- FakeClusterInstall
- Checkpoints
- ClusterDeprovision
- ClusterProvision
- ClusterState
- MachinePoolLease
The annotation added is
`operators.operatorframework.io/internal-objects` as per [OpenShift Docs](https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs)
xref: https://issues.redhat.com/browse/HIVE-1575
/cc @2uasimojo
=> Hide internal crs

pkg/controller/utils/errorscrub.go, pkg/controller/utils/errorscrub_test.go, pkg/remoteclient/remoteclient.go
Still lightly hotlooping because of the current time in this error message. 
We need to look into Abhinav's don't update if the reason hasn't changed for more controllers, but this should be a quick fix today for Monday's push.
=> Scrub errors for clusters unreachable due to cert dates.

Makefile, hack/app-sre/generate-saas-template.py, hack/app-sre/kustomization.yaml, hack/app-sre/saas-template-stub.yaml, hack/app-sre/saas-template.yaml
New `make` targets:
- `build-app-sre-template`: Makes sure hack/app-sre/saas-template.yaml is up to date with the current state of the repo. More below.
- `verify-app-sre-template`: Added to the `verify` chain. Makes sure the above has been run.
The `build-app-sre-template` target
- Syncs the resources in the new `kustomization.yaml` to make sure we're picking up all the CRDs under config/crds. The kustomization makes sure the template will contain variables, which will be substituted by app-sre via `oc process`, for the URI of the container image in the deployment.
- Uses that kustomization to generate/overwrite the new `saas-objects.yaml` to contain all the objects we wish to deploy via
app-sre.
- Runs the new `generate-saas-template.py` script, which melds the `saas-objects.yaml` with …
=> Add templates, scripts, targets for OLM-less deploy

pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go
To avoid timing issues and properly count assigned ClusterDeployments and ClusterClaims, this commit moves the assignment of ClusterClaims (updating their reference to their assigned CD) from the clusterclaim_controller into the clusterpool_controller, right next to the assignment of ClusterDeployments (updating their reference to their assigned ClusterClaim).
It also adds code to double-check that assignments are in sync (claims assigned to the clusters that ref them, and vice versa) before proceeding with pool math and further assignments. This should help eliminate assignment conflicts, and "heal" partial updates (e.g. assigning the claim succeeds, but assigning the CD fails).
[HIVE-1599](https://issues.redhat.com/browse/HIVE-1599)
=> Consolidate claim assignment into clusterpool_controller

pkg/controller/argocdregister/argocdregister_controller.go
https://issues.redhat.com/browse/HIVE-1625
=> Include CertData, KeyData in TLSClientConfig for ArgoCD cluster.

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
It is a common problem that STS-mode clusters have something
wrong with the operator roles -- typically they're bound to
the wrong (old) OIDC provider. The first place an install notices
that is when machine-api tries to create the workers.
=> add NoWorkerNodes to install-log-regexes-configmap

apis/hive/v1/clusterpool_types.go, go.mod, go.sum, pkg/constants/constants.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/test/clusterdeployment/clusterdeployment.go, pkg/test/clusterpool/clusterpool.go, vendor/github.com/davegardnerisme/deephash/.travis.yml, vendor/github.com/davegardnerisme/deephash/LICENSE, vendor/github.com/davegardnerisme/deephash/README.md, vendor/github.com/davegardnerisme/deephash/deephash.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go, vendor/modules.txt
This commit adds a mechanism for calculating a hash representing the following fields in ClusterPool.Spec:
- Platform
- BaseDomain
- ImageSetRef
- InstallConfigSecretTemplateRef
When creating a new ClusterDeployment for the pool, this hash is stored in a new annotation on the ClusterDeployment.
The clusterpool controller checks all unassigned (installing or ready) ClusterDeployments and sets a new condition on the ClusterPool. This condition is:
- "True" when all CDs are up to date with the pool (including the edge case where there are no CDs);
- "False" when one or more CDs are stale;
- "Unknown" if the annotation is missing from one or more CDs.
- (Also "Unknown" if we haven't had a chance to figure it out yet.)
Of note:
- When "False" or "Unknown", the condition's Message contains a …
=> ClusterPool:ClusterDeployment version & condition

hack/app-sre/kustomization.yaml, hack/app-sre/operator_role_binding.yaml, hack/app-sre/saas-template.yaml
Create an almost-copy of the operator cluster role binding for app-sre to deploy. The difference being that the subject namespace needs to be hardcoded due to kustomize limitations. See inline comments for more.
[HIVE-1588](https://issues.redhat.com/browse/HIVE-1588)
=> Hack: Hardcode crb subject namespace for app-sre

Makefile, go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk, vendor/modules.txt
Update our vendored build-machinery-go dep to pick up https://github.com/openshift/build-machinery-go/pull/50, and resolve the TODO that was waiting on it.
=> Update bmg, remove imagebuilder workaround

pkg/controller/metrics/provision_underway_collector.go
Encountered a cluster today with a missing image set, requirements met false, but the metric did not inform us.
=> Add requirements met condition to provision delay metric labels.

docs/syncset.md
It was not clear that deleting a [Selector]SyncSet with `resourceApplyMode: Sync` would delete all the resources in the same
spirit as editing a resource out of one. Now it is.
=> Clarify resourceApplyMode: Sync when deleting SyncSets

hack/app-sre/kustomization.yaml, hack/app-sre/saas-template.yaml
Previously, our app-sre deploys were getting aggregated into the [`dedicated-cluster-admins` ClusterRole](https://github.com/openshift/managed-cluster-config/blob/adc42a02ece09d52b852882b1ef26d9cb22bd717/deploy/rbac-permissions-operator-config/03-dedicated-admins-cluster.ClusterRole.yaml) via a [rule intended for "customer installed" operators](https://github.com/openshift/managed-cluster-config/blob/adc42a02ece09d52b852882b1ef26d9cb22bd717/deploy/rbac-permissions-operator-config/03-dedicated-admins-cluster.ClusterRole.yaml#L17-L22) due to our ClusterRole getting labeled by OLM with:
```json
{
"olm.owner": "hive-og",
"olm.owner.kind": "OperatorGroup",
"olm.owner.namespace": "hive"
}
```
With direct-deploy, that label is no longer present on our ClusterRole. Replace it with the [label …
=> dedicated-admin ClusterRole aggregation for direct deploy

config/hiveadmission/clusterdeployment-webhook.yaml, config/hiveadmission/clusterimageset-webhook.yaml, config/hiveadmission/clusterprovision-webhook.yaml, config/hiveadmission/dnszones-webhook.yaml, config/hiveadmission/machinepool-webhook.yaml, config/hiveadmission/selectorsyncset-webhook.yaml, config/hiveadmission/syncset-webhook.yaml, pkg/controller/hibernation/csr_helper.go, pkg/controller/hibernation/csr_utility.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, pkg/controller/hibernation/mock/csr_helper_generated.go, pkg/operator/assets/bindata.go, pkg/operator/hive/hiveadmission.go, pkg/operator/util/admissionregistration.go, test/e2e/common/client.go, test/e2e/postdeploy/operator/operator_test.go
OCP 4.9 uses k8s 1.22, where several deprecated objects have been removed [1]. We got partway via previous commits [2][3]. This hopefully finishes the job, addressing:
- ValidatingWebhookConfiguration
- CertificateSigningRequest
- some remaining CustomResourceDefinition references in test code
[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
[2] openshift#1395
[3] openshift#1468
[HIVE-1626](https://issues.redhat.com/browse/HIVE-1626)
[HIVE-1627](https://issues.redhat.com/browse/HIVE-1627)
=> More updates for k8s 1.22

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/utils/errorscrub.go, pkg/controller/utils/errorscrub_test.go
I started out trying to hit the AWS resource ARNs with the regex but I think it will be simpler to just target this message. There is a request id and the ARN being updated in the message.
=> Scrub AWS not authorized message which includes AWS resource ARNs

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
fix GCP CPU quota install log regexp. GCP CPU quota install log regexp
was too specific, and the tail end of the message in GCP changed.
/cc @abutcher
=> fix GCP CPU quota install log regexp

pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/controller/clusterpool/metrics.go, pkg/controller/metrics/metrics.go
3dc3c3c7c / #1484 added setting and discovery of a version marker for ClusterPool and ClusterDeployment so we could tell whether they match. This commit goes a step further and uses that information to replace stale CDs such that the pool will eventually be consistent.
The algorithm we use is as follows:
If the pool is in steady state -- i.e. we're at capacity and all unclaimed CDs are finished installing -- delete *one* stale CD. This triggers another reconcile wherein the deleted CD is replaced. We're no longer in steady state until (at least) that CD finishes installing, whereupon we're eligible to repeat.
Reasoning:
- We don't want to immediately trash all stale CDs, as this could result in significant downtime following a pool edit.
- We don't want to exceed capacity (size or …
=> Slowly delete stale pool clusters

pkg/controller/metrics/provision_underway_collector.go, pkg/controller/metrics/provision_underway_collector_test.go
This commit adds a polarity check of the given cluster deployment
condition before deciding if it is responsible for provision failure or
delay. This fixes the bug where the collector incorrectly interprets the
error status of RequirementsMet condition
=> Add polarity check for Provision Underway metric

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
Add a fake pool to e2e-pool-test.sh and use it to validate the replacement of ClusterDeployments when the pool spec is modified, per the linked jira.
[HIVE-1058](https://issues.redhat.com/browse/HIVE-1058)
=> e2e-pool: test stale cluster replacement

pkg/controller/clusterdeployment/clusterinstalls.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/clusterdeployment/metrics.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/test/clusterdeployment/clusterdeployment.go
With this PR, the clusterpool controller detects "broken" ClusterDeployments as those whose ProvisionStopped condition is True* and deletes them so they can be replaced and do not continue to consume capacity in the pool.
When adding or deleting clusters to satisfy capacity requirements, we prioritize as follows:
- If we're under capacity, add new clusters before deleting broken clusters. This is in case we hit `maxConcurrent`: we would prefer to use that quota to add clusters to the pool.
- If we're over capacity, delete broken clusters before deleting viable (installing or assignable) clusters.
We also add a metric, `hive_cluster_deployments_provision_failed_terminal_total`, labeled by clusterpool namespace/name (blank if not a pool CD), keeping track of the total number of …
=> ClusterPool: Delete broken (ProvisionStopped) clusters

pkg/operator/hive/clustersync.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
With this change, the operator will deploy controllers (including clustersync and hiveadmission) with the same NodeSelector and Tolerations as the operator itself was deployed with.
[HIVE-1635](https://issues.redhat.com/browse/HIVE-1635)
=> Copy NodeSelector/Tolerations from operator to controllers

hack/e2e-pool-test.sh
In response to flakes caused by a pool's .status.size having not yet been updated from zero, add a check for that when waiting for the pool to be "ready".
=> e2e-pool: Smarter wait_for_pool_to_be_ready

docs/clusterpools.md
The examples in clusterpools.md created the pool and other artifacts in the `hive` namespace, which wouldn't usually be a good practice. Change it to something generic and obviously example-ish.
[HIVE-1646](https://issues.redhat.com/browse/HIVE-1646)
=> Better namespace in clusterpool doc examples

docs/enhancements/cluster_pool_hot_spares.md
Add enhancement doc proposing ways to keep Active clusters in a ClusterPool for faster claiming.
[HIVE-1576](https://issues.redhat.com/browse/HIVE-1576)
=> RFE: ClusterPool hot spares

pkg/controller/clusterpool/metrics.go
This was missed in #1512 / f3e437e.
[HIVE-1058](https://issues.redhat.com/browse/HIVE-1058)
[HIVE-1645](https://issues.redhat.com/browse/HIVE-1645)
=> Register hive_clusterpool_stale_clusterdeployments_deleted metric

hack/e2e-pool-test.sh
We've started seeing flakes where the pool's ready/size statuses are copacetic before the conditions settle. This commit moves the check for AllClustersCurrent into the same loop that checks the ready/size statuses so we get a chance to retry in this case.
=> e2e-pool: Move AllClustersCurrent check into wait_for_pool_to_be_ready

apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, docs/clusterpools.md, hack/app-sre/saas-template.yaml, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/controller/hibernation/hibernation_controller.go, pkg/test/clusterdeployment/clusterdeployment.go, pkg/test/clusterpool/clusterpool.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Adds ClusterPool.Spec.RunningCount, the number of pool clusters to try to keep active at any time.
Note that when ClusterPool.Spec.HibernateAfter is set, we count from when it was claimed rather than when it was started so it doesn't hibernate early.
[HIVE-1576](https://issues.redhat.com/browse/HIVE-1576)
=> ClusterPool RunningCount

hack/e2e-common.sh, hack/e2e-test.sh, hack/statuspatch
We've seen frequent e2e flakes where the ClusterDeployment times out waiting to install, and it contains a status condition like:
```
- lastProbeTime: "2021-09-10T00:24:40Z"
lastTransitionTime: "2021-09-10T00:24:40Z"
message: 'error instantiating actuator: Secret "hiveci-613aa513-5fd-aws-creds" not found'
reason: ActuatorNotInitialized
status: "True"
type: DNSNotReady
```
This is a timing problem whereby hiveutil create-cluster is creating the secret and the ClusterDeployment in quick succession, and the dnszone controller kicks in before the secret has come to life (or appeared in the cache?). If the dnszone controller doesn't find the secret, it goes to sleep for 2h, during which time the CD doesn't progress; and we time out of the test after ~90m.
Since this is not a situation that …
=> e2e: Force DNSZone resync on ActuatorNotInitialized flake

apis/hive/v1/dnszone_types.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/dnszone/awsactuator.go, pkg/controller/dnszone/dnszone_controller.go, pkg/controller/dnszone/dnszone_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/dnszone_types.go
Adds a special purpose condition to DNSZone like the
AuthenticationFailure condition to provide details when the controller
requires DNS apis to be enabled for success.
Currently, only the AWS actuator sets this condition based on request
from HIVE-1469.
The clusterdeployment controller tracks the conditions from DNSZone, and
it now also tracks the new condition to update the DNSReady condition on
the clusterdeployment.
/cc @suhanime
=> controller/dnszone: add condition to track dns api opt-in required failures

hack/e2e-pool-test.sh, hack/statuspatch
Add a test case to e2e-pool whereby we make a CD look broken (by patching its `ProvisionStopped` status condition to `True`) and watch the clusterpool controller delete and replace it.
[HIVE-1615](https://issues.redhat.com/browse/HIVE-1615)
=> e2e-pool: Test broken pool CD replacement

pkg/controller/clusterdeployment/installconfigvalidation.go, pkg/controller/clusterdeployment/installconfigvalidation_test.go
since username and password must be set in install-config.yaml for vSphere platform in addition
to the credentialsSecretRef in clusterdeployment. We add a quick check to make sure some value
is set to give users pre-flight style check before running.
similar to https://github.com/openshift/hive/pull/1403
xref: https://issues.redhat.com/browse/OCPBUGSM-33627
/cc @suhanime
=> validate username/password set for vsphere installconfig

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
for when:
* a subnet that doesn't exist was specified
* aws credentials with insufficient permissions were provided
=> add install log failure regexes

hack/bundle-gen.py, hack/github.py, hack/requirements.txt
```
➜  hive (HIVE-1604) ✔ ./hack/bundle-gen.py --help                    
usage: bundle-gen.py [-h] [--verbose] [--dry-run] [--branch BRANCH] [--registry-auth-file REGISTRY_AUTH_FILE] [--github-user GITHUB_USER] [--hold]
Hive Bundle Generator and Publishing Script
optional arguments:
-h, --help            show this help message and exit
--verbose             Show more details while running
--dry-run             Test run that skips pushing branches and submitting PRs
--branch BRANCH       The branch (or commit-ish) from which to build and push the image. If unspecified, we assume `master`. If we're using `master`, we generate the bundle version
number based on ${HIVE_VERSION_PREFIX} and update the `alpha` channel. If BRANCH *also* corresponds to an `ocm-X.Y`, we'll also update that channel …
```
=> HIVE-1604: Amalgamate build and operatorhub push scripts.

pkg/controller/clusterprovision/installlogmonitor_test.go
@yithian @gregsheremeta 
/hold
=> Read default regexes from configmap for tests.

pkg/clusterresource/builder.go
This makes sure when we use `-oyaml` the output creates a valid secret object that can be pushed to cluster using `oc`
xref: https://issues.redhat.com/browse/HIVE-1586
=> clusterresource/builder: add type metadata for adopted kubeconfig & password secret

hack/bundle-gen.py
Was working on docs and noticed the v prefix was missing from the image tag.
/cc @2uasimojo
=> bundle-gen: Add 'v' to image tag.

apis/hive/v1/clusterdeployment_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, hack/e2e-pool-test.sh, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterinstalls.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/utils/conditions.go, pkg/test/assert/assertions.go, pkg/test/clusterdeprovision/clusterdeprovision.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Add a `Provisioned` status condition to ClusterDeployment that keeps
track of both provisioning and deprovisioning lifecycle states. Use this
to replace the `INSTALLED` output column for `oc get` to provide better
granularity and fill the gap whereby we previously couldn't tell we were
deprovisioning without looking deeply at the object and possessing some
institutional knowledge.
[HIVE-1596](https://issues.redhat.com/browse/HIVE-1596)
=> ClusterDeployment Provisioned condition

hack/bundle-gen.py
Saw the error message because I had bad creds.
```
Pushing container
Getting image source signatures
error pushing image "quay.io/openshift-hive/hive:v1.2.3254-512b7f4" to "docker://quay.io/openshift-hive/hive:v1.2.3254-512b7f4": trying to reuse blob sha256:74ddd0ec08fa43d09f32636ba91a0a3053b02cb4627c35051aff89f853606b59 at destination: unable to retrieve auth token: invalid username/password: unauthorized: Could not find robot with username: XXXXXXXX and supplied password.
ERRO[0000] exit status 125
Writing bundle files to directory: /tmp/hive-operator-bundle-d14jkjza
Generating CSV for version: 1.2.3254-512b7f4
Wrote ClusterServiceVersion:
/tmp/hive-operator-bundle-d14jkjza/1.2.3254-512b7f4/hive-operator.v1.2.3254-512b7f4.clusterserviceversion.yaml
Wrote package: …
```
=> fail on error to push container image

docs/enhancements/replace_broken_clusters.md
Add enhancement doc to propose separate bucket for stand by clusters and
validate a hibernating cluster can be successfully transitioned to
running state before assigning it to a claim
xref: https://issues.redhat.com/browse/HIVE-1602
/cc @abhinavdahiya @dgoodwin
=> RFE: Detect and replace broken clusters

pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go
In #1434, we added the paradigm of keeping some number of ClusterPool
clusters in Running state, so they don't have to suffer Resuming time
when claimed. However, that work was narrowly focussed on conforming to
the ClusterPool.Spec.RunningCount.
This commit expands the concept to try to make sure we're always running
enough clusters to satisfy claims. In particular, when we are servicing
a number of claims in excess of the pool's capacity, we create that
excess number of clusters... but we previously didn't account for that
number when calculating how many should be Running.
Now we do.
To explain via a corner case: If your pool has a zero Size and you
create a claim, we will create a cluster and immediately assign it. But
because RunningCount is zero, prior to this commit, we would …
=> ClusterPool: running clusters for excess claims

apis/hive/v1/clusterdeployment_types.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
For a newly-created ClusterDeployment, the hibernation controller can
hit the window where the ClusterSync has been created by the clustersync
controller, but it has not yet succeeded. In this case the hibernation
controller sets the Hibernating condition's Reason to
SyncSetsNotApplied. However, when the ClusterSync does go green, we
weren't resetting that condition, so it stayed that way indefinitely
until the next time the cluster hibernated.
With this commit, we check for that and set the condition to a new
SyncSetsApplied state. The subsequent reconcile does the checks for
Running and sets that state if appropriate.
We also close a latent gap whereby we would silently ignore the case
where the ClusterSync hadn't yet been created. Now we requeue in that
case so we can wait for it to …
=> Clear SyncSetsNotApplied Hibernating Reason

hack/app-sre/kustomization.yaml, hack/app-sre/saas-template-stub.yaml, hack/app-sre/saas-template.yaml, hack/app_sre_build_deploy.sh
To accommodate ICSP, guarding against a quay outage, pull the operator images by digest for OSD, causing the operator to pull the (same) image for the controllers by digest as well.
OperatorHub is not affected.
[HIVE-1504](https://issues.redhat.com/browse/HIVE-1504)
=> OSD: Pull operator/controller images by digest

pkg/controller/metrics/provision_underway_collector.go, pkg/controller/metrics/provision_underway_collector_test.go, pkg/controller/utils/conditions.go
Provision underway metric logged conditions even if they were of unknown status. Since we are initializing all the conditions now, it doesn't seem appropriate to do so anymore.
This commit ensures the provision underway metric is logged if and only if there are conditions present on the cluster deployment in undesired state. For conditions that are not part of the predetermined [list](https://github.com/openshift/hive/blob/master/pkg/controller/metrics/provision_underway_collector.go#L19-L26) of provision delay conditions, if there are conditions in error/undesired state, we would log the metric but condition and reason would be unknown. This should help with better alerts.
[HIVE-1660](https://issues.redhat.com/browse/HIVE-1660)
=> ProvisionDelay metric shouldn't log unknown conds

pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/util/apply.go
138c8e0 / #1525 / [HIVE-1581](https://issues.redhat.com/browse/HIVE-1581) added `HiveConfig.spec.exportMetrics` and
logic to the operator to enable exporting metrics when this setting is
`true`. This commit adds logic to undo same when it is changed from
`true` to `false` (or removed).
[HIVE-1655](https://issues.redhat.com/browse/HIVE-1655)
=> Unexport metrics

Dockerfile, Dockerfile.ubi
move to UBI-minimal
Smaller set of packages (105 vs 192) (no python RPMs installed at all).
We do lose standard 'dnf', as 'microdnf' is there in its place.
Adjust both Dockerfiles to minimize differences by defining a DNF
variable that is set to 'microdnf' or 'dnf' as appropriate.
openshift-install baremetal RPM dependencies
The openshift-install binary for baremetal really only needs
libvirt-libs at runtime (not the full libvirt-devel).
See differences between build-time dependencies and run-time
dependencies in:
https://github.com/openshift/installer/blob/master/images/baremetal/Dockerfile.ci
xref: https://issues.redhat.com/browse/HIVE-1673
=> UBI minimal and baremetal RPM dependencies

docs/using-hive.md
Permission route53:GetResourcesPages is not a route53 API at all, it
should be tag:GetResources.
Permission route53:ListHostedZoneByName has a typo as it should be Zones
(plural).
xref: https://issues.redhat.com/browse/HIVE-1681
=> fix DNSZone docs permissions

docs/awsprivatelink.md
related to FedRamp work and this conversation: https://coreos.slack.com/archives/C027UG79RR9/p1636063266209800?thread_ts=1636043782.182600&cid=C027UG79RR9
=> add ec2:DescribeNetworkInterfaces permission to PrivateLink permissions

pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterprovision/clusterprovision_controller_test.go, pkg/test/clusterprovision/clusterprovision.go
Refactor ClusterProvision test object creation to use a Builder pattern
like we do for other objects. No logical change; no production-side code
changes.
=> Make clusterprovision Builder test helper

apis/hive/v1/hiveconfig_types.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterprovisions.go, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Add support for a list of strings in HiveConfig which correspond to
`installFailingReason`s from [additional-]install-log-regexes.
- If the list is present and the most recent ClusterProvision has failed
with a matching reason, we will retry (assuming not otherwise blocked,
e.g. by `InstallAttemptsLimit`).
- If the list is present and the reason is _not_ in the list, we will
fail immediately (`ProvisionStopped`) even if `InstallAttemptsLimit` is
not reached.
- If the list is absent, the previous behavior is observed: we will
ignore the failure reason and proceed or stop based solely on factors
such as `InstallAttemptsLimit`.
[HIVE-1662](https://issues.redhat.com/browse/HIVE-1662)
=> HiveConfig.Spec.FailedProvisionConfig.RetryReasons

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
This PR:
- adds a new search string under the existing OCM error code for `AWSInsufficientPermissions` when a load balancer is failed to be created due to insufficient permissions.
- adds a new search string and OCM error code for when the account has exceeded its load balancer quota.
The full logs from a failed installations which prompted this PR is:
```
time="2021-11-11T22:05:47Z" level=error msg="Error: Error creating network Load Balancer: AccessDenied: User: xxxxxxxxxxx is not authorized to
perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::xxxxxxxxxxxxxxx:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing"       
```
and 
```
time="2021-11-12T00:40:07Z" level=info msg="Cluster operator ingress Available is False with …
```
=> Add install log regexes for loadbalancer-related failures

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
move the install log regex for loadbalancer creation failure to its own condition
When this happens, the problem is slightly different than just a plain ol'
permission denied, and we need to call it out as such.
/assign @mrbarge @2uasimojo 
/cc @abutcher
=> move the install log regex for loadbalancer creation failure to its own condition

apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
It is meant to indicate that at least one cluster provision was
attempted.
=> clarify when the ProvisionStopped condition would be set

pkg/operator/hive/awsprivatelink.go, pkg/operator/hive/controllersconfig.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go, pkg/operator/hive/manageddns.go, pkg/operator/hive/operatorutils.go
When managed DNS is enabled, we copy the relevant data from HiveConfig
to a ConfigMap in the target namespace. Previously this ConfigMap was
dynamically named `managed-domains-XXXXX` and we would find it via a
label. For consistency with other similar ConfigMaps used by Hive, this
commit switches it to use a static name, `hive-managed-domains`,
instead. For upgrade purposes, we have to keep the old lookup mechanism
in place until we can be sure we've flushed out all instances of the old
naming scheme.
=> Static name for managed DNS ConfigMap

pkg/clusterresource/azure.go, pkg/clusterresource/builder_test.go, pkg/controller/clusterpool/clusterpool_controller.go
`CloudName` set within the Azure Platform for `ClusterPool` will be set for created `ClusterDeployments` and within `InstallConfig` platform.
=> Respect azure cloudName set for clusterpool.

contrib/pkg/createcluster/create.go
To make generating objects easier, eg.
```
./bin/hiveutil create-cluster abutcher-azgov \
--cloud=azure \
--azure-base-domain-resource-group-name=os4-common \
--region=usgovvirginia \
--azure-cloud-name=AzureUSGovernmentCloud
```
=> [hiveutil] Add --azure-cloud-name parameter.

test/e2e/postinstall/machinesets/infra_test.go
Been seeing frequent flakes on this. Increasing the timeout,
understanding that it may be a deeper flake and we're just wasting more
time.
=> e2e: Increase node wait timeout

apis/hive/v1/clusterdeployment_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, pkg/imageset/updateinstaller.go, pkg/imageset/updateinstaller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Add a field to ClusterDeployment.Spec.Provisioning allowing
specification of an image URI to use in place of the installer image
gleaned from the ReleaseImage metadata.
[HIVE-1698](https://issues.redhat.com/browse/HIVE-1698)
=> CD.Spec.Provisioning.InstallerImageOverride

hack/e2e-common.sh
We're saving deployment logs as part of an exit trap to ensure we get
the latest, most complete picture on failure. However, the way we were
doing it previously would truncate the log files if the deployments were
gone -- which they would be if the script didn't exit early, because we
uninstall the operator as the last part of the test.
Fix the log saving logic to only overwrite the log files if the log
extraction command succeeds.
=> e2e: Fix disappearing logs

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
This PR adds two new installation log handlers, `ProxyTimeout`, and  `ProxyInvalidCABundle`, to cover cases where a cluster installation using a cluster-wide proxy is impacted due to the proxy either being unavailable or serving untrusted certificates.
Refs [OSD-9064](https://issues.redhat.com/browse/OSD-9064) / [SDE-1471](https://issues.redhat.com/browse/SDE-1471)
=> OSD-9064 add install log handlers for proxy install failures

contrib/pkg/createcluster/create.go
Specifying an SSH private key file to `hiveutil create-cluster` causes
it to parlay the contents into a Secret. However, the code is chomping
whitespace, including the trailing newline, which `ssh-add` seems to
require or it complains the file format is invalid. This commit
explicitly adds the trailing newline. This causes the resulting yaml
block scalar to be introduced with `|` now rather than `|-`, and
`ssh-add` works.
=> Fix hiveutil create-cluster --ssh-private-key-file

hack/e2e-common.sh, hack/e2e-test.sh, test/e2e/postdeploy/operator/operator_test.go
Currently, the test to verify HiveConfig CR does not validate
managed domains for azure. This PR fixes it and the e2e
x-ref: https://issues.redhat.com/browse/HIVE-1710
=> Fix azure e2e

docs/using-hive.md, pkg/installmanager/installmanager.go
Document how to configure log upload to an AWS S3 bucket for failed
provisions in two places:
- The docstring for `hiveutil install-manager`
- The `using-hive` markdown document.
[HIVE-1697](https://issues.redhat.com/browse/HIVE-1697)
=> Document failed provision log upload

pkg/controller/clusterprovision/installlogmonitor_test.go
There were a few tests where we were using copies of the yaml stanzas
from the install-log-regexes configmap. Change to use the configmap
itself.
=> Collapse duplicated regexes in installlogmonitor_test

docs/troubleshooting.md, docs/using-hive.md
When I wrote #1625 / 1566d49 I didn't realize we already had some
documentation in place for provision failure log upload. Remove the
duplicate bits; leave the appropriate bits in the appropriate docs.
[HIVE-1697](https://issues.redhat.com/browse/HIVE-1697)
=> Consolidate S3 upload docs

pkg/constants/constants.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/operator/hive/failedprovision.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go
Create a ConfigMap containing FailedProvisionConfig and use it instead of the existing mechanisms:
- Environment variables for log upload
- Directly reading HiveConfig for RetryReasons
[HIVE-1692](https://issues.redhat.com/browse/HIVE-1692)
=> Use a ConfigMap for FailedProvisionConfig

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Replace the `NoWorkerNodes` regex/reason with cloud-specific versions
`AWSNoWorkerNodes` and `GCPNoWorkerNodes`.
[HIVE-1722](https://issues.redhat.com/browse/HIVE-1722)
=> Install logs: NoWorkerNodes => (AWS|GCP)NoWorkerNodes

apis/hive/v1/clusterdeployment_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, hack/e2e-common.sh, hack/e2e-pool-test.sh, pkg/controller/clusterpool/collections.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Add functionality to check for clusteroperators to settle as we resume a hibernating cluster
To accomplish this, following things were added
- cd.Status.PowerState
- ClusterReady condition for cluster deployment, that expands on transitioning status when a cluster is resuming
- Intermediate reasons to reflect starting (and stopping) if machines, distinct from waiting for the machines to start (or stop)
xref: https://issues.redhat.com/browse/HIVE-1601
/cc @2uasimojo
=> Check clusteroperators

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
This adds a new regex string for the existing `ProxyTimeout` installation search regex handler, based on failed installation observations during the feature QE review.
Refs [OSD-9064](https://issues.redhat.com/browse/OSD-9064)
=> Add additional proxy installation failure regex

pkg/client/fake/overrideable_client.go, pkg/controller/clusterdeprovision/clusterdeprovision_controller.go, pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go, pkg/controller/clusterdeprovision/helpers_test.go
- A missed error return in the Reconcile loop if Delete() fails.
- Incomplete error path coverage in the unit test driver.
Adding unit test for the former entailed beefing up the fake controller-runtime client to allow overriding behavior for specific calls without mocking the whole thing. For this I stole/adapted a [solution](https://github.com/openshift/aws-efs-operator/blob/043676e0d01fc41279715ad740145c7ab22a2379/pkg/test/client.go) from 2020 Eric.
=> Fix some bugs identified by code inspection

pkg/operator/hive/clustersync.go, pkg/operator/hive/hive.go, pkg/operator/hive/hiveadmission.go, pkg/operator/hive/operatorutils.go
As hive-operator loads and modifies the manifests for the other
controllers, it used to assume that they only had one container. This is
not future-proof: if we added another container, it would be easy to
miss that we're now modifying the wrong one. Guard against this by
instead looking up the container by name.
There should be no functional change.
=> Stop assuming containers[0]

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Backports https://github.com/openshift/hive/pull/1645.
xref: https://issues.redhat.com/browse/HIVE-1465
This backport was created manually because there were merge conflicts to resolve in the tests related to initialized conditions.
=> OCM-2.4: Backport HIVE-1465

pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go, pkg/installmanager/installmanager.go, pkg/resource/delete.go
Previously deleting an assigned ClusterClaim would cause the
clusterclaim controller to _mark_ the associated ClusterDeployment,
Role, and RoleBinding for deletion, then remove the ClusterClaim's
finalizer so it could be garbage collected.
Per the associated Jira card, this could cause confusion if the claim
was "resurrected" -- i.e. one with the same name was created. The new
claim would take the place of the old one, making it look like it was
"assigned" the existing, deleting ClusterDeployment.
With this change, we wait to remove the ClusterClaim's finalizer until
all the associated resources are actually 404. This should make it
impossible to "resurrect" a ClusterClaim: you won't be able to create a
claim with that name until all the associated resources are gone; so the
new claim …
=> ClusterClaim deletion waits for CD, Role[Binding]

pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go, pkg/test/clusterdeployment/clusterdeployment.go
The ClusterDeployment Hibernating condition used to be the one-stop shop
for determining the target cluster's power state. In #1604 we changed
the semantics such that the Hibernating condition only reports things
about hibernation; a new Ready condition reports things about being
ready; and a new Status.PowerState field reports the cluster's power
state definitively.
The ClusterClaim controller uses the ClusterDeployment's power state to
set the ClusterClaim's ClusterRunning condition. It was previously using
the state of the ClusterDeployment's Hibernating condition to do this.
We missed changing it in #1604 to look at the Ready condition or
Status.PowerState instead. This commit does the latter.
[HIVE-1734](https://issues.redhat.com/browse/HIVE-1734)
=> Use cd.Status.PowerState for ClusterClaim Running condition

apis/hive/v1/clusterprovision_types.go, apis/hive/v1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_clusterprovisions.yaml, hack/app-sre/saas-template.yaml, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/installmanager/helper_test.go, pkg/installmanager/installmanager.go, pkg/installmanager/installmanager_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterprovision_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
This PR adds error message in the install log if we detect a
infraID set on cluster provision by previous install pod which
got killed or evicted midway through the installation process.
We also fail the cluster provision in this case. Earlier we use
to start a new install attempt which failed to update cluster
provision infraID - an immutable field giving a not so user
friendly admission webhook failure message.
This PR also fixes the bug where secrets associated with the
failed cluster provisions were getting leaked. We now store
the name of the previous provision and use it to delete
leaked secrets in the next provision attempt.
x-ref: https://issues.redhat.com/browse/HIVE-1725
=> Add error message if install pods get killed or evicted

pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go
In case the syncset managing a resource changes, the resulting state isn't the expected one. 
Indeed, we first apply the new SyncSet, and then delete any resources attached to syncset which aren't existing anymore. In case of the same resource being now owned by a different syncset (like for user-worklad-monitoring which triggers the deployment of the same configmap but with a different content), this is leading to a first application of the syncset which is not valid (new version being eventually deleted at the end of the initial reconcile loop).
Goal of this MR is to enforce the deletion of any resource managed by a former syncset before applying changes, to ensure we don't delete new version of a resource.
=> OSD-8194 : modifying order of operation for syncset update to avoid deleting new resource version

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
This adds a regex and test for the AWS "VPC not found" install error. This is believed to be a transient error due to AWS API slowness. 
Additional details in: https://issues.redhat.com/browse/OSD-9688
=> OSD-9688: Add regex for VPC missing install failure

cmd/manager/main.go, cmd/operator/main.go, cmd/util/leaderelection.go, config/controllers/hive_controllers_role.yaml, config/operator/operator_role.yaml, hack/app-sre/saas-template.yaml, pkg/operator/assets/bindata.go, pkg/operator/hive/hive.go, pkg/operator/hive/hiveadmission.go
We were using ConfigMap-based leader election. We need to migrate to using Lease instead.
Part 1: Use ConfigMap *and* Lease so we can upgrade smoothly from a build using just ConfigMap.
Part 2: Remove ConfigMap.
This is part 1.
[HIVE-1736](https://issues.redhat.com/browse/HIVE-1736)
=> Leader election migration 1: ConfigMap & Lease

apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterpools.yaml, hack/app-sre/saas-template.yaml, hack/e2e-pool-test.sh, pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterclaim/clusterclaim_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterinstalls.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/controller/clusterpool/metrics.go, pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller_test.go, pkg/controller/hibernation/aws_actuator_test.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, pkg/test/clusterdeployment/clusterdeployment.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
With this PR, the cdCollection bucket called `assignable` now only contains installed, non-deleted/deleting, *running* clusters. Since we fulfill claims out of that bucket, the result is that, when your claim is assigned a cluster, that cluster is guaranteed to be running. Before this change, it might have been hibernating and we would initiate resume when assigning; so you would need to wait before using it.
To make this work, we also add a new bucket to cdCollection called `standby`. This contains the installed, non-deleted/deleting clusters that are *not* running.
The related metrics are changed accordingly:
- `hive_clusterpool_clusterdeployments_assignable` now only counts running clusters.
- `hive_clusterpool_clusterdeployments_running` is removed, as it would have been redundant …
=> ClusterPool: Claim running clusters

config/hiveadmission/clusterdeployment-webhook.yaml, config/hiveadmission/clusterimageset-webhook.yaml, config/hiveadmission/clusterprovision-webhook.yaml, config/hiveadmission/dnszones-webhook.yaml, config/hiveadmission/machinepool-webhook.yaml, config/hiveadmission/selectorsyncset-webhook.yaml, config/hiveadmission/syncset-webhook.yaml, pkg/operator/assets/bindata.go
With newer OpenShift the kube-apiserver will be in a degraded state if
it find webhooks whose connections are signed by an unknown CA.
Annotate hive's webhooks so that they get their
.webhooks[].clientConfig.caBundle fields populated with trusted CA data.
xref: https://issues.redhat.com/browse/HIVE-1730
=> inject CA data into webhooks

pkg/constants/constants.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
Prior to #1604 we were lying about cluster status when resuming from
hibernation. That PR introduced checking the health of ClusterOperators
before we declared a ClusterDeployment to be Running.
However, this bug fix immediately began causing problems for some
consumers because:
1. It nontrivially increased the time to resume. Consumers need to
accommodate this by increasing the respective timeouts in their tooling.
2. Resume doesn't work great right now, so sometimes cluster operators
were _never_ coming up. This could result in ClusterClaims never being
fulfilled (because the pool could never present a Running cluster).
For 1, we would like to give consumers some time to stage the changes to
accommodate the fix.
For 2, we would like to provide the ability to revert to the pre-bugfix …
=> Label to disable ClusterOperators check during resume

hack/bundle-gen.py
...because my gh username isn't the same as my $USER and I'm annoyed at
having to specify it via a CLI flag.
=> bundle-gen: Recognize $GITHUB_USER

apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterpools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Add a knob causing the clusterpool controller to consider a
ClusterDeployment broken if it spends too long resuming.
[HIVE-1746](https://issues.redhat.com/browse/HIVE-1746)
=> ClusterPool.Spec.HibernationConfig.ResumeTimeout

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
there were two specific terraform race related regexps in the list,
but new ones are popping up every day. replace with a generic
catch-all InconsistentTerraformResult code.
=> prefer generic InconsistentTerraformResult install log regexp

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Added this error message ( found in the install log)  to a list of known errors in OCM, so it doesn't pop up with "OCM3999 - Unknown error" code and save Primary On-Call time debugging.
Full Install Log: https://docs.google.com/document/d/1PilYlo8wyB0kAiInyIaDnb8964Y0IIf2LXgXpacaegg/edit?usp=sharing
Related Slack Thread : https://coreos.slack.com/archives/CCX9DB894/p1643661195222699
Related Jira Card: https://issues.redhat.com/browse/OSD-9846
=> Added NATGatewayFailed Error code

build/build-image/Dockerfile
According to
[testplatform](https://coreos.slack.com/archives/CBN38N3MW/p1643925799875989)
the fact that we're using a bespoke build_root means we need to merge a
change to that dockerfile to use go1.17 to trigger the release repo's
bots to update our ci-operator config to build against 1.17. Only then
can we start dropping code changes that _need_ 1.17.
[HIVE-1753](https://issues.redhat.com/browse/HIVE-1753)
=> Trigger CI to update to go1.17

hack/app_sre_build_deploy.sh
Due to ICSP quirks, our app-sre build script skips building and pushing
an image if that has already been done. In checking whether the image
already exists, the following output (example) is normal:
```
11:23:27 + stderr='time="2022-02-07T12:23:27-05:00" level=fatal msg="Error parsing image name \"docker://quay.io/app-sre/hive:cddf7e5\": Error reading manifest cddf7e5 in quay.io/app-sre/hive: manifest unknown: manifest unknown"'
...
11:23:27 Image quay.io/app-sre/hive:cddf7e5 does not exist in the repository.
```
This is confusing because it looks like an error.
This commit adds a line of output immediately after the above like:
```
Building and pushing quay.io/app-sre/hive:cddf7e5...
```
...which will hopefully alleviate some of this confusion.
=> Add output to de-confuse first appsre build

config/templates/hiveconfig.yaml
...to get rid of this warning when deploying:
```
W0207 15:46:02.156006  359141 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
```
=> Groupify hiveconfig template

contrib/pkg/createcluster/create.go
Beef up the help text for `hiveutil create-cluster --labels` to explain
how to specify multiple labels.
=> hiveutil create-cluster: document multiple labels

apis/hive/v1/clusterclaim_types.go, apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, hack/app-sre/saas-template.yaml, vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Due to a difference in how apiserver validates `Format=duration` vs how
apimachinery unmarshals `metav1.Duration`, using that format can allow
users to blow up some of our controllers if they provide certain values
for Duration fields (specifically: containing `d` or `w` units).
Upstream issues have been opened against both sides of this discrepancy:
- https://github.com/kubernetes/apimachinery/issues/131
- https://github.com/kubernetes/apiextensions-apiserver/issues/56
In the meantime, work around the problem by using an explicit regex
instead of the built in format validator.
Closes 2050332
=> Bug 2050332: explicit Pattern to validate Duration fields

apis/hive/v1/clusterclaim_types.go, apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/clusterpool_types.go, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, hack/app-sre/saas-template.yaml, vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Due to a difference in how apiserver validates `Format=duration` vs how
apimachinery unmarshals `metav1.Duration`, using that format can allow
users to blow up some of our controllers if they provide certain values
for Duration fields (specifically: containing `d` or `w` units).
Upstream issues have been opened against both sides of this discrepancy:
- https://github.com/kubernetes/apimachinery/issues/131
- https://github.com/kubernetes/apiextensions-apiserver/issues/56
In the meantime, work around the problem by using an explicit regex
instead of the built in format validator.
(cherry picked from commit 665b268161d83a3ea9d0ab4788031528110ef4d0)
Conflicts:
apis/hive/v1/clusterpool_types.go
config/crds/hive.openshift.io_clusterpools.yaml
hack/app-sre/saas-template.yaml …
=> Explicit Pattern to validate Duration fields

hack/e2e-common.sh, test/e2e/postdeploy/operator/operator_test.go
Managed DNS feature for azure is not working currently. This is a temporary workaround to fix the e2e
Backports #1620
=> Backport OCM-2.4: Fix azure e2e

apis/hive/v1/clusterdeprovision_types.go, config/crds/hive.openshift.io_clusterdeprovisions.yaml, contrib/pkg/deprovision/ibmcloud.go, hack/app-sre/saas-template.yaml, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/install/generate.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
IBM Cloud uninstall requires being passed the `ClusterName` to clean up the correct DNS entries. `ClusterName` is currently not being provided resulting in **ALL** DNS entries in a CIS instance being deleted that match the uninstall `BaseDomain`. Without the `ClusterName`, the following regex matches all DNS entries for the provided `BaseDomain`: https://github.com/openshift/installer/blob/master/pkg/destroy/ibmcloud/dns.go#L31.
This PR passes `ClusterName` obtained from `cd.Spec.ClusterName` (which is a required field for `ClusterDeployment`) to uninstall.
=> Pass ClusterName to uninstall for IBM Cloud DNS cleanup.

pkg/installmanager/installmanager.go
`ClusterName` must also be set when we clean up a failed provision during install.
https://github.com/openshift/hive/pull/1700
=> Pass ClusterName when cleaning up failed provision.

docs/using-hive.md
Correction for the oVirt credentials/certificate secrets. These match what `hiveutil` produces.
=> oVirt: Fix credentials and cert secret docs.

contrib/pkg/deprovision/ibmcloud.go, pkg/clusterresource/ibmcloud.go, pkg/install/generate.go
[HIVE-1620](https://issues.redhat.com/browse/HIVE-1620)
* Remove `--resource-group-name` from `hiveutil deprovision ibmcloud`. Use provided `InfraID` as `ResourceGroupName`.
* Remove `--cis-instance-crn` and `--account-id` from `hiveutil deprovision ibmcloud` usage. These were removed in #1706 and I missed removing them here.
* Add `--cluster-name` to `hiveutil deprovision ibmcloud` usage. `--cluster-name` is a required parameter (needed for cleaning up DNS entries) should be in the usage example. 
* Fix an inconsistency with `hiveutil create-cluster` I noticed writing usage docs. `--ibm-instance-type` should also be reflected in the generated install config as should the default.
/hold
=> IBMCloud: Hiveutil fixes

pkg/controller/hibernation/hibernation_controller.go, pkg/controller/metrics/metrics.go
Add cumulative metrics for transitioned clusters.
To keep cardinality in check, labels are cloud platform, cluster version
(down to patch) and clusterpool name if it belongs to a clusterpool
xref: https://issues.redhat.com/browse/HIVE-1630
=> Add metrics for transitioned clusters

pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterinstalls.go
This change intends to fix a nil pointer dereference seen in assisted service CI.
```
time="2022-03-09T02:14:12.457Z" level=info msg="reconcile complete" clusterDeployment=assisted-spoke-cluster/assisted-test-cluster controller=clusterDeployment elapsedMillis=515 elapsedMillisGT=0 outcome=unspecified reconcileID=g57l4cz9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3a1df8e]
goroutine 1226 [running]:
github.com/openshift/hive/pkg/controller/clusterdeployment.(*ReconcileClusterDeployment).reconcileExistingInstallingClusterInstall(0xc005e47c00, 0xc0041b0c00, {0x55bea50, 0xc00673d5e0})
github.com/openshift/hive/pkg/controller/clusterdeployment/clusterinstalls.go:59 +0x38e …
```
=> Ensure cluster metadata has an AdminPasswordSecretRef before copying.

hack/app_sre_build_deploy.sh
By default podman builds images in OCI format, which is Old. The
preferred way is "Schema v2", which docker does by default. Set an
environment variable so this happens when we build our app-sre images.
=> appsre: Build schemav2 images under podman

contrib/pkg/createcluster/create.go, pkg/controller/machinepool/ovirt.go, pkg/controller/machinepool/ovirt_test.go
[HIVE-1789](https://issues.redhat.com/browse/HIVE-1789)
/hold
=> HIVE-1789: Fix oVirt duplicate "-0" MachineSet generation.

cmd/util/leaderelection.go
Follows up on #1660 / 7ec5c25fab0d734f9702666b1244cdd737eacee9
This is phase 2 where we move from ConfigMap+Lease to Lease only.
[HIVE-1754](https://issues.redhat.com/browse/HIVE-1754)
=> Leader election migration 2: Lease only

pkg/constants/constants.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go, pkg/validating-webhooks/hive/v1/utils.go
We have a webhook to disallow creating a ClusterDeployment with the
ClusterClaim already set. This is a problem for disaster recovery. Add a
granny switch to disable that specific check via the following label:
`"hive.openshift.io/disable-creation-webhook-for-dr": "true"`
[HIVE-1791](https://issues.redhat.com/browse/HIVE-1791)
Conflicts:
pkg/constants/constants.go
...for IBMCloud again.
=> Skip "claimed CD" creation webhook for DR

pkg/controller/hibernation/ibmcloud_actuator.go, pkg/controller/hibernation/ibmcloud_actuator_test.go, pkg/ibmclient/client.go, pkg/ibmclient/mock/client_generated.go, pkg/test/clusterdeployment/clusterdeployment.go
Region based endpoints must be set for calls to the VPC API, `ListInstances` and `CreateInstanceAction` (Start/Stop) in our client's case.
[HIVE-1801](https://issues.redhat.com/browse/HIVE-1801)
=> Set IBM Cloud VPC service API URLs for region

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller_test.go, pkg/controller/awsprivatelink/vpcinventory.go
Since we don't know the actual quota of endpoints per VPC, remove the arbitrary limit check, and create new endpoints in the least-used VPC. The result should be that we hit quota only when all the VPCs are full.
[HIVE-1803](https://issues.redhat.com//browse/HIVE-1803)
=> AWS PrivateLink: "Spread" VPC endpoints across VPCs

pkg/controller/dnsendpoint/dnsendpoint_controller.go, pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
To reduce thrashing, especially after a fresh deploy in a high-volume
environment, delay requeueing on `"name servers have not yet been
scraped"` for 15s.
[HIVE-1855](https://issues.redhat.com//browse/HIVE-1855)
=> dnsendpoint: Delay requeue for "not yet scraped"

docs/clusterpools.md
batch/v1beta1 is being removed soon. We weren't using it in code, but
had an example with it in a doc. Fix.
=> Doc: cronjob from batch v1 instead of v1beta1

Makefile, hack/bundle-gen.py, hack/version.py
Set `SOURCE_GIT_TAG` to cause builds to get the proper `versionFromGit`
tag corresponding to what would show up in OperatorHub.
For "normal" bulids (OSD, OperatorHub) this results in the first log line for hive-operator and hive-controllers looking like:
```
time="2022-04-29T19:59:37Z" level=info msg="Version: openshift/hive v1.2.3606-aca223c"
```
For local builds on commits not tracking `master` you might see something like:
```
time="2022-04-29T19:51:08Z" level=info msg="Version: openshift/hive vUnknownBranch.3509-13b0fbf"
```
i.e. `UnknownBranch` instead of a `{major}.{minor}`. However, the commit count and sha should still be accurate.
[HIVE-1717](https://issues.redhat.com//browse/HIVE-1717)
=> Correct versionFromGit for builds

Makefile, hack/version.py
version.py has some python3-specific syntax. The `python` on the AppSRE
jenkins nodes on which we build is py2. Make the script run under py3
explicitly.
[HIVE-1717](https://issues.redhat.com//browse/HIVE-1717)
=> Run version.py under python3 explicitly

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterrelocate/clusterrelocate_controller.go, pkg/controller/controlplanecerts/controlplanecerts_controller.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/remoteingress/remoteingress_controller.go, pkg/controller/unreachable/unreachable_controller.go, pkg/controller/utils/conditions.go
We were using flawed logic to determine whether to push a status update
when initializing ClusterDeployment conditions. Fix.
[HIVE-1873](https://issues.redhat.com//browse/HIVE-1873)
=> Fix condition initialization

pkg/controller/dnsendpoint/dnsendpoint_controller.go, pkg/controller/dnsendpoint/dnsendpoint_controller_test.go, pkg/controller/dnsendpoint/nameserver/aws.go, pkg/controller/dnsendpoint/nameserver/aws_live_test.go, pkg/controller/dnsendpoint/nameserver/azure.go, pkg/controller/dnsendpoint/nameserver/azure_live_test.go, pkg/controller/dnsendpoint/nameserver/gcp.go, pkg/controller/dnsendpoint/nameserver/gcp_live_test.go, pkg/controller/dnsendpoint/nameserver/mock/query_generated.go, pkg/controller/dnsendpoint/nameserver/query.go, pkg/controller/dnsendpoint/nameserverscraper.go, pkg/controller/dnsendpoint/nameserverscraper_test.go, pkg/controller/dnszone/dnszone_controller.go
It took two people three days to decipher this code after the original
authors had left. This commit renames variables and functions and leaves
helpful comments so future-we might be less confused.
[HIVE-1855](https://issues.redhat.com//browse/HIVE-1855)
=> Rename & comment dnsendpoint/nameserverscraper vars/funcs

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Set ClusterDeployment's Provisioned (False) and ProvisionStopped (True)
conditions when using managed DNS and the DNSZone never becomes ready.
Fix requeueing logic as well -- previously it would always requeue after
10m10s, which made the actual timeout some unknown/arbitrary amount more
than that.
[HIVE-1881](https://issues.redhat.com//browse/HIVE-1881)
=> Make DNSNotReadyTimedout terminal

pkg/constants/constants.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/metrics/metrics.go
- Rename some metrics for consistency
- Account for hard coded wait while pausing before we list cluster
operators while logging the metric for WaitingForClusterOperator
- Also ensure the minimum time bucket for WaitingForClusterOperator
metric is greater than the hardcoded wait (2 minutes)
xref: https://issues.redhat.com/browse/HIVE-1630
=> Minor changes for transitioning metrics

pkg/controller/dnszone/dnszone_controller.go, pkg/controller/dnszone/dnszone_controller_test.go
The dnszone controller's main Reconcile func carefully constructs a
logger that helpfully includes the name of the DNSZone being reconciled;
but helper funcs -- including the one that contains the meat of the
reconcile logic -- were using the reconciler's default logger instead.
This commit propagates the detailed logger throughout the controller to
make it easier to trace activity for a specific DNSZone.
=> Pass field logger around dnszone controller

contrib/pkg/createcluster/create.go
Currently, default is ~/.alibaba/credentials. This PR changes
the default path to ~/.alibabacloud/credentials and makes it
consistent with the installer and ccoctl
=> Fix default credentials path for alibaba used by hiveutil

pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go, pkg/installmanager/installmanager.go, pkg/installmanager/installmanager_test.go
Security group names may be the same within an AWS account (belonging to different VPCs) which means filtering on the name alone is insufficient. The VPC ID is now used to further filter the correct security group when configuring the ODF security group in worker machineset manifests. The VPC ID is discovered by using the AWS client to query subnets from the worker MachinePool. BYO VPC is required when using ODF so it is expected that the worker MachinePool platform will contain subnets we can use to discover the VPC ID.
[HIVE-1874](https://issues.redhat.com//browse/HIVE-1874)
=> Further filter ODF security group filter by VPC ID

apis/hiveinternal/v1alpha1/clustersync_types.go, config/crds/hiveinternal.openshift.io_clustersyncs.yaml, docs/syncset.md, hack/app-sre/saas-template.yaml, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go, vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
In an environment with multiple hive-clustersync replicas and a lot of
clustersync activity, a barrier to debugging was figuring out which
hive-clustersync replica was responsible for a given clusterdeployment's
syncsets. The usual way would be to grep the logs for the CD name, which
can take a nontrivial amount of time across multiple logs.
This commit adds a field to ClusterSync.Status called
ControlledByReplica. It is a pointer (so it doesn't default to zero) to
an integer indicating the ordinal of the replica reconciling it.
=> Add replica ordinal to clustersync status

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
This commit hits some cases that were making e2e failures hard to debug:
- There was a default exit trap that restored the original default
namespace. This wasn't useful. Remove.
- If things go badly very early -- during `make deploy` or managed DNS
setup performed by e2e-common.sh -- there was no way to troubleshoot.
Set up a basic exit trap to save logs. This is overridden by consuming
tests (whose traps also include saving the logs) once they have gotten
past this early setup.
- After `make deploy`, it takes a little while for hive-operator to
reconcile the hiveconfig with a non-default `targetNamespace`. We were
seeing failures in subsequent steps due to that namespace being absent.
So we add a loop to wait for the namespace to appear before proceeding.
- We had a trivial loop to try …
=> Robustify e2e a bit

Dockerfile
As CentOS 8 goes out of support on 12/2021, move the base container away
from centos:8.
Choices were:
centos:stream
centos:stream8
centos:stream9
stream9 appears to be still in development, so going with building
against 'stream'. This will probably start pointing to 'stream9' when
that becomes an officially released build.
[BZ2089490](https://bugzilla.redhat.com/show_bug.cgi?id=2089490)
=> Backport ocm-2.4: move to centos:stream base container

pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go
71c1839b / #1572 fixed an ordering problem in the clustersync controller
to address "moving" a resource from one syncset to another. In so doing,
it introduced a temporary list to look for the deletions. However, the
list was being aliased rather than copied, and the result was that
scenarios with multiple syncsets could end up ignoring changes to a
subset of them. Fix.
[HIVE-1891](https://issues.redhat.com//browse/HIVE-1891)
=> clustersync: fix missing memcpy

hack/hiveadmission-dev-cert.sh
This helper script was missed in https://github.com/openshift/hive/pull/1494 which updated same for the production code.
=> certificates.k8s.io/v1beta1 API deprecated in Kubernetes v1.19 and removed before v1.22

hack/e2e-pool-test.sh
`set -x` was producing waaay too much output, making the logs of a CI
run unusable. Turn it off. (We should augment the normal stdout/stderr
if it turns out to be inadequate as is.)
=> e2e-pool: turn off trace

Makefile
In the CI environment, `$HOME` is set to `/` (the root directory), but
that directory is not writable by the test process, so things like pip
install (even with `--user`) fail because they want to create things
like `/.local`.
With this commit, our Makefile detects when `$HOME==/` and overrides it
to `/tmp/home`, which should be writable in the CI environment.
[HIVE-1717](https://issues.redhat.com//browse/HIVE-1717)
=> Set HOME to a writable dir for CI

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
0bfa044cb / #1782 added an explicit timeout to work around the linked
issue. However, when the test process exits *normally*, the timeout
subprocess was sticking around, essentially forcing the test to take
~2h even when it could have finished earlier. Fix.
This needs to be reverted along with 0bfa044cb / #1782 when the linked
card is resolved.
[DPTP-2871](https://issues.redhat.com//browse/DPTP-2871)
=> e2e: kill the timeout subprocess on exit

apis/hive/v1/clusterdeployment_types.go, pkg/constants/constants.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Add a (secret, "unsupported") `hive.openshift.io/powerstate-pause`
annotation. When `"true"`, it causes the hibernation controller to
ignore the state of the cluster's machines with respect to
`cd.spec.powerState`; and set `cd.status.powerState` and the Ready and
Hibernating status conditions to `"Unknown"`.
[HIVE-1755](https://issues.redhat.com//browse/HIVE-1755)
=> powerstate-pause annotation: skip hibernation controller

config/operator/operator_role.yaml, hack/app-sre/saas-template.yaml
[SEC-OPS-DEP-04](https://source.redhat.com/groups/public/product-security/content/product_security_wiki/operators_secure_deployment_guide)
recommends explicitly enumerating permissions in an RBAC (Cluster)Role
rather than using wildcards (`"*"`). We believe wildcarding permissions
for groups we own is appropriate; but fix it elsewhere (which turns out
to be only one place).
[HIVE-1919](https://issues.redhat.com//browse/HIVE-1919)
=> Explicit permissions in operator ClusterRole

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
This regex hasn't been seen in recent memory, and should be "impossible"
based on the current state of the code. Remove it for now. If the error
manifests again, it'll show up as "Unknown" and be routed through the
usual triage procedures, the result of which may be one or more of:
- Fixing the root cause in code
- Reinstating the regex
- Adding it to RetryReasons
- Nothing
[HIVE-1933](https://issues.redhat.com//browse/HIVE-1933)
=> Remove NoMatchingRoute53Zone regex

hack/e2e-common.sh
30s wasn't a reasonable amount of time to expect to get all the way from
Deployment to a completed reconcile loop, and we've been seeing a lot of
CI flakes as a result.
=> e2e: increase targetNamespace timeout 30s=>3m

pkg/controller/machinepool/awsactuator.go
=> awsactuator: remove Info level log from decodeAWSMachineProviderSpec.

hack/e2e-test.sh
e2e was detecting ClusterDeployment condition ProvisionFailed to decide
whether to give up early. ProvisionStopped is appropriate also (or
perhaps instead?) so add it.
=> e2e: Bail early on ProvisionStopped

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
Reverts openshift/hive#1796
@cblecker pointed out that we might still be able to hit this in non-managed DNS code paths. It's harmless to keep it, so...
[HIVE-1933](https://issues.redhat.com//browse/HIVE-1933)
=> Revert "Remove NoMatchingRoute53Zone regex"

hack/e2e-common.sh
We're still trying to figure out how to make e2e-pool time out after
2h30m instead of 2h. In the meantime, until the linked bug is resolved,
we need our hacked timeout to happen at ~2h -- otherwise we don't get
manifests/logs.
[DPTP-2871](https://issues.redhat.com//browse/DPTP-2871)
=> e2e-pool: hack timeout at ~2h

apis/hive/v1/metricsconfig/durationMetrics.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/metrics/metrics.go, pkg/controller/utils/conditions.go, vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/durationMetrics.go
- Add gauge "hive_clustersync_failing_seconds" that logs time since the lastTransitionTime of the clusterSync's Failed condition with the label namespaced_name as $namespace/$name
- Make it optional and log it conditionally if the time since it has been failing is more than the threshold mentioned
- Skip reporting for Unreachable clusters
- Clear the metric when the clusterSync succeeds
- Clear the metric when the clusterSync is deleted
- Clear the metric when the clusterDeplyment is deleted
xref: https://issues.redhat.com/browse/HIVE-1857
=> Add ClusterSyncFailingSeconds metric

Makefile, apis/go.mod, apis/go.sum, apis/vendor/github.com/go-logr/logr/logr.go, apis/vendor/github.com/google/gofuzz/.travis.yml, apis/vendor/github.com/google/gofuzz/CONTRIBUTING.md, apis/vendor/github.com/google/gofuzz/README.md, apis/vendor/github.com/google/gofuzz/bytesource/bytesource.go, apis/vendor/github.com/google/gofuzz/fuzz.go, apis/vendor/modules.txt, docs/developing.md, hack/modcheck.go, pkg/client/clientset/versioned/clientset.go
Add a utility that compares statements in go.mod and apis/go.mod. If
matching module paths are found, the utility determines whether the
versions match, printing a human-readable report and exiting nonzero iff
*any* versions *do not* match.
Add a make rule, `make modcheck`, to run it.
Plumb `modcheck` into `verify`.
[HIVE-1941](https://issues.redhat.com//browse/HIVE-1941)
=> Ensure go.mod matches apis/go.mod

pkg/ibmclient/client.go
IBM Cloud deprovision was broken by https://github.com/openshift/hive/pull/1764 and this PR brings the client back in line with changes in the installer's client. I attempted to consume the installer client directly but we'll need a way to instantiate the client with a secret or just the `apiKey` string in addition to needing functions related to stopping/starting/listing instances.
[HIVE-1951](https://issues.redhat.com//browse/HIVE-1951)
=> Updates to ibmclient authenticator.

apis/hive/v1/metricsconfig/durationMetrics.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/durationMetrics.go
While adding ClusterSyncFailingSeconds metric, adding it to the enum in
durationMetrics was missed, which didn't catch the appropriate make
targets for adding it to the crd. This commit fixes that.
xref: https://issues.redhat.com/browse/HIVE-1857
=> Add clustersyncfailing metric to crd

pkg/controller/dnsendpoint/dnsendpoint_controller.go, pkg/controller/dnsendpoint/dnsendpoint_controller_test.go, pkg/controller/dnsendpoint/nameserverscraper.go, pkg/controller/dnsendpoint/nameserverscraper_test.go, pkg/controller/dnszone/dnszone_controller.go
For existing DNSZones with copacetic name server entries in the root
hosted zone, restarting the controller was resulting in thrashing
because:
- the nameserverscraper would ignore subdomains not already in the
cache.
- the dnsendpoint controller would error if the scraper hadn't scraped
the subdomain yet.
This chicken/egg situation would eventually resolve itself because the
scraper would "seed" the cache entry for the subdomain on the first
pass. However, it would not resolve until the second pass of the scraper
two hours later.
This commit makes the dnsendpoint controller seed the cache when it
notices it's necessary. The scraper will then scrape for the subdomain
on its next pass *and* notify the dnsendpoint controller to reconcile
that DNSZone again.
We also needed to change the …
=> Fix dnsendpoint/nameserverscraper cache

apis/hive/v1/clusterdeployment_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, pkg/remoteclient/mock/remoteclient_generated.go, pkg/remoteclient/remoteclient.go, pkg/remoteclient/remoteclient_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
https://issues.redhat.com/browse/HIVE-1955
=> Azure private endpoint support

config/rbac/hive_admin_role.yaml, config/rbac/hive_reader_role.yaml, pkg/operator/assets/bindata.go
...per https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
When hive is deployed via OLM, OLM automatically creates ClusterRoles
for owned CRDs and labels them
```rbac.authorization.k8s.io/aggregate-to-$X: "true"```
for `X` in `[admin, edit, view]`.
OSD was taking advantage of these labels to perform role aggregation per
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
When OSD stopped deploying hive via OLM (see
https://issues.redhat.com/browse/SDE-1333), hive shards were only
getting the ClusterRoles explicitly laid down by hive-operator, and
these were unlabeled, so role aggregation was no longer happening.
However, as the existing OLM-generated ClusterRoles weren't removed at
that time, we didn't notice until new shards …
=> Allow admin/view role aggregation for CRDs

pkg/controller/metrics/metrics.go
In one of the previous passes when the change for reporting the
transitioning metrics was put up, the value recorded for WaitingForCO
metric was incorrectly set to report at time since the last transition
time for Ready condition instead of Hibernating condition. This commit
corrects the mistake
xref: https://issues.redhat.com/browse/HIVE-1630
=> Report Waiting For CO metric correctly

pkg/operator/hive/hive.go, pkg/operator/util/apply.go
To enable monitoring (HiveConfig.Spec.ExportMetrics) we use
ServiceMonitor, which is an OpenShift-specific kind [1]. When monitoring
is disabled, we attempt to delete these resources idempotently (i.e.
no-op if they already don't exist). But on non-OpenShift clusters, this
would generate errors like the following:
```
time="2022-07-26T09:37:36Z" level=error msg="error deleting object with namespace override" controller=hive error="unable to delete asset: config/monitoring/hive_clustersync_servicemonitor.yaml: could not get mapping: no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1\""
```
In the case where monitoring is disabled, we can ignore this message
because we don't want the ServiceMonitor to exist anyway. This commit
makes it so.
[1] As a side effect, we …
=> hive-operator: Ignore "no such CRD" errors with monitoring disabled

docs/developing.md, hack/create-service-account-secrets.sh
Service account secrets are not automatically created on Kubernetes >= version v1.24. Add a script to create service account secrets for non-OpenShift Hive deployments (like kind) and point to the script in developing docs.
Fixes #1832
=> Add hack/create-service-account-secrets.sh script to create service account secrets.

pkg/clusterresource/aws.go
https://github.com/openshift/hive/pull/1806 updated the default volume type for install config MachinePools (created by `hiveutil create-cluster`) to gp3. Alas, installers at and before 4.9 don't know about this type, so trying to install OpenShift at those versions results in the following error:
```
Error: expected root_block_device.0.volume_type to be one of [standard io1 gp2 sc1 st1], got gp3
```
We can effectively use the previous default volume type of gp2 which [provides a baseline minimum of 100 iops](https://aws.amazon.com/blogs/storage/migrate-your-amazon-ebs-volumes-from-gp2-to-gp3-and-save-up-to-20-on-costs/) and I have tested that the gp2 volumeType can be used with 4.8->4.11 installers.
The [gp3 volume type performs better and is …
=> Revert hiveutil create-cluster's default AWS volumeType back to gp2.

pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterprovisions.go
ProvisionStopped is supposed to be terminal. That is, once you're in
that state, you should never leave it.
In certain circumstances, like reconciling DNSZones under managed DNS,
it was possible to reach ProvisionStopped without ever having created a
ClusterProvision. The logic that decides whether to "retry" provisioning
would happily do so in this case. The result would be that the
ProvisionStopped condition would be cleared (possibly to return later).
This commit adds an early check for the ProvisionStopped condition and
refuses to proceed if it's True.
[HIVE-1881](https://issues.redhat.com//browse/HIVE-1881)
=> Make ProvisionStopped terminal (f'real this time)

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/metrics/metrics.go
ClusterSync Failing metric must be cleared when clustersync is no longer
failing, however the code path that evoked clearing of that metric in
clustersync controller when the failing condition was changed to success
was somehow never evoked.
- This commit moves the clearing logic under this criterion to the
metrics controller. The controller assumes that if any clustersync is
not failing than the corresponding metric should be cleared.
- Since the code path in clustersync controller wasn't being evoked,
this commit also reverts to the previous code, and moves the clearing
logic to the metrics controller, thereby ensuring we are only setting or
clearing the metric in either the metrics controller or the
clusterdeployment controller
xref: https://issues.redhat.com/browse/HIVE-1857
/assign …
=> Fix clearing of ClusterSync Failing metric 

hack/e2e-pool-test.sh
We had a hardcoded 120s sleep to wait for hive's operator, controllers,
and admission deployments to settle. This commit makes the wait realtime
via `oc wait`.
Part of [HIVE-1940](https://issues.redhat.com//browse/HIVE-1940)
=> e2e-pool: Unhackify deployment settle check

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
This change enables `BalanceSimilarNodeGroups` for the default cluster autoscaler. `BalanceSimilarNodeGroups` will be enabled for new cluster autoscalers created by Hive and existing cluster autoscalers will be updated to enable `BalanceSimilarNodeGroups` unless `BalanceSimilarNodeGroups` was previously disabled.
With `BalanceSimilarNodeGroups` enabled, the cluster autoscaler automatically identifies node groups with the same instance type and the same set of labels (except for automatically added zone label) and tries to keep the sizes of those node groups balanced. Ref: [Running ClusterAutoscaler with nodes in multiple zones for HA purposes](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-th …
=> Enable BalanceSimilarNodeGroups for the default cluster autoscaler

hack/e2e-common.sh, pkg/controller/utils/logtagger.go, pkg/installmanager/installmanager.go
We were overenthusiastic with this message when adding support for
additional log fields: we would emit it as a Warning even when the
annotation was absent from the CR being reconciled. Example:
```
time="2022-08-09T10:20:09.286Z" level=warning msg="failed to extract additional log fields -- ignoring" clusterPool=default/mihuang-pool-1 controller=clusterpool error="no additional log fields found" reconcileID=nskm25td
```
This commit takes that down to Debug level.
[HIVE-1966](https://issues.redhat.com//browse/HIVE-1966)
=> Quiet down "no additional log fields" message

build/build-image/Dockerfile
Needed for [HIVE-1997](https://issues.redhat.com//browse/HIVE-1997)
=> Trigger CI to bump to go1.18

Dockerfile
We haven't had to build 2.3 since we did this to all the other branches.
Now we do.
Needed for [HIVE-1997](https://issues.redhat.com//browse/HIVE-1997)
=> ocm-2.3: build against centos:stream

contrib/pkg/createcluster/create.go
There were a few places where we mention a `--manifests-dir` parameter which doesn't exist. Replace those references with the `--manifests` parameter.
=> [hiveutil] Correct references to --manifests parameter.

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
the installer will fail if terraform can't destroy bootstrap resources,
resulting in a cluster provisioning failure
=> catch install log error for terraform destroy failures

pkg/controller/awsprivatelink/awsprivatelink_controller.go
Typo snuck in with the controller in b154963a0d (#1295).
=> pkg/controller/awsprivatelink: Fix "Enpoint" -> "Endpoint" typo

pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go
When finalizer is missing in a CDC, then only add a finalizer if it is in the pool inventory
=> Fix CDC restoration of finalizers

pkg/constants/constants.go, pkg/imageset/updateinstaller.go, pkg/imageset/updateinstaller_test.go
Look for a new annotation on ClusterDeployment,
`hive.openshift.io/cli-domain-from-installer-image`. If set to a truthy
value, slice and dice the resolved CLI image to use the same domain
(everything up to the first `/`) as the resolved or overridden installer
image.
[HIVE-2014](https://issues.redhat.com//browse/HIVE-2014)
=> Copy installer image domain to CLI image

pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
Platforms that don't have a hibernation actuator...
- BareMetal
- OpenStack
- VSphere
- Ovirt
- AgentBareMetal
- None
...used to show up with their PowerState empty. With this commit, we
assume they are running, since we can't actually tell. It's possible
this is a lie -- e.g. if the instances get shut down from the cloud
provider -- but a) this is a better UX than empty; and b) it makes other
bits of the code operate correctly.
[HIVE-2016](https://issues.redhat.com//browse/HIVE-2016)
=> Assume hibernation-unsupported clusters are always running

pkg/controller/clusterprovision/clusterprovision_controller.go, pkg/controller/clusterprovision/metrics.go
Add hive_cluster_deployment_install_failure_total and
hive_cluster_deployment_install_success_total metrics, which also report
on the cluster_type, cloud platform, region, cluster version, count of
replicas/workers and the number of install attempt pertaining to the
provision attempt
xref: https://issues.redhat.com/browse/HIVE-2006
=> Add install success/fail metrics

config/clustersync/statefulset.yaml, config/controllers/deployment.yaml, config/hiveadmission/deployment.yaml, config/operator/operator_deployment.yaml, hack/app-sre/saas-template.yaml, pkg/controller/utils/utils.go, pkg/imageset/generate.go, pkg/imageset/generate_test.go, pkg/install/generate.go, pkg/install/generate_test.go, pkg/operator/assets/bindata.go, pkg/test/assert/assertions.go
This reverts commit a76ba2ff6cc663eb1672c7f3203439a8a81e2048.
Pods won't run with these changes on clusters with version 4.10 and below. There is no restricted SCC that allows setting `seccompProfile` `RuntimeDefault`. Reverting and investigating options for either conditionally deploying with these settings or creating an SCC that allows pods to run with this `securityContext`.
=> Revert "Explicit pod security"

pkg/constants/constants.go, pkg/installmanager/installmanager.go
ARO requires a different set of credentials for installer and in-cluster 
operations. This commit adds an annotation that would override 
the existing credentials mode in the install-config. The reason we 
do this hack is because in ARO we do not want to pass installer 
credentials inside the cluster. This is done by setting credentials 
mode to `Manual`. We want to instead pass the credentials 
supplied by manifestSecretRef and use the same by overriding 
credentials mode from `Manual` to `Passthrough`.
[HIVE-1989](https://issues.redhat.com//browse/HIVE-1989)
=> Add support to override effective in-cluster credentials mode

contrib/pkg/deprovision/alibabacloud.go, contrib/pkg/deprovision/awstagdeprovision.go, contrib/pkg/deprovision/azure.go, contrib/pkg/deprovision/gcp.go, contrib/pkg/deprovision/ibmcloud.go, contrib/pkg/deprovision/openstack.go, contrib/pkg/deprovision/ovirt.go, contrib/pkg/deprovision/vsphere.go, contrib/pkg/utils/alibabacloud/alibabacloud.go, contrib/pkg/utils/aws/aws.go, contrib/pkg/utils/azure/azure.go, contrib/pkg/utils/gcp/gcp.go, contrib/pkg/utils/generic.go, contrib/pkg/utils/ibmcloud/ibmcloud.go, contrib/pkg/utils/openstack/openstack.go, contrib/pkg/utils/ovirt/ovirt.go, contrib/pkg/utils/vsphere/vsphere.go, pkg/constants/constants.go, pkg/install/generate.go, pkg/installmanager/installmanager.go, pkg/installmanager/installmanager_test.go
Pods created by hive-controllers require information from secrets and configmaps (for example, cloud credentials) in order to function. Previously these were passed into the pods from the hive-controllers side via environment variables and volumes. In scale mode (see [HIVE-1861](https://issues.redhat.com//browse/HIVE-1861)) we're going to need that same business logic -- which parts of which objects are needed in what form -- on the hiveutil side.
In order to avoid duplication of that logic, we're moving it *all* to the hiveutil side, even for non-scale mode.
The cloud credentials secret and other secrets/configmaps are no longer passed through via the pod spec. Instead, the hiveutil command itself uses a local client to load those secrets and set up the same environment variables and …
=> Move secret/configmap retrieval to hiveutil for prov/deprov

docs/aws-sts-provisioning.md
The previous doc in the repo was created prior to `ccoctl` being built into the release image (around the 4.7 timeframe) so the steps did not include how to obtain `ccoctl` or commands like `ccoctl aws create-all` which creates the key, s3 bucket, IAM roles and secrets.
=> Update Hive AWS STS doc.

Makefile, config/operator/operator_role.yaml, hack/app-sre/saas-template.yaml, pkg/operator/hive/hiveadmission.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
We had some checks and tweaks for OpenShift 3.11, which has been EOL for a looong time. Clean up.
Of note: We also remove our write RBAC for CRDs. The reader perms were used to determine 3.11-ness, but are still used to determine supported contracts for ClusterInstall. The writer perms became obsolete at some point when we stopped doing
[this](https://github.com/openshift/hive/pull/385/files#diff-5b450b52ce1d65cb9d1e448269a23d1fc71a200dfa6462a5bc0a3cd2019fafa7R77-R88), but were never removed.
Of note: This partially reverts 5fecbe55 / #990, which added some yq magic to remove a field from our CRDs because 3.11 didn't like it. However, it seems controller-gen stopped generating that field anyway at some point, so this bit no longer had any effect anyway.
=> Get rid of OpenShift 3.11 cruft

docs/using-hive.md
Add more detail to the MachinePool section of usage docs to include information regarding MachinePool platform immutability as well as noting that a MachinePool for workers mirroring the workers defined in the install-config is not required but will result in Hive managing the worker MachineSets.
https://github.com/openshift/hive/pull/1891 should update this once `Labels` and `Taints` are merged instead of overridden.
/cc @suhanime
=> [docs] Add more detail to MachinePool section of usage docs.

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Currently, the checks for BootstrapFailed are only checking for the generic error message. The installer checks to see if the API came up and if the status is set to complete
in the bootstrap config map before exiting with BootstrapFailed error and this can be checked to possibly see if the API came up before it errored out.
xref: https://issues.redhat.com/browse/HIVE-2047
=> Refine error checks

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
Per OSD-13578, we've identified another way that an install will fail on AWS due to insufficient permissions via logs like:
```
time="2022-10-14T18:40:17Z" level=error msg="Error: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ${encoded stuff}
```
So I added a regex search to `AWSInsufficientPermissions`
I will make a separate PR for the other failure method identified due to a blocking SCP since we will be able to give the customer a more specific error message in that case since they may have tried to give the necessary permissions, but are being blocked by an organizational SCP that they have forgotten about.
=> Add regex to catch another occurence of AWSInsufficientPermissions

docs/using-hive.md
I noticed that a few headings were nested incorrectly in the table of contents. This PR adjusts headings around `DNS` and moves the `Create Cluster on Bare Metal` header up a level to not be a sub-section of `MachinePools`.
See rendered markdown here: [docs/using-hive.md](https://github.com/openshift/hive/blob/21ddecf9bcbfd8706d2a00bc1819b39d739495f9/docs/using-hive.md) and double check that the headings look correct in the TOC.
=> [docs] Adjust several heading levels in docs/using-hive.md and regenerate the table of contents.

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Per OSD-13578, sometimes installs can fail due to a service control policy (SCP) that the customer may unknowingly be restricted by.
I chose to make this its own error message rather than bundling it into `AWSInsufficientPermissions` because the customer may have set up the roles as documented, but a different internal team may be responsible for an SCP, which isn't as obvious to them as a possible reason if we send the message: `AWS credentials are insufficient for performing cluster installation`
=> Add AWSDeniedBySCP failed install reason and regex

build/build-image/Dockerfile
Bumping in the build Dockerfile similar to #1680 to make some change that should allow the subsequent update (with the rest of the Dockerfiles) to go in #1907.
=> Trigger CI to update to go 1.19.

config/hiveadmission/hiveadmission_rbac_role.yaml, config/operator/operator_role.yaml, hack/app-sre/saas-template.yaml, pkg/operator/assets/bindata.go
Make hiveadmission logs stop saying things like
```
W1107 19:49:51.940311       1 reflector.go:324] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: prioritylevelconfigurations.flowcontrol.apiserver.k8s.io is forbidden: User "system:serviceaccount:hc-hs1:hiveadmission" cannot list resource "prioritylevelconfigurations" in API group "flowcontrol.apiserver.k8s.io" at the cluster scope
E1107 19:49:51.940382       1 reflector.go:138] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: prioritylevelconfigurations.flowcontrol.apiserver.k8s.io is forbidden: User "system:serviceaccount:hc-hs1:hiveadmission" …
```
=> hiveadmission: enable API Priority and Fairness

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
`SCACertsPullFailed` and `SCACertPullFailed` were distinct error messages, but targeting the same error.
Kind of funnily there are two main status conditions that have been observed recently that indicate this failure:
* `SCAAvailable is False` and
* `SCANotAvailable is True`
but the latter was getting overruled since it didn't match the first regex and getting caught as `BootstrapFailed` instead due to the ordering/priority in install log regexes.
This PR consolidates the two error messages into one and keeps the more generic regex so that both cases can be correctly identified. I kept `SCACertsPullFailed` because it already corresponds to the OCM error code `OCM3050`
=> [OSD-13716] Deduplicate and consolidate SCACertsPullFailed error

pkg/controller/clustersync/clustersync_controller.go
This reverts commit 6568c2041d2a92956b430730fd599258166711f1, reversing changes made to 18e4e87e11b63c6c7231e1645bf648b214787c55.
=> Revert "Merge pull request #1903 from dlom/HIVE-2038"

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
For OSD-13928, we found that sometimes AWS runs out of EC2 capacity in a specific availability zone without a specific error message. This creates one and the plan is to add it as a retry reason to SREP's HiveConfig next. Even if it continues to fail through the retries, the hope is that this error code/message makes a lot more sense for the user and/or SREP if it ends up paging us.
=> Add new installer failure reason when AWS has insufficient capacity

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Per OSD-13933, this is no longer a blocking install failure reason. Especially since it's at the top of the list, it has been causing confusion with customers. 
I don't think it has value to even point SRE too because it may confuse us if this is a "known install failure reason" when in fact it is no longer blocking a successful install, so I am removing it!
It will also be removed from OCM as well.
=> SCACertsPullFailed is no longer a blocking reason an install can fail

hack/e2e-pool-test.sh
Mysterious cdc-* clusters started appearing in our running instance reports, but not our CI leak reports. We believe these are from e2e-pool runs where customized clusters weren't getting cleaned up when tests timed out prematurely. To make them show up in our leak reports, change the names to be prefixed with `hiveci-`.
=> e2e-pool: rename cdc-* clusters => hiveci-cdc-*

apis/hive/v1/clusterdeployment_types.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, pkg/controller/remoteingress/remoteingress_controller.go, pkg/controller/remoteingress/remoteingress_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
This PR adds support to override HttpErrorCodePages field in IngressController CR made via ClusterDeployment using Syncset. 
ref: https://issues.redhat.com/browse/HIVE-2040
=> Add support for custom http error pages

docs/using-hive.md
This PR adds the namespace parameter to the sample cmd to adopt a hive cluster. During an adoption process in production we accidentally adopted a hive into the default namespace. This parameter will specify the namespace
=> add namespace parameter to sample adoption cmd

pkg/controller/clustersync/clustersync_controller.go
This PR adds re-adds the functionality that was reverted in #1914, additionally adding some logs to better capture what's really going on in the stage environment.  There are 2 more subsequent related PRs:
* #1923 - reverts the functional changes included in this PR but retains the logging
* #1924 - reverts the non-functional logging changes included in this PR
These PRs are supersets of this PR and contain the same commit SHAs.  They should be merged in order.
=> Syncset Testing PR #1

pkg/controller/clustersync/clustersync_controller.go
This PR reverts the functional changes of #1921 but retains the logging.  This PR is a superset of #1921 and should be merged after it, but before #1924 (which is a superset of this PR).
=> Syncset Testing PR #2

docs/using-hive.md
Signed-off-by: chuckersjp <cdouglas@redhat.com>
Per [recent docs](https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-network-customizations.html#nw-network-config_installing-aws-network-customizations) the proper stanza is
`networking.machineNetwork`
=> Fix typo in sample install-config.yaml

docs/using-hive.md
- Updates adoption info to address Privatelink clusters for ROSA as well as any extra configs that may be in use
- addresses limitations of using hiveutil as it does not support privatelink setting or any extra configurations required (which we set in FedRAMP)
=> updates adoption steps for privatelink clusters/added configurations

hack/e2e-pool-test.sh
1eb917189 / #1918 tried to rename the cluster we generate for testing ClusterPool inventory so it would be caught by our leak detector lambda. We erroneously thought all we had to do was prefix the name with `hiveci-` when in fact the whole name gets parsed to glean the timestamp (when the test started) and the PR number under test. As such, when one of these clusters leaked, it was causing an exception in the lambda function like:
```
Traceback (most recent call last):
  File "/var/task/ci_monitor_lambda_function.py", line 58, in lambda_handler
    formatted, count = build_report_text(vpcs, debug=debug)
  File "/var/task/ci_monitor_lambda_function.py", line 84, in build_report_text
    parsed = parse_vpc(vpc)
  File "/var/task/ci_monitor_lambda_function.py", line 23, in parse_vpc …
```
=> Name inventory test cluster to be caught by lambda

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
In [OSD-14978](https://issues.redhat.com//browse/OSD-14978) we learned about a new way installs can fail.
> Why `Gp3VolumeLimitExceeded` and not `VolumeLimitExceeded`?
I would like to be able to give the customer the exact quota to increase, in this case: "L-7A658B76"
=> Add Gp3VolumeLimitExceeded install failure reason

pkg/controller/argocdregister/argocdregister_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/controller/dnsendpoint/nameserver/aws_test.go, pkg/controller/hibernation/azure_actuator_test.go, pkg/controller/hibernation/ibmcloud_actuator_test.go, pkg/controller/machinepool/awsactuator_test.go, pkg/controller/machinepool/azureactuator_test.go, pkg/controller/machinepool/machinepool_controller_test.go, pkg/installmanager/helper_test.go, pkg/installmanager/ibm_metadata_test.go, pkg/installmanager/installmanager.go, pkg/test/clusterprovision/clusterprovision.go, pkg/validating-webhooks/hive/v1/clusterprovision_validating_admission_hook_test.go, test/e2e/postinstall/machinesets/infra_test.go
Noticed that `pointer.StringPtr` has been deprecated for `pointer.String` as well: https://pkg.go.dev/k8s.io/utils/pointer#StringPtr so just a bit of a cleanup PR while doing #1946
=> StringPtr deprecated in favor of String

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
This failure reason isn't very common, but currently it is being caught as `FallbackInstancesFailedToBecomeReady`, which doesn't really provide any actionable hints when troubleshooting the failed install. The AWS docs describing this failure case can be found here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-internal
The relevant log lines have `Client.InternalError: Client error on launch` and this means that the default EBS encryption key does not have enough permissions to allow the installer to run EC2 instances and decrypt EBS volumes.
Relates to https://issues.redhat.com/browse/OSD-14201
=> OSD-14201 Add new installer failure reason: DefaultEbsKmsKeyInsufficientPermissions

cmd/manager/main.go
xref: [HIVE-2139](https://issues.redhat.com//browse/HIVE-2139)
Note: This is not a fix, this is merely to enable diagnostics so we can collect for information
/cc @abutcher
=> Enable pprof for hive-clustersync-n (and every other controller)

pkg/controller/awsprivatelink/awsprivatelink_controller_test.go, pkg/controller/awsprivatelink/cleanup.go, pkg/controller/awsprivatelink/cleanup_test.go
Previously, deleting a ClusterDeployment with an AWS PrivateLink configured would always result in the deletion of the PrivateLink. This change ensures the PrivateLink is preserved when PreserveOnDelete is enabled.
https://issues.redhat.com/browse/HIVE-2087
=> AWS.PrivateLink is preserved with PreserveOnDelete

hack/app_sre_build_deploy.sh
Potential fix for "too many open files" on our [downstream build](https://ci.int.devshift.net/job/openshift-hive-gh-build-master/).
=> Set ulimit for image build.

hack/app_sre_build_deploy.sh
Revert bumping the ulimit in our build command. The build nodes have had their [default ulimit increased](https://gitlab.cee.redhat.com/app-sre/infra/-/merge_requests/610/diffs) within `/usr/share/containers/containers.conf` so we no longer need to set here.
This reverts commit 8473f52536cd9f168ab47d393fd42aacd098666e, reversing changes made to c2d531b75f71d28730a1bf8a751998e94f2c5434.
=> Revert "Set ulimit for image build."

go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk, vendor/github.com/openshift/build-machinery-go/make/targets/golang/vulncheck.mk, vendor/github.com/openshift/build-machinery-go/scripts/vulncheck.sh, vendor/modules.txt
Bring in the latest BMG so we can now `make vulncheck` to get a preview of what dependabot might complain about.
=> Upgrade build-machinery-go for `make vulncheck`

hack/app_sre_build_deploy.sh
We hit a case where the first 7c of the commit sha was ambiguous, so our appsre build script helpfully used 8c instead. Unfortunately, the tooling on the appsre saas deploy side doesn't have the ability to do this same disambiguation, so it tried the 7c prefix and the deploy failed.
Increase the prefix length to 10c to greatly reduce (but not eliminate, sad-face) the probability of future collisions.
[HIVE-2194](https://issues.redhat.com//browse/HIVE-2194)
=> Bump appsre image tag from 7 to 10c

build/build-image/Dockerfile, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
This is the weird thing where we have to change the golang version in one file and then merge and then CI will let us change it in all the other files.
To `verify` under go 1.20, we also have to fix the following new `go vet` error:
```
pkg/controller/clusterdeployment/clusterdeployment_controller_test.go:4007:29: loop variable envVar captured by func literal
```
[HIVE-2193](https://issues.redhat.com//browse/HIVE-2193)
=> Prompt CI to bump to golang 1.20

Dockerfile, Dockerfile.ubi, apis/go.mod, docs/developing.md, go.mod, vendor/modules.txt
Step 3/3 (I think) in getting to go 1.20.
NOTE: The builder image in the dockerfiles says 4.14 even though we're actually using 4.12 in CI. There should be no impact on the build artifacts themselves.
[HIVE-2193](https://issues.redhat.com//browse/HIVE-2193)
=> Bump to go 1.20

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterinstalls.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/clusterdeployment/metrics.go
hive_cluster_deployments_provision_failed_terminal_total should be logged everytime we set ProvisionStopped condition to true, however it was found that logging of this metric was skipped when DNSZoneFailedToReconcile and DNSNotReadyTimedOut. This commit fixes that.
xref: https://issues.redhat.com/browse/HIVE-2056
=> Log ProvisionFailedTerminal metric if DNSZoneFailedToReconcile or DNSNotReadyTimedOut

contrib/pkg/deprovision/awstagdeprovision.go
Changes made via #1874 / 0f4b1de caused hiveutil deprovisioning commands to try to load up a cloud credentials secret upon startup. When run in standalone mode, this doesn't work (unless you have configured some very specific environment variables) BUT the deprovisioner is able to work without it as long as your cloud creds are in one of the usual expected places (e.g. credentials file, env vars). This is in fact how those deprovisioners have always worked when invoked standalone.
However, prior to this commit, if we're entirely unable to contact the cluster API, we would abort the command. With this commit, we instead print a warning and proceed.
Note that we're only doing this for aws-tag-deprovision at this time, as it's the only deprovisioner used in standalone mode with any …
=> hiveutil aws-tag-deprovision: don't require a cluster

pkg/controller/clusterprovision/clusterprovision_controller.go, pkg/controller/clusterprovision/clusterprovision_controller_test.go
Customer reports a panic in:
```
github.com/openshift/hive/pkg/controller/clusterprovision.(*ReconcileClusterProvision).getWorkers(_, {{{0x4581c54, 0x11}, {0xc003588a20, 0x14}}, {{0xc00562e9d6, 0x9}, {0x0, 0x0}, {0xc00562e9e0, ...}, ...}, ...})
github.com/openshift/hive/pkg/controller/clusterprovision/clusterprovision_controller.go:611 +0x263
```
(This is running hive commit cef3cb07)
This can happen if the install-config.yaml is improperly formatted in any of several ways:
- There is no `compute` section.
- The `compute` section has no item with `name: worker`.
- That section has no `replicas` field.
This commit adds some simple nil checking and reports zero workers in those scenarios.
[HIVE-2200](https://issues.redhat.com//browse/HIVE-2200)
=> Fix nil pointer exception looking up no workers

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
[OSD-13511](https://issues.redhat.com//browse/OSD-13511)
Investigating AuthenticationOperatorDegraded, which is currently the 
fifth-most common install failure, can be annoying because install
failures are not caused by the Authentication operator failing; instead
it is a symptom of another failure. This PR represents a repeatable
finding where a log line indicating that 0 worker nodes have joined the 
cluster causes AuthenticationOperatorDegraded.
Returning this instead will point us in a better direction to start
investigating the install failure. If we find that it makes up all cases
of AuthenticationOperatorDegraded we can remove that failure reason.
This error code is very similar to AWSNoWorkerNodes and 
GCPNoWorkerNodes, however based on our history neither of them have
triggered …
=> New install failure reason: NoWorkerNodesReady

pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go
ClusterPool status fields Size, Standby, and Ready were being ignored in the deletion path for the ClusterPool, and we never noticed because the ClusterPool was disappearing (see referenced card). Fix.
[HIVE-1557](https://issues.redhat.com//browse/HIVE-1557)
=> Update ClusterPool status counts while deleting

apis/hive/v1/clusterpool_types.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go, pkg/controller/clusterpool/collections.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
Backports commits from [HIVE-1557](https://issues.redhat.com//browse/HIVE-1557)
=> ClusterPool: hold until all clusters deleted, subject to maxConcurrent

pkg/controller/clusterdeployment/installconfigvalidation.go, pkg/controller/clusterprovision/clusterprovision_controller.go
We recently discovered that `gopkg.in/yaml.v2` doesn't work properly in
cases where the struct being unmarshalled to has only `json` tags. An
important example is unmarshalling install-config. The reason can be
found in this blog post [1].
Swap to `sigs.k8s.io/yaml` in the couple of places where this applies.
(Notably, we're leaving alone places where the target struct has `yaml`
tags, as the interface between the two libraries is not fully
compatible.)
[1] https://web.archive.org/web/20190603050330/http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/
[HIVE-2205](https://issues.redhat.com//browse/HIVE-2205)
=> s,gopkg.in/yaml.v2,sigs.k8s.io/yaml for json-tagged structs

cmd/operator/main.go, config/operator/operator_role.yaml, contrib/pkg/utils/alibabacloud/alibabacloud.go, contrib/pkg/utils/aws/aws.go, contrib/pkg/utils/azure/azure.go, contrib/pkg/utils/gcp/gcp.go, contrib/pkg/utils/ibmcloud/ibmcloud.go, contrib/pkg/utils/openstack/openstack.go, contrib/pkg/utils/ovirt/ovirt.go, contrib/pkg/utils/vsphere/vsphere.go, hack/app-sre/saas-template.yaml, pkg/constants/constants.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/install/generate.go, pkg/operator/hive/clustersync.go, pkg/operator/hive/dynamicclient.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
This commit rounds out our support for clusterwide proxies by doing two
things:
- Previously, we relied on an outside agent (typically OLM) to set
`HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables on the
hive-operator deployment  We would pass these values down to the
controllers and thence to workload pods such as provisioner and
deprovisioner. This commit adds logic to discover those values from the
cluster proxy object if not already set.
- Install the cluster proxy's trusted CA bundle in all provision and
deprovision pods. The ultimate source of this bundle is the ConfigMap
referenced by the proxy's spec.trustedCA.name. We take advantage of the
Cluster Network Operator's facility [1] to inject the merged CA bundle --
which includes the proxy's trusted CA bundle -- into …
=> Beef up clusterwide proxy support

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/metrics/custom_collectors.go, pkg/controller/metrics/custom_collectors_test.go, pkg/controller/metrics/metrics.go
The hive_cluster_deployment_deprovision_underway_seconds metric and the
hive_clustersync_failing_seconds metric are both susceptible to a
caching behavior described in this issue, which could allow for a
previously cleared metric to be reported due to a stale resource:
https://github.com/kubernetes-sigs/controller-runtime/issues/2239#issuecomment-1478542119
These cleared metrics are therefore good candidates for a custom
collector.
Create new collectors for
hive_cluster_deployment_deprovision_underway_seconds and
hive_clustersync_failing_seconds.
xref: https://issues.redhat.com/browse/HIVE-2191
=> Move cleared metrics into custom collector

docs/hive_metrics.md
Label hive_clustersync_failing_seconds metric as optional and add an
example of metricsConfig.
=> Edit hive metrics docs

pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
[HIVE-2198](https://issues.redhat.com//browse/HIVE-2198) / #1999 / 253408e introduced a `Watch()` on `Proxy` so we can
update environment variables and CA bundles when it changes. But `Proxy`
is an OpenShift CRD, so that `Watch()` blows up the operator when
running on vanilla k8s (and similar).
This commit conditions that `Watch()` such that we only add it if we're
running on OpenShift.
[HIVE-2210](https://issues.redhat.com//browse/HIVE-2210)
=> Only Watch Proxy when running on OpenShift

pkg/constants/constants.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/install/generate.go
If we're not running on OpenShift, the magic label doesn't cause OpenShift to populate the merged CA bundle ConfigMap. This would cause the ConfigMap mount to fail, and provisions wouldn't start. This commit defaults that key to empty so the file will always exist and the mount will work. (Note that `update-ca-trust` properly ignores an empty file.)
[HIVE-2210](https://issues.redhat.com//browse/HIVE-2210)
=> Dummy ca-bundle.crt for non-OpenShift

config/hiveadmission/sa-token-secret.yaml, pkg/operator/assets/bindata.go, pkg/operator/hive/hiveadmission.go
Starting with k8s 1.24, service account token secrets are no longer created automatically by k8s. The hiveadmission service needs one, so this commit explicitly creates one. This should work for pre- and post-1.24.
[HIVE-2219](https://issues.redhat.com//browse/HIVE-2219)
=> Create ServiceAccount token secret for hiveadmission

test/e2e/postinstall/machinesets/infra_test.go
ONLY IN mce-2.3!
This autoscale test has been mysteriously failing for Azure and GCP in the mce-2.3 branch, but not in master where everything seems pretty much the same. We are under a time constraint to land some fixes here, so disable the test while we investigate.
=> mce-2.3: Disable autoscale e2e test for GCP, Azure

contrib/pkg/createcluster/create.go, pkg/clusterresource/builder.go
Add a featureset flag to the hiveutil command. The string value provided will be passed directly into the installconfig.
=> Add featureset flag to hiveutil

contrib/pkg/createcluster/create.go, pkg/clusterresource/azure.go
Add a azure-resource-group-name flag to the hiveutil command. The string
value provided will be passed directly to the install config
platform.azure.resourceGroupName parameter.
=> Add azure-resource-group-name flag to hiveutil

docs/using-hive.md, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
Hive controllers *and* in some cases the consumer must be able to set ClusterDeployment.spec.clusterMetadata.platform.azure.resourceGroupName. Previously our "clusterMetadata is immutable" validating webhook would (uh, sometimes??) bounce such a change. Make a special case for this sub-field.
[HIVE-2222](https://issues.redhat.com//browse/HIVE-2222)
=> Allow azure resource group to be set/updated in clusterMetadata

hack/e2e-common.sh
Debugging e2e failures -- especially those with a timing component -- will be easier if we have date stamps on our output messages. Make it so.
Note that this commit is only overriding the `echo` command. Output from subcommands won't be affected. That may turn out to be a problem, but it's one we can solve later.
=> Add timestamps to messages in e2e tests

pkg/controller/clusterclaim/clusterclaim_controller.go
Fix what appears to be a copy/paste miss in #1068: the ClusterClaim controller was watching `Role` twice instead of `Role` and `RoleBinding`. Fix.
Closes: #2024
=> ClusterClaim controller: Watch RoleBindings

hack/e2e-common.sh, hack/e2e-pool-test.sh
- Fix a logic bug where we were redundantly hibernating a cluster in the fake pool while it was still in the pool and thus already hibernating. Now we claim a cluster, validate that it's Running by the time the claim is fulfilled, then hibernate it.
- Also add resuming the above.
- Also add deleting the claim and verifying that the claimed CD gets deleted.
=> e2e-pool: minor fixes

apis/hive/v1/aws/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Previously, via [HIVE-1224](https://issues.redhat.com//browse/HIVE-1224) / #1234 / a27ef2e, we started filtering out public subnets if they were provided in an AWS MachinePool. This led to two issues:
- Users could not create machines in public subnets at all ([HIVE-2196](https://issues.redhat.com//browse/HIVE-2196)).
- In PrivateLink, subnets are always private, even though they may appear public based on their attributes ([HIVE-1805](https://issues.redhat.com//browse/HIVE-1805)).
With this commit, we relax the restrictions such that, if the number of subnets matches the number of availability zones, we allow them whether they're public or private.
Here's a complete description of the new behavior:
- We still accept an empty Subnets list, as before.
- If the number of subnets matches the …
=> AWS MachinePool: Allow public and/or private subnets

docs/using-hive.md, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
When MachineSets were generated, we overrode the existing labels and taints on the remoteMachineSet to reflect what was present on the MachinePool. This commit preserves the existing labels and taints on the MachineSet as long as they do not clash with those on MachinePool.
xref: https://issues.redhat.com/browse/HIVE-2035
=> Merge Labels/Taints of MachineSets

pkg/constants/constants.go, pkg/controller/machinepool/awsactuator_test.go, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go, pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook_test.go
Normally we forbid updates to MachinePool.Spec.Platform via an admission hook because, while we would roll out the changes to the MachineSets on the target cluster, MCO ignores those changes.
With this commit, you can add an annotation to a MachinePool
```
hive.openshift.io/override-machinepool-platform: "true"
```
to bypass this check. By doing so, you are taking responsibility for forcing rollout of any changes, e.g. by deleting the Machines on the target cluster.
[HIVE-2024](https://issues.redhat.com//browse/HIVE-2024)
=> MachinePool: Allow Platform edits via override

test/e2e/postinstall/machinesets/infra_test.go
TestAutoscalingMachinePool has been failing consistently in gcp and azure (but not aws??) because the busybox deployment we use to force scale-up wasn't starting:
```
- lastTransitionTime: "2023-06-02T21:50:36Z"
lastUpdateTime: "2023-06-02T21:50:36Z"
message: 'pods "busybox-5b578f78f-5bzf7" is forbidden: violates PodSecurity
"restricted:latest": allowPrivilegeEscalation != false (container "sleep"
must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities
(container "sleep" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot
!= true (pod or container "sleep" must set securityContext.runAsNonRoot=true),
seccompProfile (pod or container "sleep" must set securityContext.seccompProfile.type
to "RuntimeDefault" or "Localhost")'
reason: FailedCreate …
```
=> e2e: add pod security on busybox for autoscaler test

hack/e2e-test.sh
Trivial update to add some helpful information to an error message.
=> e2e: print name of stale resource in old targetNamespace

docs/syncset.md
Just making the example in the documentation a bit more clear, adding ``replicas`` under the ``spec`` section.
=> Deployment patch example misses the spec part

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
It was annoying to not be able to get things like clusterdeployment manifests for e2e runs that completed successfully. Now e2e will save those manifests twice: once right after the ClusterDeployment has been created and once on cleanup. (As today, the latter will only be interesting if the test fails.)
=> e2e: Save interim manifests

pkg/operator/hive/hive.go
Hard-code the previously-unpopulated .apiVersion and .kind fields so that Secret/hive-additional-ca can be deleted by controller. 
See https://issues.redhat.com/browse/HIVE-2248
=> Enable Hive to delete the hive-additional-ca Secret

docs/using-hive.md, hack/e2e-test.sh, pkg/clusterresource/aws.go, pkg/controller/clusterdeployment/installconfigvalidation_test.go, pkg/installmanager/installmanager_test.go, pkg/installmanager/testdata/install-config-with-existing-pull-secret.yaml, pkg/installmanager/testdata/install-config-with-pull-secret.yaml, pkg/installmanager/testdata/install-config.yaml
Update AWS default instance settings to match current openshift-install values.
https://issues.redhat.com/browse/HIVE-2232
=> HIVE-2232: Update AWS default instance configuration to match openshift-install values.

config/hiveadmission/deployment.yaml, pkg/operator/assets/bindata.go
Reverts openshift/hive#2015
Turns out this is not The Way.
[HIVE-2243](https://issues.redhat.com//browse/HIVE-2243)
=> Revert "Require TLS cipher min version TLSv1.3"

hack/e2e-common.sh, hack/e2e-test.sh
In b3c1262 / #2042 we changed e2e to use region us-east-2... across the board. That region doesn't exist in clouds that aren't AWS. Fix so we only specify that region for AWS, and otherwise let hiveutil pick the default.
=> e2e: Use the default region for non-AWS

contrib/cmd/hiveutil/main.go, contrib/pkg/awsprivatelink/awsprivatelink.go, contrib/pkg/awsprivatelink/disable.go, contrib/pkg/awsprivatelink/enable.go, contrib/pkg/awsprivatelink/endpointVPC.go, contrib/pkg/awsprivatelink/endpointvpc/add.go, contrib/pkg/awsprivatelink/endpointvpc/remove.go, contrib/pkg/utils/aws/aws.go, docs/awsprivatelink.md, docs/hiveutil.md, pkg/awsclient/client.go, pkg/awsclient/mock/client_generated.go, pkg/operator/hive/clustersync.go, pkg/operator/hive/configmap.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go, pkg/operator/hive/operatorutils.go
Automate the networking setup & teardown between associate VPCs & endpoint VPCs, as well as the update of HiveConfig. 
With the new subcommand, e2e tests on PrivateLink clusters can be automated as follows:
1. Create a CloudFormation stack (not necessarily in Hive cluster's region) for an endpoint VPC and get the returned stackID. Here we can use "./hack/awsprivatelink/vpc.cf.yaml" for example. 
2. Wait until the stack is successfully created. 
3. Get VPC ID and private subnet IDs from the above stack.
4. Enable PrivateLink with "hiveutil awsprivatelink enable ..." 
5. Set up networking between the new endpoint VPC & each associate VPC with "hiveutil awsprivatelink endpointvpc add ..."
6. Create a PrivateLink cluster in the region of the endpoint VPC with "hiveutil create-cluster …
=> Add awsprivatelink subcommand to hiveutil

hack/e2e-common.sh, hack/e2e-test.sh, pkg/install/generate.go, pkg/install/generate_test.go, pkg/installmanager/installmanager.go
The pod that runs the installer first copies the `openshift-install` and `oc` binaries over from their respective images. It makes sense to run these copies in InitContainers rather than regular Containers:
- The real container no longer needs explicit logic to wait for those files to appear.
- Debugging is a bit simpler: you no longer need to gain the tribal knowledge that the `hive` container is the one doing the real work.
- You no longer need to specify a container when requesting logs.
- Previously if those copies failed, the `hive` container would sit around waiting for them until the pod deadline finally killed it. Now if they fail, the pod will fail right away.
Note that we may incur a slight wall-clock time penalty: InitContainers run synchronously and serially before Containers …
=> Provision: Copy CLI tools in InitContainers

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
Current implementation didn't account for labels that could have empty string as a value. Allow for such labels from MachinePool and remote MachineSet to be carried over to the generated MachineSet.
xref: https://issues.redhat.com/browse/HIVE-2268
=> Allow labels with empty value to carry over

hack/bundle-gen.py
When opening PRs, bundle-gen will re-use one of the repositories cloned earlier to save a clone.  However, the origin of this repository points to the upstream reposistory instead of the fork repository.
/cc @lleshchi @2uasimojo 
/assign @lleshchi
=> bundle-gen.py: Set the url of the origin remote unconditionally

hack/bundle-gen.py
We were using the wrong annotation to discover the channel of a given bundle. This resulted in `replaces` pointing to an incorrect version, and the bundles wouldn't pass CI. Fix.
[HIVE-1658](https://issues.redhat.com//browse/HIVE-1658)
=> bundle-gen: Fix channel discovery for get_previous_version

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
With recent installer changes to accommodate zones in vSphere, the name of the default worker pool in OCP 4.13+ is now suffixed with a `-0` even when only one zone is in play. Hive's day 2 MachinePool logic needs to be able to generate the correct MachineSet name when talking to a 4.13+ cluster -- but also when talking to a 4.12- cluster. This commit adds in a special case to discover and account for this difference where it exists.
[HIVE-2254](https://issues.redhat.com//browse/HIVE-2254)
=> MachinePool: hack name of vSphere default worker MachineSet

hack/run-hive-locally.sh, pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/clustersync/clustersync_controller.go
Quoting from the `usage` function:
"The script runs a Hive component (hive-opeartor or hive-controllers) locally,
simulating in-cluster environment. It records the current in-cluster Hive configurations,
scales down the selected component, then runs it locally with the same environment.
On pressing ctrl + c, the script is stopped and relevant components are scaled back up.
Warnings:
- The active cluster may be in use, in which case the script could interfere with its functioning.
Notes:
- Artifacts (in-cluster Hive configurations and log files), if produced, are stored in the --artifacts_folder
which is removed after the script ends if the --cleanup_artifacts is specified.
- Selecting hive-controllers runs all Hive controllers (including hive-clustersync) together
as a single replica.
- …
=> Run Hive components locally 

apis/hive/v1/machinepool_types.go, pkg/controller/machinepool/gcpactuator.go, pkg/controller/machinepool/machinepool_controller.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
Add support for overriding the VM image used for GCP MachinePools via the `hive.openshift.io/image-id-override` annotation, which was previously only available for AWS.
This is (still) not part of the official API.
[HIVE-2275](https://issues.redhat.com//browse/HIVE-2275)
=> MachinePool/GCP: support image override annotation

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
Resolve a long-standing TODO which allows AWS environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to be used when present, even if a credentials file exists, as the gods intended.
hiveutil already uses the appropriate logic such that, if a creds file is not supplied, it looks for the env vars. We just needed to fix it so we don't pass that arg in at all if the env vars are set.
(This was an incidental requirement of [HIVE-2234](https://issues.redhat.com//browse/HIVE-2234): the AWS credentials from the hypershift installation were taking precedence for managed DNS, which then bounced because the expected hosted zone is in a different account.)
=> e2e (AWS): Allow env var to override creds file

hack/e2e-common.sh, hack/e2e-pool-test.sh
- Allow the `REGION` environment variable to override the default region (`us-east-2`) used for the AWS path in e2e.
- Add the region arg to the clusterpool path in e2e-pool. This used to default to `us-east-1` when omitted. Now it will default to `us-east-2` via the same code path as above; but it can also be overridden by the `REGION` env var.
=> e2e (AWS): Allow region override

pkg/controller/utils/logtagger_test.go
Allow various tests which were not running to run.
Correct some minor formatting errors.
=> Remove leftover debugging statement in tests

Dockerfile.ubi
We use the `tar` command to package up the results of `oc adm must-gather` when install fails. It used to be included in ubi-minimal (I swear), but isn't anymore. Install it explicitly.
[HIVE-2288](https://issues.redhat.com//browse/HIVE-2288)
=> Add `tar` to installer image

hack/e2e-common.sh
Our e2e suite for AWS was setting a default base domain that (AFAIK) we don't have control over, so we were overriding it in the test config. We've recently switched to a new AWS account for these tests. Change the default base domain accordingly so we don't need to override it in the test config.
[HIVE-2259](https://issues.redhat.com//browse/HIVE-2259)
=> e2e (AWS): Default BASE_DOMAIN for new CI account

hack/e2e-pool-test.sh
Goal: reduce e2e-pool wallclock time by ~35m.
Problem Statement: When ClusterPool inventory
(ClusterDeploymentCustomization) testing was added to e2e-pool (4fddbe7 / #1672), it triggered ClusterPool's staleness algorithm such that we were actually wasting a whole cluster while waiting for the real pool to become ready. Grab a cup of coffee...
To make the flow of the test a little bit easier, we were creating the real pool, then using its definition to generate the fake pool definition -- which does not have inventory -- and then adding inventory to the real pool.
But if you add or change a pool's inventory, we mark all its clusters stale. So because of the flow above, when we initially created the real pool without inventory, it started provisioning a cluster. Then when we updated it …
=> e2e-pool: Start real pool provisions after inventory added

contrib/pkg/clusterpool/clusterpool.go, contrib/pkg/createcluster/create.go, hack/e2e-common.sh, hack/e2e-test.sh, pkg/clusterresource/aws.go, pkg/clusterresource/builder_test.go, pkg/controller/clusterpool/clusterpool_controller.go, test/e2e/postinstall/machinesets/infra_test.go
This commit cleans up how we handle instance types in hiveutil and e2e CI.
- `hiveutil create-cluster` now accepts an `--aws-instance-type` option.
- The default instance type is now `m6i.xlarge`. It was previously `m5.xlarge` for hiveutil and `m4.large` for the MachinePool scaling tests in our e2e CI.
- This default now lives in one place, so it's easier to change later without missing things.
- To allow easier noodling via CI rehearsals, `e2e` will feed a new `$AWS_INSTANCE_TYPE` environment variable through to the new `--aws-instance-type` param for `create-cluster`.
[HIVE-2235](https://issues.redhat.com//browse/HIVE-2235)
=> Consolidate and bump default AWS instance type (m6i.xlarge)

hack/e2e-pool-test.sh
We've been seeing some weird timeouts in e2e-pool where the test itself succeeds, but clusterclaim deletion hangs until the job times out and is killed by the monitor. Previously we had no good way to debug this because we had last captured manifests & logs *before* issuing the clusterclaim deletion.
With this commit, we:
- Do that deletion (and that of the clusterpools) in the background.
- Re-capture logs and manifests periodically while we're waiting for cleanup to complete.
=> e2e-pool: Improve cleanup artifact gathering

contrib/pkg/awsprivatelink/enable.go
user.Current() errors out when the binary runs as an unknown user (no entry in /etc/passwd), which is the case when running in Openshift. 
https://github.com/golang/go/issues/38599
=> Fix hiveutil awsprivatelink bug caused by unknown user

hack/e2e-pool-test.sh
It turns out we weren't actually disabling managed DNS for e2e-pool -- see https://github.com/openshift/release/pull/42172. However, attempting to do so revealed a timing problem which was being papered over: We were using `oc wait` to wait for the controllers to become ready, but hive-operator hadn't yet gotten a chance to create those deployments. (When we were enabling managed DNS, that process took some time *and* waited for those deployments, so we never noticed.)
With this commit, after waiting for the hive-operator deployment itself to become Available, we then wait for HiveConfig to report Ready, indicating that the operator has created the deployments.
=> e2e-pool: Better wait for controllers to be ready

pkg/controller/clusterpool/clusterpool_controller.go
Fix how Hive sorts un-assigned clusters in a ClusterPool. 
@2uasimojo 
https://issues.redhat.com/browse/HIVE-2292
=> Bug fix -- sorting

hack/e2e-common.sh, hack/e2e-pool-test.sh, hack/e2e-test.sh
We want cleanup to be best-effort, and we don't want failures therein to blow the whole test up if it already succeeded otherwise. `set +e` in all exit traps.
=> e2e: unset exit-on-error during cleanup

hack/e2e-pool-test.sh
hiveutil still defaults the base domain to new-installer.openshift.com, which is probably what we want since we (hive engineers) are the ones invoking it by hand, using the hive-team cluster as a hub, and will thus prefer less typing.
But now that we're switching to a new AWS account for CI, we want the AWS-based e2e suites to use the new base domain. We recognize and default a `$BASE_DOMAIN` variable for e2e itself, but weren't yet plumbing it through to e2e-pool. Fix.
[HIVE-2259](https://issues.redhat.com//browse/HIVE-2259)
=> e2e-pool: Plumb in BASE_DOMAIN

pkg/clusterresource/builder.go, pkg/controller/clusterdeployment/installconfigvalidation_test.go
Installer will default the network type to OVNKubernetes if not specified. We have been overriding it to OpenShiftSDN in the clusterresource builder used for hiveutil and thus e2e. This commit removes that override, letting the installer default it for resources provisioned through those code paths.
=> Use default network type

pkg/controller/clusterdeployment/clusterdeployment_controller.go
Due to the controller-runtime update to v0.15.0, reconcile for cluster install now requires a Reconciler to have a Manager field in order to create a KindSource using it's cache.
Add Manager field to ReconcileClusterDeployment object.
[HIVE-2296](https://issues.redhat.com//browse/HIVE-2296)
=> Add manager field to ReconcileClusterDeployment object

hack/e2e-test.sh, pkg/controller/unreachable/unreachable_controller.go, pkg/controller/unreachable/unreachable_controller_test.go, pkg/remoteclient/fake.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/mock/remoteclient_generated.go, pkg/remoteclient/remoteclient.go
With the controller-runtime upgrade from 8cfdccaec, our remote client `Builder` interface's `Build()` method got lazier. Before, if the remote client was unreachable, `Build()` itself would fail. Now it won't fail until the resulting client is actually used. This resulted in our "unreachable" controller incorrectly marking the ClusterDeployment's APIURLOverride as reachable when it wasn't, which had the ripple effect of making the clustersync controller fail early by trying to use that URL rather than falling back to the default.
This was exposed in situations where the DNS for the APIURLOverride was being configured via a syncset: the clustersync controller tried to use a URL that wouldn't resolve, so it couldn't sync the resource that would make that DNS work.
To fix, this commit adds a …
=> Add and use Reachable() in (remote client) Builder

apis/hive/v1/machinepool_types.go, config/crds/hive.openshift.io_machinepools.yaml, docs/using-hive.md, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go, pkg/controller/utils/taints.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
With implementing the merging of MachinePool Labels and Taints, we lost the ability to sync and update based on MachinePool.Spec. To fix this, we add two new statusfields to MachinePool: OwnedLabels and OwnedTaints. These keep track of the labels and taints that were added to the remote MachineSets at the behest of this MachinePool. Conversely, this allows us to identify which ones were added on the remote side, and thus shouldn't be touched by our controller.
We also fix the logic for matching taints, which are "keyed" by the combination of the Key and Effect fields.
To summarize the behavior with this commit in play:
- Labels and taints listed in MachinePool.Spec are synced to the remote MachineSets.
- Labels and taints that are *not* in MachinePool.Spec are removed from the remote …
=> Properly handle MachinePool Labels and Taints

pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go, vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go, vendor/github.com/openshift/installer/pkg/destroy/aws/shared.go
In case we want to add some debug statements to installer destroy code for [HIVE-2297](https://issues.redhat.com//browse/HIVE-2297)
=> Adding Temporary debug logs to vendored installer destroy code

pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go, vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go, vendor/github.com/openshift/installer/pkg/destroy/aws/shared.go
This partially reverts #2102 / 8b12180d.
We are finished debugging vendored installer code, so restore the vendor directory to its pristine state. This should fix `verify`.
To lockstep with Clusters Service, who needs to refresh their hive/apis version, we are **leaving the immutable clusterMetadata webhook check disabled** and toggling the unit tests so `unit` and `coverage` will pass.
This should allow merges to master to resume in the normal fashion.
TODO: Revert the webhook bypass and corresponding test changes once CS has been updated.
[HIVE-2297](https://issues.redhat.com//browse/HIVE-2297)
=> Refresh vendor, temporarily "fix" webhook CI

hack/grafana-dashboards/grafana-dashboard-hive-slo.configmap.yaml
When exporting the JSON of an existing dashboard, it was chosen with an option `Export externally`, which has made it incompatible with the predefined variables that are define in the app-interface repo.
=> Fix grafana dashboard

pkg/controller/unreachable/unreachable_controller.go, pkg/controller/unreachable/unreachable_controller_test.go, pkg/remoteclient/fake.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/mock/remoteclient_generated.go, pkg/remoteclient/remoteclient.go, pkg/remoteclient/remoteclient_test.go
With the controller-runtime upgrade from 8cfdcca, our remote client
`Builder` interface's `Build()` method got lazier. Before, if the remote
client was unreachable, `Build()` itself would fail. Now it won't fail
until the resulting client is actually used. This resulted in our
"unreachable" controller incorrectly marking the ClusterDeployment's
APIURLOverride as reachable when it wasn't, which had the ripple effect
of making the clustersync controller fail early by trying to use that
URL rather than falling back to the default.
This was exposed in situations where the DNS for the APIURLOverride was
being configured via a syncset: the clustersync controller tried to use
a URL that wouldn't resolve, so it couldn't sync the resource that would
make that DNS work.
Initially, to fix this …
=> Revert builder.Unreachable() and add reachable check to builder.Build()

pkg/util/scheme/scheme.go
This was missed in #2052 / 26a0b814.
[HIVE-2308](https://issues.redhat.com//browse/HIVE-2308)
=> Register OpenStackProviderConfig/v1alpha1 with master scheme

apis/hive/v1/aws/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Mirror the installer's new AdditionalSecurityGroupIDs field (see openshift/installer#7151) into hive's MachinePool CRD. Plumb it into the installer's provider code so the additional SGIDs are included in generated MachineSets.
Note:
There's a back door, added via #1743 / a028ecd0 and refined via #1767 / cdf36016, whereby a (single) additional security group can be added by name. It is mutually exclusive with this feature: if you try to use both, your MachinePool will get the UnsupportedConfiguration condition. (We probably didn't *need* to make the two things mutually exclusive, but we did anyway.)
[HIVE-2306](https://issues.redhat.com//browse/HIVE-2306)
=> MachinePool (AWS): AdditionalSecurityGroupIDs

pkg/remoteclient/fake.go, pkg/remoteclient/remoteclient.go
Fake clusters report their version based on a dummy CVO incorporated into their special remote client builder. Previously we were hardcoding that value to "4.6.8" in that builder. With this commit, we plumb in the value from cd.status.installVersion -- which gets set by the imageset/installer process even for fake clusters. So now if you watch the `VERSION` field for a fake cluster, it behaves the same as for a real cluster: empty until the cluster is `Provisioned` and the clusterversion controller kicks in again, whereupon it is set to the correct value based on the input release image.
[HIVE-2312](https://issues.redhat.com//browse/HIVE-2312)
=> Fix fake cluster version

apis/hive/v1/machinepool_types.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
This commit fix 2 typos:
- Field-tags for MachinePool TaintIdentifier had a colon before omitempty instead of a comma
- When making a slice for OwnedTaints as a part of update, set it to the length of unique taints instead of MachinePool spec.taints, as Machinepool could have duplicate taints which will not be migrated to OwnedTaints
xref: https://issues.redhat.com/browse/HIVE-2268
=> Fix field-tag of MachinePool TaintIndentifier

apis/hive/v1/gcp/machinepools.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/gcpactuator.go, pkg/controller/machinepool/gcpactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
Add NetworkProjectID to the GCP Platform section of MachinePool and plumb it through to the generated MachineSets. This is in support of XPN (shared VPC).
[HIVE-2310](https://issues.redhat.com//browse/HIVE-2310)
=> MachinePool (GCP): Add NetworkProjectID 

pkg/controller/unreachable/unreachable_controller.go, pkg/controller/unreachable/unreachable_controller_test.go, pkg/remoteclient/fake.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/mock/remoteclient_generated.go, pkg/remoteclient/remoteclient.go, pkg/remoteclient/remoteclient_test.go
Backport [#2109](https://github.com/openshift/hive/pull/2109)
[HIVE-2300](https://issues.redhat.com//browse/HIVE-2300)
=> mce-2.4: Revert builder.Unreachable() and add reachable check to builder.Build()

pkg/controller/hibernation/hibernation_controller.go
Today when an AWS API call fails during hibernation, the "Hibernating" ClusterDeployment status condition is updated with the error message. Sometimes this message is sent through a scrubber to ensure it does not cause thrashing if it happens to be unique every time (e.g. if it includes a timestamp or transaction ID). One example is an authorization failure, e.g. when the IAM user lacks a necessary role to perform the API action. In such cases, the encoded failure message is redacted for purposes of the status condition. The full (encoded) message is in the logs... but the user doesn't necessarily know that. So with this commit, we tell them by adding a little note to the status condition message.
[HIVE-2319](https://issues.redhat.com//browse/HIVE-2319)
=> Refer to logs for AWS auth errors

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
* IngressOperatorDegraded is a more pertinent install failure reason than the existing AuthenticationOperatorDegraded as it is often the root cause of other degraded operators.
* AWSSubnetInsufficientIPSpace is a failure condition that can be immediately sent to the customers to remediate without paging SRE.
[OSD-19003](https://issues.redhat.com//browse/OSD-19003)
=> New install failures reasons IngressOperatorDegraded and AWSSubnetInsufficientIPSpace

pkg/resource/apply.go
When hive applies objects -- notably for [Selector]SyncSets, but also as hive-operator lays down resources such as controller Deployments, webhook configurations, etc. -- we call into k8s library code used by `kubectl apply`. This has some quirks around the
`kubectl.kubernetes.io/last-applied-configuration` annotation which, under certain circumstances, could cause our apply-er to fail with this annoying error:
```
error when patching "object": <thing> is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
There were several possible solutions (see linked card), but the one we're using in this commit is to use (the code equivalent of) the `--force` option, which disregards resourceVersion conflicts.
Note that this may result in race conditions under …
=> Use force when applying objects (for clustersync et al)

pkg/client/applyconfiguration/hive/v1/taintidentifier.go
Still don't know what applyconfiguration is or does, but `make update` made this change that looks like it should have been swept up in #2112.
[HIVE-2268](https://issues.redhat.com//browse/HIVE-2268)
=> Fix TaintIdentifier fields in applyconfiguration

config/clustersync/statefulset.yaml, pkg/operator/assets/bindata.go
Get rid of annoying log messages and potential future inability to stand up clustersync pods.
=> clustersync: fix pod security

apis/hive/v1/vsphere/machinepools.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/vsphereactuator.go, pkg/controller/machinepool/vsphereactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/vsphere/machinepools.go
xref: [HIVE-2090](https://issues.redhat.com//browse/HIVE-2090)
This will allow a user of hive to supply their own resource pool as part of the spec
=> HIVE-2090: Add ResourcePool field to hive's MachinePool CRD

pkg/controller/metrics/custom_collectors.go, pkg/controller/metrics/custom_collectors_test.go, pkg/controller/metrics/metrics.go, pkg/controller/metrics/metrics_with_dynamic_labels.go
- Add label that reports the status of unreachable condition for the corresponding ClusterDeployment
- Add optional label support
- Use the existing implementation for dynamic labels wherever possible
- MustNewConstMetric used to report this metric via custom collector does not accept a map of label-value pairs. So supply a slice of values for the corresponding labels instead. To achieve this, maintaining the order of labels used while defining the metric is important.
- Add a wrapper struct around dynamic labels which, in addition to the fixed and optional labels, also stores the labelList
- Add buildLabelSlice method which is logically similar to buildLabels, but instead of reporting a map of labels and values, uses the labelList and returns a slice of label values to be used while …
=> Add labels to ClusterSyncFailing metric

config/clustersync/statefulset.yaml, pkg/operator/assets/bindata.go
Reverts openshift/hive#2127
...which apparently breaks KIND.
Closes #2145
=> Revert "clustersync: fix pod security"

contrib/pkg/deprovision/gcp.go
This was missed in #2151.
[HIVE-2334](https://issues.redhat.com//browse/HIVE-2334)
=> Pass networkProjectID to destroyer

pkg/install/generate.go
This was *also* missed in #2151.
[HIVE-2334](https://issues.redhat.com//browse/HIVE-2334)
=> Add --network-project-id param to GCP destroyer command

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Yet another miss from #2151
Also add some UT for these snowflake ClusterDeprovision fields for AWS, Azure, and GCP.
[HIVE-2334](https://issues.redhat.com//browse/HIVE-2334)
=> Plumb GCP NetworkProjectID through ClusterDeprovision

pkg/installmanager/installmanager.go, pkg/installmanager/installmanager_test.go
installmanager_test takes an annoyingly, unnecessarily long time because there are several `time.Sleep()`s in the installmanager code.
This commit moves the sleep function to the InstallManager struct so we can fake it out with a no-op in the test suite.
=> Spoof Sleep() for installmanager_test

pkg/constants/constants.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterprovision/clusterprovision_controller.go, pkg/install/generate.go, pkg/installmanager/installmanager.go
Certain environments, like ARO:
- Always use InstallerImageOverride
- Don't care to must-gather spokes on install failures
The latter is the only thing we use the `oc` command for. And the release image is only used to discover the URI for the installer image and the `oc` image.
To reduce burdens like ensuring those images are available and secure, this commit introduces a (back door, not-officially-supported) "minimal install mode". Activate it by doing two things:
1. Set ClusterDeployment annotation `hive.openshift.io/minimal-install-mode: True`
2. Set `ClusterDeployment.Spec.Provisioning.InstallerImageOverride`
This will cause hive to wend its way through the provisioning flow without pulling the release or `oc` images. It will use the InstallerImageOverride as the source of the …
=> Minimal install mode (don't pull release or oc images)

config/configmaps/install-log-regexes-configmap.yaml, pkg/operator/assets/bindata.go
We found another way an AWS cluster's default EBS KMS Key can be misconfigured in [OSD-19693](https://issues.redhat.com//browse/OSD-19693)
```
time="2023-11-15T13:06:50Z" level=error msg="Error: waiting for EC2 Instance (i-0e4febdf8a337aa30) create: unexpected state 'shutting-down', wanted target 'running'. last error: Client.InvalidKMSKey.InvalidState: The KMS key provided is in an incorrect state"
```
=> Add additional regex for DefaultEbsKmsKeyInsufficientPermissions

pkg/constants/constants.go, pkg/imageset/updateinstaller.go, pkg/imageset/updateinstaller_test.go
We find the image we use to obtain the `openshift-install` binary based on its name in release metadata.
```
{
"name": "installer",   <== THIS NAME
"annotations": {
"io.openshift.build.commit.id": "ead355d7836a8a24613d062bf06ab0a6eef2765c",
"io.openshift.build.commit.ref": "",
"io.openshift.build.source-location": "https://github.com/openshift/installer"
},
"from": {
"kind": "DockerImage",
"name": "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b2942182a31a0591dcbf3a3eec10c363d9d1f05dd75b98e1f8ac7f486b0ce25e"
},
"generation": null,
"importPolicy": {},
"referencePolicy": {
"type": ""
}
},
```
By default, we use the image identified as `"installer"`; or `"baremetal-installer"` for bare metal installations.
Alternative or experimental installer images may be included in certain …
=> Annotation to override installer image name

pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go
Remove the code to clean up legacy SyncSetInstance CRs and CRD, which were supplanted by ClusterSync via #1093 ~3y ago.
The consequence is that, if a customer upgrades from a pre-ClusterSync version of hive to a version at/after this commit, the SyncSetInstance CRs and CRD will be orphaned, unnecessarily cluttering etcd.
It has been long enough that we consider the probability of this to be quite low. If it does happen, there is a simple workaround: manually delete the CRs and CRD.
Why do this at all? I'm glad you asked. Since the SyncSetInstance CRD existed in the now-deprecated v1beta1 apiVersion of apiextensions.k8s.io, our API call to discover it was showing up on customers' radar and making them uncomfortable. At this point the risk of orphaning resources is the lesser evil. …
=> Remove SyncSetInstance cleanup code

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
These were showing up as `FallbackInsvalidInstallConfig` with a generic message. Make them more specific/scrutable/actionable.
[HIVE-2360](https://issues.redhat.com//browse/HIVE-2360)
=> Add install log regexes for cert-related network failures

build/build-image/Dockerfile
[HIVE-2197](https://issues.redhat.com//browse/HIVE-2197)
=> Prompt CI to bump to golang 1.21

docs/enhancements/cluster-install-apis.md
CRDs implementing the ClusterInstall contract must be labeled with `contracts.hive.openshift.io/clusterinstall: "true"` in order to be considered valid.
cc @2uasimojo
=> Add documentation for registering new ClusterInstall implementations

Dockerfile, Dockerfile.ubi, apis/go.mod, apis/go.sum, docs/developing.md, go.mod, go.sum, vendor/modules.txt
[HIVE-2197](https://issues.redhat.com//browse/HIVE-2197)
=> Bump to go 1.21

docs/hive_metrics.md
It can be confusing for consumers wanting to add labels to metrics with optional label support without being aware of the fixed labels already reported by those metrics, this commit documents the same to resolve the problem.
There's also the fix for cluster sync failing metric - recently it allows additional labels but document update was pending.
=> Add Fixed Labels to metrics doc

hack/update-codegen.sh
fix 2 parts in update.codegen.sh:
1. change to gsed on MAC env
2. fix the trap after exit
=> fix vendor is not put back and failed on MAC env after run update-codegen.sh

config/clustersync/statefulset.yaml, config/controllers/deployment.yaml, config/hiveadmission/deployment.yaml, config/operator/operator_deployment.yaml, hack/app-sre/saas-template.yaml, pkg/operator/assets/bindata.go
Add `readOnlyRootFilesystem` to our Deployments and StatefulSets. Why? Cause it's more securer.
One thing I needed to do to make this work was to add a volume for `/tmp`, which I guess is by default part of `/`. This resulted in an actual problem in hive-controllers creating a Session for AWS... but I did it for all the things just in case.
This scares me a little bit. For one thing, any time we mess with `securityContext`s we seem to break our friends running hive under vanilla k8s. But also, who knows what corner cases are expecting to be able to write somewhere in the root file system? We won't find out if, like, trying to use additional certs under OpenStack is a problem until some customer tries it.
[HIVE-2350](https://issues.redhat.com//browse/HIVE-2350)
=> Read-only root file system

apis/hive/v1/syncset_types.go, config/crds/hive.openshift.io_selectorsyncsets.yaml, config/crds/hive.openshift.io_syncsets.yaml, docs/syncset.md, hack/app-sre/saas-template.yaml, pkg/client/applyconfiguration/hive/v1/selectorsyncsetspec.go, pkg/client/applyconfiguration/hive/v1/syncsetcommonspec.go, pkg/client/applyconfiguration/hive/v1/syncsetspec.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go, pkg/controller/clustersync/templates.go, pkg/test/syncset/syncset.go, vendor/github.com/openshift/hive/apis/hive/v1/syncset_types.go
Via a new knob, `[Selector]SyncSet.Spec.EnableResourceTemplates: True`
(that's a bool), it is now possible to use golang
[text/template](https://pkg.go.dev/text/template)-isms in `[Selector]SyncSet.Spec.Resources[]` string values (not keys! do you need that?). Note, however, that there is no "dot" (data object) so the out-of-the-box functionality won't convey a lot of power.
However, this commit introduces one custom function: `fromCDLabel`. If you include a string like
`{{ fromCDLabel "any.clusterdeployment/label-key" }}`
in a resource, hive will substitute it with the value of that label from the ClusterDeployment owning the [Selector]SyncSet being processed. For example:
```yaml
---
apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
name: mygroup
spec:
clusterDeploymentRefs:
- …
```
=> SyncSet: Parameterized CD labels in resources

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/openstackactuator.go, pkg/controller/machinepool/openstackactuator_test.go
Another attempt to address the move of OpenstackProviderSpec from cluster-api-provider-openstack to openstack/api/machine. See #2117 for background. In that PR, we simply replaced our imports. The result is that we could only decode the _new_ thing. The problem is that we may still get the _old_ thing if we're talking to an old cluster.
We only need the decoding to steal the osImage from the master machines so we can use that value for new workers. Rather than importing both schemata, trying to figure out which version we're talking to, and decoding against the correct one, this commit unmarshals the providerSpec as raw JSON into an Unstructured object and explicitly paths into it map-wise.
On the creation side, we're told that the spoke cluster itself will understand the new thing even …
=> Unstructured OpenstackProviderSpec

hack/e2e-test.sh
To save internal cost, reduce the `compute` pool to one replica.
[HIVE-2420](https://issues.redhat.com//browse/HIVE-2420)
=> Use 2 workers for e2e spoke

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
Our algorithm to spread MachinePool.Spec.Autoscaling.MinReplicas and .MaxReplicas across spoke MachineAutoscalers previously assumed that it was sane to create one MachineAutoscaler per AZ and set maxReplicas to zero if that's what our computation came out with.
Not so.
MachineAutoscaler.Spec.MaxReplicas -- in contrast to MachineSet.Spec.Replicas -- is [not allowed to be zero](https://github.com/openshift/cluster-autoscaler-operator/blob/67999a5e79d0200ee0a4aab3dcfbfd18e097b514/pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go#L18).
The resulting behavior would manifest as a hive-controllers error similar to:
```
time="2024-02-21T16:33:56.802Z" level=error msg="unable to create machine autoscaler" controller=machinepool error="MachineAutoscaler.autoscaling.openshift.io …
```
=> Allow MachinePool autoscaler maxReplicas < #AZs

contrib/pkg/createcluster/create.go, hack/e2e-common.sh, hack/e2e-test.sh, pkg/clusterresource/aws.go, test/e2e/postinstall/machinesets/infra_test.go
For cost savings:
- Change the default AWS instance type we use for `hiveutil create-cluster` and clusterpools from m6i.xlarge to m6a.xlarge. These have the same specs, but we're told `i`(ntel) is more expensive than `a`(md).
- Plumb a new `--aws-worker-instance-type` flag into `hiveutil create-cluster` to allow customizing _just_ the worker instance type in the generated install-config and machine pool. If unset, the previous behavior will hold: we'll use `--aws-instance-type` for (masters and) workers.
- Use the above to shrink the default worker instance type for e2e to m6a.large, which has half the CPU and memory of m6a.xlarge.
[HIVE-2426](https://issues.redhat.com//browse/HIVE-2426)
=> hiveutil create-cluster: cheaper AWS instances

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
Our algorithm to spread MachinePool.Spec.Autoscaling.MinReplicas and .MaxReplicas across spoke MachineAutoscalers previously assumed that it was sane to create one MachineAutoscaler per AZ and set maxReplicas to zero if that's what our computation came out with.
Not so.
MachineAutoscaler.Spec.MaxReplicas -- in contrast to MachineSet.Spec.Replicas -- is
[not allowed to be zero](https://github.com/openshift/cluster-autoscaler-operator/blob/67999a5e79d0200ee0a4aab3dcfbfd18e097b514/pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go#L18).
The resulting behavior would manifest as a hive-controllers error similar to:
```
time="2024-02-21T16:33:56.802Z" level=error msg="unable to create machine autoscaler" controller=machinepool error="MachineAutoscaler.autoscaling.openshift.io …
```
=> [mce-2.4] Allow MachinePool autoscaler maxReplicas < #AZs

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
Our algorithm to spread MachinePool.Spec.Autoscaling.MinReplicas and .MaxReplicas across spoke MachineAutoscalers previously assumed that it was sane to create one MachineAutoscaler per AZ and set maxReplicas to zero if that's what our computation came out with.
Not so.
MachineAutoscaler.Spec.MaxReplicas -- in contrast to MachineSet.Spec.Replicas -- is
[not allowed to be zero](https://github.com/openshift/cluster-autoscaler-operator/blob/67999a5e79d0200ee0a4aab3dcfbfd18e097b514/pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go#L18).
The resulting behavior would manifest as a hive-controllers error similar to:
```
time="2024-02-21T16:33:56.802Z" level=error msg="unable to create machine autoscaler" controller=machinepool error="MachineAutoscaler.autoscaling.openshift.io …
```
=> [mce-2.3] Allow MachinePool autoscaler maxReplicas < #AZs

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
Our algorithm to spread MachinePool.Spec.Autoscaling.MinReplicas and .MaxReplicas across spoke MachineAutoscalers previously assumed that it was sane to create one MachineAutoscaler per AZ and set maxReplicas to zero if that's what our computation came out with.
Not so.
MachineAutoscaler.Spec.MaxReplicas -- in contrast to MachineSet.Spec.Replicas -- is
[not allowed to be zero](https://github.com/openshift/cluster-autoscaler-operator/blob/67999a5e79d0200ee0a4aab3dcfbfd18e097b514/pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go#L18).
The resulting behavior would manifest as a hive-controllers error similar to:
```
time="2024-02-21T16:33:56.802Z" level=error msg="unable to create machine autoscaler" controller=machinepool error="MachineAutoscaler.autoscaling.openshift.io …
```
=> [mce-2.2] Allow MachinePool autoscaler maxReplicas < #AZs

pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go
When spot instance support was added for MachinePools, it wasn't yet available in all then-supported versions of OpenShift (4.5+). Now it is. Remove the version check, which is now dead code.
=> Tech debt: Remove AWS spot version check

pkg/OWNERS
This change will have prow apply an area/unit-tests label to any PR that changes a unit test file inside the "pkg" dir.
=> Automatically apply area/unit-tests label to PRs

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
MachineAutoscalers are not allowed to have MaxReplicas==0.
PR #2215 / bce2d472 partially fixed the scenario where a MachinePool's autoscaling maxReplicas is less than the number of AZs by causing such MAs not to be *created*. However, when reducing the MachinePool's maxReplicas to below the number of AZs, we were still trying to update *existing* MAs to have MaxReplicas==0. This commit adjusts the logic to delete them instead.
[HIVE-2415](https://issues.redhat.com//browse/HIVE-2415)
=> Delete MachineAutoscalers that would get MaxReplicas==0

apis/hive/v1/aws/machinepool.go, apis/hive/v1/aws/zz_generated.deepcopy.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/clusterresource/aws.go, pkg/clusterresource/builder.go, pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go, pkg/controller/machinepool/machinepool_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/zz_generated.deepcopy.go
[OCM-6713](https://issues.redhat.com//browse/OCM-6713)
Create AWS tags for machine pool on cluster creation time (day 1) and post-cluster creation time (day 2) on ROSA Classic.  Modification of AWS tags are out-of-scope.
Hive to support additional map of AWS tags on MachinePools
These are AWS user-defined / custom tags, not to be confused with node labels
The strategy opted for this PR is to merge the user tags with ClusterDeployment.Spec.Platform.AWS.UserTags, where the machine pool level field takes precedence when keys collide.
=> OCM-6713 | feat: allow user defined tags on machinepool creation

pkg/controller/machinepool/machinepool_controller_test.go, pkg/controller/machinepool/openstackactuator_test.go, pkg/test/machinepool/machinepool.go
In preparation for expanding OpenStack-specific MachinePool unit tests, refactor the helper funcs in the existing suite to use the MachinePool "Builder" pattern with "Options". For example, we change this:
```go
machinePool: func() *hivev1.MachinePool {
mp := testMachinePoolWithoutLabelsTaints()
mp.Spec.Labels = make(map[string]string)
mp.Spec.Labels["test-label"] = "test-value"
return mp
}(),
```
to:
```go
machinePool: testMachinePoolWithoutLabelsTaints(
testmp.WithLabels(map[string]string{
"test-label": "test-value",
}),
),
```
This makes the test code slightly tighter and more readable, and brings the suite more in line with our usual (or at least, best practice) patterns.
Facilitates [HIVE-2476](https://issues.redhat.com//browse/HIVE-2476)
=> Refactor MachinePool unit tests to use Builder/Options

apis/hive/v1/gcp/machinepools.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/gcpactuator.go, pkg/controller/machinepool/gcpactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
To facilitate machine types with GPUs, MachinePool consumers need to be able to tell those machines to terminate on reboot. Add `MachinePool.Spec.Platform.GCP.OnHostMaintenance` to populate the field of the same name on the GCP providerSpec.
[HIVE-2483](https://issues.redhat.com//browse/HIVE-2483)
=> MachinePool: Add GCP OnHostMaintenance

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
Compiling hiveutil is not for the faint of heart and the default Konflux buildah task was not up to it. The 8gb one should do it.
=> HIVE-2491: Raise the memory buildah task

.tekton/hive-mce-25-pull-request.yaml, .tekton/hive-mce-25-push.yaml
In order to build hiveutil, we need a Konflux build step with higher available memory.
=> HIVE-2492: Increase buildah memory for Konflux

pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/clusterinstalls.go
Before this commit if the Provisioned condition was not updated none of the other cluster install conditions would get copied to the cluster deployment.
This updates the logic so that other status updates are still saved even when the provisioning state does not also change.
=> Copy conditions while cluster install is provisioning

config/controllers/deployment.yaml, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeprovision/clusterdeprovision_controller.go, pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go, pkg/controller/clusterprovision/clusterprovision_controller.go, pkg/controller/clusterprovision/clusterprovision_controller_test.go, pkg/controller/utils/utils.go, pkg/imageset/generate.go, pkg/imageset/generate_test.go, pkg/install/generate.go, pkg/install/generate_test.go, pkg/operator/assets/bindata.go
We already copy `nodeSelector` and `tolerations` from hive-operator into the various controllers. But we weren't copying them into the Jobs for imageset, provision, and uninstall. This could result in their Pods e.g. being scheduled to Nodes that can't run them; or being totally unschedulable.
With this commit, we:
- Add the namespace and name of the running pod as env vars on hive-controllers.
- Use those env vars to retrieve the hive-controllers Pod spec.
- Copy the nodeSelector and tolerations from that Pod spec down into the (PodSpecs of the) Jobs for imageset, provision, and uninstall.
[HIVE-2496](https://issues.redhat.com//browse/HIVE-2496)
=> Copy nodeSelector, tolerations into Jobs

docs/troubleshooting.md
In the doc for troubleshooting, add a section that talks about looking at the cluster deployment conditions
xref: https://issues.redhat.com/browse/HIVE-2251
=> Add section for CD conditions in troubleshooting

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
Per OSD-22828, sometimes an install can fail if Terraform can't properly cleanup after itself (e.g., because the user attached the bootstrap node's security group to an unrelated network interface). While TerraformFailedToDeleteResources already covered this scenario, it seems that Terraform gives a slightly different error message in some cases, tripping up the existing regex. This PR adds an additional regex to TerraformFailedToDeleteResources that should recognize the alternative error message.
=> Add alternate regex for TerraformFailedToDeleteResources

docs/using-hive.md
xref: https://issues.redhat.com/browse/HIVE-2502
=> Document no support of vSphere static IPs with MachinePools

docs/enhancements/metricsConfig_redesign.md
xref: https://issues.redhat.com/browse/HIVE-2344
=> Enhancement for metricsConfig redesign

apis/hive/v1/aws/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/machinepool_controller.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
The MachinePool controller compares generated MachineSets with existing remote MachineSets to figure out which to add, update, or delete.
We used to do this matching based on naming conventions, but those have been changing upstream, so we recently ([HIVE-2254](https://issues.redhat.com//browse/HIVE-2254) / #2179) changed to matching by label + failure domain. The latter is extracted using code from control-plane-machine-set.
Unfortunately, in AWS, the same failure domain can contain a subnet represented in three different ways:
- ID (canonical)
- ARN (canonical; not used)
- Filters (ambiguous)
If the generated and remote MachineSets differ in either the way the failure domain subnet is represented (e.g. ID vs Filters) or both are using Filters that differ despite resolving to the same …
=> MachinePool/AWS: Match MachineSets by AZ only (not subnet)

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
This copies the golang (Re2)regular expression S that we use in prow[0] and leverages the fact that according to [1] on-cell-expression has a special "files.all" value that contains a list of all the added/modified/removed/renamed files. It also says that you can use CEL[2] expressions on those. Thus, we should only run the build if all the files in "files.all" do not match the aforementioned regular expression S.
[0] https://github.com/openshift/release/blob/ee0afebfe1ca88b8c35426120cb175fc8d989ffc/ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml#L83
[1] https://pipelinesascode.com/docs/guide/authoringprs/
[2] https://github.com/google/cel-spec/blob/master/doc/langdef.md#macros
=> HIVE-2509: Skip Konflux builds when possible

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
There are new mandatory parameters for the deprecated-base-image-check in Konflux that we need to update tekton to [0].
[0]https://github.com/konflux-ci/build-definitions/blob/main/task/deprecated-image-check/0.4/MIGRATION.md
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>
=> HIVE-2510: deprecated image check to 0.4

apis/hive/v1/aws/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/machinepool_controller.go, vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
The MachinePool controller compares generated MachineSets with existing
remote MachineSets to figure out which to add, update, or delete.
We used to do this matching based on naming conventions, but those have
been changing upstream, so we recently ([HIVE-2254](https://issues.redhat.com//browse/HIVE-2254) / #2179) changed to
matching by label + failure domain. The latter is extracted using code
from control-plane-machine-set.
Unfortunately, in AWS, the same failure domain can contain a subnet
represented in three different ways:
- ID (canonical)
- ARN (canonical; not used)
- Filters (ambiguous)
If the generated and remote MachineSets differ in either the way the
failure domain subnet is represented (e.g. ID vs Filters) or both are
using Filters that differ despite resolving to the same …
=> [mce-2.3] MachinePool/AWS: Match MachineSets by AZ only (not subnet)

pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
Within the hibernateAfter code path, if the check for InstalledTimeStamp takes place before the clusterDeployment controller reconcile has had a chance to update it (for ex, for adopted clusters - aka the clusterdeployments created with installed field set to true but the InstalledTimeStamp nil, we set it to creationTimeStamp), the code would panic. This commit adds a nil check for the same to skip computing the installedSince. The logic for calculating if Hibernation should happen tried to find the latest one amongst installedSince, claimedSince, runningSince, and should work fine with the other values present.
xref: https://issues.redhat.com/browse/HIVE-2486
=> Nil check for InstalledTimeStamp missing

Makefile
Even though they are related, podman is much more common than buildah nowadays. It makes sense to have a target for podman for rootless, daemonless builds
TODO: Add Jira reference
=> HIVE-2531: Add podman build target

apis/hiveinternal/v1alpha1/clustersync_types.go, contrib/pkg/adm/managedns/enable.go, contrib/pkg/testresource/command.go, contrib/pkg/utils/generic.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go, pkg/controller/controlplanecerts/controlplanecerts_controller.go, pkg/controller/remoteingress/remoteingress_controller.go, pkg/operator/hive/hive_controller.go, pkg/remoteclient/fake.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/mock/remoteclient_generated.go, pkg/remoteclient/remoteclient.go, pkg/resource/helper.go, pkg/resource/restconfig_factory.go, vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
xref: [HIVE-2399](https://issues.redhat.com//browse/HIVE-2399)
(copied and formatted explanation from the comments in the code)
[HIVE-2399](https://issues.redhat.com//browse/HIVE-2399): In the cluster sync controller, `getRESTConfigFactory` is called once per reconcile loop. Previously, a `restConfigClientGetter` was created for every reconcile, used to apply (or rather, attempt to apply) various synced objects, and then thrown away at the end of the reconcile pass.
The `restConfigClientGetter` (or more accurately, the  `cmdutil.Factory` that wraps it) is used by the cluster sync controller (via the resource `helper`) to apply the various objects to the target cluster during the syncing process. During the application process (see `apply.go`), the apply command is set up (aptly named …
=> HIVE-2399: Reuse restConfigClientGetter when creating cmdutil.Factory

build/build-image/Dockerfile
Reverts openshift/hive#2305
We're having trouble (understanding and) executing the multi-step process to get this bumped in hive and CI, and we need to get other commits merged while we figure it out.
=> Revert "HIVE-2400: Bump build-image to rhel9"

apis/hive/v1/hiveconfig_types.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, pkg/constants/constants.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/machinepool/machinepool_controller.go, pkg/operator/hive/clustersync.go, pkg/operator/hive/hive.go, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
In addition to `Watch()`ing the local MachinePool and ClusterDeployment objects, the machinepool controller also sets up a poll. Previously the interval was hardcoded to 30m. With this commit, we retain that as the default, but allow it to be tuned via a new field: `HiveConfig.Spec.MachinePoolPollInterval`.
This is a Duration string -- e.g. `"30m"`. If set to zero or less (e.g. `"0m"`) we won't poll at all.
[HIVE-2536](https://issues.redhat.com//browse/HIVE-2536)
=> Make MachinePool poll interval tunable

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
With these unsorted, it was possible to thrash MachinePools.
[HIVE-2541](https://issues.redhat.com//browse/HIVE-2541)
=> machinepool: sort ownedLabels, ownedTaints

Makefile, hack/app-sre/generate-saas-template.py, hack/bundle-gen.py, hack/statuspatch
New builder images do not alias python to python3
=> HIVE-2400: fix obsolete python references

pkg/install/generate.go
In #2260 we changed how we're invoking the openshift-install binary.
Before: Copy openshift-install into the hive container and run it via `/usr/bin/hiveutil install-manager`
After: Copy hiveutil into the installer container and run installer via `/output/hiveutil.rhel$VER install-manager`
What we missed was that, for STS flows, we inject an AWS credentials file containing a `credential_process` that invoked `/usr/bin/hiveutil install-manager aws-credentials` -- but `hiveutil` no longer lives there.
Fix.
[HIVE-2400](https://issues.redhat.com//browse/HIVE-2400)
=> Fix AWS STS for RHEL8/9 transition

pkg/operator/hive/sharded_controllers.go
Since splitting out the MachinePool controller via #2341, the MachinePool controller was failing to authenticate to AWS for clusters configured with STS/AssumeRole:
```
error="could not generate machinesets: processing subnets: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```
This is because we forgot to add the
`HIVE_AWS_SERVICE_PROVIDER_CREDENTIALS_SECRET` env var to the split-out controller pods. Fix.
[HIVE-2537](https://issues.redhat.com//browse/HIVE-2537)
=> MachinePool controller: Add env for AssumeRole

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
The upcoming OpenShift Pipelines which will be deployed shortly has stricter validations on Pipelines and Task manifests. Clamav would fail the new validations. This commit should make us ready.
Fixes: #[HIVE-2563](https://issues.redhat.com//browse/HIVE-2563)
=> fix(build): update to the fixed clamav image

cmd/manager/main.go
I have no idea why this package was imported, but, at present, importing this package imports a [single Go file](https://github.com/openshift/generic-admission-server/blob/8dcc3c9b298fefaf4d31c60001907222bf2c3f83/pkg/cmd/cmd.go) which does not have an init function, but, does pull in other packages that eventually do have init functions.
The result of this being imported in `main.go` is that it ends up calling the component base metrics workqueue stuff first, which means the controller-runtime stuff doesn't win the race currently.
This removal could have unintended side effects if there are other `init` functions that we are relying on, but it does remove the component-base workqueue metrics from the init tree, fixing the metrics issue at hand. If there are other `init`s that we are …
=> Remove redundant import of generic admission server cmd

Dockerfile, Makefile
perf(build): Build hiveutil only for RHEL8
In the hive operator image we take all the binaries from the RHEL9 stage
and only hiveutil from the RHEL8 stage. Thus, we waste a lot of time
building the non-hiveutil Go components. This commit:
- Adds a build-machinery-go using target to build only hiveutil
- Changes the Dockerfile to build only the new target for RHEL8
fix(build): Drop obsolete build-image call
This build-machinery-go call was referencing a no longer existing:
/build/build-image/Dockerfile
fix(build): Drop dnf updates from image build
In order to progress towards hermetic builds, i.e., builds that do not
need to access the internet and can have a prepared list of RPMs to be
supplied, we need to drop the dnf update which can take any random
package and update it.
To sum up, …
=> Build improvements

Dockerfile, Makefile
This prevents the hiveutil go compilation from ending up in too many open files error in both podman, buildah and Konflux.
=> HIVE-2571: fixing build not to end up erroring out on too many open files

pkg/controller/argocdregister/argocdregister_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/cleanup.go, pkg/controller/clusterclaim/clusterclaim_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterinstalls.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/utils/secrets.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/remoteclient.go
Users with write access to the admin kubeconfig Secret for a given ClusterDeployment should not be able to execute arbitrary code in the privileged environment in which we run the controllers that use those Secrets. Funnel all code paths that load such Secrets through a validator to ensure that the AuthInfos[].Exec path is not used.
[HIVE-2485](https://issues.redhat.com//browse/HIVE-2485)
=> Forbid kubeconfig exec

.snyk
Due to the chaotic go-client history with tags, snyk misidentifies our go-client version as not meeting the minimum version containing a couple of fixes. This commit introduces entries in .snyk to ignore them.
=> fix(snyk): Ignore go-client misreporting

contrib/pkg/utils/aws/aws.go, docs/awsprivatelink.md
In the terraform based installer, the worker security group was named INFRA_ID-worker-sg. However, when the installer transitioned to the CAPI based installer, the worker security group name became INFRA_ID-node. As a result, the hiveutil awsprivatelink endpoint command failed to find the security group.
This change adds the new name in addition to the old one so that both formats will be found when searching for the worker security group.
=> HIVE-2565: hiveutil awsprivatelink to be compatbile with CAPI based installer

pkg/awsclient/client.go
A previous commit (#2306 / 13ea4f47) put in checks to forbid the use of `credential_process` in AWS config/credentials files. It turns out that AWS accepts this key case-insensitively, so this commit updates our checks accordingly.
[HIVE-2485](https://issues.redhat.com//browse/HIVE-2485)
=> AWS: Forbid case-insensitive `credential_process`

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
This is a cherry-pick of #2373 that undoes the removal of the CEL filtering. That PR was created through the Konflux UI asking it to create a branch new config (so the new template would be used).
=> fix(builds): Update tekton files

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml, Dockerfile
In order to be able to download non ubi packages in the konflux builds, we need to use the activation key mechanism.
=> fix(konflux): use activation key

Dockerfile
We should not be touching the red hat subscription manager link when we are not using an activation key. Doing so harms the local builds on developers using a Red Hat developer subscription (as well as the jenkins builds).
=> fix(builds): Only unlink rhsm-host when act key

.tekton/hive-mce-27-pull-request.yaml, .tekton/hive-mce-27-push.yaml
While we don't branch out mce-2.7 on freeze date, we should build the
mce-2.7 Konflux builds from master. Once we branch out we need to:
* Remove .tekton/hive-mce-27-pull-request.yaml from master
* Remove .tekton/hive-mce-27-push.yaml
* In mce-2.7, remove the main branch tekton files and change the CEL
expression to build on target-branch == "mce-2.7"
=> Build Konflux mce-2.7 component from master

hack/requirements.txt
When I tried to run hack/bundle-gen.py from within venve this week, I encountered the following error message:
```bash
$ ./bundle-gen.py
Traceback (most recent call last):
File "./bundle-gen.py", line 10, in <module>
import semver
ModuleNotFoundError: No module named 'semver'
```
Adding 'semver' to the requirement.txt and re-running pip install fixed the problem
=> Add python dep 'semver' to hack/requirements.txt

pkg/controller/machinepool/awsactuator.go, pkg/controller/machinepool/awsactuator_test.go
We need to keep the worker-sg filter for pre 4.16 clusters
=> OCPBUGS-38009: Add pre-4.16 SG filters

Makefile
If a go cache is configured (per `go env GOCACHE`), mount it into the container when running `make podman-dev-build`. This should speed up the build, and also reduce the size of interim container layers.
NOTE: This currently only affects `podman-dev-build`. If you're using docker, or the real `image-hive` target, this doesn't help you.
=> Build faster and leaner: podman-dev-build uses local go cache

pkg/controller/machinepool/openstackactuator.go
This is *not* a cherry-pick of #2253 / (c6b37ee6 & f59f327d). That solution revendored installer to pick up the fix from upstream. In older branches, this would have dragged in too many dependencies, so we instead fix it "locally" with an explicit nil check.
Note also that the original fix added unit tests. We can't do that here either because the new tests rely on the OpenStack UT suite being un-broken [1], which again relied on upstream changes [2][3] we can't pull into older branches.
[1] https://github.com/openshift/hive/pull/2251
[2] https://github.com/openshift/installer/pull/8187
[3] https://github.com/openshift/installer/pull/8209
[HIVE-2476](https://issues.redhat.com//browse/HIVE-2476)
=> MachinePools/OpenStack: Fix nil pointer exception

pkg/controller/machinepool/machinepool_controller.go
We are having lots of problems with MachinePool scaling since we introduced failure domain matching as the way to tell whether a generated MachineSet needs to be created, updated, or deleted on the spoke. This commit adds logging that prints the contents of the generated and remote failure domains when a mismatch is detected. It should help with FFDC in the field.
=> MachinePool failure domain logging

pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/clusterpool/clusterpool_controller_test.go
Since ClusterPools create their ClusterDeployments in unique namespaces, it could be tricky to find them -- you would have to do some variant of `oc get cd -A | grep $clusterpoolName` or some fancy jq'ing.
With this commit, we add two labels to ClusterDeployments created by a ClusterPool:
- `hive.openshift.io/clusterpool-namespace`
- `hive.openshift.io/clusterpool-name`
...with the obvious values. With this, you should be able to find all CDs for a pool unambiguously with a query like:
`oc get cd -A -l hive.openshift.io/clusterpool-namespace=poolns,hive.openshift.io/clusterpool-name=poolname`
Often you'll only have one pool in a namespace, or your pool name will be unique in your cluster, so you'll be able to get away with just one of those filters.
Note that upgrading your hive to/past …
=> ClusterPool: Label owned ClusterDeployments

pkg/controller/machinepool/machinepool_controller.go, pkg/operator/hive/hive.go, pkg/operator/hive/sharded_controllers.go
Previous work (#2310 / 4117577) added a knob to control the poll interval for the MachinePool controller.
Then a subsequent effort (#2341 / 35ce9c6) split the MachinePool controller into its own StatefulSet.
But the latter forgot to carry the poll interval plumbing into the sharded version of the controller.
Fix.
[HIVE-2536](https://issues.redhat.com//browse/HIVE-2536)
=> Fix MachinePool poll interval for sharded controller

hack/e2e-common.sh
In our e2e, we've been missing capturing logs from the controllers that have been sharded out into statefulsets: clustersync and (recently, via [HIVE-2537](https://issues.redhat.com//browse/HIVE-2537)) machinepool. Fix.
=> e2e: Capture logs from statefulsets (clustersync, machinepool)

contrib/pkg/adm/managedns/enable.go, contrib/pkg/awsprivatelink/awsprivatelink.go, contrib/pkg/clusterpool/clusterclaim.go, contrib/pkg/clusterpool/clusterpool.go, contrib/pkg/createcluster/create.go, contrib/pkg/deprovision/awstagdeprovision.go, contrib/pkg/deprovision/azure.go, contrib/pkg/deprovision/gcp.go, contrib/pkg/deprovision/ibmcloud.go, contrib/pkg/deprovision/openstack.go, contrib/pkg/deprovision/ovirt.go, contrib/pkg/deprovision/vsphere.go, contrib/pkg/report/deprovisioning.go, contrib/pkg/report/provisioning.go, contrib/pkg/utils/client.go, contrib/pkg/utils/generic.go, docs/syncset.md, pkg/controller/clusterrelocate/clusterrelocate_controller.go, pkg/controller/clusterrelocate/clusterrelocate_controller_test.go, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/utils/clientwrapper.go, pkg/imageset/updateinstaller.go, pkg/installmanager/installmanager.go, pkg/operator/hive/hive_controller.go, pkg/remoteclient/kubeconfig.go, pkg/remoteclient/remoteclient.go, pkg/resource/apply.go, pkg/resource/helper.go, pkg/resource/patch.go
When debugging CR updates, e.g. via `--show-managed-fields`, hive used to annoyingly show `manager: manager`, which is not helpful.
With this commit, we've tried to make sure all updates are driven by a fieldManager with a `hive` prefix:
- For many paths, the prefix will be `hiveN` where `N` is an integer unique to the code path that's configuring the fieldManager. We did this to make it easier to trace these paths in the code (which can otherwise be Very Hard™).
- `hiveutil` commands will show up as either `hiveutil-$subcommand` or `hiveN-util-$subcommand`, depending which path they go through to create their client.
If you find cases that still show up as `manager` -- or some other unhelpful string -- please open a bug!
[HIVE-1744](https://issues.redhat.com//browse/HIVE-1744)
**Note to …
=> fieldManager: "hive-$controllername"

apis/hive/v1/azure/machinepool.go, apis/hive/v1/machinepool_types.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/azureactuator.go, pkg/controller/machinepool/azureactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
Add networking fields to the Azure MachinePool API:
MachinePool.Spec.Platform.Azure.NetworkResourceGroupName will end up in MachineSet.Spec.Template.Spec.ProviderSpec.Value.NetworkResourceGroupName...
unless VirtualNetwork is unspecified, in which case the ResourceGroup is used. (This logic lives in the upstream installer code and is accurate at the time of this writing 😇)
MachinePool.Spec.Platform.Azure.ComputeSubnet will end up in MachineSet.Spec.Template.Spec.ProviderSpec.Value.Subnet.
MachinePool.Spec.Platform.Azure.VirtualNetwork will end up in MachineSet.Spec.Template.Spec.ProviderSpec.Value.Vnet.
The MachinePool API field names are taken from their install-config.yaml equivalents.
[HIVE-2582](https://issues.redhat.com//browse/HIVE-2582)
=> Azure MachinePool: NetworkResourceGroupName, ComputSubnet, VirtualNetwork

apis/hive/v1/machinepool_types.go, apis/hive/v1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go, pkg/test/machinepool/machinepool.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
The existing MachinePool.Spec.Labels field populates the resulting MachineSets' *MachineSpec*, resulting in the specified labels ending up on *Nodes*.
This commit adds MachinePool.Spec.MachineLabels, which populates the *MachineTemplateSpec*, resulting in the specified labels ending up on *Machines*. But note that we will ignore labels that conflict with those generated by installer code:
- machine.openshift.io/cluster-api-cluster
- machine.openshift.io/cluster-api-machineset
We also add MachinePool.Status.OwnedMachineLabels, corresponding to the existing OwnedLabels, to help us merge values correctly.
[HIVE-2320](https://issues.redhat.com//browse/HIVE-2320)
=> MachinePool API: MachineLabels

Makefile
...if this is the first build in this file system.
In this case, `podman` will freak out when passed that directory as a volume mount.
So check the directory and only use it if it exists.
=> GOCACHE dir may not exist

.snyk
Ignore https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMAZUREAZURESDKFORGOSDKAZIDENTITY-7246767
This is a Moderate CVE, fixed in mce-2.6 and later, thus deemed acceptable to disregard since it would be difficult to resolve.
[HIVE-2532](https://issues.redhat.com//browse/HIVE-2532)
=> Snyk: Ignore azidentity

apis/hive/v1/azure/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/azureactuator.go, pkg/controller/machinepool/azureactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go
Add MachinePool.Spec.Azure.VMNetworkType to the API. Vendored installer code maps this to MachineSet...ProviderSpec...AcceleratedNetworking:
- "Accelerated" => true
- ""/unset or "Basic" => false
[HIVE-2530](https://issues.redhat.com//browse/HIVE-2530)
=> Azure MachinePool: Add VMNetworkType

pkg/controller/machinepool/gcpactuator.go, pkg/controller/machinepool/gcpactuator_test.go
When `MachinePool.Spec.Platform.GCP.Zones` does not explicitly enumerate the zones to use, we attempt to default to all zones in the configured region. However, this query was using an overly-broad regex which matched any zone whose region was a *substring* of the configured region. This broke when GCP added regions `europe-west10` and `europe-west12`, which our filter would retrieve when the cluster was in region `europe-west1`.
The zone list response includes the region as a full URI (e.g. `https://www.googleapis.com/compute/v1/projects/openshift-hive-dev/regions/europe-west1`). Fix our regex to match our full region string, anchored by the last `/` and the end of the string.
[HIVE-2610](https://issues.redhat.com//browse/HIVE-2610)
=> MachinePool GCP: fix zone filter

pkg/gcpclient/client.go
Enabling AllowPscGlobalAccess so that the endpoint is available from all of the regions as is necessary when the endpoint exists in a region other than the one a VPN is connected to.
=> OCPBUGS-41797: PrivateLink: GCP PSC to use global endpoints

hack/grafana-dashboards/grafana-dashboard-hive-logs.configmap.yaml
This commit adds a grafana dashboard for easy filtering of hive logs from CloudWatch.
Please check the dev version [here](https://grafana.stage.devshift.net/d/edy3mdkcmzfnkb/hive-logs)
[Hive-2602](https://issues.redhat.com/browse/HIVE-2602)
=> Add hive logs grafana dashboard

hack/grafana-dashboards/grafana-dashboard-hive-logs.configmap.yaml
The limit - aka the total number of log events the query will fetch - was set to 20. This commit allows the user to choose larger limits based on their needs. The largest is set to 10,000, assuming anything larger might result in hitting the CloudWatch timeout.
=> Hive Logs: Make limit custom

apis/hive/v1/hiveconfig_types.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, pkg/constants/constants.go, pkg/controller/clusterversion/clusterversion_controller.go, pkg/operator/hive/hive.go, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Add HiveConfig.Spec.ClusterVersionPollInterval, a time.Duration value which (plus random jitter of 0-1s) will be used to requeue ClusterDeployments for the clusterversion controller, which is responsible for setting `hive.openshift.io/version*` labels on ClusterDeployment objects based on the ClusterVersion object on the spoke.
If unset or zero, this is disabled, resulting in the legacy behavior: we will reconcile on controller startup, ClusterDeployment changes, or (I think) the default controller-runtime interval of 1000s.
[HIVE-2619](https://issues.redhat.com//browse/HIVE-2619)
=> ClusterVersion: tunable poll interval

apis/go.mod, apis/go.sum, apis/vendor/modules.txt, go.mod, go.sum, vendor/modules.txt
This is a special revendor.
A prior commit (https://github.com/openshift/hive/pull/2460 / https://github.com/2uasimojo/hive/commit/c7581516b99535b743844d12fa574828d5ea53b7) included installer as a dependency in our apis/ package for the first time. This was causing problems for downstream consumers seemingly because the pseudo-version generated by `go mod`  represented a years-old tag with a recent commit, resulting in excessive churn in the go sum database -- see the referenced bug report.
Now a tag has been created at that commit to make this pseudo-version less gappy, hopefully eliminating this problem for downstreams.
However, when I tried to revendor to that tag, go replaced it with a pseudo-version... and then complained that we shouldn't use a pseudo-version when there's a tag …
=> No-op revendor installer

hack/modcheck.go
Our modcheck tool looks at the go.mod files in the repository root and the apis/ directory, and fails if any entries in the latter exist in the former at a different version. Heretofore, such failures would have to be addressed by manually updating the apis/go.mod to sync those versions.
With this change, we add a `-f` flag which asks modcheck to `f`ix discrepancies it encounters.
In this first phase, we add the ability for modcheck to fix `require` entries, as these are by far the most common discrepancies we encounter.
*Further work is required to make the tool fix `exclude` and `replace` entries.*
The tool will succeed (exit zero) if the files are in sync when it completes -- whether because they started that way, or because it fixed everything it encountered.
The tool will fail (exit …
=> modcheck -f phase 1: fix `require`s

Makefile, config/crds/hive.openshift.io_checkpoints.yaml, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterdeprovisions.yaml, config/crds/hive.openshift.io_clusterimagesets.yaml, config/crds/hive.openshift.io_clusterpools.yaml, config/crds/hive.openshift.io_clusterprovisions.yaml, config/crds/hive.openshift.io_clusterrelocates.yaml, config/crds/hive.openshift.io_clusterstates.yaml, config/crds/hive.openshift.io_dnszones.yaml, config/crds/hive.openshift.io_hiveconfigs.yaml, config/crds/hive.openshift.io_machinepoolnameleases.yaml, config/crds/hive.openshift.io_machinepools.yaml, config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml, config/crds/hive.openshift.io_selectorsyncsets.yaml, config/crds/hive.openshift.io_syncidentityproviders.yaml, config/crds/hive.openshift.io_syncsets.yaml, config/crds/hiveinternal.openshift.io_clustersyncleases.yaml, config/crds/hiveinternal.openshift.io_clustersyncs.yaml, config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml, hack/app-sre/saas-template.yaml
The build-machinery-go project is suffering from bit rot, which is making it difficult to upgrade the version of controller-gen we use to generate CRDs, which we're going to need to do in order to upgrade k8s dependencies (see [HIVE-2616](https://issues.redhat.com//browse/HIVE-2616)).
With this change, we stop using the piece of build-machinery-go that deals with controller-gen, and instead install it directly from our vendor directory.
[HIVE-2626](https://issues.redhat.com//browse/HIVE-2626)
=> controller-gen: use vendor/, not build-machinery-go

go.mod, go.sum, vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go, vendor/modules.txt
...to pick up OCPBUGS-31808 /
https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/287 which resolves a nil pointer exception referencing fields under Infrastructure.Spec.PlatformSpec, which apparently is not always present (on VSphere).
[HIVE-2627](https://issues.redhat.com//browse/HIVE-2627)
=> Revendor cluster-control-plane-machine-set-operator

pkg/controller/privatelink/actuator/awsactuator/awshubactuator.go, pkg/controller/privatelink/actuator/gcpactuator/gcplinkactuator.go
Prior to this change, the GCP Link actuator failed to return an error when a failure was experienced while creating certian cloud resources. This is because the actuators were overriding the value of the err varliabe prior to using it in a following return statement. As a result, the controller would assume the link actuator was successful and continue calling the hub actuator. This caused, the PrivateLinkFailed condidtion would show an error regarding the failed provisioning of DNS resources instead of the underlying issue in the link actuator.
This change fixes the problem by placing the secondary assignment of the err variable into the corrisponding if block, thereby maintaining the origional value of the variable. This causes the final return to act as expected by condition of the …
=> OCPBUGS-42740: PrivateLink Actuators should return errors on failure.

pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go
The machinepool controller tracks labels, machineLabels, and taints in the MachinePool.Status (OwnedLabels, OwnedMachineLabels, OwnedTaints) so that, when the user removes them from the spec, we can idempotently know which ones to remove from the spoke MachineSet. This is to avoid removing any of those things if they were added directly by the user on the spoke rather than through the MachinePool.
Note that, in the case of a conflict (the same key in both the MachinePool and added directly on the spoke), the MachinePool would "win".
However, when MachineLabels were implemented (#2420 / 315aa266) we needed special handling to avoid stomping on *generated* labels -- those produced by the installer code that generates the MachineSet -- because these have special meaning and function to the …
=> MachinePool: Generated MachineLabels are not "owned"

pkg/controller/hibernation/hibernation_controller.go, pkg/controller/hibernation/hibernation_controller_test.go
When installation finishes, the clustersync and hibernation controllers race to start their business. But the latter needs to make use of the ClusterSync object. When the clustersync controller hasn't created it yet, the hibernation controller needs to requeue and wait for it.
Previously we were just letting the 404 from Get(ClusterSync) to bubble up; but this counts against the reconciler error budget for which alerts may be triggered. Since this is an expected scenario, we change this code path to do a non-error immediate requeue instead.
[HIVE-2611](https://issues.redhat.com//browse/HIVE-2611)
=> Hibernation: Requeue without error when ClusterSync doesn't exist yet

apis/hive/v1/hiveconfig_types.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Today our backstop for invalid (i.e. not parseable as Duration) values for HiveConfig.Spec.
- SyncSetReapplyInterval
- MachinePoolPollInterval
- ClusterVersionPollInterval
...is to crash the respective controllers.
With this change, we add schema validation, which should cause invalid values to be rejected by the kube API server before they even get into etcd. (We leave the backstops in place for invalid values in pre-existing deployments.)
[HIVE-2635](https://issues.redhat.com//browse/HIVE-2635)
=> Use Duration Pattern for syncset, machinepool, clusterversion polls

pkg/constants/constants.go, pkg/controller/hibernation/hibernation_controller.go, pkg/controller/utils/clusterdeployment.go
Add a back door ClusterDeployment annotation,
`hive.openshift.io/infra-disabled: "True"`, for Azure clusters to request that the hibernation controller be disabled, and spoof the cluster's powerState to Running.
[HIVE-2643](https://issues.redhat.com//browse/HIVE-2643)
=> Azure "disable infra" annotation

Dockerfile, Makefile, config/crds/hive.openshift.io_checkpoints.yaml, config/crds/hive.openshift.io_clusterclaims.yaml, config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterdeprovisions.yaml, config/crds/hive.openshift.io_clusterimagesets.yaml, config/crds/hive.openshift.io_clusterpools.yaml, config/crds/hive.openshift.io_clusterprovisions.yaml, config/crds/hive.openshift.io_clusterrelocates.yaml, config/crds/hive.openshift.io_clusterstates.yaml, config/crds/hive.openshift.io_dnszones.yaml, config/crds/hive.openshift.io_hiveconfigs.yaml, config/crds/hive.openshift.io_machinepoolnameleases.yaml, config/crds/hive.openshift.io_machinepools.yaml, config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml, config/crds/hive.openshift.io_selectorsyncsets.yaml, config/crds/hive.openshift.io_syncidentityproviders.yaml, config/crds/hive.openshift.io_syncsets.yaml, config/crds/hiveinternal.openshift.io_clustersyncleases.yaml, config/crds/hiveinternal.openshift.io_clustersyncs.yaml, config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml, go.mod, go.sum, hack/app-sre/saas-template.yaml, vendor/modules.txt
There's been quite a lot of improvements on Hive's Dockerfile and Makefile that speed up development and delivery work. We should bring them in mce-2.4 to to make backports less of a chore.
=> Backport all the Dockerfile Makefile improvements

apis/hive/v1/clusterdeprovision_types.go, apis/hive/v1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_clusterdeprovisions.yaml, contrib/pkg/deprovision/azure.go, hack/app-sre/saas-template.yaml, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/install/generate.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
If an Azure spoke was provisioned with a custom
BaseDomainResourceGroupName, DNS records were being leaked when destroying because we weren't passing that information through to the deprovisioner.
We were already requiring this value on input in
ClusterDeployment.Spec.Platform.Azure.BaseDomainResourceGroupName. This change plumbs it through ClusterDeprovision and into the Azure deprovision helper.
[HIVE-2651](https://issues.redhat.com//browse/HIVE-2651)
=> Azure: Pass BaseDomainResourceGroupName to destroyer

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
...for https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOLANGJWTJWTV4-8341242
(Manual apply of #2508 / #2509 since automatic cherry-pick failed.)
[HIVE-2654](https://issues.redhat.com//browse/HIVE-2654)
=> Bump jwt/v4 to 4.5.1

apis/hive/v1/syncset_types.go, docs/syncset.md, vendor/github.com/openshift/hive/apis/hive/v1/syncset_types.go
We were exporting a data type, SyncSetPatchApplyMode, whose code was either removed or never implemented. Scrub it to avoid confusion for consumers.
[HIVE-2658](https://issues.redhat.com//browse/HIVE-2658)
=> Tech Debt: nix SyncSetPatchApplyMode

apis/hive/v1/azure/machinepool.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, pkg/controller/machinepool/azureactuator.go, pkg/controller/machinepool/azureactuator_test.go, vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go
Add `OutboundType` to the Azure-specific MachinePool section so that `UserDefinedRouting` -- which results in an empty `PublicLoadBalancer` field in the MachineSet providerSpec -- can be used.
[HIVE-2674](https://issues.redhat.com//browse/HIVE-2674)
=> Azure MachinePool: Support OutboundType: UserDefinedRouting

apis/hive/v1/syncset_types.go, config/crds/hive.openshift.io_selectorsyncsets.yaml, config/crds/hive.openshift.io_syncsets.yaml, docs/syncset.md, hack/app-sre/saas-template.yaml, pkg/controller/clustersync/clustersync_controller.go, pkg/controller/clustersync/clustersync_controller_test.go, pkg/controller/clustersync/templates.go, pkg/test/syncset/syncset.go, vendor/github.com/openshift/hive/apis/hive/v1/syncset_types.go
[HIVE-1748](https://issues.redhat.com//browse/HIVE-1748) / #2192 added the ability to flip a switch in a [Selector]SyncSet that causes hive to process golang [text/template](https://pkg.go.dev/text/template)s in leaf values of objects in the [S]SS's `resources` section.
This does a similar thing for JSON patch strings in the `patches` section. For example:
```yaml
apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
name: paramss
spec:
...
enablePatchTemplates: true
...
patches:
- apiVersion: v1
kind: ConfigMap
name: foo
namespace: default
patch: |-
{"metadata": {"annotations": {"test": "{{ fromCDLabel "hive.openshift.io/cluster-platform" }}" }}}
patchType: merge
```
Note that the data type of `patches[].patch` is `string`, so internal quotes must be escaped somehow (in the above …
=> syncset: support templates in `patches`

pkg/operator/metrics/metrics.go
Metric hive_hiveconfig_conditions reports the status of HiveConfig Ready condition. Under normal circumstances, this value can either be 1 (when reason = Success) or 0 (when reason = ErrorDeployingHive). Consequently we never bothered to clear the metric as it would be automatically reset when the pod is restarted.
However, during migration, this can result in conflicting values. First, the metric reports 1, but when migration is started, the metric starts reporting 0 without clearing the previous 1, resulting in two values at the same time.
Once the migration is successful, the previous metric value of 0 is also not cleared when we start reporting 1. Only when the pod is restarted, the correct value is reported.
This commit fixes the problem by deleting all the values for …
=> Always reset hive_hiveconfig_conditions[Ready]

apis/hive/v1/gcp/platform.go, apis/hive/v1/gcp/zz_generated.deepcopy.go, config/crds/hive.openshift.io_clusterdeployments.yaml, config/crds/hive.openshift.io_clusterpools.yaml, contrib/pkg/createcluster/create.go, hack/app-sre/saas-template.yaml, pkg/clusterresource/gcp.go, pkg/controller/clusterpool/clusterpool_controller.go, pkg/controller/hibernation/aws_actuator_test.go, pkg/controller/hibernation/gcp_actuator.go, pkg/controller/hibernation/gcp_actuator_test.go, pkg/gcpclient/client.go, pkg/gcpclient/mock/client_generated.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go, vendor/github.com/openshift/hive/apis/hive/v1/gcp/platform.go, vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
It would seem as though, when stopping an instance with SSDs, one is required to specify whether their contents should be preserved or discarded, despite what the documentation [1] says about defaulting that behavior to the latter. This will result in a failure to stop instances, with the following message appearing in the ClusterDeployment's Hibernating condition:
```
Error 400: VM has a Local SSD attached but
an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false`
or `--discard-local-ssd=true` to your command.
```
This change adds
ClusterDeployment.Spec.Platform.GCP.DiscardLocalSsdOnHibernate, a _pointer_ to a bool that we will pass through to the GCP API if provided. The default behavior is as before: when the field is not populated, we will …
=> GCP: Hibernation: Support SSDs

go.mod, go.sum, vendor/modules.txt
...for CVE-2022-1996, which gets flagged based on seeing 2.15 in go.sum, even though none of the actual code is imported at all.
[ARO-14549](https://issues.redhat.com//browse/ARO-14549)
=> Replace go-restful v2.15=>2.16 in go.sum

pkg/controller/privatelink/actuator/gcpactuator/gcplinkactuator.go, pkg/controller/privatelink/actuator/gcpactuator/gcplinkactuator_test.go
Prior to this change, the gcp privatelink firewall rule was targeting the <infraid>-master network tag. However, in 4.16 the installer changed to using <infraid>-control-plane. This change adds the newer tag to the firewall rule.
=> HIVE-2752: PrivateLink: add control-plane network tags to gcp psc

Dockerfile, Makefile, hack/ubi-build-deps.sh
This adds a Makefile target that relies on ubi8, ubi9 and centos stream to provide an upstream image that is fit for OperatorHub.
=> HIVE-2764: Upstream builds for operatorhub

docs/hive_metrics.md
We get frequent queries about which hive metric someone can use to trace a cluster that is causing an alert to fire. So this commit adds a small addition to metrics documentation to document our stance regarding the same.
This was added in the hive metrics document because metrics users are more likely to read there, instead of general hive FAQs
=> Document metrics FAQ

.tekton/hive-pull-request.yaml, .tekton/hive-push.yaml, hack/ubi-build-deps.sh
Use upstream golang for Operatorhub builds since ubi8 does not have go 1.23 available.
=> fix(builds): Operatorhub golang bump to 1.23

hack/bundle-gen.py, hack/version2.py
Our OperatorHub bundle generator validates the discovered/specified operator image by querying the repository to see if it exists. Previously if it did not exist, we would simply fail. With this change, we instead attempt to build and push it.
This also changes the default repository from AppSRE's to hive's.
...and addresses a latent syntax error in a regex used to generate semvers from MCE branch names.
[HIVE-2766](https://issues.redhat.com//browse/HIVE-2766)
=> bundle-gen.py: build and push public images

pkg/controller/machinepool/gcpactuator.go, pkg/controller/machinepool/gcpactuator_test.go, pkg/controller/machinepool/machinepool_controller.go
Remove logic associated with checking whether the spoke cluster's version is >=4.4.8, since that's way out of service.
=> HIVE-2785: Remove obsolete version check

apis/hive/v1/gcp/machinepools.go, config/crds/hive.openshift.io_machinepools.yaml, hack/app-sre/saas-template.yaml, vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
GCP seems to have added some disk types since we wrote our API for MachinePool.Spec.Platform.GCP.OSDisk.DiskType with an enum restricting it to two values (`pd-standard` and `pd-ssd`).
The proximate need is to be able to stand up C3 instances such as `c3-standard-192-metal`, which require a disk type of `hyperdisk-balanced`.
However, for future compatibility -- i.e. against the advent of GCP adding more disk types down the road -- this change simply removes the restriction, allowing the user to enter any string value. If they get it wrong, it just means it will be GCP rather than k8s that bounces the request.
Note that absorbing this change should only be a matter of reinstalling CRDs (specifically MachinePool). Controller code is not affected, here or downstream.
=> HIVE-2788: MachinePool/GCP: Remove DiskType enum

go.mod, vendor/modules.txt
Replace x/crypto with the openshift fork containing the fix. (The upstream fix in 0.35.0 requires golang 1.23, and bumping in this release would be Hard™.)
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXCRYPTOSSH-8747056
[ACM-18369](https://issues.redhat.com//browse/ACM-18369)
=> [mce-2.5] HIVE-2786: CVE-2025-22869: x/crypto/ssh v0.33.openshift.1

pkg/installmanager/installmanager.go, pkg/installmanager/installmanager_test.go
xref: [HIVE-2804](https://issues.redhat.com//browse/HIVE-2804)
=> HIVE-2804: Scrub username and password fields on metadata.json 

.snyk
Add a couple of ignores to .snyk for things that rely on difficult backports of transitive dependencies.
=> HIVE-2805: Ignore a couple of snyk vulns

hack/version2.py
- With the coordinated release process, we will often be generating OperatorHub bundles from an explicit commit that is behind the tip of `master`.
- The routine that searches for the branch associated with such a commit (used to determine the semver major.minor) was written before konflux started polluting our ref space.
The combination was resulting in errors like:
```
$ ./hack/bundle-gen.py --commit  b19773ecfc98ab9819f56e30433dd3716c14b9ce
Cloning git@github.com:openshift/hive.git to /tmp/hive-repo-h5ctac_7
Working in /tmp/hive-repo-h5ctac_7
Trying to discover a suitable branch from commit b19773e...
descendants: {'master', 'konflux/references/master'}
Could not determine a branch! Please specify one explicitly.
```
This change explicitly skips refs with `konflux/` in their name, as …
=> HIVE-2769: bundle-gen: skip konflux branches

test/e2e/common/machinepool.go, test/e2e/postinstall/machinesets/infra_test.go
This is to reduce/eliminate flakes like:
```
=== RUN   TestScaleMachinePool
time="2025-03-26T17:11:35Z" level=info msg="expected Machine name prefix: hiveci-67e42826-a44-54t2j-worker-" pool=hiveci-67e42826-a44-worker test=TestScaleMachinePool
time="2025-03-26T17:11:35Z" level=info msg="scaling pool to 1 replicas" pool=hiveci-67e42826-a44-worker test=TestScaleMachinePool
infra_test.go:67:
Error Trace:	/go/src/github.com/openshift/hive/test/e2e/postinstall/machinesets/infra_test.go:67
Error:      	Received unexpected error:
Operation cannot be fulfilled on machinepools.hive.openshift.io "hiveci-67e42826-a44-worker": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestScaleMachinePool
Messages:   	cannot update worker machine pool to …
```
=> HIVE-2812: e2e: MachinePool tests retry on 409

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v5/README.md, vendor/github.com/golang-jwt/jwt/v5/SECURITY.md, vendor/github.com/golang-jwt/jwt/v5/parser.go, vendor/github.com/golang-jwt/jwt/v5/token.go, vendor/modules.txt
...for https://www.cve.org/CVERecord?id=CVE-2025-30204
(cherry picked from commit 7bbe855cf33dc6b416a44ee20767d765e86801be)
[ACM-19209](https://issues.redhat.com//browse/ACM-19209)
(cherry picked from commit 0fabe293b965250cd6d2c6519f104580f7b2cb53) (cherry picked from commit 15f658337790d27f9ac194798958a9932ce698c3)
=> [mce-2.6] HIVE-2813: Bump jwt/v4 and v5

pkg/constants/constants.go, pkg/controller/clusterversion/clusterversion_controller.go, pkg/controller/clusterversion/clusterversion_controller_test.go
This PR lifts the `Upgradeable` status from the ClusterVersion into a new `hive.openshift.io/minor-version-upgrade-unavailable` label on the ClusterDeployment.
Higher level tools can consume this message to warn users about minor version upgrades that CVO would reject with a reason.
=> HIVE-2819: Lift upgradeable condition from CVO to cluster deployment label

apis/hive/v1/machinepool_types.go, pkg/client/fake/overrideable_client.go, pkg/controller/machinepool/machinepool_controller.go, pkg/controller/machinepool/machinepool_controller_test.go, pkg/test/machinepool/machinepool.go, vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
Previously there was a whole class of errors in the MachinePool controller that would result in the user seeing nothing -- no change on the spoke, and no update to the MachinePool CR. Ultimately it was necessary to look at logs to triage further.
With this change, we have introduced two new status conditions covering four code paths which comprise the majority of the controller:
- `MachineSetsGenerated` indicates the success or failure of the actuator's `GenerateMachineSets()` function.
- `Synced` indicates the success or failure of our attempt to sync MachineSets, MachineAutoscalers and the ClusterAutoscaler -- disambiguated by way of the condition's reason code -- to the spoke cluster.
For failure conditions in each case, we copy the error text to the condition's `message` field. This …
=> HIVE-2416: MachinePool errors in status conditions

pkg/controller/clusterversion/clusterversion_controller.go, pkg/controller/clusterversion/clusterversion_controller_test.go
This is a follow up to https://github.com/openshift/hive/pull/2639 , but moving the value to the cluster deployment annotations instead of labels. This change is due to an issue found with certain allowed characters for labels that do not affect annotations.
For example, the following error was seen testing the labels from the previous PR:
```
time="2025-04-01T15:52:28.453Z" level=error msg="Reconciler error" controller=clusterversion-controller error="...a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]"
```
=> HIVE-2819: Use annotation instead of label for upgradeable

pkg/controller/dnsendpoint/dnsendpoint_controller_test.go, pkg/controller/machinepool/gcpactuator_test.go, pkg/controller/metrics/custom_collectors_test.go
Issue: N/A
Some len parameters of make() look non-zero unintentionally. These slices had leading non-zero values and essential values followed them.
=> Correct len parameters of make() in some tests

pkg/controller/machinepool/machinepool_controller.go
PR #2628 added a couple of new status conditions to MachinePool. Due to a copy/paste mistake, it was setting the wrong Reason code for a couple of the code paths. Fix.
=> HIVE-2416: Fix copypasta error in MachinePool Reasons

pkg/controller/machinepool/machinepool_controller.go
[HIVE-2416](https://issues.redhat.com//browse/HIVE-2416) / #2628 / c2b9a17b made a mistake in the updating of status conditions in the green path: it updated the same condition multiple times in sequence with different reason/message values. Each update triggered an immediate requeue, resulting in thrashing.
Rookie mistake.
Fixed by consolidating to one reason/message for the green path.
=> HIVE-2827: Fix MachinePool thrashing on conditions

pkg/validating-webhooks/hive/v1/syncset_validating_admission_hook.go, pkg/validating-webhooks/hive/v1/syncset_validating_admission_hook_test.go
[Selector]SyncSet.Spec.Patches[].PatchType is defaulted in code to `strategic` if empty or missing. However, our webhook was not accepting the empty string as a valid value. Relax it accordingly.
Note: We could have removed the webhook entirely and added enum schema validation on the field itself, but that would _technically_ be a breaking API change.
=> HIVE-2807: SyncSet: Accept empty patchType

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller_test.go, pkg/controller/awsprivatelink/cleanup.go
The reverted commits were attempting to introduce code to clean up stale resources from AWSPrivateLink reconciles. This turned out to be too fragile, error-prone, and expensive to be worth the benefit we would derive from it.
=> HIVE-2837: Revert AWSPrivateLink cleanup code

Makefile, docs/developing.md
PR #2476 / 60592842 introduced syntax to our modcheck utility to ask it to fix discrepancies it finds. This commit adds and documents a `make` rule to invoke it thusly.
=> HIVE-2624: `make modfix`

hack/e2e-common.sh
This PR add the option to run the `make test-e2e` target with Nutanix as cloud provider.
e.g.
```bash
MANIFESTS=nutanix_secrets \
RELEASE_IMAGE=quay.io/openshift-release-dev/ocp-release:4.19.0-ec.5-x86_64 \
HIVE_IMAGE=quay.io/my-user/hive:latest \
CLOUD=nutanix \
make test-e2e
```
/cc @2uasimojo
=> HIVE-2792: Add Nutanix as a valid cloud provider in E2E tests

contrib/pkg/createcluster/nutanix.go, pkg/clusterresource/builder_test.go, pkg/clusterresource/nutanix.go
- Allow installation without certificate on hiveutil.
- Fix case where the certificate is empty and the controller fail validating that the certificate.
=> HIVE-2792: Allow hive util to not pass any PC certificate

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- Detect whether a previously-configured hub VPCEndpoint went bad (was rejected or deleted) and replace it.
- Produce a log message with the count of the total number of hub VPCEndpoints to facilitate leak detection. This is at Warn level if >1, Info otherwise; and contains a field with key `numVPCEndpoints` for your alerting needs.
=> HIVE-2847: AWSPrivateLink: improve VPCEndpoint reconcile

config/configmaps/install-log-regexes-configmap.yaml, pkg/controller/clusterprovision/installlogmonitor_test.go, pkg/operator/assets/bindata.go
We recently saw a cluster fail to install on AWS where at least one subnet had reached the maximum number of tags (50) and therefore the install could not proceed.
The exact log from the installer was:
```
time=\"2025-05-06T11:12:26Z\" level=fatal msg=\"failed to fetch Cluster: failed to generate asset \\"Cluster\\": could not add tags to subnets: TagLimitExceeded: The resultant tag set must not have more than 50 user tags.\n\tstatus code: 400, request id: b097f663-0c2e-4403-9efa-73ca2ca3051c\"
```
This adds a handling for `could not add tags to subnets: TagLimitExceeded` which should cover this specific scenario.
=> OSD-29996: Handle TagLimitExceeded failures for AWS subnets during install

.tekton/hive-mce-29-pull-request.yaml, .tekton/hive-pull-request.yaml
Add CEL syntax to both pull-request konflux configs to avoid running the jobs on draft PRs.
=> Konflux: Don't run on draft PRs

.tekton/hive-mce-29-pull-request.yaml, .tekton/hive-mce-29-push.yaml, .tekton/hive-pull-request.yaml, .tekton/hive-push.yaml
* Match our main konflux config with what we have for mce 2.9 (this will hopefully make convincing others to just use our main config to be much easier)
* TODO: mce 2.5-2.8 - can we just use the main config also?
* TODO: mce 2.4 - I think this config will have to be backported to that branch (hopefully this will be the only backport)
xref: [HIVE-2661](https://issues.redhat.com//browse/HIVE-2661)
=> HIVE-2661: Complete Konflux efforts for Hive

hack/e2e-common.sh, hack/e2e-test.sh
This PR aims to add e2e testing for Hive on the OpenStack cloud.
The cluster parameters match those used to create the OpenStack hub cluster in Prow CI.  The following resources are pre-created in CI and used in the Hive e2e:
-  api floating ip - API_FLOATING_IP
-  ingress floating ip - INGRESS_FLOATING_IP 
-  spoke cluster name - HIVE_CLUSTER_NAME
Below is the log from my local run:
- The test parameters are consistent with those in Prow CI.  [local-e2e-test-openstack.log](https://github.com/user-attachments/files/19018775/local-e2e-test-openstack.log)
- The test parameters were created manually. [local-e2e-openstack.log](https://github.com/user-attachments/files/19018773/local-e2e-openstack.log)
=> HIVE-2581: OpenStack e2e

pkg/controller/clusterversion/clusterversion_controller.go, pkg/controller/clusterversion/clusterversion_controller_test.go
Follow up to [HIVE-2819](https://issues.redhat.com//browse/HIVE-2819) - always show the upgradeable annotation. If the annotation is present with an empty string, this means that the cluster is upgradeable.
=> HIVE-2871 - Always show the upgradeable annotation.

config/hiveadmission/apiservice.yaml, config/hiveadmission/clusterdeployment-webhook.yaml, config/hiveadmission/clusterimageset-webhook.yaml, config/hiveadmission/clusterprovision-webhook.yaml, config/hiveadmission/dnszones-webhook.yaml, config/hiveadmission/machinepool-webhook.yaml, config/hiveadmission/selectorsyncset-webhook.yaml, config/hiveadmission/syncset-webhook.yaml, pkg/operator/assets/bindata.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go
This change corrects the hiveadmission service's authentication to the hub's kube-apiserver by injecting the correct CA bundle into the ValidatingWebhookConfigurations (VWHCs) when running on OpenShift.
Previously we were relying on the `service.beta.openshift.io/inject-cabundle` annotation. It turns out this injects the *wrong* bundle for VWHCs (though, accidentally, the right one for the aggregated APIService). Our webhooks still worked because the KAS has special handling, ignoring the VWHC's caBundle entirely, for clients using the aggregated API service, which hiveadmission does. However, OpenShift's kube-apiserver-operator (KASO) has a webhook validator that lacks this special handling (see OCPBUGS-50978) and thus generates error logs. While these errors are harmless and do not …
=> HIVE-2870: hiveadmission: proper authn to the KAS

pkg/installmanager/installmanager.go
When deleting Nutanix clusters, residual Nutanix resources such as virtual machines and images were not being properly cleaned up. This occurred due to an incorrect casting of the `cd.Spec.Platform.Nutanix.PrismCentral.Port` field from `int32` to `string` using a direct string() cast.
/cc @2uasimojo
=> HIVE-2861: Fix residual Nutanix resources after cluster deletion due to incorrect casting of Prism Central port

.tekton/hive-mce-29-pull-request.yaml, .tekton/hive-mce-29-push.yaml, .tekton/hive-pull-request.yaml, .tekton/hive-push.yaml, hack/hermetic/redhat.repo, hack/hermetic/rpms.lock.yaml
With the ELS image in use, there are old versions of RPMs lingering while the lockfile specifies new versions. Using the EUS repo aligns the versions.
Slack thread: https://redhat-internal.slack.com/archives/C06TJJ3E0MU/p1751287431351829
=> Align RPM versions with the ELS image

pkg/controller/clusterversion/clusterversion_controller.go, pkg/controller/clusterversion/clusterversion_controller_test.go
Currently, the controller will not recognize that the "upgradeable" annotation is missing and requires repopulation. This change treats a missing annotation as a required change that needs to be updated during reconcilation.
=> HIVE-2871 | (fix): Update the clusterversion controller to handle the case where the upgradeable annotation doesn't exist and needs to be re-populated

Makefile
Trying to build `hiveutil` on Debian (and most likely all Debian derivatives) fails because not only does the default Bourne shell not support Bash-isms like `shopt` but neither does the shell that it's commonly symlinked to, Dash.
For example:
```
$ make build-hiveutil
/bin/sh: 1: set: Illegal option -o pipefail
...
$ readlink -f /bin/sh
/usr/bin/dash
```
I currently don't have access to my Red Hat-issued Fedora machine, but spinning up a Fedora VM in Vagrant shows that `sh` is linked to Bash:
```
[vagrant@vagrant-fedora hive]$ readlink -f /bin/sh
/usr/bin/bash
```
Even though it's probably safe that Fedora will continue to symlink to Bash, it doesn't hurt to harden the Makefile by adding the SHELL variable.
This was tested on both Debian and Fedora. …
=> Set default shell to Bash in Hive's Makefile

pkg/operator/hive/configmap.go, pkg/operator/hive/hive.go, pkg/operator/hive/hiveadmission.go, pkg/operator/hive/sharded_controllers.go, pkg/operator/util/apply.go
Modernize the code hive-operator uses to apply objects to the cluster, employing the options pattern so we can consolidate to just one function. This improves maintainability by, for example, allowing us to add a new object configuration without adding a whole new (set of) Apply function(s).
=> HIVE-2887: Consolidate operator apply functions

pkg/controller/awsprivatelink/awsprivatelink_controller.go
What does this PR do?
After migrating to AWS SDK v2, I observed occasional timeouts during the creation of PrivateLink resources. While not consistently reproducible, these timeouts can cause installation failures. This PR increases the timeout duration to address this potential issue.
=> HIVE-2897: Increase timeout for AWS PrivateLink resource creation

pkg/controller/awsprivatelink/cleanup.go, pkg/controller/awsprivatelink/cleanup_test.go
What does this PR do?
Due to incomplete cleanup of associated VPC Endpoints and VPCEndpointServices, deletion operations fail with resource in use errors, thereby blocking cluster deprovisioning.
=> HIVE-2898: Fix cleanup of leftover resources for VPC Endpoints and VPCEndpointServices

pkg/controller/machinepool/azureactuator.go, pkg/controller/machinepool/azureactuator_test.go
When users created a MachinePool in an Azure region that does not support availability zones,since the region does not provide availability zones, the MachinePool creation failed.
**Solution:**
- Based on Eric’s comments in https://github.com/openshift/hive/pull/2732#pullrequestreview-3129384057 
If no zones are specified, and the region has no zones, just pass through "no zones", and let the mset generator do what it does for a "no AZ region".
=> HIVE-2544: Support machinepool creation in Azure regions without availability zones

pkg/controller/awsprivatelink/awsprivatelink_controller.go, pkg/controller/awsprivatelink/awsprivatelink_controller_test.go, pkg/controller/privatelink/conditions/conditions.go, pkg/controller/utils/errorscrub.go, pkg/controller/utils/errorscrub_test.go
Possibly as a result of the AWS SDK v2 transition (HIVE-2949 / #2695), or possibly just an arbitrary API change, AWS started spelling the embedded key for request IDs in error messages `RequestID` (it was previously some case variant of `Request ID` -- with a space). This befuddled our regex that was scrubbing such request IDs out of messages we include in status conditions, so those conditions were being updated every reconcile, so their CRs were being requeued immediately, causing thrashing.
Fix the regex to add an optional space.
Also DRY a couple of other spots that were using similar regex-based scrubbing. These may or may not have been causing problems *yet*, but they surely would have at some point. Also tech debt reduction is goodness.
=> HIVE-2923: AWS started spelling it `RequestID`

apis/hive/v1/clusterdeployment_types.go, apis/hive/v1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_clusterdeployments.yaml, hack/app-sre/saas-template.yaml, pkg/constants/constants.go, pkg/controller/clusterversion/clusterversion_controller.go, pkg/controller/clusterversion/clusterversion_controller_test.go, vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Add a new field, ClusterDeployment.Status.ClusterVersionStatus.
At the behest of an (undocumented, unsupported) annotation, `hive.openshift.io/sync-clusterversion-status: "true"` (note: string `"true"` since it's an annotation) our clusterversion controller (the same one that updates the `hive.openshift.io/version*` labels) will populate it with a wholesale copy of the spoke's ClusterVersion.Status field.
NOTE: This requires that our vendor of openshift/api be kept up to date, as e.g. new enum values for `capabilities` will break us.
[HIVE-2366](https://issues.redhat.com//browse/HIVE-2366)
=> Copy ClusterVersion.Status into ClusterDeployment

apis/hive/v1/hiveconfig_types.go, apis/hive/v1/zz_generated.deepcopy.go, config/crds/hive.openshift.io_hiveconfigs.yaml, hack/app-sre/saas-template.yaml, pkg/constants/constants.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterprovisions.go, pkg/controller/utils/podconfig.go, pkg/controller/utils/utils.go, pkg/imageset/generate.go, pkg/install/generate.go, pkg/operator/hive/dynamicclient.go, pkg/operator/hive/hive.go, pkg/operator/hive/hive_controller.go, pkg/operator/hive/hiveadmission.go, pkg/operator/hive/operatorutils.go, pkg/operator/hive/sharded_controllers.go, vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go, vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
xref: [HIVE-2891](https://issues.redhat.com//browse/HIVE-2891)
/cc @huangmingxia 
When deploying hive from a private image repository, in addition to supplying an `imagePullSecret` to the hive operator deployment, users will need to specify this same secret on the `HiveConfig`.  With this change, private image users will be able to provision clusters from any namespace, not just Hive's namespace
=> HIVE-2891: Add new HiveConfig field "HiveImagePullSecretRef"
