openshift/hive

- README.md
- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/templates/cluster-deployment.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types_test.go
- pkg/apis/hive/v1alpha1/installconfig.go
- pkg/apis/hive/v1alpha1/machinepools.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
The installer's InstallConfig is not currently usable as a Kube type, so it had to be copied in, with a few minor modifications. (remove some objectmeta, change the IPNet usage to string, and critically ensure the auto-generated methods are present for Kube such as DeepCopyInto) I am pursuing what we should do with this long term with installer team, but this gets us moving now and we can change easily in future.
ClusterDeployment template allows creating with your desired admin info and SSH key.
Controller updated to create a dummy job that just passes, associated with the cluster deployment. (automatically cleaned up and triggering resyncs of the cluster deployment on job updates changes)
> Template for creating ClusterDeployments and spawning dummy jobs in the controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Previous one did not and the generated yaml was all lowercase.
Both were already vendored via our deps.
> Use a yaml library that respects json tags.

- build/build-image/Dockerfile
- build/hive/Dockerfile
> Change Hive repo to be compatible w/ OpenShift CI.

- Makefile
- build/verify-imports/import-rules.yaml
- contrib/cmd/hiveutil/main.go
- contrib/pkg/verification/imports.go
- pkg/apis/addtoscheme_hive_v1alpha1.go
add initial import verification list config file
update verify-imports subcommand to print filename of failed file
update Makefile with 'verify-imports' target
update files failing new import naming rule
> bring import naming verification into hiveutil

- Makefile
- contrib/cmd/hiveutil/main.go
- contrib/pkg/awstagdeprovision/awstagdeprovision.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
> Add make verify target

- config/default/kustomization.yaml
with kustomize version 1.0.8, it errors with
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: Load from path ../rbac/*.yaml failed: open /home/jdiaz/projects/hive/src/github.com/openshift/hive/config/rbac/*.yaml: no such file or directory
taking out the wildcards gets things working
> kustomize isn't liking the wildcards

- Makefile
> Move make verify dependencies down to targets

- Makefile
> Change 'make fmt' to be inline with 'make verify-format'

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
If the number of load balancers to delete is zero, `lbToAWSObjects` throws an
error which is swallowed by the caller, causing an infinite retry loop in the
exponential backoff wait.
Make the LB deletion function idempotent by correctly handling empty LB lists.
> Fix load balancer deletion hang

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
The previous implementation silently ignored errors returned by `lbToAWSObjects`.  After inserting some debugging logging and running against our CI account, I saw:
```
DEBU[2018-09-28T21:54:47-07:00] failed to convert to lbObjects: Error fetching tags for load balancers: ValidationError: 1 validation error detected: Value '[ci-op-d7qwcq8r-1d3f3-con, ci-op-d7qwcq8r-1d3f3-ext, ci-op-d7qwcq8r-1d3f3-int, ci-op-274cpi9w-1d3f3-con, ci-op-274cpi9w-1d3f3-ext, ci-op-274cpi9w-1d3f3-int, ci-op-i01107d8-1d3f3-con, ci-op-i01107d8-1d3f3-ext, ci-op-i01107d8-1d3f3-int, ci-op-5c88gcn3-1d3f3-int, ci-op-5c88gcn3-1d3f3-con, ci-op-5c88gcn3-1d3f3-ext, ci-op-pp79f299-1d3f3-con, ci-op-pp79f299-1d3f3-ext, ci-op-pp79f299-1d3f3-int, ci-op-dnflccjn-1d3f3-con, ci-op-dnflccjn-1d3f3-ext, ci-op-dnflccjn-1d3f3-int, …
```
> awstagdeprovision: Tag 20 load balancers (max) per request

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
If Status.Installed is true, then return without attempting to install again.
> Avoid installing a clusterdeployment more than once

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/templates/cluster-deployment.yaml
- pkg/apis/hive/v1alpha1/installconfig.go
- pkg/install/generate.go
Switch to secrets for ssh public key, admin password, and image pull secret
> InstallConfig: use secret references instead of strings

- README.md
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
For now uses annotation on ClusterDeployment resource to determine the TectonicClusterID. Eventually, it should be set in the ClusterDeployment's status.
Tidies up generation functions for install/uninstall.
> Generate uninstall job on clusterdeployment deletion

- README.md
- config/crds/hive_v1alpha1_clusterdeployment.yaml
- contrib/cmd/hiveutil/main.go
- contrib/pkg/installmanager/installmanager.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
Modifies the installer container to just copy the install artifacts to a shared empty volume. Adds another sidecar container with a new hiveutil command that will manage execution of the installer, and upload required artifacts after it completes.
> Hive Install Manager Sidecar Container

- Makefile
- README.md
- config/templates/cluster-deployment.yaml
- contrib/pkg/installmanager/installmanager.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
The admin kubeconfig secret, and cluster metadata config map, should be cleaned up when a cluster is deleted.
> Add ownerref to uploaded artifacts.

- Makefile
- README.md
- config/default/clusterdeployment_crd_status_patch.yaml
- config/default/dnszone_crd_status_patch.yaml
- config/default/kustomization.yaml
- config/rbac/rbac_role.yaml
- hack/minishift-deploy.sh
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/install/generate.go
Add a script for deploying to a minishift cluster.
Fixes CRD validation errors due to missing status fields.
Fix image pull policies for in-cluster. (always pull latest installer
image, pull latest hive image if not present)
Fixes RBAC problems in-cluster.
> Fixes for running controllers in-cluster.

- contrib/cmd/hiveutil/awstagdeprovision.go
- contrib/cmd/hiveutil/main.go
- contrib/pkg/awstagdeprovision/awstagdeprovision.go
Builds on #44; review that first.
The cobra code is part of the command-line interface, and removing it reduces the dependency load on folks who are calling the library package from Go.
Also, when building the new `hiveutil` I see:
```console
$ go build -v ./contrib/cmd/hiveutil
github.com/openshift/hive/pkg/apis/hive/v1alpha1
pkg/apis/hive/v1alpha1/clusterdeployment_types.go:89:44: cannot use ClusterDeployment literal (type *ClusterDeployment) as type runtime.Object in argument to SchemeBuilder.Register:
*ClusterDeployment does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/hive/v1alpha1/clusterdeployment_types.go:89:70: cannot use ClusterDeploymentList literal (type *ClusterDeploymentList) as type runtime.Object in argument to SchemeBuilder.Register: …
```
> contrib/pkg/awstagdeprovision: Move cobra code into the hiveutil command

- contrib/cmd/hiveutil/awstagdeprovision.go
- contrib/cmd/hiveutil/main.go
- contrib/pkg/awstagdeprovision/awstagdeprovision.go
Builds on #45; review that first.  I can also rebase this onto master if you want it to go in before #45.
Explaining how multiple tag values interact.
Also fix the usage instructions to show that one `KEY=VALUE` argument is required and more are optional, as documented in the `SYNOPSIS` section of [`man-pages(7)`][1].
[1]: http://man7.org/linux/man-pages/man7/man-pages.7.html#DESCRIPTION
> contrib/cmd/hiveutil/awstagdeprovision: Add long description

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
Dereference the bucket name string pointer when formatting the "error getting tags" debug output.  Neglecting to do so produces error messages like the following:
DEBUG error getting tags for bucket %!s(*string=0xc420433708): [...]
* `contrib/pkg/awstagdeprovision/awstagdeprovision.go` (`bucketsToAWSObjects`): Dereference `bucket.Name`.
> awstagdeprovision: Fix bucket name in debug output

- contrib/cmd/hiveutil/awstagdeprovision.go
- contrib/pkg/awstagdeprovision/awstagdeprovision.go
Builds on #46; review that first.
AWS docs for filters are a bit sparse, but [the AWS docs][1] have:
> Combining search filters
>
> In general, multiple filters with the same key field (for example, tag:Name, search, Instance State) are automatically joined with OR.  This is intentional, as the vast majority of filters would not be logical if they were joined with AND.  For example, you would get zero results for a search on Instance State=running AND Instance State=stopped.  In many cases, you can granulate the results by using complementary search terms on different key fields, where the AND rule is automatically applied instead.  If you search for tag: Name:=All values and tag:Instance State=running, you get search results that contain both those criteria.  To fine-tune your results, …
> contrib/pkg/awstagdeprovision: Allow for OR filters

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
In case there are too many instance to fit on the single `DescribeInstances` page.  Docs for the new function are [here][1].  This might address an issue I saw yesterday, where the instance reaper exited early:
```console
$ oc logs --timestamps -f e2e-aws -c teardown | tee /tmp/teardown.log
$ cat /tmp/teardown.log
2018-10-24T01:45:49.406653647Z Gathering artifacts ...
...
2018-10-24T01:46:16.142364238Z Waiting for logs ...
...
2018-10-24T01:46:19.33849685Z Deprovisioning cluster ...
...
2018-10-24T01:46:19.359616557Z level=debug msg="Deleting instances"
...
2018-10-24T01:46:19.988936278Z level=debug msg="deleting instance: i-0bfc77b0fd7bbe707"
...
2018-10-24T01:46:20.173421738Z level=debug msg="deleting instance: i-0905586e42655a097"
...
2018-10-24T01:46:20.362874514Z level=debug …
```
> contrib/pkg/awstagdeprovision: Switch to DescribeInstancesPages

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
To delete these load balancers:
* deleting V2 load balancers
```console
aws elbv2 describe-load-balancers
{
"LoadBalancers": [
{
"DNSName": "crawford-aws-int-a85653d6d18c082c.elb.us-east-1.amazonaws.com",
"VpcId": "vpc-06de9aca2fabbf1b7",
"State": {
"Code": "active"
},
"Type": "network",
"AvailabilityZones": [
{
"ZoneName": "us-east-1c",
"SubnetId": "subnet-061048a5f17adb00b",
"LoadBalancerAddresses": [
{}
]
},
{
"ZoneName": "us-east-1d",
"SubnetId": "subnet-03506a45cf76bbb78",
"LoadBalancerAddresses": [
{}
]
},
{
"ZoneName": "us-east-1a",
"SubnetId": "subnet-0d36ad7ab10e8a721",
"LoadBalancerAddresses": [
{}
]
},
{
"ZoneName": "us-east-1f",
"SubnetId": "subnet-00f19af286407f964",
"LoadBalancerAddresses": [
{}
]
},
{
"ZoneName": "us-east-1e",
"SubnetId": "subnet-0adbb874efe59de3f", …
```
> awstagdeprovision: add support for deleting V2 LBs and LB Target groups

- pkg/apis/hive/v1alpha1/machinepools.go
- pkg/controller/clusterdeployment/aws.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/convertconfig.go
- pkg/install/convertconfig_test.go
If no default machine pool AMI is set, we will lookup the latest for
RHCOS and store it there for use on any pools that do not explicitly
store their own AMI. This lookup is done with code from
openshift-install.
In future we expect the RHCOS image to use to be a part of the release
image metadata.
> Lookup default AMIs.

- pkg/apis/hive/v1alpha1/register.go
The tools that generate Go clients from Kubernetes API expect the
the existence of the `AddToScheme` and `Resource` functions in the API
package, otherwise compilation of the generated code fails. But the Hive
API doesn't define these functions. This patch adds them.
> Add code generation requirements to API types

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Install manager will now explicitly link to the secret where it uploaded
the admin kubeconfig after installation, rather than this being an
assumed name.
Also extracts the server URL from the admin kubeconfig, and stores a
link to the API and web console in status.
Includes a short term hack that will let this roll out to any persistent
environments by populating the admin kubeconfig secret name based on the
current assumption. We can remove this shortly.
CC @jhernand 
Fixes: https://github.com/openshift/hive/issues/73
> Add kubeconfig secret and API/console URLs to cluster deployment status.

- README.md
When running Hive from source I needed to create the DNSZone crd before Hive could run.
> Add dnszone crd creation to readme

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
When I try to run:
```
make run
```
I get errors:
```
pkg/controller/clusterdeployment/clusterdeployment_controller.go:241: Entry.Errorf call has arguments but no formatting directives
pkg/controller/clusterdeployment/clusterdeployment_controller.go:245: Entry.Errorf call has arguments but no formatting directives
make: *** [Makefile:70: vet] Error 2
```
This PR fixes that.
> Fix cdLog typos

- config/overlays/sd-dev/image_patch.yaml
When replacing with Kustomize it replaces the whole stanza, not just the
properties we specified, and our debug logging command was lost.
> Fix lack of debug logging in sd-dev cluster.

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
We're leaking clusters in CI because of errors [like][1]:
time="2018-11-27T18:48:25Z" level=fatal msg="Unrecoverable error/timed out: error converting route53 zones to internal AWS objects: Throttling: Rate exceeded\n\tstatus code: 400, request id: 0573f1b4-f275-11e8-b479-fd079d6c6b48"
With this commit, we just assume that any error will go away eventually, and keep rolling forward with exponential backoff.  When that assumption breaks down, we expect the caller (e.g. ci-operator or a human user) to kill teardown (and optionally fix whatever was blocking it).
Docs for AWS rate limits are [here][2]; the main takeaway is that these limits are set by AWS with no way for us to request changes, and that most are per-account (not per-VPC or other resource that scales with the number of …
> awstagdeprovision: Ignore more errors

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
We had never tested use of generate name, and were inconsistently using
the cluster deployment name, vs it's spec.config.clusterID.
So far this has surfaced in parsing the cluster name out of kubeconfigs,
and in the arguments we pass to uninstall jobs for the kube cluster ID
tag.
> Fix bugs resulting from use of generate name.

- config/templates/cluster-deployment.yaml
- pkg/awsclient/client.go
- pkg/install/generate.go
Installer was using this format instead, it's more consistent with
~/.aws/credentials and we're soon to have code that will need to read
both, preferably we should sync on the format.
CC @jhernand this will affect you next time we roll out Hive. There are some more disruptive API changes coming, we'll try to land them all at once and summarize them together.
> Sync AWS credential secret keys with installer.

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/install/generate.go
Fixes: https://github.com/openshift/hive/issues/123
Also fixes an uninstall error resulting from my recent rename of the aws cred secret properties.
> Fix GenerateName Bug in Remote Machine Set Controller, and Uninstall Missing Credentials

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
installer wants to start using VPC endpoints (https://github.com/openshift/installer/pull/745), so the uninstaller should find and remove them (they are untaggable objects)
also, remove the code that would remove the individual routes from a route table (it's not needed to remove routes to be able to delete RouteTables)
needed to add these permissions to get the installer/uninstaller working:
ec2:DescribePrefixLists
ec2:DescribeVpcEndpoints
ec2:CreateVpcEndpoint
ec2:DeleteVpcEndpoints
> remove VPC endpoints

- README.md
- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
- test/integration/clusterdeployment/clusterdeployment_controller_test.go
The tectonicClusterID tag is being replaced with openshiftClusterID in the installer. This change will use the new tag name.
Hold on openshift/installer#817.
/hold
> replace tectonicClusterID tag with openshiftClusterID

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/install/generate.go
This is no longer necessary, and was recently removed from the image
meaning Hive installs are now completely blocked as we're waiting on
that binary to be copied.
Installer now vendors Terraform so the binary is not needed.
> Stop copying terraform binary out of installer image.

- Gopkg.lock
- Gopkg.toml
- cmd/manager/main.go
- config/crds/hive_v1alpha1_clusterdeployment.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/utils/utils.go
when we have a kubeconfig for the remote cluster, fetch the ClusterVersion.Status and store it in ClusterDeployment.Status.ClusterVersionStatus
handle nil values for fields in clusterVersion.Status (so we can pass object validation)
update test cases to work with new need to mock up remote ClusterVersion object
refactor the building of a remotecluster kubeclient (and update remotemachineset controller accordingly)
build on top of https://github.com/openshift/hive/pull/127 to get beyond the gomock issues
> store cluster version into clusterdeployment status

- contrib/pkg/installmanager/installmanager.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/utils/utils.go
move clusterversion.Status field fixing into utils and use it where necessary in installmanager
current installer seems to be failing, but the updating of the status is working now:
```
time="2018-12-12T15:06:43Z" level=info msg="uploaded cluster metadata configmap" configMapName=jdiaz-hive-metadata
time="2018-12-12T15:06:43Z" level=info msg="uploading admin kubeconfig"                                                                                         
time="2018-12-12T15:06:43Z" level=info msg="uploaded admin kubeconfig secret" secretName=jdiaz-hive-admin-kubeconfig
time="2018-12-12T15:06:43Z" level=info msg="updating cluster deployment status"
!!!!! NO ERROR LINE HERE WHILE UPDATING CLUSTERDEPLOYMENT !!!!!
time="2018-12-12T15:06:43Z" level=fatal msg="failed due to install error" …
```
> fix clusterversion.Status is more places

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/templates/cluster-deployment.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/install/generate.go
Now passed as an override for the installer. Will soon be used to
determine what installer image to use.
> Add support for specifying release image.

- Dockerfile
- Makefile
Simplify image building by using a single multi-stage Dockerfile. Existing Dockerfile will be removed in a follow-up PR after modifying CI config.
> Add multistage Dockerfile

- pkg/controller/utils/utils.go
Fixes error when listing machine sets.
```
time="2018-12-18T19:45:24Z" level=error msg="unable to fetch remote machine sets" clusterDeployment=abutcher controller=remotemachineset error="no kind is registered for the type v1alpha1.MachineSetList" namespace=myproject
```
> Set cluster api scheme in cluster api client builder.

- contrib/pkg/installmanager/installmanager.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/install/generate.go
Use install-config.yaml instead of install-config.yml. The name of the file used by openshift-install has changed and install-config.yml is deprecated.
> use install-config.yaml

- Makefile
- README.md
- config/hiveadmission/hiveadmission.yaml
- config/manager/manager.yaml
- config/templates/cluster-deployment.yaml
- manifests/00-namespace.yaml
We no longer use the oc cluster up method and thus the use of local hive
images was no longer useful.
Instead we default to latest published images on registry.ci, and a
simple make deploy to install Hive.
> Improve process and docs for deploying in cluster.

- pkg/controller/utils/utils.go
Fixes this error:
ERRO[0143] error fetching remote clusterversion object   clusterDeployment=dgoodwin1 error="no kind is registered for the type v1.ClusterVersion" job=dgoodwin1-install namespace=openshift-hive
Any idea what happened here @joelddiaz or @csrwng  ? I don't understand why this would show up suddenly.
> Fix missing config.openshift.io type in scheme.

- pkg/install/generate.go
Appears this has been changed back to not have an underscore prefix:
https://github.com/openshift/installer/blob/master/pkg/asset/ignition/bootstrap/bootstrap.go#L148
> Fix installer release image override var name.

- README.md
- contrib/federation_example/00_namespace.yaml
- contrib/federation_example/00_namespace_placement.yaml
- contrib/federation_example/cluster-role-binding-placement.yaml
- contrib/federation_example/cluster-role-binding-template.yaml
- contrib/federation_example/cluster-role-placement.yaml
- contrib/federation_example/cluster-role-template.yaml
- contrib/federation_example/deployment-placement.yaml
- contrib/federation_example/deployment-template.yaml
- hack/install-federation.sh
Example enables installation of [etcd-operator](https://github.com/coreos/etcd-operator) on target clusters.
> Add operator federation example

- config/templates/cluster-deployment.yaml
For some reason our clusters started failing to come up properly this
week. Comparing a working CLI run to our install config, these changes
in the networking CIDRs showed up, and appeared to correct the problem.
Also updated to a newer default release image.
> Fix networking in cluster deployment template.

- cmd/hiveadmission/main.go
- config/hiveadmission/hiveadmission.yaml
- config/samples/hive_v1alpha1_clusterdeployment.yaml
- config/templates/hiveadmission.yaml
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
> Make ClusterDeployment.spec mostly immutable

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- pkg/apis/hive/v1alpha1/machinepools.go
- pkg/controller/clusterdeployment/aws.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/install/convertconfig_test.go
This feature was broken after we merged validation that you cannot
change anything outside of spec.Compute. Rather than adding another
exception, this moves the default AMI pinning to an annotation, as the
entire feature is not going to be needed once we implement the design
for OS image lifecycle, so the sooner it's out of the API the better.
CC @jhernand 
I think this will roll out to opshive smoothly. We will lose the AMI that was pinned when that cluster deployment was created. The controller's will realize this and lookup the latest RHCOS image as soon as they sync the CD again. That will then be stored in the annotaton. It's very possible it will be different than the previous image, and when we sync machine sets it would then be set in-cluster. However that would only take effect …
> Remove AMIs from API.

- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Refactors tests to use functions instead of global vars to prevent any one test from being able to change a value and affect later tests.
> Allow editing PreserveOnDelete.

- config/templates/cluster-deployment.yaml
- pkg/install/generate.go
If annotation is present, generated job will not do a backoff and pods created by it will not restart on failure.
The default clusterdeployment template will allow passing TRY_INSTALL_ONCE=true to enable this behavior.
> Add annotation to try install only one time

- README.md
- config/overlays/sd-dev/image_patch.yaml
- pkg/controller/clusterdeployment/aws.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Generally related to pre-existing cluster deployments without some fields set, possibly worse on 3.10.
> Fix bugs uncovered when rolling out to opshive

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
1) Adding the missed https:// prefix from the web console url.
> adding https prefix to web console url

- Makefile
- contrib/cmd/waitforjob/main.go
- hack/e2e-test.sh
This script is meant to be invoked by an openshift_installer_src job in CI
> Add e2e test that installs hive and creates a cluster

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/crds/hive_v1alpha1_dnszone.yaml
- hack/install-federation.sh
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/federation/clusterdeployment_federation_controller.go
- pkg/controller/federation/clusterdeployment_federation_controller_test.go
Adds field to ClusterDeployment status to keep track of corresponding FederatedCluster resource. Synchronizes labels from ClusterDeployment to FederatedCluster resource.
Adds unit tests to federation controller.
> Federation controller: handle label sync

- config/templates/cluster-deployment.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/install/convertconfig_test.go
Related to https://github.com/openshift/release/pull/2922 and maybe the cause of the cluster CI failures all day today.
I'm not strictly sure if this required to get through CI or not.
CC @jhernand this will require a change on the UHC side once this rolls out.
> Match OpenshiftSDN -> OpenShiftSDN network type change.

- pkg/controller/add_clusterversion.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/utils/utils.go
Moves the code to update the cluster version status on a cluster deployment to its own controller so that it can be updated on an interval over the life of a cluster.
Adds fix to FixupEmptyClusterVersionFields so that it can set a value on History.CompletionTime and avoid a validation error.
> Add controller to update clusterversion status

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- hack/e2e-test.sh
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
Adds the `cd` short name to the `ClusterDeployment` CRD so that we can do `kubectl get cd`.
Adds `baseDomain` and `status.installed` as custom printer columns so that the printer output looks like
```
$ kubectl get cd
NAME     BASEDOMAIN                                INSTALLED   AGE
ffranz   ffranz-cluster-deployment.openshift.com   false       4m7s
```
@csrwng @dgoodwin makes sense?
> Short name and custom printer columns for the ClusterDeployment CRD

- config/templates/cluster-deployment.yaml
- contrib/cmd/waitforjob/main.go
- hack/e2e-test.sh
- pkg/install/generate.go
Adds annotation to clusterdeployment to allow running uninstall job only once.
Watches uninstall job in e2e script and displays the uninstall log.
> Improve debug logging for e2e uninstall

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/install/convertconfig.go
- pkg/install/convertconfig_test.go
- pkg/install/generate.go
Allow adding non-worker compute pools when initially creating clusterdeployment. The installer will error with extra pools but we can try to make them later when syncing machinesets.
> Remove non-worker pool when generating install config for installer.

- Makefile
Since https://github.com/openshift/hive/commit/d22c82bcb was introduced,
there is no need to to run generate before the build as well, since it's
already happening inside the Dockerfile.
> remove generate as a dependency of docker-build

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
- vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
- vendor/github.com/openshift/installer/pkg/rhcos/ami.go
- vendor/github.com/openshift/installer/pkg/rhcos/qemu.go
Generated with:
```console
$ dep ensure -update
```
using:
```console
$ dep version
dep:
version     : v0.5.0-31-g73b3afe
build date  : 2019-02-08
git hash    : 73b3afe
go version  : go1.10.3
go compiler : gc
platform    : linux/amd64
features    : ImportDuringSolve=false
```
Pulling in snapshot (openshift/installer#1346) and network-interface (openshift/installer#1361) deletion.
> vendor: Update the installer to get additional AWS deletion

- Makefile
- config/hiveadmission/clusterimageset-webhook.yaml
- config/kustomization.yaml
- config/manifests/01_clusterimageset_crd.yaml
- config/templates/cluster-deployment.yaml
- hack/e2e-test.sh
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hiveadmission.go
Ensures that clusterimagesets and corresponding webhook are provisioned by the Hive operator. Makes the use of clusterimagesets the default in the clusterdeployment template and in the e2e test.
> Use ClusterImageSets in clusterdeployment template and in e2e

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
- pkg/install/generate_test.go
--> Skips the creation of uninstall job only if Spec.PreserveOnDelete and Status.Installed are true. If the cluster deployment is not installed, overrides the PreserveOnDelete to create an uninstall job.
> Override PreserveOnDelete if cd is not installed

- build/olm-registry/Dockerfile
- bundle/0.1.494-3f73a592/hive-operator.v0.1.494-3f73a592.clusterserviceversion.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_clusterdeployment.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_clusterimageset.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_dnszone.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_hiveconfig.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_selectorsyncidentityprovider.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_selectorsyncset.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_syncidentityprovider.yaml
- bundle/0.1.494-3f73a592/hive_v1alpha1_syncset.yaml
- bundle/0.1.5-4b53b492/hive-operator.v0.1.5-4b53b492.clusterserviceversion.yaml
- bundle/hive.package.yaml
- config/hiveadmission/hiveadmission_rbac_role.yaml
- docs/olm.md
- hack/generate-operator-bundle.py
- hack/olm-registry/catalog-source.yaml
- hack/olm-registry/hive-subscription.yaml
- hack/olm-registry/operator-group.yaml
Updates operator bundle generation script, document how to use it,
generate a bundle and CSV, build an OLM registry image, and then install
everything in a 4.0 cluster.
> Generate new OLM bundles and document testing.

- contrib/pkg/testresource/command.go
- pkg/operator/assets/bindata.go
- pkg/resource/apply.go
- pkg/resource/info.go
- test/integration/resource/apply_test.go
Separates out the Info function so that we can call it first for all resources before applying anything to the cluster.
> resources: add separate Info function

- build_deploy.sh
The build_deploy.sh script now creates and pushes the hive-registry olm
catalog container.
It uses this repo to support keep the story of CSV versions and to generate
the hive-registry image:
https://github.com/app-sre/saas-hive-operator-bundle/tree/staging
> Create operator registry container in AppSRE CI/CD

- config/hiveadmission/daemonset.yaml
- pkg/operator/assets/bindata.go
We suspect this is blocking pod creation in hive-stage. Until we sort
out what is blocking this and if we can/should work past it, removing
the node selector moves hiveadmission to run on every compute node.
We may move to something other than a daemonset once this is fully
sorted out if this is desirable long term.
> Remove hiveadmission daemonset node selector.

- README.md
- build_deploy.sh
- hack/olm-registry-deploy.sh
- hack/olm-registry/olm-artifacts-template.yaml
IMAGE_TAG is a convention of saasherder, the CI/CD tool used by the
AppSRE team:
https://github.com/openshiftio/saasherder/
This tool revolves around the idea of deploying OpenShift templates,
always passing `IMAGE_TAG` as a parameter generated by obtaining the
short git commit hash.
In this particular case we need IMAGE_TAG to appear in the OpenShift
template we are applying:
`/hack/olm-registry/olm-artifacts-template.yaml`.
Since we need to have more than one catalog stream, namely `production`
and `staging` we opted for the idea of generating:
- `staging-<hash>` and `production-<hash>` as the non-moving targets
- `staging-latest` and `production-latest` as the moving targets
When it comes to iterating the CatalogSource, we would need to oc apply
the non-moving target, so it kicks OLM …
> Adds IMAGE_TAG

- Gopkg.lock
- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/operator/operator_role.yaml
- config/rbac/rbac_role.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/controller/add_remoteingress.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/operator/assets/bindata.go
extend ClusterDeployment to allow defining a list of ingress objects that should be configured on the cluster as IngressController objects for the openshift-ingress-operator to set up.
spec.ingress can be empty which will result in default cluster behavior (ie self-signed certs, *.apps.<base domain> default route, etc). otherwise, spec.ingress can provide for additional ingress objects (although you must provide settings for the 'default' ingress object in this case). and once you define ingress objects, you cannot go back to default behavior. all this is enforced by the admission webhooks.
when spec.ingress is defined, it will create a syncset object with all the desired ingress definitions so that the appropriate IngressController objects are set up in the cluster.
this version of the …
> remoteingress controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/install/generate.go
When using a ClusterImageSet and its release image is set. Ensure that we are using that to set the OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE environment variable.
> Ensure release image from ClusterImageSet is set for install job

- contrib/cmd/waitforjob/main.go
At least a couple of e2e tests have failed with us timing out waiting for the job to complete, but nothing wrong going on in the install log. This increases the timeout so we don't prematurely fail the job.
> Increase timeout for CI install job

- config/hiveadmission/deployment.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
--> Replaces the hiveadmission daemonset with a deployment (replication = 2)
--> Removes the daemonset from the clusters that might already have it. Needs to be removed once it is run in opshive
> Replacing hiveadmission daemonset to deployment

- pkg/apis/hive/v1alpha1/clusterimageset_types.go
Without this the code generated by the `informers-gen` tool produces
code that then fails to compile with this error:
```
pkg/hive/informers/externalversions/hive/v1alpha1/interface.go:57:54:
unknown field 'namespace' in struct literal of type clusterImageSetInformer
```
> Place `genclient:nonNamespaced` before `genclient`

- cmd/manager/main.go
- pkg/controller/add_metrics.go
- pkg/controller/metrics/metrics.go
- pkg/controller/utils/utils.go
This is just a starter PR, @ShivamChamoli will be taking over writing most of these. Vendors prometheus, exposes a couple cluster deployment controller metrics, and establishes a metrics calc loop outside of controllers for more global totals calculated every 2 minutes.
This can be tested with "make run" and "curl http://localhost:2112/metrics".
> Add initial support for publishing prometheus metrics

- pkg/install/generate.go
Credentials are not tagged in the new style because the infra ID is not
yet officially available in the cluster itself.
This change matches what the installer delete cluster command does by
also including the old openshiftClusterID tag.
> Fix IAM user leak on deprovision.

- cmd/operator/main.go
- config/hiveadmission/clusterimageset-webhook.yaml
- config/operator/operator_role.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/util/admissionregistration.go
- pkg/resource/apply.go
Restores the setting of kube/service CA on APIService and webhooks, which was dropped in recent refactoring. This is now performed in the operator, but only if running on a 3.11 cluster.
> HiveAdmission Fixes

- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
this is needed for the ability to generically apply all kinds of object types (from https://github.com/openshift/hive/pull/247 )
> add Type info for the IngressController objects

- config/crds/hive_v1alpha1_hiveconfig.yaml
- config/operator/operator_role.yaml
- pkg/apis/hive/v1alpha1/hiveconfig_types.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
Adds a hash to the operator config to keep track of the openshift-config-managed/kube-apiserver-aggregator-client-ca configmap's contents. If it changes, admission is redeployed.
> Restart Hive Admission when certs expire

- hack/e2e-test.sh
The `uuidgen` approach is from fce37416 (#222), where we were working around a broken `oc` call and the installer's poor handling of long cluster names.  The long-name handling has since been fixed, so this commit drops the workaround `cut`.  It also adds a `hive-` prefix to make it easier to track down issues when we leak CI resources.
> hack/e2e-test: Add "hive-" prefix to cluster name

- config/clusterimagesets/openshift-4.0.0-0.8.yaml
- config/templates/cluster-deployment-customimageset.yaml
- config/templates/cluster-deployment.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/imageset/generate.go
- pkg/install/generate.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
- test/integration/clusterdeployment/clusterdeployment_controller_test.go
Pull secrets are returned from try.openshift.com in a format that is invalid if used with a dockercfg secret. The correct secret type is dockercfgjson. 
This change converts our templates and all code to use the new secret type, and key within that secret.
We are not migrating pre-existing pull secrets, rather I have made sure to remove any code that uses those secrets after the cluster is installed, so outdated pull secrets should not be an issue in stage, which is the only environment where they could exist right now. Cluster deployment controller was unnecessarily loading pull secrets and reconstructing the install job even after installation, and the remote machine set controller was loading it just as an input to obtain a installer config, which it definitely does not need the pull …
> Replace incorrect use of dockercfg pull secrets with dockerconfigjson.

- pkg/controller/remotemachineset/remotemachineset_controller.go
This only shows up on edits but it contains a very large blob of bytes
that is largely useless and looks quite strange in logs. Trim down and
just note why we're updating the machineset.
> Remove logging of full machineset in remotemachineset controller.

- config/rbac/hive_frontend_role.yaml
cc @jhernand 
The HiveConfig is always named "hive".
> Add frontend role RBAC for HiveConfig to view top level DNS zones.

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/dnszone/zonereconciler.go
- pkg/controller/utils/utils.go
- pkg/install/generate.go
To help alleviate problems where one version of hive can only generate
one version of the install config, but we need to install many possible
releases which may not support that install config version.
This change now assumes that the hiveutil install wrapper looks up the
cluster deployment, and then generates the install config on the fly. By
pinning one version of hiveutil to one version of the installer (via a
ClusterImageSet), we should remain more compatible over time.
The previous method of generating an install config in the controller
and mounting via config map is still left behind for backward
compatability. Once we can drop beta2 and beta3 ClusterImageSets this
can be removed.
> Generate install-config in hiveutil install wrapper.

- pkg/controller/clusterversion/clusterversion_controller.go
This should change relatively infrequently, 30 seconds was a bit
excessive in the logs. Instead we will let the normal resync interval
take over. (10-30m or so)
> Remove cluster status resync interval.

- config/rbac/hive_admin_role.yaml
- config/rbac/hive_admin_role_binding.yaml
- hack/update-bindata.sh
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
This role allows the basic cluster wide permissions we expect to need to
administer a hive cluster.
It grants read access to all the Hive types, as well as jobs, pods, and
pod logs.
It grants write access to the HiveConfig.
It does not grant access to secrets or configmaps.
This is delivered via the operator itself, rather than the CSV because
we need to bind to a group, not a service account.
> Deliver a hive-admin role via the operator.

- config/rbac/rbac_role.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/operator/assets/bindata.go
plumb through code to pull the certBundle's secrets that ingress objects refer to so that the syncset created also makes sure a secret is mirrored over to the remote cluster so that the ingressController objects on the remote cluster can come up with custom certificates.
> add support for ingress objects referencing certificates

- contrib/pkg/testresource/command.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/operator/hive/externaldns.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/util/apply.go
- pkg/resource/apply.go
- pkg/resource/factory_discovery.go
- pkg/resource/helper.go
- pkg/resource/info.go
- pkg/resource/kubeconfig_factory.go
- pkg/resource/patch.go
- pkg/resource/restconfig_factory.go
- pkg/resource/serializer.go
- test/integration/resource/apply_test.go
- Apply now reports whether the call resulted in a create, modification, or no change
- Makes creating a helper from an existing rest.Config more robust by using the rest.Config directly instead of first serializing to a kubeconfig
- Fixes a bug with serialization that resulted in every apply always calling patch (because of `creationTimestamp: null` being present)
> ResourceHelper improvements

- pkg/controller/add_federation.go
We can enter a state in which the federation finalizer is not removed
from a deleting cluster because federation is only installed in a
different namespace. We need a better method for determining whether a
cluster should be federated.
> Disable federation controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/install/generate.go
1) Calculated deprovision job duration metrics by assigning a label to the uninstall job which has the unix timestamp when it is created, and found out the difference between the unix timestamp when the uninstall job finished.
2) Used unix timestamp so that there is no date compatibility issue.
3) Metrics were not calculated if the job failed at any step.
> deprovision job duration metrics

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
UHC reporting long delays between creating clusterdeployment and having the install job launched.
logs indicated delays from when we clear the empty clusterversion in status and adding the finalizer. for these two paths, force a requeue.
add test cases to check for results from Reconcile()
> force requeue after fixing status fields and adding finalizer

- config/operator/operator_role.yaml
This is blocking rollout of the plural fix for hive-admin role as kube
thinks the operator is trying to grant more permissions than it has.
> Fix plural rbac for operator for hive CRDs.

- config/manager/deployment.yaml
- config/operator/operator_deployment.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/operator/assets/bindata.go
Switches from serially processing 1 reconcile at a time to 100 for most controllers, it might be possible to go to thousands here but this is just a first test. Want to see how this behaves in stage.
Moved creation of a remote client in cluster deployment controller into a guarded block where it's actually used. We were doing this even if we didn't need it for every cluster.
Remove CPU and memory limits per advice from @jeremyeder .
> Attempted fix for long (5-20m) delays creating install jobs.

- Dockerfile
- Makefile
- build/build-image/Dockerfile
This is now failing because master for gomock appears to require go
1.11.
However we don't need to generate code for a Docker build, assume we're
building a container with the latest committed code. A developer using
containers for their work will need to run make generate before building
their container.
> Remove generation from container build process.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/federation/clusterdeployment_federation_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/utils.go
On advice from deads this is probably a better idea, mostly for
debugability in logs, but it's a common value from Kube that has never
gone wrong for them, so it should be good for us as well.
> Drop from 100 to 5 for concurrent goroutines.

- pkg/apis/hive/v1alpha1/hiveconfig_types.go
The description of the `HiveConfig` type has the
`+genclient:nonNamespaced` comment, but not `+genclient`. Both need to
be present, otherwise the code generation tools don't generate a client
for the type.
> Use `+genclient` for the configuration object

- pkg/awsclient/mock/client_generated.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
unconditionally creating the non-nil map was causing the equality check against the remote machinesets to always detect a difference when there are no lables on the machine set. check if we will need to populate the map before allocating he map.
also pull in some unrelated generated mockgen changes
> avoid needlessly making a non-nil map

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
- pkg/imageset/generate.go
- pkg/install/generate.go
This covers total jobs running / failed, and the time between cluster creation and job to resolve creation.
We've discussed revamping this so we only resolve once per cluster image set instead of for every deployment, we just need to solve the pull secret problem.
> Add some imageset resolution metrics

- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/awsclient/mock/client_generated.go
when adding a new ingress, it is possible that the new ingress entry will need to reference a new spec.certificiateBundles[] entry. mark certificatesBundles as mutable.
after installing in default mode (ie self-signed certs) cluster, it is reasonable to then migrate to signed certificates which will require making controlPlaneConfig.servingCertificates.* as mutable.
also pull in some unrelated mockgen changes
> allow modifying certificateBundles and controlPlaneConfig.servingCertificates

- pkg/awsclient/mock/client_generated.go
- pkg/imageset/generate.go
In the event of a error running the oc adm release command to resolve
the installer image to use, the script does not return an error, nor
does the hiveutil sidecar pod, and the controller sees the job finished,
no installer image set, so it recreates a new job.
This leads to a hotloop where in the event of a long lived failure, the
controllers are deleting and recreating new jobs and pods as quickly as
possible, which leads to excessive reconciliation results in the
controllers.
To fix this change just returns a non-zero exit code when the release
extraction command fails. This causes the job to see an failure and
re-try with backoff. If we run up against the job expiration the
controllers should then see a finished job, no installer image, and
create a new one as they do now.
> Fix imageset job hotloop.

- config/rbac/hive_admin_role.yaml
- pkg/operator/assets/bindata.go
This is needed because we need to set up a pipeline that manages the SelectorSyncSets on the Hive clusters
> hive-admin role can CRUD SelectorSyncSets

- config/crds/hive_v1alpha1_selectorsyncset.yaml
- config/crds/hive_v1alpha1_syncset.yaml
- contrib/pkg/testresource/command.go
- pkg/apis/hive/v1alpha1/syncset_types.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/resource/patch.go
- test/integration/resource/patch_test.go
I added a second commit that will test the patch type provided so that we get a useful error message for incorrect patch types.
```
ERRO[0019] failed to setup patch command controller=syncset error="Invalid patch type: potato. Valid patch types are 'strategic', 'merge' or 'json'"
ERRO[0019] unable to apply sync set patches clusterDeployment=abutcher controller=syncset error="Invalid patch type: potato. Valid patch types are 'strategic', 'merge' or 'json'" namespace=default syncSet=example2
```
>  Use short patch strings in syncset patch definition.

- cmd/hiveadmission/main.go
- config/hiveadmission/selectorsyncset-webhook.yaml
- config/hiveadmission/syncset-webhook.yaml
- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hiveadmission.go
Adds validating webhooks for syncsets and selectorsyncsets. Rejects patches with invalid patch types.
> Validate SyncSet PatchType

- pkg/controller/metrics/metrics.go
Failed jobs do not have a completion time, so they were appearing as
running.
> Fix failed jobs showing as running in metrics.

- config/rbac/manager_role.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/operator/assets/bindata.go
A fix is coming to UHC next week to prevent namespaces from being deleted before the cluster deployment is gone.
However in meantime, and in case this happens again, we need to watch for the error and if encountered, give up on deprovision, as there's little we can do. This change removes the finalizer and lets the cluster go away.
> Give up on deprovisioning in deleted namespaces.

- Makefile
- config/operator/operator_role.yaml
- config/rbac/hive_admin_role.yaml
- config/rbac/hive_reader_role.yaml
- hack/update-bindata.sh
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Due to an OLM bug where CRDs are only created new, never updated, we
need a temporary workaround until a fix can be delivered. Rather than
having humans kubectl apply all the CRDs we'll do so with our operators.
The CRDs still are referenced in the OLM bundle, but we're re-applying
them here.
Change also adds hive admin and reader permissions to view CRDs, as this
is coming up a lot given the current bugs.
> Deploy CRDs in the hive-operator.

- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
Adds a toleration to IngressControllers that we sync to the remote cluster with a hash of the current cert secret data as the value. If the cert secret changes, we will update the toleration with a new hash value and cause the IngressController to reload.
> Remote ingress - include toleration to ensure ingresscontroller reload

- config/clusterimagesets/openshift-4.0-beta3.yaml
- config/clusterimagesets/openshift-4.0-beta4.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
rc.3+ will work better, but quay rate limiting is affecting the ability
to install these releases.
> Drop outdated and broken ClusterImageSets.

- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
When specifying a default certificate for the control plane, use the AdditionalCertificates field in the APIServer config instead of the DefaultServingCertificate.
We need to do this until the kube-apiserver operator is fixed in 4.x
> Control plane certs - use additionalCertificates field

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- docs/developing.md
- pkg/install/generate.go
Modifies install manager to write a sleep-seconds.txt file that uses the
current number of retries for exponential backoff when an install fails,
up to a max of 24 hours. This will help prevent constant API calls on
clusters that need attention before they can possibly install
successfully.
Pod install command is now a shell script that optionally looks for this
file, and if found, sleeps the requested number of seconds. This should
allow the feature to be backward compatible with older hive images which
do not write the file.
This approach should limit the memory consumed as the hiveutil
install-manager has exited, and we're just left with a shell sleep.
Additionally this change adds a deprovison immediately after failed installs.
This will help reduce running resources in the event of a …
> Delay install retries with sleep.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/federation/clusterdeployment_federation_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/cacrt.go
- pkg/operator/hive/hive.go
Adds field to ClusterDeployment status to hold the raw kubeconfig
Points the original status.AdminKubeconfigSecret to a new generated secret that contains additional CAs
Includes fix to hive operator to force a reload of the hive controllers pod when the AdditionalCertificateAuthorities value changes.
> Generate kubeconfig secret with additional CAs

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Workaround an issue we've seen at least on 3.11 where is it possible for
a dnszone to be terminating when it's parent cluster deployment is gone,
despite blockOwnerDeletion on it's owner ref.
Instead we now refuse to remove the cluster deployment finalizer until
managed dnszones are deleted.
Additionally we have seen rare clusters where deleting the parent
cluster deployment did not automatically delete the managed DNSZone.
Also watch for this situation and issue our own delete if encountered.
> Workarounds for problems with managed DNSZone cleanup.

- contrib/pkg/installmanager/installmanager.go
Recent change to cleanup immediately after failed installs had a bug
where we updated the cluster deployment with the new infra ID, but on a
different pointer to the object than we used later in the code to do the
cleanup, resulting in an attempt to cleanup an infra ID we already
cleaned up, and nothing is found, leaving cluster objects in place.
Issue surfaced as a DNS hosted zone already existing in this case.
Fix by setting the infra ID explicitly on the cd we use throughout the
install.
> Fix leaking resources on install retries.

- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/awsclient/mock/client_generated.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
> wildcard ingress migration and webhook validation

- pkg/awsclient/mock/client_generated.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/imageset/generate.go
- pkg/imageset/generate_test.go
When specified in a cluster deployment, the release image from the cluster deployment should take precedence over the release image from a clusterimageset to run the job that determines an installer image.
Fixes https://jira.coreos.com/browse/CO-425
> Use release image from clusterdeployment when present

- pkg/apis/helpers/namer.go
- pkg/apis/helpers/namer_test.go
- pkg/awsclient/mock/client_generated.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnszone/zonereconciler.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/imageset/generate.go
- pkg/install/generate.go
Introduces utility from origin to shorten long names, switches to using the utility wherever we generate names of API resources from a clusterdeployment name.
Fixes https://jira.coreos.com/browse/CO-435
> Handle long clusterdeployment names

- config/configmaps/install-log-regexes-configmap.yaml
- config/rbac/manager_role.yaml
- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- hack/update-bindata.sh
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/add_installlogmonitor.go
- pkg/controller/installlogmonitor/installlogmonitor_controller.go
- pkg/controller/installlogmonitor/installlogmonitor_controller_test.go
- pkg/controller/installlogmonitor/installlogregex.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Adds a new controller to monitor the install logs we upload as
configmaps. Logs will be logged to the main hive-controllers log so we
can find them in one place.
Logs will be scanned for a list of regexes (defined in a configmap and
delivered by our operator) which map to keys. If encountered those keys
are reported as the reason on the InstallFailing condition, and a metric
is incremented.
Only two errors right now, we've lost our access to ConfigMaps but the logging in this PR will let us see them again and we can add more search strings once we know what to expect.
> Monitor install logs for errors.

- config/templates/cluster-deployment.yaml
- contrib/pkg/createcluster/create.go
- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
- pkg/awsclient/mock/client_generated.go
- pkg/install/generate.go
allow storing the ssh private key in the ssh secret
extend installmanager to set up ssh agent (if necessary), read in terraform file, generate script to fetch logs, and run the script to fetch the logs
TODO: store the saved log somewhere (S3, the in-cluster registry)
> scaffolding for saving log tarball on failures

- contrib/pkg/installmanager/installmanager.go
- pkg/controller/installlogmonitor/installlogmonitor_controller.go
Seeing clusters failing at this stage due to permissions, and their
retries are not getting limited via the sleep seconds.
> Write sleep seconds file when we fail to generate assets.

- pkg/awsclient/mock/client_generated.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
allow detection of an install job spec change by saving the hash of the job.Spec into an annotation on the job.
with this we can detect when we need to delete/replace an existing install job (for example when a new version of hive is installed and wants to launch install jobs with different configurations than the previous version (fixing a bug to get the install jobs unstuck)).
> save job spec hashes for install jobs

- Makefile
- hack/e2e-test.sh
- test/e2e/common/apiservice.go
- test/e2e/common/client.go
- test/e2e/common/deployment.go
- test/e2e/common/diff.go
- test/e2e/common/service.go
- test/e2e/postdeploy/admission/admission_test.go
- test/e2e/postdeploy/hivecontroller/manager_test.go
- test/e2e/postdeploy/operator/operator_test.go
Adds post-deploy tests for hive, ensuring that main components (operator, controllers, and admission) are functional.
Switches to logging the install console log if available to reduce main log size. The full debug log should still be available in the artifacts directory.
> Post-Deploy e2e tests

- hack/generate-operator-bundle.py
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,
as the default Loader is unsafe
> Fix the YAMLLoadWarning in generate-operator-bundle.py

- pkg/install/generate.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
we can't easily add new cli parameters to the install-manager subcommand b/c it would break
compatibility with older install images.
retire the recently added --ssh-priv-key-path param, and use SSH_PRIV_KEY_PATH env var instead.
update tests, and job generator as appropriate.
> remove recent command line params for passing private ssh info

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/installlogmonitor/installlogmonitor_controller.go
- pkg/controller/metrics/clientwrapper.go
- pkg/controller/metrics/clientwrapper_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/unreachable/unreachable_controller.go
Adds a transport wrapper which parses a little info about the request to determine what resource we're dealing with, and then increments a prometheus counter with labels for method, resource, and what controller the client is from. This allows us to identify who is causing hotloops with excessive writes.
Only tricky part of this was the rest config copying, last week it did not function properly (no metrics), today it does, so we'll see how this goes in stage.
> Client Metrics

- config/external-dns/deployment.yaml
- pkg/operator/assets/bindata.go
Changes the external-dns deployment to use a TXT record registry and mode `sync` so that when a dnsendpoint is deleted, it cleans up the records associated with that dnsendpoint.
Fixes https://jira.coreos.com/browse/CO-403
> Cleanup NS records created for managed domains

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Removes unnecessary code to fixup status fields in clusterdeployment controller (the fields are no longer required in latest crds)
Implements the following pattern when deleting a related resource:
- If deleting the resource, run the delete and return immediately (don't assume we can continue). No requeue is needed because the delete will cause a requeue.
- When retrieving the resource, if the resource is being deleted (DeletionTimestamp is non-nil), return and requeue for an interval of time. (Otherwise we are not guaranteed that the resource will be requeued)
Other than that, a few minor fixes in the code.
> Update clusterdeployment controller to handle deleted resources

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/utils.go
This code mistakenly assumed that if you tried to hit a cluster that
already has unreachable condition set, we should return that as an
error. This however causes the controller-runtime framework to keep
retrying, with backoff, but still a lot of reconciling and errors
logged.
Instead we should check for the condition and skip reconcile, without
considering this an error.
In time, if the cluster comes back, the unreachable controller will
clear the condition at which point all these controllers will resume
normal operation.
> Skip reconciles for unreachable clusters.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/installlogmonitor/installlogmonitor_controller.go
- pkg/controller/metrics/metrics.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/unreachable/unreachable_controller.go
controller-runtime technically does this for us but due to a bug the
results currently include queue time, which completely skews the
results.
Add our own metric so we can monitor how long we're taking to get
through reconcile loops.
> Add controller reconcile time metrics for all controllers.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
With the change each log from CD will contain controller=clusterDeployment
> Make logging from CD consistent with other controllers

- config/operator/operator_role.yaml
- config/rbac/hive_admin_role.yaml
- pkg/operator/assets/bindata.go
Allow the Hive admin role to be able to query admission related config and create requests directly to the admission API group in order to debug hive admission.
> Add permissions to allow debug of admission

- Makefile
The reason we're seeing stack dumps on failing tests is that we're hitting the default `go test` timeout of 10 minutes. All e2e tests have built-in timeouts so the outer timeout is redundant. With a value of 0, we remove the timeout.
> Remove e2e test timeout

- contrib/cmd/hiveutil/main.go
- contrib/pkg/createcluster/create.go
- contrib/pkg/deprovision/awstagdeprovision.go
- hack/e2e-test.sh
Switches to using `hiveutil create-cluster` in e2e test
Adds --install-once and --uninstall-once flags to create-cluster command
> Use hiveutil create-cluster in e2e test

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
Some time back we moved this logic into the installmanager which runs
alongside the installer and is closely versioned with it. We carried
this code for the sake of some older ClusterImageSets which still needed
it, but these should be long gone now.
> Remove legacy controller gen of install config.

- config/rbac/hive_admin_role.yaml
- pkg/operator/assets/bindata.go
Admins need to setup identity providers for support purposes that land on groups of clusters.
> ClusterRole hive-admin can edit selectorsyncidentityproviders CRs

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller_test.go
- pkg/controller/utils/jobs.go
- pkg/install/generate.go
Similar to what we do for install jobs, track a hash of the spec we
generate and store in an annotation. If this is missing or changed on
the current job, delete it and allow another to be created.
> Regenerate deprovision jobs when spec changes.

- cmd/manager/main.go
- cmd/operator/main.go
- config/rbac/manager_role.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/operator/assets/bindata.go
Primarily to prevent any problems during upgrades when both new and old
versions of the code may be running.
> Add leader election for both operator and controllers.

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
This is surfacing again in stage and historically one of the most common
failures.
> Add an installlog entry for the standard API timeout.

- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
The uninstall job uses the default service account. The deprovision controller does not need to create the install service account.
> controller: do not create service account for deprovision

- cmd/manager/main.go
- config/rbac/manager_role.yaml
- pkg/controller/add_velerobackup.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/test/clusterdeployment/clusterdeployment.go
- pkg/controller/utils/constants.go
- pkg/controller/utils/utils.go
- pkg/controller/velerobackup/clusterdeployment.go
- pkg/controller/velerobackup/clusterdeployment_test.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
- pkg/operator/assets/bindata.go
namespace
backup is taken immediately.
> Add Velero Backup When ClusterDeployment Changes

- pkg/operator/hive/hive.go
The nil check did not work if globalPullSecret was specified but empty,
which has turned up as a helpful thing to support for AppSRE templates
across environments.
Also check for an empty name and skip global pull secret if this is the
case.
> Support empty global pull secret instead of absent.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Requires an immediate requeue as we do not write anything to the cluster
deployment in this case.
> Fix long delays to install after generating global pull secret.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/imageset/generate.go
The log gathering PR merged earlier today missed the fact that image
resolution jobs use the new script, but an old hive image to process the
results of the script (if the ClusterImageSet predates the change). This
causes the CLI image to be resolved but never set on the
ClusterDeployment status. As a result the new code will not create an
install job until the CLI image is resolved and saved in status.
Temporary fix that will probably need to be cleaned up in this commit.
Uses the latest Hive image (i.e. what we're running the controllers
from, as set by the operator), falling back to the hive image in the
ClusterImageSet. This change is likely permanent considering the work
we're doing this week, only the fallback will likely be removed.
> Use latest hive image for processing image resolution job.

- pkg/install/generate.go
staticaly set it to 'hive' so we can document that any particular cluster was created through hive.
> set OPENSHIFT_INSTALL_INVOKER when launching install

- docs/troubleshooting.md
- docs/using-hive.md
- hack/logextractor.sh
If the install pod is no longer running, we need a way to get access to
the logs PVC. This script creates a dummy deployment we can use to copy
from, finds the pod name, waits for it to come online, copies the logs
out, and then deletes the deployment.
> Add script to extract cluster logs from PVC after failures.

- hack/app_sre_create_image_catalog.sh
- hack/generate-operator-bundle.py
OLM parses the version and uses github.com/blang/semver to validate it
as a semver.
We have found out that if the prerelease starts with
`0` it raises this error:
https://github.com/blang/semver/blob/1a9109f8c4a1d669a78442f567dfe8eedf982793/semver.go#L376
When this happens OLM refuses to deploy the CSV and no further updates
will happen.
After some testing, we decided to prepend the prerelease with the string
`sha` so this error is not raised.
```go
package main
import (
"fmt"
"os"
"github.com/blang/semver"
)
func main() {
v, err := semver.Parse(os.Args[1])
if err != nil {
panic(err)
}
fmt.Printf("%v\n", v)
}
```
```
$ ./testsemver 0.1.1036-0152295
panic: Numeric PreRelease version must not contain leading zeroes "0152295"
goroutine 1 [running]:
main.main() …
```
> semver complains if the prerelease first char is a 0

- contrib/pkg/certificate/create.go
The fullchain.pem is required because it includes intermediate certs needed by some clients (webconsole won't work without it)
> cert util: change copied cert from cert.pem to fullchain.pem

- config/operator/operator_role.yaml
- config/rbac/hive_admin_role.yaml
- pkg/operator/assets/bindata.go
Change the permissions for the operator role to use `sync.admission.hive.operator.io` instead of `rsync.admission.hive.operator.io`.
> Fix typo in operator role for syncset admission controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Fix a minor bug in clusterdeployment controller where `Info` was used instead of `Infof`.
> Use Infof instead of Info when formatting needed

- Makefile
- golangci.yml
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/controller/utils/secrets_test.go
- pkg/controller/velerobackup/helpers_test.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
- pkg/operator/hive/hive_controller.go
Also updated the installation method to make it work in CI systems as per https://github.com/golangci/golangci-lint#ci-installation
Commented some of the check in `golangci.yml` because either these need more effort to fix or not critical as compared to making `golangci-lint` default in `make test`. 
Once  `golangci-lint` is enabled it will help fixing incoming code for lint issues and we can gradually add more checks by removing the comments in  `golangci.yml`.
> Update makefile to run golangci lint bydefault

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/installer/pkg/asset/machines/aws/machinesets.go
- vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
- vendor/github.com/openshift/installer/pkg/types/aws/platform.go
- vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
- vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
- vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
- vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
- vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
- vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
- vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
- vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
- vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
- vendor/github.com/openshift/installer/pkg/types/installconfig.go
- vendor/github.com/openshift/installer/pkg/types/machinepools.go
- vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
we want the fix for the AWS deprovisioning in https://github.com/openshift/installer/pull/2284
update installer hash to ae2baf820f22b9bf1ed40932e7b702d790087574 (latest as of this writing), and `dep ensure -update`.
> vendor updated installer

- Dockerfile
- Dockerfile.dev
This was present in the Dockerfile.dev we were using, but not in the
final layer we based on for official builds. Unfortunately RHEL based
containers cannot run yum during builds due to lack of entitlements.
With this PR we lose the ability to build the main Dockerfile locally,
but we still have the much faster Dockerfile.dev and associated make
targets.
> Add ssh-agent to hive container for log gathering.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/provisionexpectations.go
- pkg/controller/utils/expectations.go
- pkg/controller/utils/expectations_test.go
Use expectations to ensure that clusterDeployment controller does not create multiple overlapping clusterprovisions.
There is currently a race condition where the controller will create a second clusterprovision if the first clusterprovision has not been added to the local cache by the time the clusterdeployment is reconciled again after creating the first clusterprovision. To prevent this, these changes use expectations to block the controller from creating the second clusterprovision unitl the controller sees that the first clusterprovision has been created.
When the clusterDeployment controller creates a clusterprovision, the controller will increase the number of creation expectations for the clusterdeployment. When the controller sees an add event for the clusterprovision, the …
> fix clusterprovision creation race

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
There are no clusterdeployments in stage or production with wildcards ingress domains.
Stage
```
$ oc get cd --all-namespaces -o json | jq .items[].spec.ingress[].domain
"apps.tparikh-quay-poc.a0a0.s1.devshift.org"
"apps.compliance-soc2-test-201906-take2.o4a5.s1.devshift.org"
"apps.rogbas-stg.o9a7.s1.devshift.org"
"apps.test-liza-aug28.b3i3.s1.devshift.org"
"apps.tzhou-018.a9u8.s1.devshift.org"
"apps.cindytest.d2z5.s1.devshift.org"
"apps.cindymulti.p6w3.s1.devshift.org"
"apps.aaaaa.j8c4.s1.devshift.org"
"apps.lseelye-srep-15.j8i1.s1.devshift.org"
"apps.chcollin.z3j0.s1.devshift.org"
"apps.nmalik1.i4n2.s1.devshift.org"
"apps.nmalik2.o5m1.s1.devshift.org"
"apps.nmalik3.t3e0.s1.devshift.org"
"apps.nmalik4.m5z8.s1.devshift.org"
"apps.nmalik419-1.w7n1.s1.devshift.org" …
```
> remove migration of wildcard ingress domains

- Makefile
- docs/developing.md
- hack/e2e-test.sh
- hack/local-e2e-test.sh
- Modifies the e2e script to allow overriding of environment variables. 
- Adds instructions on how to run the e2e test locally 
- Provides a sample script to run the e2e test locally
- Modifies the `go test` call in the Makefile for post-install and post-deploy tests so that results are not cached
> Local e2e example and instructions

- build/build-image/Dockerfile
Sending the PR to just change the Dockerfile as without this is merged the unit tests will never pass for the Makefile change in https://github.com/openshift/hive/pull/528
Fixes part of  https://jira.coreos.com/browse/CO-539
> Moving the installation of golangci-lint to Dockerfile

- docs/syncidentityprovider.md
docs: fix typo in `SelectorSyncIdentityProvider` definition
`SyncIdentityProvider` -> `SelectorSyncIdentityProvider`
> docs: fix typo in SelectorSyncIdentityProvider definition

- Makefile
Fixes https://jira.coreos.com/browse/CO-539
Can be merged after https://github.com/openshift/hive/pull/514 is merged.
> Removing downloading of golangci-lint in Makefile

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- hack/duplicate_cd.sh
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/clusterstate/clusterstate_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/install/generate.go
- pkg/install/generate_test.go
- pkg/installmanager/installmanager.go
- pkg/operator/assets/bindata.go
- test/e2e/common/clusterdeployment.go
* The installed field in clusterdeployment has been moved from the status to the spec. This allows the field to be retained when a clusterdeployment is restored. The installed field in status is deprecated but will be retained until all existing clusterdeployments are converted to use the installed field in spec.
* Adjust the validation for clusterprovision to accommodate adopting an existing cluster. When adopting, the expectation is that the podSpec field will be omitted. So when the podSpec field is empty, the validation ensures that the stage is "complete", that the attempt number if 0, and that there is not a previous infra ID or cluster ID.
* If the clusterdeployment is marked as installed but there is not a reference to the clusterprovision, then the controller will attempt to …
>  allow for restoring clusterdeployment and clusterprovision

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
- pkg/controller/clusterprovision/jobexpectations.go
Use expectations to ensure that clusterProvision controller does not create multiple overlapping install jobs.
There is currently a race condition where the controller will create a
second install job if the first install job has not been added
to the local cache by the time the clusterprovision is reconciled again
after creating the first install job. To prevent this, these changes
use expectations to block the controller from creating the second install job
unitl the controller sees that the first install job has been created.
When the clusterProvision controller creates an install job, the controller
will increase the number of creation expectations for the clusterprovision.
When the controller sees an add event for the job, the controller
will reduce the number of creation …
> fix install job creation race

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
If a clusterdeployment was installed prior to the changes that brought clusterprovisions to be, then the clusterdeployment will not have a clusterprovision associated with it. This is not a problem for normal operation. However, if the clusterdeployment is backed up and restored, then the clusterdeployment will lose its infra ID and kubeconfig secret reference, since those are stored in the status. Normally, after a restore, these items--along with others--are copied back into the clusterdeployment from the clusterprovision. So, in order for the clusterdeployment to work after being restored, the controller needs to create a dummy clusterprovision for the clusterdeployment with the pertinent data to be restored.
> create dummy clusterprovision for legacy clusterdeployment

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
The status.installed field is deprecated but should still be set when the cluster is installed to accommodate users that are still using the field.
> Set installed field in cd status when cluster installed

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
- vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
- vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
- vendor/github.com/openshift/installer/pkg/types/aws/platform.go
- vendor/github.com/openshift/installer/pkg/types/azure/platform.go
- vendor/github.com/openshift/installer/pkg/types/installconfig.go
- vendor/github.com/openshift/installer/pkg/types/machinepools.go
... and security groups.  Pulling in openshift/installer@55630a304 (openshift/installer#2214).
Generated with:
```console
$ sed -i 's/ae2baf820f22b9bf1ed40932e7b702d790087574/6fdffbb9c21d90ba97fc79dff3ccbeac22fb2a0e/' Gopkg.toml
$ dep ensure
```
The k8s.io/apimachinery/pkg/util/clock addition in Gopkg.lock is probably catching up with c759bfa2d2 (#518).
> vendor: Bump installer to destroy untagged subnets

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- pkg/apis/hive/v1alpha1/machinepools.go
- pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
- pkg/install/convertconfig.go
- pkg/operator/assets/bindata.go
The azure and gcp platform-specific machine pool information was not being converted into the install config.
> add missing conversion for non-aws machine pool platforms

- Makefile
It seems like an issue when go code running in container as non-root user, and the user does not exist in the container. Go by default disables the cache. It seems we will need to set GOCACHE explicitly when running a build as a nonexistent user (in our case it is root I think) [1] . Not sure what user ID we are expected to use in the CI system.
As per [2] $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.
The idea is to set it to a location where the go program (in this case golangci-lint) have write access.
[1] golang/go#26280
[2] https://specifications.freedesktop.org/basedir-spec/0.6/ar01s03.html
Signed-off-by: Lalatendu …
> Fixing golangci-lint cache permission issue

- config/crds/hive_v1alpha1_hiveconfig.yaml
- pkg/apis/hive/v1alpha1/hiveconfig_types.go
- pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
- pkg/constants/constants.go
- pkg/controller/velerobackup/helpers_test.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
taken per X seconds where X seconds defaults to 180 (3 minutes) and is
settable in hiveconfig. This allows for bundling of multiple
changes into a single backup.
as the backup timestamp in the checkpoint object.
hiveconfig rate limiting option.
> Add rate limiting to Velero backup controller

- config/manager/deployment.yaml
- contrib/pkg/createcluster/azure.go
- contrib/pkg/createcluster/gcp.go
- hack/e2e-test.sh
- pkg/operator/assets/bindata.go
- test/e2e/postinstall/machinesets/infra_test.go
When running e2e tests, create a cluster on azure and gcp as well as aws.
> e2e tests for azure and gcp

- hack/logextractor.sh
To be useful in the stage and production clusters, the logextractor script needs to be able to use clusterdeployments in non-default namespaces.
> accept a namespace to logextractor

- pkg/installmanager/installmanager.go
The Azure provisioning PR added logging of the install-config.yaml, which was supposed to have been removed before merging.
> remove logging of install-config.yaml

- pkg/awsclient/client.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/utils/sa.go
- pkg/controller/utils/utils.go
- pkg/installmanager/dnscleanup.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
These are leaking due on occasion due to a bug in the installer leading
to an install that cannot complete.
Add code to deprovision A records after we run the installer's
deprovision code. A records are the only ones we're seeing an issue
with, others can be added in future if necessary.
This code is not linked to the standard deprovision for a cluster
deployment deletion. We are confident this is safe during an install,
we're not sure if it is during a deprovision.
> Add support for install retry cleanup of A records in managed DNSZones.

- pkg/installmanager/installmanager.go
If the `openshift-install create cluster` command fails after the bootstrapping has completed, then run `openshift-install wait-for install-complete` once to wait an additional 30 minutes for the cluster to finsih installing. It is not uncommon for a cluster install to time out when the cluster is at 99+% complete. This will give those clusters a chance to finish before tearing them down and
starting over.
> installmanager: wait-for install-complete after failed install

- pkg/installmanager/installmanager.go
When the private ssh key file is empty, the installmanager is reporting that gathering the logs from the bootstrap node was successful even though the logs where not gathered. The `gatherBootstrapNodeLogs` function should be returning a non-nil error in this scenario.
> installmanager: gather logs reporting success with empty private ssh key file

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
The clusterDeployment controller emits a warning log when a dnszone for a clusterdeployment does not getting deleted when the clusterdeployment is deleted. However, this is expected behavior as the owned objects do not get deleted until the finalizers (other than the gc finalizer) are removed
from the owner.
In addition to no longer emitting the warning, the controller also requeues the clusterdeployment while waiting for the dnszone to be removed from storage. The controller will not get a watch event when the dnszone is removed from storage, so it neeeds to manually requeue.
> remove unnecessary warning about dnszone not getting deleted

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
There is a race condition where the clusterDeployment controller may reconcile a clusterdeployment for which a deprovisionrequest had recently been created prior to the local cache receiving that deprovisionrequest. In that case, the controller will attempt to create the deprovisionrequest again, and the creation request will be rejected by the api server. This is not indicative of an error: It should not result in an error log entry.
> do not emit error on failure creating duplicate deprovision request

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
The isBootstrapComplete check in InstallManager is returning true when there was an error validating that the bootstrap is complete. This is backwards: It should be returning false in this case.
> installmanager: fix check for whether bootstrap is complete

- hack/e2e-test.sh
When a clusterdeployment install fails during e2e tests, store the must-gather logs that where captured.
> store e2e must-gather logs

- pkg/controller/remoteingress/remoteingress_controller.go
If a serving certificate secret cannot be found, the remoteingress controller emits an error-level log entry. However, this is a common occurrence as the serving certificates are created after the
clusterdeployment is created. These changes remove this log entry. The controller will still emit a warning-level log entry with text of "will need to retry until able to find all certBundle secrets".
See https://jira.coreos.com/browse/CO-582.
> controller: reduce severity of log for missing cert bundle secret

- config/hiveadmission/clusterdeployment-webhook.yaml
- config/hiveadmission/clusterimageset-webhook.yaml
- config/hiveadmission/dnszones-webhook.yaml
- config/hiveadmission/selectorsyncset-webhook.yaml
- config/hiveadmission/syncset-webhook.yaml
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
- pkg/operator/assets/bindata.go
The names need to be different else kubectl get <resource name>
will get rejected by the admission controller
> Modifying admission validator names to make the plural names of CRDs to work

- Makefile
- config/operator/operator_role.yaml
- config/rbac/hive_admin_role_binding.yaml
- config/rbac/hive_reader_role_binding.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
We deploy two ClusterRoles and ClusterRoleBindings intended to be mapped
to hive-admin and hive-reader groups in Hive clusters. Because these
groups only exist as OpenShift types, it appears using the OpenShift
variant of ClusterRole and ClusterRoleBinding is the only way to map to
them.
These two roles however are not required or useful for development, and
as such can be safely skipped.
hive-operator now checks if we're running on OpenShift by attempting to
list DeploymentConfigs. If this fails, these assets will not be
deployed and a warning is logged.
This change does not get the operator fully working on vanilla Kube,
next up will be fixed for hiveadmission certs.
> Skip minor OpenShift specific assets when running on vanilla Kube.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/dnszone/zonereconciler.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
There are numerous places where a controller tries to get a resource by a known name and, if the resource does not exist, then create said resource. This operation has a race condition where the controller may attempt to reconcile the controlling resource again prior to the local cache being populated with the resource recently created by the controller. When this happens, the controller spits out an error log entry, even though this is not indicative of a problem.
These changes provide a helper GetOrCreate function that can be used by a controller to attempt to get a resource or create it if it is not found. All of the places where a controller does a get/create are changed so that the log entry emitted on the conflicted create is an info-level entry instead of an error-level entry.
See …
> controller: no error message on creation when already exists

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
A dummy provision should be created for all legacy clusterdeployments. However, a dummy provision is not being created for legacy clusterdeployments that have an installed timestamp. To remedy this, the check for the installed timestamp has been moved inside the if statement verifying that the clusterdeployment has a link to a clusterprovision.
Additionally, the clusterdeployment controller has been changed to stop reconciling a clusterdeployment that is installed, has no clusterprovision to adopt, and has no infra ID. This is likely to happen when a clusterdeployment is restored prior to its clusterprovision being restored. The clusterdeployment controller should under no circumstances create a new clusterprovision when the spec of the clusterdeployment indicates that the cluster is …
> controllers: dummy provision for clusterdeployment with installed timestamp

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
The comments for and variables used for returns from updatePullSecretInfo incorrectly mention that the status of the clusterdeployment is modified. The only things updated is the merged pull secret.
> controllers: improve variables and comments around updatePullSecretInfo

- pkg/controller/controlplanecerts/controlplanecerts_controller.go
The code in the controlplanecerts controller that sets the conditions does a deep copy of the clusterdeployment and a full reflect comparison. This is inefficient when there is already a function that can tell us whether the conditions changed.
> controllers: simplify conds changed check in controlplanecerts

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
All of the clusterdeployments in prod and stage that have status installed set also have spec installed set.
> controllers: remove code to set spec installed when legacy status installed set

- hack/create-clusters.sh
What do we think about this? This is mostly a copy of kubefed's script I just included the wait util at the bottom directly.
First time usage is basically:
```
CREATE_INSECURE_REGISTRY=true CONFIGURE_INSECURE_REGISTRY_HOST=TRUE CONFIGURE_INSECURE_REGISTRY_CLUSTER=true NUM_CLUSTERS=1 hack/create-clusters.sh
```
After this you've got a registry you can use locally:
```
IMG=172.17.0.1:5000/hive:latest make docker-dev-push
DEPLOY_IMAGE=172.17.0.1:5000/hive:latest make deploy
```
Now if you want to redeploy your hive cluster, you need to drop a few options so you don't try to re-deploy the local registry:
```
CONFIGURE_INSECURE_REGISTRY_CLUSTER=true NUM_CLUSTERS=1 hack/create-clusters.sh
```
Do we like this approach? I'd almost like a script to setup local registry and configure the host, …
> Add variant of kubefed's create-clusters.sh script.

- docs/architecture.md
It was already mentioned in hive readme.
Removing this section can make sure we do not
need to maintain such data in two places.
> docs: Delete support clouds section

- docs/using-hive.md
Neither the ClusterImageSet nor the ClusterDeployment allows for specifying a Hive image to use any longer. The Hive image used is always tied to the Hive image used for the Hive operator. These changes remove the references to configuring the Hive image from the using-hive docs.
> docs: remove reference to hive image for clusterdeployment

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Adding the logging to inform the user when we overwrite the value of label. Communicating this in log will make the user aware of the overwrite and help understand the behavior of Hive. 
> Adding a log when we change the platform label

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
There is dead code in the getSyncSetCommonSpec function that will never be reached.
> controllers: remove dead code in syncsetinstance controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/utils/clientwrapper.go
- pkg/controller/utils/utils.go
The clusterdeployment controller makes an early attempt to fixup the clusterversion field so that it passes validation. However, there are some other controllers that race with the clusterdeployment controller to write to the status of a clusterdeployment. When one of the other controllers wins the race, that update fails and emits an error log entry. To avoid the race, the logic for fixing up the clusterversion field has been moved to a wrapper around the status client. Consequently, every update of a clusterdeployment by every controller will fixup the clusterversion prior to making the update.
> controllers: ensure all status update of clusterdeployment have valid clusterversion

- config/operator/operator_role.yaml
Looks like there is an implicit watch needed for the controller runtime
client to be able to do the list we use to check if we're running on
OpenShift.
> Fix error in operator logs watching DeploymentConfigs.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
The clusterdeployment status needs special massaging for it to be acceptable to the validator. The controllers do this massaging automatically, but the imageset job does not. To ensure that status updates from the imageset job are accepted, these changes have the clusterdeployment controller update the status prior to creating the imageset job if the massaging has not yet been done.
> controllers: ensure valid cd status for imageset jobs

- docs/using-hive.md
The secret will be created from either AWS credential file or from
the env varsi, it was already handled in the create-cluster logic.
/cc @dgoodwin
> docs: added a note for the creation of secret for AWS

- hack/duplicate_cd.sh
The script was failing because of this
```
$ hack/duplicate_cd.sh lalatendum-test-1 20
Duplicating lalatendum-test-1 20 times
clusterdeployment.hive.openshift.io/lalatendum-test-1-dup-kgdmv created
The ClusterProvision "" is invalid: 
* spec.prevClusterID: Invalid value: "0c7714c9-4052-4b63-b207-ffc1a30dcf25": previous cluster ID must not be set for pre-installed cluster
* spec.prevInfraID: Invalid value: "lalatendum-test-1-xrdcd": previous infra ID must not be set for pre-installed cluster
```
The clusterprovision yaml
```yaml
{
"apiVersion": "hive.openshift.io/v1alpha1",
"kind": "ClusterProvision",
"metadata": {
"namespace": "default",
"ownerReferences": [
{
"apiVersion": "hive.openshift.io/v1alpha1",
"blockOwnerDeletion": true,
"controller": true,
"kind": "ClusterDeployment",
"name": …
```
> Previous cluster ID and infra ID must not be set for pre-installed cluster

- contrib/pkg/createcluster/gcp.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
to be able to build MachineSets to sync out to GCP clusters, we need to know the instance-type to put into the MachineSet.
make the instance-type field mandatory for GCP.
> add webhook validation for GCP to ensure the instance types are provided

- docs/using-hive.md
In the docs is not specified how to generate the secret for the ssh-publickey.
I'm not sure if this is automatically created when using hiveutil, if that's the case let me know and I'll add a note like the one used for AWS credentials.
Thanks,
> Added ssh-public-key secret creation

- docs/developing.md
/cc @dgoodwin 
@dgoodwin there are also some other problems for the current e2e section, it only mentions how to test via AWS, but not for other platforms, I think the document also needs to be updated to clarify how to run e2e for other platforms, like Azure, GCP etc. Comments?
> docs: updated e2e test steps.

- contrib/pkg/createcluster/create.go
- docs/developing.md
- hack/create-kind-cluster.sh
--adopt options allow you to adopt an already installed cluster into
Hive for purposes of using SyncSets, and Hive deprovision code.
This feature is likely most helpful for Hive developers who need are not
looking to explicitly test provisioning and would like to quickly get
valid clusters into hive without waiting for a full provision.
Adds documentation for using a kind cluster as your adopted
ClusterDeployment.
> Add hiveutil create-cluster support for adopting clusters.

- pkg/controller/dnsendpoint/nameserver/gcp.go
- pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
The NS records created for GCP do not carry a trailing dot as required. These changes add the trailing dot and remove the trailing dot in the results returned from a Get call.
> dnsendpoint: fix dotting for gcp

- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
- pkg/controller/dnsendpoint/nameserverscraper.go
- pkg/controller/dnsendpoint/nameserverscraper_test.go
When the controllers start, all existing dnsendpoint resources are queued for reconciliation. This happens concurrently with the initial scrape of the name servers. If a dnsendpoint is reconciled prior to the initial scrape, then the controller will determine that the NS records for the dnsendpoint do not exist and attempt to create them. This causes unnecessary and bursty traffic with the cloud provider. These changes force the controller to wait until the initial scrape is complete before reconciling any dnsendpoint resources.
Note that reconciling a deleted dnsendpoint is allowed. We want to allow the delete to go through even if there has not been a scrape so that deletes can still happen in the event of a problem with the scraper. 
https://jira.coreos.com/browse/CO-632
> dnsendpoint: do not reconcile until initial scrape of root domain

- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Need to figure out how we handle extra compute machine pools. Either reuse existing subnets, or handle creating of new subnets as needed.
For now simply only allow the single original machine pool.
> do not allow more than one compute machine pool on GCP

- .gitignore
As part of running Hive locally on kind, a directory is created with certs for hiveadmission. These certs should be ignored by git.
> add hiveadmission certs to git ignore

- config/rbac/hive_frontend_role_binding.yaml
- pkg/operator/assets/bindata.go
This PR is an attempt to solve https://jira.coreos.com/browse/APPSRE-961.
The plan is to add OCM developers to this group on the integration environment only.
Please let me know what you think.
> add hive-frontend Group to ClusterRoleBinding

- config/crds/hive_v1_clusterdeployment.yaml
- pkg/apis/hive/v1/baremetal/machinepool.go
- pkg/apis/hive/v1/baremetal/platform.go
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/imageset/generate.go
- pkg/operator/assets/bindata.go
Adds a new platform, currently just an empty struct, for BareMetal.
If we're provisioning bare metal we need to lookup a ref for a different
installer image. Using this image the openshift-install binary will be
in the exact same location with the exact same name as we normally use,
so we just need to swap out the image reference and everything else can
remain the same.
There is a pending need for installing mkisofs which is hopefully going
to be handled by the requirement being removed upstream soon.
> Add basic support for bare metal cluster provisioning.

- pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
- pkg/controller/syncmachineset/syncmachineset_controller_test.go
Fixes `secretReference.Kind` validation.
The `SelectorSyncSet` tests were unseparated so I fixed that and also needed to make a change in `syncmachineset_controller_test.go` for golint.
> Fix secretReference kind validation.

- build/build-image/Dockerfile
This is the first step to removing the mockgen installation from the makefile.
See https://github.com/openshift/hive/pull/736.
> build: include mockgen in build image

- Makefile
- config/crds/hive_v1alpha1_syncsetinstance.yaml
- pkg/apis/hive/v1alpha1/syncsetinstance_types.go
- pkg/controller/metrics/metrics.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Adds four new metrics, and SyncSetInstance.Status.Applied for a simpler
API to determine if everything in the SyncSet is applying properly.
Currently you must interpret at least 4 conditions, some of which are
errors and one of which is success. The new field is displayed as a
column in kubectl get output.
hive_selectorsyncset_clusters_total is a gauge labeled by name showing
the number of clusters that matched the label selector.
hive_selectorsyncset_clusters_unapplied_total is similar but for the
number that are not currently applying. Both are calculated by
examining SyncSetInstances.
hive_syncsets_total is a gauge that shows the total number of SyncSets,
and hive_syncsets_unapplied_total the number that are not currently
applying. This is also calculated by examining SyncSetInstances.
> Add SyncSet metrics.

- Makefile
- docs/developing.md
- hack/make
As with golintci-lint, it should be left up to the developer to manually install mockgen on their local development environment.
Also, provide a means for running builds locally using the build image.
* make build-build-image will build the build image
* ./hack/make script will run make in a container using the build image
> makefile: do not install mockgen automatically

- config/crds/hive_v1_hiveconfig.yaml
- config/manager/deployment.yaml
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
The .spec.logLevel field has been added to the HiveConfig CRD. This field will get passed to the hive-controllers deployment to set the log level used for the controllers.
https://jira.coreos.com/browse/CO-648
> add field to HiveConfig for setting log level

- pkg/awsclient/client.go
- pkg/gcpclient/client.go
Add user-agent to the requests made to AWS and GCP. The user-agent identifies Hive as the user making the requests.
https://jira.coreos.com/browse/CO-268
> add user-agent to aws and gcp requests

- config/crds/hive_v1_clusterdeployment.yaml
- config/crds/hive_v1_clusterdeprovision.yaml
- contrib/pkg/createcluster/create.go
- contrib/pkg/createcluster/gcp.go
- contrib/pkg/deprovision/gcp.go
- docs/using-hive.md
- hack/e2e-test.sh
- pkg/apis/hive/v1/clusterdeprovision_types.go
- pkg/apis/hive/v1/gcp/platform.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/dnsendpoint/nameserver/gcp.go
- pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
- pkg/gcpclient/client.go
- pkg/install/generate.go
- pkg/installmanager/installmanager.go
- pkg/operator/assets/bindata.go
The GCP Project ID can be obtained from the GCP credentials. So, rather than requiring that the user supply the Project ID again in the ClusterDeployment, Hive will get the Project ID from the credentials.
https://jira.coreos.com/browse/CO-636
> remove gcp project_id from clusterdeployment

- pkg/controller/dnsendpoint/nameserver/gcp.go
- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/gcpactuator.go
- pkg/gcpclient/client.go
When a cluster with managed DNS is deleted, the DNSZone is deleted concurrently with the deprovision of the cluster. However, the cloud zone cannot be deleted until the deprovision has removed all of the records from cloud zone. The changes in this commit reduce the level of the log entry emitted when the hosted-zone delete fails from Error to Info when the delete fails due to the zone not being empty.
https://jira.coreos.com/browse/CO-609
> dnszone: info level for log when deleting non-empty hosted zone

- Dockerfile
- Dockerfile.dev
- pkg/install/generate.go
- pkg/installmanager/installmanager.go
This was fine in Kube but in OpenShift both ssh to libvirt, and .cache
image copying broke due to the security constraints in OpenShift.
This change adds a home dir, changes it's permissions so it will work
with a random UID, and adds that random runtime UID to /etc/passwd so
SSH will work.
Also moved mounting of the ssh private key such that it will always
happen even if log gathering is disabled.
> Fix baremetal provisioning when run on OpenShift.

- docs/using-hive.md
The old command doesn't work. Replacing with a
functioning command.
Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>
> New command to retrieve kubeadmin's password

- config/crds/hive_v1_clusterdeployment.yaml
- pkg/apis/hive/v1/aws/platform.go
- pkg/apis/hive/v1/aws/zz_generated.deepcopy.go
- pkg/apis/hive/v1/azure/platform.go
- pkg/apis/hive/v1/azure/zz_generated.deepcopy.go
- pkg/apis/hive/v1/gcp/platform.go
- pkg/apis/hive/v1/gcp/zz_generated.deepcopy.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/operator/assets/bindata.go
The use of this field was lost in either the change to v1 or the change to the MachinePool CRD. It was never working entirely correctly. It does not seem too onerous to require the user to fill out each MachinePool fully rather than relying on ClusterDeployment-wide defaults. So, these changes remove the DefaultMachinePlatform fields from ClusterDeployment.
https://jira.coreos.com/browse/CO-580
> types: remove DefaultMachinePlatform

- pkg/hive/apis/hive/hiveconversion/conversion.go
- pkg/hive/apiserver/registry/checkpoint/proxy.go
- pkg/hive/apiserver/registry/clusterdeployment/proxy.go
- pkg/hive/apiserver/registry/clusterdeprovisionrequest/proxy.go
- pkg/hive/apiserver/registry/clusterimageset/proxy.go
- pkg/hive/apiserver/registry/clusterprovision/proxy.go
- pkg/hive/apiserver/registry/clusterstate/proxy.go
- pkg/hive/apiserver/registry/dnszone/proxy.go
- pkg/hive/apiserver/registry/hiveconfig/proxy.go
- pkg/hive/apiserver/registry/selectorsyncidentityprovider/proxy.go
- pkg/hive/apiserver/registry/selectorsyncset/proxy.go
- pkg/hive/apiserver/registry/syncidentityprovider/proxy.go
- pkg/hive/apiserver/registry/syncset/proxy.go
- pkg/hive/apiserver/registry/syncsetinstance/proxy.go
- pkg/hive/apiserver/registry/util/convert.go
Updating the existing object is necessary to preserve fields that v1alpha1 does not populate. For example, if a ClusterDeployment has a non-nil .spec.provisioning.manifestsConfigMapRef, then an update of the ClusterDeployment via the v1alpha1 API needs to leave that field untouched.
> apiserver: updating existing object when converting

- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
The "master" pool name is used by the control-plane, which cannot be configured via a MachinePool CR.
https://jira.coreos.com/browse/CO-198
> validation: reject machinepool with pool name of master

- contrib/pkg/createcluster/create.go
To keep syncsets created in the same namespace from colliding.
selectorsyncsets are applied to the same label so they don't need a prefix.
> Add cd name to sample syncsets.

- config/crds/hive_v1alpha1_hiveconfig.yaml
- pkg/apis/hive/v1alpha1/hiveconfig_types.go
- pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
If set to true, will scale down hive-controllers to 0 replicas. Only
useful in extreme situations where we need to ensure the controllers are
not manipulating data, as in our upcoming v1 migration.
> Add maintenanceMode support in HiveConfig.

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/clusterstate/clusterstate_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
- pkg/controller/utils/utils.go
- pkg/hive/apis/hive/clusterdeployment_types.go
- pkg/imageset/generate.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
controller ownership relationships can be reconciled
> Add labels used for ownership reconciliation

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
Surfaces as: "Error: Error creating NAT Gateway:
NatGatewayLimitExceeded: Performing this operation would exceed the limit
of 5 NAT gateways"
Scanning just for the AWS error string seems easiest and safe.
> Add an install log scan regex for AWS NAT gateway limit exceeded errors.

- config/crds/hive_v1_clusterdeployment.yaml
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
- pkg/operator/assets/bindata.go
Originally done as part of a PoC for bare metal provisioning with a
dedicated libvirt hypervisor host, we now wish to make this a more long
term hive feature.
As a first step in this, this change removes the ssh known host
annotation and makes it a formal part of the Hive API. The hosts are now
represented in in spec.Provisioning.SSHKnownHosts. This is generic and
not tied to bare metal provisioning as we're not sure the extent we may
need ssh in installs in the future. We already use ssh to gather logs on
failures and while this does not currently require known hosts entries,
it seems best to keep the door open.
> Formalize addition of ssh known hosts in install manager.

- pkg/controller/remoteingress/remoteingress_controller.go
s/remoteIngressConrollerSecretsNamespace/remoteIngressControllerSecretsNamespace/g
> controllers: remoteingress spelling error

- contrib/pkg/createcluster/create.go
Trying to
``` 'create-cluster -o yaml' | sed 'change from us-east-1 to us-east-2' | oc create -f - ```
and it applies the secrets and cluster deployment, but you get error messages for the syncset-related items.
```
unable to get type info from the object "*unstructured.Unstructured": Object 'Kind' is missing in 'object has no kind field '
```
Add type info for these objects.
> add type info for syncsets and selectorsyncsets

- pkg/controller/doc.go
This is a dummy PR to ensure that the pipelines to hive-stage and hive-int are disabled.
> controllers: add doc.go

- Dockerfile
This was done for bare metal install work. We'll need another solution,
the rpms cannot be installed from UBI, or from RHEL images if you are
not entitled.
This was working in CI because they replace the FROM, but would fail
locally, or if run in the appsre job.
> Remove install of libvirt deps temporarily.

- config/apiserver/deployment.yaml
- config/apiserver/hiveapi-cluster-role-binding.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hiveapi.go
Change the port that the apiserver is listening on to 10443 to match the target port set for the service.
Add a ClusterRoleBinding for the apiserver service account to system:auth-delegator.
Remove the code in hive-operator that was trying to set up for RBAC for the apiserver service account. This will always fail because the operator does not have the necessary permissions to pass to the apiserver. The RBAC needs to be set up for the apiserver in the same way that it is set up for the hiveadmission.
> apiserver: fix rbac and port used

- pkg/controller/remoteingress/remoteingress_controller.go
This was done to force the rollout of ingress config, which should no
longer be needed as of 4.2.0.
The code in question is now causing a problem for hive users who need to
adjust default router tolerations to land them on specific nodes, also
being done by syncsets, and now both syncsets are fighting for the
tolerations causing the pods to restart often, impacting running
services.
With this change, remoteingress will no longer work seamlessly on 4.1
OpenShift clusters, manual restarts may be required. We do not believe
this will impact many users as 4.2 and 4.3 are both available now.
> Stable: Remove now obsolete toleration edit in remoteingress controller.

- hack/app_sre_build_deploy.sh
- hack/app_sre_create_image_catalog.sh
Since we are using the `stable` branch to deploy fixes to stage and production, and since each deployment is ordered (number of commits from a past commit are used to count), we need the `stable` branch's count to be aligned with the `master` branch count.
To do this, we specify the commit we are cherry picking from `master`. That commit will be used for the count, and to guarantee that it takes precedence over the commit in `master`, we add 1.
This should fix the problem of staging images not created in https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/hive/job/openshift-hive-gh-build-stable/3.
IMPORTANT:
1. this change assumes that `stable` will never be merged into `master`.
2. this change assumes that every change to `stable` is cherry-picked from `master`.
3. the …
> sync stable order with master when using cherry-pick

- Gopkg.lock
- cmd/hive-apiserver/main.go
- cmd/hiveadmission/main.go
- pkg/certs/certs.go
- vendor/github.com/blang/semver/LICENSE
- vendor/github.com/blang/semver/json.go
- vendor/github.com/blang/semver/range.go
- vendor/github.com/blang/semver/semver.go
- vendor/github.com/blang/semver/sort.go
- vendor/github.com/blang/semver/sql.go
- vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
- vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
- vendor/k8s.io/component-base/metrics/counter.go
- vendor/k8s.io/component-base/metrics/gauge.go
- vendor/k8s.io/component-base/metrics/histogram.go
- vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
- vendor/k8s.io/component-base/metrics/metric.go
- vendor/k8s.io/component-base/metrics/opts.go
- vendor/k8s.io/component-base/metrics/processstarttime.go
- vendor/k8s.io/component-base/metrics/registry.go
- vendor/k8s.io/component-base/metrics/summary.go
- vendor/k8s.io/component-base/metrics/version_parser.go
- vendor/k8s.io/component-base/metrics/wrappers.go
The hiveadmission and hiveapi pods use certs that may change while the pods are running. When the certs change, the pods will no longer be able to do their work. The pods need to be restarted to pick up the new certs.
> restart pods with injected certs when the certs rotate 

- Dockerfile
- Dockerfile.dev
- build/hive/Dockerfile
- pkg/installmanager/installmanager.go
As of OpenShift 4.3, there is no need for the installmanager to manually manipulate the /etc/passwd file. The version of cri-o included in OpenShift 4.3 will automatically add the user to the /etc/passwd file.
Also, remove build/hive/Dockerfile which does not appear to be used anywhere.
https://issues.redhat.com/browse/CO-770
> installmanager: remove manual adding to /etc/passwd

- contrib/pkg/v1migration/deleteobjects.go
- contrib/pkg/v1migration/restoreownerrefs.go
- contrib/pkg/v1migration/saveownerrefs.go
- hack/v1migration/README.md
- hack/v1migration/delete.sh
- hack/v1migration/remove_hiveadmission.sh
- hack/v1migration/scaledown.sh
- hack/v1migration/scaleup.sh
- hack/v1migration/verify_scaledown.sh
* Fix differences seen in namespace when comparing cluster-scoped resources.
* Ignore not-found errors when trying to restore owner references on DNSEndpoints and install-log PVCs.
* Fix delete_jobs script function.
* Do not do a dry-run delete of jobs as that is not supported with oc 3.11.
* Make a separate step for removing the validating webhooks. The hiveadmission will not work once the Hive CSV is deleted. So the validating webhooks need to be deleted prior to run the delete.sh script.
* Make the scaling scripts more granular. Deleting the Hive CSV will delete the hive-operator deployment.
* Accept a missing dpeloyment as an acceptably scaled-down deployment.
> migration: changes to support hive-int

- Gopkg.lock
- config/crds/hive_v1_hiveconfig.yaml
- contrib/pkg/adm/managedns/enable.go
- contrib/pkg/createcluster/create.go
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/constants/constants.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/hive/manageddns.go
The hive operator would not relaunch the hive-controllers deployment when the only change to the HiveConfig was adding/removing an existing managed domain entry (leaving at least one managed domain).
Update the logic to create a new configmap with a new name (so that the controllers cannot see the old configmap contents on controller restart), and detect when changes are needed so that the hive-controllers deployment is re-deployed as necessary.
A notable change is that a HiveConfig with no managed domain entries will now have a configmap with an empty list of managed domains used in the hive-controllers deployment (the dns controllers already handle the case of an empty list of managed domains). Previously the hive-operator would simply not create the configmap at all.
> handle changing managed domains in hiveConfig

- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
The MCO does not support updating existing machines when platform details are changed in a machineset. Consequently, Hive should not support making such changes.
https://issues.redhat.com/browse/CO-798
> validation: reject changes to MachinePool platform fields

- config/crds/hive_v1_dnszone.yaml
- config/crds/hive_v1_hiveconfig.yaml
- pkg/apis/hive/v1/dnszone_types.go
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/awsclient/client.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnsendpoint/nameserver/aws.go
- pkg/controller/dnszone/awsactuator.go
- pkg/operator/assets/bindata.go
Use a custom endpoint for route53 when the region is a "cn-" region.
A region field has been added to .spec.managedDomains[].aws in HiveConfig. When the managed domain is handled by AWS China, the region field should be set to "cn-northwest-1" so that the route53 requests are sent to AWS China instead of regular AWS.
https://issues.redhat.com/browse/CO-769
> support aws china for managed dns

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/utils/cacrt.go
We discovered that in situations where the status URLs get set, but at a time when the additional CAs were not configured properly, the cluster goes into a state where it's admin kubeconfig will never be updated. Because it lacks the correct CAs, the cluster is permanently marked unreachable and hive cannot communicate with it.
This fix adjusts the admin kubeconfig reconciliation such that it always runs even if status URLs are already set. The postProcessAdminKubeconfig method was broken down as it mixed implicit updates with updates the caller was expected to do, and we require different assumptions regarding the status URLs. Methods renamed to be more clear as to what they're actually doing.
Added two tests which only check that we copied the kubeconfig data to the raw field, …
> Add additional CAs to admin kubeconfig even when status URLs set.

- contrib/pkg/v1migration/deleteobjects.go
- contrib/pkg/v1migration/discoverowned.go
- contrib/pkg/v1migration/recreateobjects.go
- contrib/pkg/v1migration/ref.go
- contrib/pkg/v1migration/restoreownerrefs.go
- contrib/pkg/v1migration/saveownerrefs.go
- contrib/pkg/v1migration/v1migration.go
- hack/v1migration/README.md
- hack/v1migration/delete.sh
- hack/v1migration/delete_hive_jobs.sh
- hack/v1migration/hivetypes.sh
- hack/v1migration/restore.sh
- hack/v1migration/save.sh
This PR covers the 3 areas that we discussed changing to improve the speed of migration.
1) When saving owner references, we should only look at resource types that are known to have owner references to Hive resources. The `hiveutil v1migration save-owner-refs` command now has a hard-coded list of resource types that will be searched for owner references. This list can be overriden by passing in a file containing the list of resource types. Additionally, there is a `hiveutil v1migration discover-owned` command that can be run to collect the resource types owned by Hive resources. This command can be run on the int, stage, and prod clusters to ascertain prior to migration day which resource types should be included.
2) We should make use of parallelization for long tasks. The processes of …
> migration: make speed improvements

- contrib/pkg/v1migration/saveownerrefs.go
On the hive-int cluster, there are certificaterequests with owner references to ClusterDeployments. We need to save and restore those owner references during migration.
> migration: add certificaterequests to owner refs to save

- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
The domain field must not include the protocol or port information from the clusterDeployment.status.APIURL field.
https://issues.redhat.com/browse/CO-799
> ensure hive puts a domain into the apiserver object

- pkg/constants/constants.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
One to sleep on install failures for a configurable duration, allowing
developers to rsh into the install pod and poke around.
One to disable log scrubbing of passwords as in some scenarios this can
redact important info.
cc @dhellmann
> Add install failure debugging annotations.

- config/crds/hive_v1_hiveconfig.yaml
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/constants/constants.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Adding for safety net in scenarios where you'd like to make sure no
deprovision jobs can accidentally trigger.
> Add HiveConfig.Spec.DeprovisionsDisabled.

- contrib/pkg/v1migration/deleteobjects.go
- hack/v1migration/delete.sh
* Use a Patch instead of an Update to remove finalizers. This eliminates the need to do the initial Get of the resource from the cluster.
* Eliminate the pre-conditions check on the Delete, in case it takes some extra time to validate the pre-conditions.
* Remove the deleting of jobs from the delete.sh script as that has been moved to the delete_hive_jobs.sh script, run separately.
> migration: remove initial fetch from delete process

- contrib/pkg/v1migration/saveownerrefs.go
- hack/v1migration/README.md
- hack/v1migration/delete_in_namespace.sh
- hack/v1migration/hive_owner_refs_in_namespace.sh
- hack/v1migration/hive_resources_in_namespace.sh
- hack/v1migration/hivetypes.sh
- hack/v1migration/save.sh
- hack/v1migration/validate.sh
- pkg/hive/apiserver/registry/clusterdeployment/proxy.go
Provide tooling for fixing resources that did not restore properly during a migration.
The process is the following.
1. Create restore data for only the namespace with problems so that fixes can be made in isolation to the resources in that namespace.
1. Clear out Hive resources from the problem namespace.
1. Restore the isolated data for that namespace with whatever changes needed to be made.
> migration: process for fixing bad restores mid-migration

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
This PR mimics the logic behind setting the platformLabel in the
Clusterdeployment CR. Previously present strings were also moved to
const's in the same package.
> Set region label on Clusterdeployment CR

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
- pkg/operator/assets/bindata.go
When the baremetal installer fails to connect via ssh to a remote libvirt 
host, the error message included embedded and *escaped* carriage returns 
and newlines. This change unescapes them so that any redaction of the error
message contents is minimized. The change is in cleanupLogOutput instead of
the function that reads the log because there are no tests for the reading
function and there are for the cleaning function.
Addresses #878
> update cleanupLogOutput to handle malformed data from libvirt and ssh

- docs/using-hive.md
- pkg/apis/hive/v1/machinepool_types.go
- pkg/controller/remotemachineset/gcpactuator.go
- pkg/controller/remotemachineset/gcpactuator_test.go
- pkg/controller/remotemachineset/leaseexceptions.go
Code did not properly handle the case when no lease characters are
available.
Added a short docs blurb, and a condition to be set when this situation
arises.
cc @lwan-wanglin
> Fix crash when using more than 35 GCP MachinePools.

- pkg/hive/apiserver/registry/util/convert.go
The aggregated API server was assuming that the serviceCIDR and machineCIDR were
required fields in the v1alpha1 ClusterDeployment. However, they can be omitted
to use defaults. When they were omitted in the v1alpha1 ClusterDeployment,
the aggregated API server was creating a bad element in the serviceNetwork
and machineNetwork fields in the installconfig.
These changes
(1) keep the bad element from being created and
(2) treat a bad element (with the text "<nil>") as non-existent to correct the
problem for existing clusters.
> apiserver: omit empty serviceNetwork and machineNetwork from installconfig

- hack/olm-registry/olm-artifacts-template.yaml
OLM artifacts: switch managed dns config to an array
To more easily support multiple managed domains and dns providers,
switch managed dns config to an array.
> OLM artifacts: switch managed dns config to an array

- hack/olm-registry/olm-artifacts-template.yaml
OLM artifacts: use empty array for MANAGED_DOMAINS default
The previous attempt to populate the array with dummy data
was invalid oc template syntax. Use an empty array.
> OLM artifacts: use empty array for MANAGED_DOMAINS default

- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/hive/hiveapi.go
Rather than list DeploymentConfig objects to detect whetther or not hive is running on openshift, query the available resources for the DeploymentConfig group/version to determine OpenShift vs non-OpenShift.
This should silence some of the log output from the operator that looks like:
`E0303 16:28:56.009055 1 reflector.go:329] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:204: expected type *v1beta1.CustomResourceDefinition, but watch event object had type *unstructured.Unstructured`
by having the controller-runtime not open a watch on the DeploymentConfigs.
> modify openshift detection logic

- config/crds/hive_v1_hiveconfig.yaml
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
When using hive in a disconnected bare metal environment the user
needs to be able to specify the location of the CLI image. Add a field
to the config spec and use it to set the existing environment variable
via the deployment for the controller.
> add config setting for cli image

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
Situations were encountered where the edge-trigger event for clearing
the metrics was being missed, resulting in alerts that would never clear
until the pod was restarted.
Delete was discovered and allows us to clear a metric, regardless if it
exists or not. This is far preferable to setting to 0 in very specific
scenarios and then stopping reporting.
> Improved clearing of provision/deprovision underway metrics.

- config/templates/cluster-deployment-customimageset.yaml
- config/templates/cluster-deployment.yaml
- contrib/pkg/createcluster/create.go
- pkg/clusterresource/aws.go
- pkg/clusterresource/azure.go
- pkg/clusterresource/builder.go
- pkg/clusterresource/builder_test.go
- pkg/clusterresource/gcp.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/install/generate.go
In preparation for cluster pools, we will want a way to generate a ClusterDeployment and all related objects in the core hive code. We however do not want this code reading from the filesystem or environment variables, or assuming the use of apply.
Move parts of hiveutil's create-cluster command which generates the runtime.Objects into a new package. A Generator object can be created and configured incrementally prior to generating all the required objects. Callers likely don't care what the objects are, they just configure the generator, get the list of objects, and then create or apply them.
In the midst of this there is a new option for re-using a credentials secret that already exists.
Still needs validation and unit tests.
> Refactor hiveutil create-cluster code into a package.

- config/crds/hive_v1_clusterdeployment.yaml
- docs/using-hive.md
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/operator/assets/bindata.go
This is regretably a breaking API change, but we believe this is driven
by the only user of the bare metal provisioning API.
> Fix case on bare metal platform to match openshift-install.

- cmd/hiveadmission/main.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/clusterimageset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/decoder_test.go
- pkg/apis/hive/v1/validating-webhooks/dnszone_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/dnszone_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
The basic GO JSON unmarshal is case-insensitive for field names. Kube is case-sensitive for field names. Since the admission webhooks were using JSON unmarshal, resources that used the incorrect case for fields were being incorrectly accepted. For example, if a user attempted to create a bare-metal ClusterDeployment but used .spec.platform.baremetal instead of .spec.platform.bareMetal, then the ClusterDeployment would be accepted by the validating webhook even though it should be rejected for not having a platform specified.
https://issues.redhat.com/browse/CO-846
> admission: use kube decoder instead of go json unmarshal

- config/crds/hive_v1_selectorsyncset.yaml
- config/crds/hive_v1_syncset.yaml
- pkg/apis/hive/v1/syncset_types.go
- pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/operator/assets/bindata.go
https://issues.redhat.com/browse/CO-830
SyncSet [resourceApplyMode](https://github.com/openshift/hive/blob/master/docs/syncset.md#syncset-object-definition) is case sensitive and we only support `""`, `"Upsert"` (default) and `"Sync"` modes so we should validate them in the API.
Ex.
```
➜  oc create -f ~/syncsets/sss.yaml
The SelectorSyncSet "mygroup" is invalid: spec.ResourceApplyMode: Unsupported value: "sync": supported values: "Upsert", "Sync"
```
> Validate SyncSet ResourceApplyMode

- test/e2e/postinstall/machinesets/infra_test.go
The apiVersion "extensions/v1beta1" got deprecated,so changed it from extensions/v1beta1 to apps/v1.
> Modified the Deployment version in e2e test postinstall file

- config/crds/hive_v1_syncsetinstance.yaml
- pkg/apis/hive/v1/syncsetinstance_types.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/hive/apis/hive/syncset_types.go
- pkg/hive/apis/hive/syncsetinstance_types.go
- pkg/operator/assets/bindata.go
This does the following:
- Fix a hard coded reference of `sync` to the proper `hivev1.SyncResourceApplyMode`
- Update some API comments that were incorrect
> Update ResourceApplyMode for remoteingress

- Makefile
- cmd/hive-apiserver/main.go
- cmd/hiveadmission/main.go
- cmd/manager/main.go
- cmd/operator/main.go
- contrib/cmd/hiveutil/main.go
- contrib/pkg/version/version.go
- pkg/version/version.go
Add LDFLAGS to inject version details for each build based on the git
tag and commit SHA.
Add a hiveutil version subcommand.
Log the version info at the startup of all other commands.
> add version information to log output

- docs/syncset.md
- pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
Update our syncset docs to reflect the name change from `secretReferences` to `secretMappings` introduced in https://github.com/openshift/hive/pull/783.
/cc @csrwng
> Update to secretMappings in syncset doc.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/clusterstate/clusterstate_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/remoteclient/mock/remoteclient_generated.go
- pkg/remoteclient/remoteclient.go
- pkg/remoteclient/remoteclient_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
- pkg/test/secret/secret.go
Use the unreachable controller work queue backoff as the means of backing off from attempting to connect to an unreachable remote cluster.
If an API URL override is set, continue attempting to connect to the cluster using the work queue backoff rather than falling back to the 2-hour check used when the cluster is reachable.
When a reachable ClusterDeployment is synced in the unreachable controller, requeue the ClusterDeployment so that it is re-synced for the 2-hour check.
In other controllers that connect to the remote cluster, set the unreachable condition if there is a failure to connect to the remote cluster. This will give a bit faster feedback when a cluster becomes unreachable, and will allow the controllers to fall back to the initial API URL more quickly. …
> controller: use requeue as backoff for unreachable controller

- Makefile
The code generation being done by the k8s.io/code-generator tools has become significantly slower with the change to go modules. Using the vendored dependencies makes it faster, although still slower than what it was before.
> use vendored dependencies during generate

- Dockerfile
- Makefile
The Dockerfile was using go build directly, which meant the version
information was not being injected in the way expected. Switching to
use make required adding a new "binaries" target that does not include
the "generate" dependency because the builder image does not include
mockgen. The old "build" target is left in place with a dependency on
generate and binaries to provide backwards compatibility.
> update dockerfile to use make to build binaries

- hack/olm-registry-deploy.sh
Fixes issue: https://github.com/openshift/hive/issues/911
> Fix CSV_FILE name substitution in hack/olm-registry-deploy.sh

- contrib/pkg/labelobjects/labelobjects_test.go
- pkg/apis/hive/v1/metaruntimeobject.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/ownership.go
- pkg/controller/utils/ownership_test.go
- pkg/controller/utils/utils.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
controller owner of the object is correctly set.
Add ownership reconciliation based on labels
> Add ownership reconciliation based on labels

- docs/developing.md
Currently, we support 0.5.1 version of kind. Our development doc does not mention
it. This PR updates the doc specifying the supported version of kind.
> Update docs to specify supported version of kind

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
This PR adds following install failure reasons to install-log-regexes
1) simulator throttling: "validate AWS credentials: checking install permissions:
error simulating policy: Throttling: Rate exceeded"
2) general throttling  :  "Throttling: Rate exceeded"
> Add throttling to install failure reasons

- contrib/pkg/labelobjects/labelobjects_test.go
- pkg/apis/hive/v1/metaruntimeobject.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/ownership.go
- pkg/controller/utils/ownership_test.go
- pkg/controller/utils/utils.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
> Fix bug in label ownership reconciliation

- contrib/pkg/deprovision/gcp.go
The `hiveutil deprovision gcp` command no longer takes a --gcp-project-id flag. But the help message still tells the user to add it.
> hiveutil: remove --gcp-project-id from deprovision help

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/resource/apply.go
- pkg/resource/patch.go
- pkg/resource/serializer.go
https://issues.redhat.com/browse/CO-793
Return `reconcile.Result{Requeue: true}` when an error is encountered applying a syncset instead of returning the error. This will backoff as if we had returned the error but will no longer result in a controller error for metrics. An `applyErr`can occur if we can't apply the resource/patch or if we can't read a local secret wrt `secretMappings`.
An `applyErr` is still logged as an error in several places. I can change this if we'd rather treat as debug logs.
> Stop treating syncset applyErrs as controller errors.

- Makefile
- cmd/operator/main.go
- hack/e2e-test.sh
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/hive/hiveapi.go
- pkg/operator/hive/operatorutils.go
- pkg/operator/util/apply.go
- test/e2e/common/utils.go
- test/e2e/uninstallhive/uninstallhive_test.go
If the HiveConfig named 'hive' (the only name we recognize) is deleted,
Hive components will be torn down.
This is accomplished by automatically adding owner references to most
resources the hive-operator creates, to the HiveConfig hive. Once
deleted we let kubernetes garbage collection take care of cleaning
everything up.
> Implement Hive uninstallation via deleting HiveConfig 'hive'.

- go.mod
- test/e2e/postinstall/syncsets/syncsets_suite_test.go
Add e2e test for syncsets. 
According to Cesar's detail and helpful review comments, add watch of object deletion, standard coding style, and fix issues Cesar found.
there exists needed ginkgo package in go.sum, so this PR doesn't change go.sum file.
> Add e2e test for syncsets

- config/templates/hive-csv-template.yaml
Hive is now shipped on operatorhub.io. Enhance the CSV with
data typically found in a shipped operator -- description,
links, etc.
extracted from #931 but also added our email address and changed the tile name per request from Brand.
/cc @dgoodwin
> enhance the CSV template for operatorhub.io deployment

- pkg/controller/metrics/metrics.go
When a selector sync set has failing instances, but all failure clear
and all instance has been applied, the metric was not being cleared.
This change will not clear unapplied metrics for any currently known
selector sync set if they do not have any failing instances.
NOTE: we still would have an issue if the selector sync set was entirely
deleted. This metric would not clear until the pod is restarted.
> Fix syncset unapplied metrics not clearing.

- cmd/hiveadmission/main.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
Trying an alternate approach for detecting changes to the serving cert
by monitoring the secret in the hive-operator, and on any change we
reconcile. Reconcile will then hash the secret data and store in an
annotation on the pod template in the hiveadmission deployment. Any
change to this value will result in a new rollout.
> Detect serving cert changes in operator instead of hiveadmission.

- hack/generate-operator-bundle-operatorhub.py
Add new generate-operator-bundle-operatorhub.py script. This script
is adapted from the existing hack/generate-operator-bundle.py, and
is capable of generating a bundle for both operatorhub and OSD. For
now we're only using it for operatorhub and keeping the OSD pipeline
unchanged. At a later date we'll adapt the OSD pipeline and rename
this script.
/cc @dgoodwin
> add new operator bundle generate script for operatorhub deploys

- pkg/constants/constants.go
- pkg/installmanager/installmanager.go
This PR provides an option to set additional 'wait-for install-complete'
executions after a timed out cluster initialization by using annotation on the
Cluster Deployments
> Add annotation based option to set additional waits to complete cluster provision

- Makefile
Add the docker-dev-build target to the makefile for building the dev image using docker (or a replacement such as podman).
> makefile: add docker-dev-build target

- config/crds/hive_v1_hiveconfig.yaml
- docs/using-hive.md
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/operator/assets/bindata.go
- v1alpha1apiserver/pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- v1alpha1apiserver/pkg/apis/hive/v1alpha1/hiveconfig_types.go
- v1alpha1apiserver/pkg/hive/apis/hive/clusterdeployment_types.go
- v1alpha1apiserver/pkg/hive/apis/hive/hiveconfig_types.go
- v1alpha1apiserver/vendor/github.com/openshift/hive/pkg/apis/hive/v1/clusterdeployment_types.go
- v1alpha1apiserver/vendor/github.com/openshift/hive/pkg/apis/hive/v1/hiveconfig_types.go
I believe the references to `managedDNS` in the docs are incorrect and they
should be changed to `manageDNS`.
> replace references to managedDNS with manageDNS

- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
Change the clusterversion controller so that when it writes the .status.clusterVersionStatus field, it replaces a nil availableUpdates field with an empty array. This is necessary to keep other controllers
that use a deep equal to determine whether the controller has made any changes to the ClusterDeployment from seeing the field as changed.
> controller: force .status.clusterVersionStatus.availableUpdates to empty array

- contrib/pkg/deprovision/gcp.go
- contrib/pkg/utils/gcp/gcp.go
- docs/hiveutil.md
Fix up the difference where when using hiveutil to create a cluster you would set GCP_SHARED_CREDENTIALS_FILE, but on deprovision you would set GOOGLE_CREDENTIALS.
Standardize around the installer's use of GOOGLE_CREDENTIALS. Update the docs to more clearly specify that we actually search for ~/.gcp/osServiceAccount.json, GOOGLE_CREDENTIALS and the --creds-file parameter. Also add a --creds-file parameter for deprovision to make it more similar to the create-cluster workflow.
> standardize on GCP creds flags/env vars

- config/crds/hive.openshift.io_hiveconfigs.yaml
- config/hiveadmission/clusterdeployment-webhook.yaml
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/utils/clusterdeployment.go
- pkg/controller/utils/clusterdeployment_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
- pkg/test/generic/generic.go
The admission webhook for CluterDeployments has been modified to inspect DELETE requests as well. The webhook will reject any DELETE request for a ClusterDeployment that has the "hive.openshift.io/protected-delete" annotation set to a true value. In order to delete such a ClusterDeployment, a user is required to delete the annotation prior to making the DELETE request.
The "deleteProtection" field has been added to the HiveConfig. When the field is set to "enabled", the clusterdeployment controller will add the "hive.openshift.io/protected-delete" annotation to the ClusterDeployment when transitioning the ClusterDeployment to installed.
https://issues.redhat.com/browse/CO-277
> protect against accidental deletes of installed clusters

- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
This reverts commit c7bd4f82be829456846e875909eac9ceda0685b5.
There are reports that it is still preventing deletes.
/cc @staebler
> Revert "validation: decode correct object on clusterdeployment delete"

- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/utils/dnszone.go
We are seeing stuck terminating namespaces in some of our environments,
it appears it is possible for the ClusterDeployment to be gone when
reconciling a deleted DNSZone, despite the owner reference with
blockOwnerDeletion.
Add metrics to track the force deletion of dnszones which was quietly
being handled despite possibly leaking resources.
> Disable DNSZone relocation temporarily.

- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/utils/dnszone.go
- pkg/controller/utils/dnszone_test.go
dnsendpoint controller used the same code recently disabled in dnszone
controller. It appears it is possible and common at least on 3.11 for
the ClusterDeployment to be deleted and gone, the namespace marked for
deletion, and but the DNSZone still hanging around, despite having an
owner ref with blockOwnerDeletion.
> Another attempt at clearing stuck DNSZones.

- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
Since the dnszone and dnsendpoint controllers have had their logic for handling relocated clusters neutered, then cluster relocation must be disabled when using managed DNS.
> disabled cluster relocation when using managed DNS

- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Blocked during admission, but as a secondary check we also make sure not
to reconcile such a SyncSet and log a warning.
This change is not relevant for SelectorSyncSets which are cluster
scoped.
> Block SyncSets with secret ref in another namespace.

- config/crds/hive.openshift.io_machinepools.yaml
- pkg/apis/hive/v1/aws/machinepool.go
- pkg/apis/hive/v1/machinepool_types.go
- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/awsactuator_test.go
- pkg/operator/assets/bindata.go
Currently, Hive can install the cluster in an already existent VPC. But when a
new MachinePool is created, Hive creates the MachineSets in the cluster without
specifying the subnet IDs, thus causing the Machine objects to get into failed
state. This PR adds an option to specify the subnet IDs to be used in the
MachinePool.
Fixes #886
> Add MachinePool support for bring your own VPC

- hack/e2e-test.sh
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
This PR ensures that the install pod gets deleted after successful cluster
provision. It also deletes failed cluster provisions that are more than 7 days
old.
cc: @staebler @gregsheremeta
> Delete successful install pods and old failed provisions

- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
Currently, adding machinepool to the cluster installed in existing vpc panics
when subnets are invalid. This is because kubernetes client used to update
machinepool object is not initialized. This PR fixes it.
jira: https://issues.redhat.com/browse/CO-992
> Fix panic while adding machinepool in existing vpc

- pkg/remoteclient/remoteclient.go
Currently, if remote cluster becomes unreachable, condition is not getting set
on the ClusterDeployment. This PR fixes it.
Jira: https://issues.redhat.com/browse/CO-932
> Fix connection refused error not setting unreachable condition

- config/crds/hive.openshift.io_selectorsyncsets.yaml
- config/crds/hive.openshift.io_syncsets.yaml
- go.mod
- go.sum
- pkg/apis/hive/v1/syncset_types.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/operator/assets/bindata.go
- pkg/resource/apply.go
- pkg/resource/info.go
- test/integration/resource/apply_test.go
- test/integration/resource/createonly_test.go
- test/integration/resource/createupdate_test.go
If a resource is too large to include in an annotation, we currently fail to apply it via syncsets. This PR adds an applyBehavior field that can be set to either Apply (default), CreateOrUpdate, or CreateOnly
https://issues.redhat.com/browse/CO-379
CreateOrUpdate allows large resources to be synced, and its behavior is almost like Apply. However, we lose some functionality by not having the original resource in an annotation.
Because the original configuration is not present in the object, we lose the ability to delete previously-created keys in structs. (Lists should be ok afaik)
An example:
My original syncset: { "foo": "1", "bar": "2", "baz": "3"} 
That gets created on the target cluster...
then I change my syncset to {"foo": "1", "bar": "2"}
After applying the new change, the resource …
> Handle applying resources too large to include in an annotation

- pkg/constants/constants.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/controller/utils/utils.go
- test/e2e/postinstall/syncsets/syncsets_suite_test.go
This affects only two areas, the remotemachineset controller, and
syncsetinstance.
SyncSet now decodes to unstructured data as we cannot decode to
runtime.Object if the type is not registered with our scheme, which is
not guaranteed with RawExtensions in SyncSets.
> Add hive.openshift.io/managed annotation to resources synced to cluster.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/utils/ownership.go
- pkg/controller/utils/ownership_test.go
- pkg/installmanager/installmanager.go
- pkg/test/dnszone/dnszone.go
- pkg/test/generic/generic.go
To ensure admin secrets are not lost when the cluster has transitioned to installed and cluster provision is deleted, we add cluster deployment as additional owner reference to the admin secrets
> Add cluster deployment as owner reference to admin secrets

- config/crds/hive.openshift.io_hiveconfigs.yaml
- go.sum
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Introduce spec.disabledControllers as a list of strings that - when provided - will be used to set the `--disabled-controllers` param when the Hive operator is creating/updating the Hive controllers Deployment.
Also, move the log-level param to also live under spec.containers[].args (instead of spec.containers[].command).
> allow disabling controllers via HiveConfig

- cmd/manager/main.go
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterrelocate/clientwrapper_test.go
- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/utils/clusterdeployment.go
- pkg/controller/utils/clusterdeployment_test.go
- pkg/controller/utils/dnszone.go
- pkg/controller/utils/dnszone_test.go
- pkg/remoteclient/kubeconfig.go
- pkg/remoteclient/remoteclient.go
- pkg/test/generic/generic.go
When a ClusterRelocate has a label selector that matches with a ClusterDeployment, the clusterrelocate controller will relocate the matching ClusterDeployment.
1. Set the hive.openshift.io/relocate annotation to outgoing on the ClusterDeployment and the DNSZone.
2. Copy secrets, configmaps, machinesets, syncsets, and syncidentityproviders.
3. Copy the DNSZone for the ClusterDeployment, with the relocate annotation set to incoming.
4. Copy the ClusterDeployment, with the relocate annotation set to incoming.
5. Set the relocate annotation on the DNSZone and ClusterDeployemnt to complete.
When a ClusterDeployment with a relocate annotation set to incoming is reconciled by the clusterRelocate controller, the relocate annotation is removed from the DNSZone and the ClusterDeployment. This …
> ClusterRelocate to move ClusterDeployments between Hive instances

- pkg/constants/constants.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- test/e2e/postinstall/syncsets/syncsets_suite_test.go
This will allow using a selector in admission webhooks interested in
protecting these resources.
> Change hive.openshift.io/managed from annotation to label.

- pkg/apis/hive/v1/dnszone_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/dnszone_controller_test.go
This PR sets the ClusterDeployment status with a more informative reason and
message when a DNS zone cannot be created due to AWS credentials lacking correct 
permissions.
> Set ClusterDeployment status when DNS Zone cannot be created due to missing permissions

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/resource/info.go
- test/integration/resource/info_test.go
Currently, we first gather info about all the resources before creating them.This way 
we cannot create a CRD and CR in the same syncet, because to fetch the info about
the CR we need to first create the CRD. This PR fixes it by fetching info and creating 
one resource at a time.
Jira: https://issues.redhat.com/browse/CO-540
> Fix unable to install CRD and CR in same syncset

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/test/clusterdeprovision/clusterdeprovision.go
Do not remove the deprovision finalizer from the ClusterDeployment until the DNSZone created for managed DNS has been removed from storage. This helps users that rely on the ClusterDeployment being removed from storage as a trigger for when it is safe to delete the namespace.
https://issues.redhat.com/browse/CO-966
> wait for dnszone to finish delete before clearing cd finalizer

- contrib/pkg/createcluster/create.go
- hack/e2e-test.sh
- pkg/clusterresource/aws.go
When running e2e tests on AWS, add the "expirationDate" user tag to the resources created so that the resources can be properly cleaned up by the pruner in case the deprovision fails.
https://issues.redhat.com/browse/CO-710
> test: add expiration tags to e2e aws resources

- pkg/constants/constants.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
Add the following labels to ClusterDeployments based on the desired version set in the cluster's ClusterVersion resource.
* hive.openshift.io/version-major
* hive.openshift.io/version-major-minor
* hive.openshift.io/version-major-minor-patch
https://issues.redhat.com/browse/CO-626
> add version labels to clusterdeployments

- cmd/manager/main.go
- docs/developing.md
Allows developers using make run to bypass the delay on startup waiting
for leader election timeouts.
> Add env var for devs to disable leader election.

- go.mod
github.com/blang/semver should have been added to go.mod as part of https://github.com/openshift/hive/pull/1041
> add semver to go.mod

- go.mod
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
- pkg/controller/remotemachineset/gcpactuator.go
- pkg/controller/remotemachineset/gcpactuator_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- test/e2e/postinstall/machinesets/infra_test.go
Starting with OpenShift 4.4.8, the restriction that machine pool names can only be a single character long has been lifted. As a consequence, the worker machinesets created by the installer now use the full name "worker", where Hive assumes that they will use the name "w".
These changes will use the full pool name when the cluster has a version of 4.5 or greater and continue to use name leases for clusters with older versions. However, for clusters that started as older versions and have been upgraded to 4.5 or greater, name leases will be used if there are existing leases or if Hive determines that the worker machinesets created by the installer--which used the "w" pool name--still exist.
https://issues.redhat.com/browse/CO-1030
> add support for full gcp machine pool names

- pkg/clusterresource/builder.go
With https://github.com/openshift/hive/pull/1024, code was added to the create-cluster command to skip the MachinePool for certain platforms. However, the code that added the MachinePool indiscriminately was not removed. The result was that 1 MachinePool was added for some platforms and 2 duplicates MachinePools were added for other platform.
> stop adding MachinePool twice

- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/azureactuator.go
- pkg/controller/dnszone/azureactuator_test.go
- pkg/controller/dnszone/dnszone_controller_test.go
- pkg/controller/dnszone/gcpactuator.go
- pkg/controller/dnszone/gcpactuator_test.go
- pkg/controller/utils/utils.go
- pkg/gcpclient/client.go
- pkg/gcpclient/mock/client_generated.go
When deleting a DNSZone, the cloud zone cannot be deleted while there are still recordsets in the zone. Since the zone was created for the DNSZone, Hive can safely clear the recordsets.
https://issues.redhat.com/browse/CO-1071
> delete recordsets in cloud zones when deleting DNSZone

- pkg/controller/remotemachineset/gcpactuator.go
- pkg/controller/remotemachineset/gcpactuator_test.go
OpenShift 4.4.7 uses full GCP machineset names
> use full GCP machineset names in OpenShift 4.4.7

- hack/generate-operator-bundle-operatorhub.py
adding the CRD ownership in f0f66ff missed creating `dest_path`
/cc @dgoodwin
> fix bug in hack/generate-operator-bundle-operatorhub.py

- contrib/pkg/createcluster/create.go
When there is a validation error running `hiveutil create-cluster`, the command exits without an output to the user. These changes log the validation error and exit with a non-zero exit code.
> hiveutil: print validation error for create-cluster

- config/crds/hive.openshift.io_clusterclaims.yaml
- pkg/apis/hive/v1/clusterclaim_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/installmanager/installmanager.go
- pkg/operator/hive/hiveapi.go
- pkg/resource/delete.go
- pkg/test/clusterclaim/clusterclaim.go
When a ClusterClaim is assigned a cluster, the clusterclaim controller will create a Role and RoleBinding in the namespace
of the ClusterDeployment. The Role will grant full permissions for Hive resources and GET permissions for the admin kubeconfig and password secrets. The RoleBinding will assign the role to the subjects specified in the ClusterClaim.
https://issues.redhat.com/browse/CO-1070
> create RBAC for accessing claimed cluster

- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
When a cluster is created for a ClusterPool, hibernate the cluster, as the cluster will not be used until it is assigned to a claim. As part of assigning a cluster to a claim, power the cluster back on.
https://issues.redhat.com/browse/CO-1073
> hibernate clusters created for ClusterPool

- pkg/imageset/generate.go
- pkg/install/generate.go
For containers that are using an OpenShift image, use the IfNotPresent pull policy instead of the Always pull policy. The OpenShift images should not be changing.
This changes makes it possible to use OpenShift release images for the CI registry when running on Kind.
> use image pull policy IfNotPresent for OpenShift images

- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
When one managed domain is a child of another managed domain, the the user can create a ClusterDeployment with a base domain that is the same as the child managed domain. This will cause problems when it comes time to change the recordsets in the base domain. These changes will have the validating webhook reject the ClusterDeployment.
For example, if there are managed domains of example.com and child.example.com, then the user should not be allowed to create a ClusterDeployment with a base domain of child.example.com.
> validation: base domain that is a managed domain

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
When the ClusterImageSet is found after not being found, the clusterdeployment controller is not setting the status of the
ClusterImageSetNotFound condition to false. These changes fix the controller so that it does set the condition to false
when the ClusterImageSet is found.
https://issues.redhat.com/browse/CO-906
> clear ClusterImageSetNotFound condition when imageset exists

- test/integration/resource/apply_test.go
- test/integration/resource/createonly_test.go
- test/integration/resource/createupdate_test.go
This fixes three dropped test errors in `test/integration/resource`.
> test/integration/resource: fix dropped test errors

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/clusterprovision_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
This PR adds a ClusterDeployment condition to detect install pod stuck in the pending phase. The install pod will be in the pending phase for sometime after creating a job. To handle this the pod status check is performed only if 60 seconds have elapsed after creating the job.
jira: https://issues.redhat.com/browse/CO-1037
> Detect install pod stuck in pending phase

- hack/olm-registry/olm-artifacts-template.yaml
This reverts commit 53c19cc2702ff7276517ec1047abec3937bb5cd8.
The template doesn't like the boolean -- it wants a string.
We don't feel like messing with this anymore because it is
temporary, so we will revert and instead ask SRE-P to change
it manually.
/cc @staebler @dgoodwin
> Revert "expose hiveAPIEnabled in hiveconfig template"

- test/e2e/destroycluster/destroy_test.go
This fixes two dropped `err` variables in `test/e2e/destroycluster`.
> test/e2e/destroycluster: fix dropped errors

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
In 8b7044b12ee5de1cc9c54c46a91b9b946aefa854 a new ClusterDeployment
condition type was added, but it was not added to the list of
AllClusterDeploymentConditions.
When encountered in the wild the metrics code would attempt to increment
an int in a map we expected to be initialized to 0 but was instead nil.
This change adds the condition type to the list of all, adds a warning
comment, and a safety check and log warning if this happens again in the
future.
> Fix metrics crash on new InstallLaunchError condition.

- pkg/controller/dnszone/awsactuator.go
- pkg/installmanager/dnscleanup.go
- pkg/installmanager/installmanager.go
Rather than two similar DNS cleanup functions, unify onto one implementation that can be used by all callers.
This means we now remove more than just A records on a failed install.
> pick one DNS cleanup codepath and use it everywhere

- contrib/pkg/createcluster/create.go
- pkg/clusterresource/builder.go
Hi Hive-Team,
we are using a private CA for our private cloud endpoints. Currently kubeutil does not support this feature. I added the functionality to the code. Please merge or let me know what is missing.
> additional-trust-bundle support added to hiveutil

- pkg/controller/hibernation/hibernation_controller.go
It has been observed that certain clusters take longer than 2 minutes
to update their node status to "NotReady" when resuming from
hibernation. This introduces a quickfix of doubling the time that
the controller waits until it starts checking node status. However,
a longer term more deterministic fix is likely needed.
> Hibernation: increase delay to check for node readiness

- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/dnszone_controller_test.go
- pkg/installmanager/dnscleanup.go
- pkg/installmanager/installmanager.go
Try number 2 to use one AWS DNS cleanup implementation.
Rework the DNSZone controller's AWS actuator code for DNS zone cleanup so that it is an exported function that can also be called during a failed cluster installation.
Rather than two similar DNS cleanup functions, unify onto one implementation that can be used by all callers.
This means we now remove more than just A records on a failed intall.
Also, populate DNSZone status immediately after fetching zoneID during Refresh() and Create()
Add test case to cover DNSZone being deleted without status.
Align with other actuators and just store entire AWS dnszone after receiving it.
> Aws dns cleanup refactor

- hack/olm-registry/olm-artifacts-template.yaml
This adds the velero backup to the olm artifact template and defaults to disabled.
> Add Velero to OLM Artifact Template

- hack/app_sre_create_image_catalog.sh
the :latest container appears broken. Probably a bad idea
to chase :latest in this build anyway.
> pipeline: lock registry container to 4.5

- go.mod
- go.sum
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/azureactuator.go
- pkg/controller/remotemachineset/constants.go
- pkg/controller/remotemachineset/gcpactuator.go
- pkg/controller/remotemachineset/openstackactuator.go
- pkg/controller/remotemachineset/ovirt.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/remotemachineset/secrets.go
- pkg/controller/remotemachineset/secrets_test.go
- pkg/controller/remotemachineset/vsphereactuator.go
- vendor/github.com/blang/semver/v4/LICENSE
- vendor/github.com/blang/semver/v4/go.mod
- vendor/github.com/blang/semver/v4/json.go
- vendor/github.com/blang/semver/v4/range.go
- vendor/github.com/blang/semver/v4/semver.go
- vendor/github.com/blang/semver/v4/sort.go
- vendor/github.com/blang/semver/v4/sql.go
- vendor/modules.txt
The worker-user-data secret name became worker-user-data-managed in 4.6.
Hive now supports alternate names for this secret.
This builds on https://github.com/openshift/hive/pull/1092. I was not able to push my changes into Michael's branch.
> CO-1114. Handle different worker-user-data secret name for 4.6

- pkg/controller/dnszone/dnszone_controller_test.go
- pkg/controller/dnszone/gcpactuator.go
- pkg/installmanager/dnscleanup.go
- pkg/installmanager/installmanager.go
- pkg/test/dnszone/dnszone.go
Have GCP dns cleanup be similar to how AWS is now handled (from https://github.com/openshift/hive/pull/1107 ).
Perform DNS cleanup after failed install for GCP.
Similar to how we try to clean up stray DNS records after a failed AWS installation (when the ClusterDeployment has ManagedDNS), do the same for GCP.
Share the existing zone cleanup code from the dnszone controller.
Actually make a GCP DNSZone for the DNSZone test for GCP
Consistently populate the DNSZone status after retriving the information from GCP API calls.
> GCP DNS cleanup after install failure

- pkg/azureclient/client.go
- pkg/controller/dnszone/actuator.go
- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/azureactuator.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/gcpactuator.go
- pkg/installmanager/dnscleanup.go
Cleanup DNS after install failure (like we do for AWS and GCP).
Update status as soon as we fetch the Azure DNS zone info (a no-op today).
Create new azureclient builder that takes the credentials as a byte array.
Additionally, retire the ModifyStatus function from the DNS actuator. Use it internally for all actuators.
> Azure dns cleanup after install failure and retire ModifyStatus from Actuator

- contrib/pkg/deprovision/awstagdeprovision.go
- pkg/constants/constants.go
- pkg/install/generate.go
Previously the uninstall pod would never restart if it launched with
since deleted or bad creds, and the user updated the credentials secret.
This change switches to mounting the creds as a secret instead of
passing through env vars. The hiveutil wrapper code sets them as env
vars and establishes a file watch on the directory where the secret is
mounted. On any change or watch error we exit to restart the pod.
It seems to usually take about 1 minute for the secret changes to
surface in the pod.
> Restart deprovision pods if credentials secret changes.

- contrib/pkg/deprovision/deprovision.go
- pkg/install/generate.go
The "--creds-dir" flag has been added to the `hiveutil deprovision` command. When this flag is used, the command will create a file observer watching for any changes to any files in that directory. If a change is detected, the command will be terminated.
The uninstall pods for platforms other than AWS have been updated to include the "--creds-dir" flag in the call to the deprovision
command.
https://issues.redhat.com/browse/CO-1135
> deprovision: kill deprovision when creds change

- config/crds/hive.openshift.io_clusterclaims.yaml
- pkg/apis/hive/v1/clusterclaim_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/utils/utils.go
- pkg/controller/utils/utils_test.go
- pkg/test/clusterclaim/clusterclaim.go
The `.spec.lifetime` field has been added to the ClusterClaim type. The lifetime field determines how long a ClusterClaim can live once it has been assigned a cluster. When the lifetime of a ClusterClaim elapses, the clusterclaim controller will delete the ClusterClaim.
https://issues.redhat.com/browse/CO-1133
> add lifetime field to clusterclaim

- contrib/pkg/deprovision/deprovision.go
When finding the files to watch for creds changes, skip symlinks. The `..data` symlink links to a directory, causing which causes
the program to error out attempting to read the directory. The other symlinks point to files that are already included in the watch.
> deprovision: skip symlinks in creds file watch

- cmd/manager/main.go
- cmd/operator/main.go
- docs/developing.md
This PR introduces following changes to hive's leader election
- Lease duration set to 360s 
- Renew deadline set to 270s
- Retry period set to 90s (default of 2s results in excessive etcd writes) 
- Enabled ReleaseOnCancel to immediately release the lock on normal shutdown 
eliminating the delay before another pod takes over
- Removed env var DISABLE_LEADER_ELECTION used to skip leader election
> Improve Hive leader election

- pkg/apis/hive/v1/machinepool_types.go
- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/awsactuator_test.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
Add the UnsupportedConfiguration condition to the MachinePool type. This condition is used to indicate that the cluster does not support the configuration specified in the MachinePool. If the MachinePool specifies spot instances but the cluster is running an OpenShift version earlier than 4.5, then the UnsupportedConfiguration condition will be set on the MachinePool and not MachineSets will be generated.
https://issues.redhat.com/browse/CO-1042
> machinepool condition for unsupported spot instances

- Dockerfile
- Dockerfile.dev
- build/build-image/Dockerfile
Change dockerfiles to use go 1.15.
We need to upgrade the dependency on github.com/openshift/library-go. That necessitates upgrading github.com/openshift/build-machinery-go. That, in turn, requires that we build with at least go 1.14.4.
> dockerfiles: use go 1.15

- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
Instead of watching for the ClusterSync to be added, have the clustersync controller requeue the ClusterDeployment after creating the ClusterSync resource. Then, the clustersync controller will error on getting the ClusterSync on subsequent reconciles until the ClusterSync resource makes it into the local cache.
> requeue cd after creating clustersync

- config/crds/hive.openshift.io_clusterdeployments.yaml
- contrib/pkg/createcluster/create.go
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/clusterresource/builder.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
When a cluster has been in a running state (installed with no hibernate
condition, or hibernate condition=false) for more than the
hibernate-after duration, the cluster will be automatically put to
sleep.
Intended for dev clusters where you do not want them to accidentally be
left running beyond the workday.
> Implement hibernate-after annotation to auto-powerdown.

- pkg/controller/clustersync/clustersync_controller.go
This will give us some info to dig a little deeper in terms of which
cluster was involved and what to search for in logs.
/assign @suhanime
> Log first success times when we report the metrics.

- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
Sort the patches for IdentityProviders by name so that the patch in the created SyncSet is consistent. This keeps the SyncSet from potentially thrashing due to a non-determinstic ordering.
https://issues.redhat.com/browse/CO-1144
> sort patches for identityproviders

- go.mod
- go.sum
- vendor/modules.txt
Ignore librarygo from installer that requires missing goautoneg dependencies
> Tag librarygo version

- Makefile
- config/crds/hive.openshift.io_checkpoints.yaml
- config/crds/hive.openshift.io_clusterclaims.yaml
- config/crds/hive.openshift.io_clusterdeployments.yaml
- config/crds/hive.openshift.io_clusterdeprovisions.yaml
- config/crds/hive.openshift.io_clusterimagesets.yaml
- config/crds/hive.openshift.io_clusterpools.yaml
- config/crds/hive.openshift.io_clusterprovisions.yaml
- config/crds/hive.openshift.io_clusterrelocates.yaml
- config/crds/hive.openshift.io_clusterstates.yaml
- config/crds/hive.openshift.io_dnszones.yaml
- config/crds/hive.openshift.io_hiveconfigs.yaml
- config/crds/hive.openshift.io_machinepoolnameleases.yaml
- config/crds/hive.openshift.io_machinepools.yaml
- config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
- config/crds/hive.openshift.io_selectorsyncsets.yaml
- config/crds/hive.openshift.io_syncidentityproviders.yaml
- config/crds/hive.openshift.io_syncsets.yaml
- config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
- config/crds/hiveinternal.openshift.io_clustersyncs.yaml
- pkg/gcpclient/mock/client_generated.go
Force build-machinery-go to grab an earlier version of controller-gen. The newer version adds annotations on pod specs that will cause the CRDs to fail validation. The fix for that requires the CRDs to use v1, but we still need to support users that are running kube versions that only have v1beta1.
https://issues.redhat.com/browse/CO-1193
/cc @abutcher
> makefile: use earlier version of controller-gen

- config/crds/hive.openshift.io_selectorsyncsets.yaml
- config/crds/hive.openshift.io_syncsets.yaml
- pkg/apis/hive/v1/syncset_types.go
Add a status sub-resource to the SyncSet and SelectorSyncSet types. With older versions of kubernetes (1.11 as an example), the CRD strategy will not update the generation of the resource if the CRD does not have a status sub-resource.
See https://github.com/kubernetes/kubernetes/blob/v1.11.0/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/strategy.go#L90
https://issues.redhat.com/browse/CO-1191
/cc @dgoodwin
> types: add status sub-resource to syncsets

- config/crds/hive.openshift.io_clusterdeployments.yaml
- hack/e2e-test.sh
- pkg/apis/hive/v1/clusterdeployment_types.go
Drop ClusterName, it's virtually always identical to the
ClusterDeployment.Name.
Drop BaseDomain, doesn't seem useful.
Add Platform, Region, OpenShift version, and the observed power state
from the Hibernating condition.
> Refine ClusterDeployment printcolumns.

- config/crds/hiveinternal.openshift.io_clustersyncs.yaml
- pkg/apis/hiveinternal/v1alpha1/clustersync_types.go
- pkg/apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
`clusterSync.Status.FirstSyncSetsSuccessTime` represents the first time that all syncsets were successfully applied for a `ClusterSync`.
Debugging from an info log which has been removed:
```
time="2020-09-23T19:35:30.404Z" level=info msg="allSyncSetsAppliedDuration: 455.403955562" ClusterDeployment=default/abutcher-fake19 controller=clustersync
time="2020-09-23T19:37:11.989Z" level=info msg="allSyncSetsAppliedDuration: 72.989812565" ClusterDeployment=default/abutcher-fake20 controller=clustersync
time="2020-09-23T19:38:05.293Z" level=info msg="allSyncSetsAppliedDuration: 15.293506293" ClusterDeployment=default/abutcher-fake21 controller=clustersync
time="2020-09-23T19:38:13.863Z" level=info msg="allSyncSetsAppliedDuration: 14.863788385" ClusterDeployment=default/abutcher-fake22 …
```
> Set clusterSync.Status.FirstSyncSetsSuccessTime and add metric

- config/crds/hive.openshift.io_clusterdeployments.yaml
- config/crds/hive.openshift.io_clusterdeprovisions.yaml
- config/crds/hive.openshift.io_clusterpools.yaml
- contrib/pkg/deprovision/azure.go
- pkg/apis/hive/v1/azure/platform.go
- pkg/apis/hive/v1/clusterdeprovision_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/hibernation/azure_actuator.go
- pkg/controller/hibernation/azure_actuator_test.go
- pkg/install/generate.go
New versions of the installer supports installing an Azure cluster into a pre-existing resource group.
The name of the resource group needs to be used when deprovisioning a cluster that was installed this way.
> suport clusters installed into manually created Azure resource groups

- cmd/manager/main.go
- cmd/operator/main.go
- config/controllers/deployment.yaml
- config/operator/operator_deployment.yaml
- pkg/operator/assets/bindata.go
With the current Deployment strategy of rolling update, a new pod is brought up
before the old is terminated. The new pod leader election has already determined
someone else is leader before the old releases it's lock, and will wait the full
renew interval of 270 seconds before checking again.
To fix we switch to the recreate strategy which will delete the old pod first,
then create the new. This seems the desired strategy for leader election based
operators.
> Fix stalled leader election after Deployment updates

- cmd/manager/main.go
Allow skiping leader election to add some flexibility when developing on hive where we can simultaneously have hive running in a cluster (potentially with some controllers disabled), and running hive locally.
> allow skipping leader election

- hack/app_sre_create_image_catalog.sh
dockerhub is adding rate limiting. Change our build to use
yq from quay.
Long term, it would be better to change the build to use
the app-interface graphql endpoint, but this will at least
make sure the builds don't stop working.
/cc @suhanime
> change osd pipeline build to use quay

- config/crds/hive.openshift.io_clusterdeployments.yaml
- config/crds/hive.openshift.io_clusterdeprovisions.yaml
- config/crds/hive.openshift.io_clusterpools.yaml
- contrib/pkg/deprovision/azure.go
- pkg/apis/hive/v1/azure/platform.go
- pkg/apis/hive/v1/clusterdeprovision_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/hibernation/azure_actuator.go
- pkg/controller/hibernation/azure_actuator_test.go
- pkg/install/generate.go
This reverts commit 34d28c1d6e001687fae2d0fc3ac722fe173f0c8c, reversing
changes made to 54442c3959748609d63aeacdba010b86a97e7a5e.
The bring-your-own-resource-group introduces a behavior when we hit an error during installation that causes the pre-made resource group to be deleted (that's how the uninstall process works). So any future installation attempt will fail b/c that resource group no longer exists.
This behavior doesn't map to the kind of retry loops that are implemented in hive, so we will not be supporting this BYO-resource-group.
> Revert "Merge pull request #1154 from joelddiaz/azure-resource-groups"

- pkg/constants/constants.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/metrics/metrics.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/utils/clientwrapper.go
- pkg/controller/utils/utils.go
- pkg/controller/velerobackup/velerobackup_controller.go
Use custom buckets for the kube client request histogram, previously capping at 10, we might be going well beyond that in some cases.
Add a reconcileID random string field to the logger in the cluster sync controller. Searching for "reconcile complete" will help us identify slow reconciles, and we can then walk back easily to search just for the log entries for that loop. Went with a random string 8 chars long instead of a full uuid just for brevity and log space, as a true globally unique ID is not really required here.
Add utility for controllers to log their elapsed time and report the metric. Will now log consistent elapsedMillis instead of a duration with varying units. We probably can't do greater than queries in kibana because of limitations in how openshift uses it, but it's still …
> Multiple changes to improve insight into clustersync performance.

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/provision_underway_collector.go
For a stuck provision, add the install failure details to the provision underway metric.
Relevant cluster deployment conditions are InstallFailing, ProvisionFailed and InstallLaunchError.
InstallFailing is not used anywhere currently and looks to be replaced by ProvisionFailed, hence it has been dropped.
> Add install failure details to provisioning underway metric

- config/crds/hive.openshift.io_clusterdeployments.yaml
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
This PR adds an option to limit the number of install restarts by setting a
value in the ClusterDeployment field `limitInstallRestarts`. Once this limit has
reached, `ProvisionStopped` error condition will be set in the status.
> Add option to limit install attempts

- docs/syncset.md
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
Remove `ResourcesToDelete` in `SyncStatus` when `ResourceApplyMode` is `"Upsert"`.
/assign @staebler 
/cc @akhil-rane 
Create `SyncSet` containing two configmap resources with `resourceApplyMode: Sync`:
```yaml
---
apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
name: sample-configmap
spec:
resourceApplyMode: Sync
clusterDeploymentRefs:
- name: abutcher
resources:
- apiVersion: v1
kind: ConfigMap
namespace: default
metadata:
name: sample-configmap-one
namespace: default
data:
foo: bar
- apiVersion: v1
kind: ConfigMap
namespace: default
metadata:
name: sample-configmap-two
namespace: default
data:
foo: bar
```
Check that `resourcesToDelete` contains both configmap resources:
```
$ oc get clustersync abutcher -o jsonpath='{range …
```
> CO-1188: Changing resourceApplyMode on SSS doesn't update ClusterSync.

- docs/developing.md
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/resource/patch.go
To allow other callers to manage parts of the APIServer configuration
in-cluster, switch to patching in the certs we need instead of fully
managing the resource.
Refactors tests a bit to not rely on validation functions and instead
test most things consistently across every set of test inputs.
> Patch APIServer config for certs instead of assuming full control.

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/destroy/azure/azure.go
- vendor/modules.txt
This commit will point the installer to the ocm-2.1 branch of
openshift-hive/installer, which is a fork of installer repo.
It will also bring in the fix of Azure deprovision
[bug](https://bugzilla.redhat.com/show_bug.cgi?id=1888378)
> Point installer to forked branch

- contrib/pkg/adm/managedns/enable.go
- contrib/pkg/testresource/command.go
- contrib/pkg/utils/generic.go
- pkg/constants/constants.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/utils/clientwrapper.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/resource/apply.go
- pkg/resource/helper.go
- test/integration/resource/apply_test.go
- test/integration/resource/createonly_test.go
- test/integration/resource/createupdate_test.go
- test/integration/resource/info_test.go
- test/integration/resource/patch_test.go
Adds a new developer annotation that can be applied to HiveConfig, hive.openshift.io/fake-applies: true, which will configure hive to fake out all Apply operations (SyncSets) to remote clusters. This is for simulated scale testing and allows us to use one spoke cluster and adopt it thousands of times. 
Commit still included for Greg's original work in this area in case we ever want to reference or use it, his solution uses a nodejs server which we tell to wait a specified ms before returning. In my testing a Sleep performs fairly similar, a little faster but I believe this is because we are double simulating requests in the nodejs approach, if we lookup real world data for the sleep array, then do an http request telling it to wait this time, it will be slower than the data we looked up. …
> Major improvement for syncset apply performance and simulated scale testing.

- hack/e2e-test.sh
Hive CI config was recently changed to use "multi-steps" workflow for
IPI installs of e2e tests.
This commit changes the e2e hack scripts to adapt to the environment
variables made available from the CI change.
> Fix e2e to adapt to multi-steps

- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
Recent change was not tested with new clusters as all eyes were on
making sure we rolled out for existing clusters smoothly.
JSON patches will not apply if the json sections referenced do not yet
exist.
This change adds two new directions to the json patch to ensure that the
two parent sections for what we need to patch exist. Because these are
all within the same json patch, they do not modify the resource. (which
they would if we applied each individually)
Because we need to ensure the .spec.serviceCerts node exists (by inserting
an empty node followed by then adding the list of certs), we still
effictively own everything underneath .spec.serviceCerts and will stomp
any non-hive changes when reconciling the control plane certs.
> Fix control plane cert patching for new clusters.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
This PR ensures that DNS is configured before hive halts installation 
when install attempts limit is set in the ClusterDeployment
jira: https://issues.redhat.com/browse/CO-1251
> Configure DNS before stopping install when attempts limit is set

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
Will now set a provision failed condition reason for bad project IDs and
non-existent instance types on GCP. Both should flow out through the
alert as well.
/cc @twiest
> Add two new GCP specific install failure search strings.

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
- pkg/test/clustersync/clustersync.go
*  Set a `ClusterSync.Status.FirstSuccessTime` of `time.Now()` when there are no `SyncStatuses` found for `ClusterSync`. This means there are no `SyncSets` to apply.
* Determine if `SyncSets` have been applied in hibernation controller
* If no `ClusterSync.Status.FirstSuccessTime` has been set for 10 minutes since `ClusterDeployment.Status.InstalledTimestamp`, hibernate anyway.
* If 10 minutes have not passed since install and `ClusterSync.Status.FirstSuccessTime` is unset, requeue `ClusterDeployment` for time remaining to meet 10 minutes since cluster was installed.
> CO-1107: Wait to Hibernate ClusterPool Clusters until SyncSets Applied

- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
This PR ensures that editing 'labels' and 'taints' on MachinePools gets
reflected in the underlying MachineSet created. Currently, both 'labels' and
'taints' fields are validated as immutable fields by hive admission webhook
and hence cannot be updated. Changing it to treat them as mutable.
jira: https://issues.redhat.com/browse/CO-1265
> Add support for editing Labels and Taints on MachinePools

- go.mod
- pkg/controller/remotemachineset/openstackactuator.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- vendor/modules.txt
> Bug 1880443: fix Openstack machinesets

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/metrics/provision_underway_collector.go
- pkg/operator/assets/bindata.go
The escape chars in the install log regex configmap led to it being unparseable, so all attempts to parse install logs are presently failing in stage and prod.
Also added the cluster platform and imageset to the metric labels to help us identify when it's a failing 4.7 nightly on gcp, which is where all our failures seem to be right now.
> Fix regexes

- pkg/constants/constants.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
This PR adds support to group non-selector syncsets using 'hive.openshift.io/syncset-metrics-group' 
annotation and report first applied metrics for each group.
jira: https://issues.redhat.com/browse/CO-1217
> Support opt-in Non-Selector SyncSet first applied metrics

- config/prometheus/prometheus-configmap.yaml
- config/prometheus/prometheus-deployment-with-pvc.yaml
- config/prometheus/prometheus-deployment.yaml
This is in preparation for the hive-clustersync pods that we expect to
soon be running, we no longer will have one pod to scrape by going to a
service, rather we'll want to scrape all pods by endpoints behind the
service.
Breaks out hive-controllers (name matches app-sre configuration,
although it doesn't matter as this is just dev prometheus setup for
scale testing), and adds hive-clustersync job. Both are capable of
scraping multiple pods, though this is not strictly relevant for
hive-controllers, it should work fine.
> Add dev prometheus config for scraping multiple pods.

- config/crds/hive.openshift.io_clusterclaims.yaml
- pkg/apis/hive/v1/clusterclaim_types.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/controller/utils/conditions.go
Previously claim.spec.namespace is set as soon as a cluster is assigned to the claim, but the user then needs to wait for the cluster to wake from hibernation and be fully running before it can be used.
This change adds a new ClusterClaim condition, ClusterRunning, which will be True when the cluster is ready to be used, and can be waited for with `oc wait --for=condition=ClusterRunning --timeout=600s ClusterClaim myclaim`.
/cc @suhanime
> Improve ClusterClaim Wait Experience

- config/controllers/hive_controllers_role.yaml
- config/rbac/hive_clusterpool_admin.yaml
- docs/clusterpools.md
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
xref: https://issues.redhat.com/browse/CO-1282
Any role bindings in the namespace of the clusterpool that refer the ClusterRole `hive-cluster-pool-admin`
will be used to provide the subjects the same permission in the namespaces created for various
clusterdeployments for the clusterpool.
The controller performs these additional actions for each reconcile,
- lists all the rolebindings in clusterpool's namespace that refer the ClusterRole `hive-cluster-pool-admin`
to collect all the subjects.
This makes sure that no work needs to be done when there are such rolebindings. And since k8s ensures that a rolebinding
cannot be created when the ref doesn't exist, this will ensure that only when the ClusterRole exists would the controller
run the next steps.
- lists all the namespaces attached to …
> clusterpool: ensure clusterdeployments namespace has same rbac as cluster-pool-admin

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/metrics/provision_underway_collector.go
- pkg/controller/utils/credentials.go
Fix the immediate problem where passing bad credentials for a vSphere installation means that deleting the ClusterDeployment doesn't get deleted (b/c the deprovision fails (b/c of the bad creds)).
Test the creds, and set a condition so that we can avoid ever even creating a ClusterProvision when we detect bad credentials. This means deprovision works b/c the provision was never attempted. Right now we only check vSphere credentials, but more platforms can (and should) be added.
Add test cases to validate this.
> vsphere creds checking

- config/crds/hive.openshift.io_clusterpools.yaml
- pkg/apis/hive/v1/clusterpool_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/controller/utils/conditions.go
- pkg/test/clusterpool/clusterpool.go
xref: https://issues.redhat.com/browse/CO-1278
Today the cluster pool keeps creating clusters to match `.spec.size` as ready clusters
are claimed by users. This is usually not possible as the secret used by the cluster pool usually
maps to an account in cloud that has limits/quotas and therefore there is need to allow admin
to set a limit on the maximum number of clusters created by a pool (already claimed + unclaimed).
The new field `.spec.maxSize` allows the admin to set this limit on maximum number of clusters
that are created for a pool. This includes the already claimed clusters, clusters ready to be claimed and
clusters that being provisioned, and does not include clusters are being deleted.
NOTE: when unset, this implies Inf capacity.
Similar to quotas in accounts, most cloud …
> clusterpool: allow setting max size and max concurrent actions

- config/crds/hive.openshift.io_hiveconfigs.yaml
- docs/troubleshooting.md
- hack/logextractor.sh
- pkg/apis/hive/v1/hiveconfig_types.go
- pkg/awsclient/client.go
- pkg/awsclient/mock/client_generated.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
- pkg/install/generate_test.go
- pkg/installmanager/helper_test.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
- pkg/installmanager/loguploaderactuator.go
- pkg/installmanager/s3loguploaderactuator.go
- pkg/installmanager/s3loguploaderactuator_test.go
- pkg/operator/hive/hive.go
> Store install logs in s3 compatible storage

- pkg/apis/hive/v1/clusterdeprovision_types.go
Since there was not omitempty on the new field added in
https://github.com/openshift/hive/pull/1196/files#diff-e993baf98b3c3bef0bc8ca5fe256449adb63079a3267f02b6ea11a1e5ca90d9eR80 a new object would created for clusterdeprovision with `null` value for the field
causing validation errors like
```
Invalid value: "null": spec.platform.openstack.certificatesSecretRef in body must be of type object: "null"
```
xref: https://issues.redhat.com/browse/CO-1303
/cc @dgoodwin
> OpenStackClusterDeprovision: fix optional certficate field marshalling

- pkg/apis/hive/v1/clusterpool_types.go
clusterpool's installConfigSecretTemplateRef is not a required field so it should be omitted from json when empty
cc: @dgoodwin
> Omit clusterpool's installConfigSecretTemplateRef field when empty

- config/crds/hive.openshift.io_clusterpools.yaml
- pkg/apis/hive/v1/clusterpool_types.go
- pkg/constants/constants.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller.go
- pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller_test.go
- pkg/controller/utils/clusterclaim.go
The cluster pool 's max concurrent will include the deleting claimed clsuters. This is
to make sure cluster pool actions are safe and under limits as specified by the admin.
previously the claimed clusters from a pool, were deleted out band directly by the clusterclaim
controller when the claim was deleted. This made controlling the max concurrent provision/
deprovision difficult because 2 controllers are making the same decision making independently.
To enforce the max concurrent for pool, all the actions of cluster provision/deprovision had to
be moved to clusterpool controller so that it can ensure the max concurrent limit.
Thefore, the clusterclaim controller now annotates the clusterdeployment that it should be removed
when the claim is deleted, it still removes all the other claim …
> clusterpool: include deleting claimed clusters for max concurrent

- docs/clusterpools.md
Fixes a typo, deprecated api version and inconsistent usage of clusterpool names
/cc @staebler
> Fix errors in clusterpool documentation

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/imageset/generate.go
The cluster deployment controller creates a job that resolves the installer and cli
images for installing the cluster. this job uses the release image to extract these details.
When the release image being used can't be pulled due to some failure like authentication
the controller provides no update / condition that would provide use details on this failure and
the user sees no update on the clusterdeployment object.
With this change we add InstallImagesNotResolved condition to the clusterdeployment when the job fails.
Previously the job had activeDeadline set to 24 hrs, therefore the job controller would wait for that interval
before marking it complete+failed. To make sure the controller can actually give users report of job failure
the deadline is reduces to 2 minutes. This now matches …
> clusterdeployment: include InstallImagesNotResolved condition when job fails

- pkg/install/generate.go
The previous code would overwrite the cmd without adding it to the certificates copy command chain
xref: https://issues.redhat.com/browse/HIVE-1329
> install/generate.go: fix openstack deprovision command when certificates are in use

- go.mod
- pkg/controller/utils/credentials.go
- vendor/modules.txt
When a vSphere ClusterDeployment defines the CA certificates Secret, use the CA certificate data when validating vSphere credentials.
The high-level client library doesn't allow providing a CA certificate early enough, so we need to implement a lot of the lower-level connection setup so that we can slip in the custom CA data when needed.
> use ClusterDeployment's CA data when validating vsphere credentials

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
The commit adds a regex to detect following error in the install log
```
level=info msg="Consuming Bootstrap Ignition Config from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: googleapi: Error 412: Request violates constraint 'constraints/storage.uniformBucketLevelAccess', conditionNotMet"
level=error
level=error msg="  on ../tmp/openshift-install-281334585/bootstrap/main.tf line 1, in resource \"google_storage_bucket\" \"ignition\":"
level=error msg="   1: resource \"google_storage_bucket\" \"ignition\" {"
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply Terraform: failed to complete the change"
level=fatal msg="failed to get …
```
> Update install log regex definitions to detect GCP precondition failed error

- config/crds/hive.openshift.io_machinepools.yaml
- pkg/apis/hive/v1/aws/machinepool.go
- pkg/awsclient/client.go
- pkg/awsclient/mock/client_generated.go
- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/awsactuator_test.go
To be consistent with install config, allow public subnets to be
specified in MachinePool even if the MachineSets created would use only
private subnets.
Account for success in all of the following cases:
- No subnets specified
- Only private subnets specified
- Both public and private subnets specified
Private subnets are required to be exactly one per availability zone if
subnets are specified. If public subnets are also specified, then there
should be exactly 1 public and 1 private subnet for each availability
zone.
> Allow public subnets in AWS MachinePool

- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
We need to be able to create ClusterDeployment with spec.installAttemptsLimit = 0, this way we can flip it to 1 to initiate a deploy at our time of choosing.
Webhook blocks the change
Add InstallAttemptsLimit to the mutable string. Thx @akhil-rane
> Enable installAttemptsLimit for modification. (make mutable for webhook)

- cmd/manager/main.go
- cmd/operator/main.go
- pkg/util/logrus/logr.go
- pkg/util/logrus/logr_test.go
controller runtime currently defaults to NullLogger [1] which doesn't log anything.
This is bad because any error returned from Reconcile function is therefore not logged anywhere
which is same as just eating the error. To make sure the controller runtime errors are also logged
we would need an adapter for logrus as this project uses that for logging.
Therefore, this implements a wrapper around lorgus that satisfies the logr.Logger interface and
confure the hive-controller and hive-operator managers with it.
The wrapper uses logrus.DebugLevel for all info messages and logrus.ErrorLevel for all error messages
from controller-runtime regardless of level (V) selected by caller in controller-runtime. This makes
sure all error messages from controller-runtime are always visible and the rest …
> ensure controller runtime uses logrus for logging

- contrib/pkg/clusterpool/clusterpool.go
```
$ bin/hiveutil clusterpool create-pool lwan-pool-aws \
--region us-east-2 \
--base-domain qe.devcluster.openshift.com \
--size 2 \
--release-image registry.svc.ci.openshift.org/ocp/release:4.7.0-0.nightly-2020-12-13-202314 \
-n test-test -o yaml
apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
creationTimestamp: null
name: lwan-pool-aws
namespace: test-test
spec:
baseDomain: qe.devcluster.openshift.com
imageSetRef:
name: lwan-pool-aws-imageset
platform:
aws:
credentialsSecretRef:
name: lwan-pool-aws-aws-creds
region: us-east-2
size: 2
status:
ready: 0
size: 0
... more
```
now namespace is added to the cluster pool object when -n flag is used.
xref: https://issues.redhat.com/browse/HIVE-1321
/cc @dgoodwin
> create clusterpool: make sure clusterpool has namespace set when using -n

- pkg/installmanager/fake.go
> Change fake-cluster-id to a real uuid

- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/provision_underway_collector.go
- pkg/controller/metrics/provision_underway_collector_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
hive_cluster_deployment_provision_underway_seconds metric currently reports the elapsed time for all clusterdeployments
that provisioning. To allow for reduce the metrics reported and still ensure the metric can be used to alert installs taking
too long, the collector now allows setting minDuration. The minDuration ensures the collector only cares about provisioning times
greater than minDuration.
Another metric that's important for tracking failing installs is the number of restarts for installs. This allows catching failures
that fail really quickly, like permissions, compared to underway_seconds where the installs might have to restart for a very large value
to be alerted.
so a new metric hive_cluster_deployment_provision_underway_install_restarts is added that tracks the number of …
> Add hive_cluster_deployment_provision_underway_install_restarts metric

- config/crds/hive.openshift.io_clusterdeployments.yaml
- pkg/apis/hive/v1/agent/installstrategy.go
This field cannot be used with VIPDHCPAllocationMode false. We will have to handle it in validation.
cc @filanov
> Make agent install strat MachineNetwork optional.

- config/crds/hive.openshift.io_clusterdeployments.yaml
- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/imageset/generate.go
- pkg/imageset/updateinstaller.go
- pkg/imageset/updateinstaller_test.go
The release image today include the metadata (cincinatti metadata) for version
information in release-metadata file, see [1].
The update-installer-image job today reads the release image contents and then
extracts images for installer and cli for each cluster deployment. Since it already
interacts with release image once per cluster deployment, it seems like the right place
to also include code to extract and report the release image version.
- the install image set job init container now copies /release-image/release-metadata file
in additions to the image-references file.
- the update-installer-image command reads this release-metadata file and reports the version
to the status like the installer, cli images.
NOTE: oc uses the release metadata to get the version field and fallback to …
> report release image version in clusterdeployment status

- go.mod
- go.sum
- vendor/modules.txt
Tag go-slug to v0.5.0 for BZ [1914887](https://bugzilla.redhat.com/show_bug.cgi?id=1914887)
https://issues.redhat.com/browse/HIVE-1356
> Tag hashicorp/go-slug to v0.5.0

- config/crds/hive.openshift.io_clusterdeployments.yaml
- pkg/apis/hive/v1/agent/installstrategy.go
- pkg/apis/hive/v1/agent/platform.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
General approach: we have agreed that we are focused on declarative gitops driven workflows with the Kube CRDs rather than the imperative guided build up of a cluster definition from the assisted service today. As such, by default in Hive, most things are immutable and we must explicitly opt-fields into being mutable after creation. The programatic workflow would be to delete your clusterdeployment, correct what's wrong, and try again. With this in mind I skipped the plan to allow field edits until an install is launched.
At this layer we should not be doing any validations against external lookups, so this is primarily to make sure the data is logical when combined with other data, and well formed. I did not do any CIDR validation, we don't typically do this in Hive today and the …
> Agent install strategy and platform validation

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
- pkg/test/dnszone/dnszone.go
support managed dns
longer than allowed
/cc @dgoodwin 
xref: https://issues.redhat.com/browse/HIVE-1129
> Separate out DNSNotReady condition reasons

- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
This change re-enables most of the clusterdeployment controller for Agent based clusters. Previously we just blanket disabled everything, but this skipped the imageset job which was required for extracting useful info for Agent installs, such as the specific semver openshift version.
Now the controller will mostly run as normal with the exception of creation of a ClusterProvision. Getting Agent clusters to link up with the ClusterProvision flow will be handled in the future.
/cc @abutcher @filanov @avishayt @mhrivnak
> Act on agent clusters

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
We're encountering more and more "*LimitExceeded" errors and this would capture all of them generically. Do we prefer this to having a regex for each type of resource limit exceeded to prevent needing to check logs.
Add tests for `"NATGatewayLimitExceeded"` and `"VPCLimitExceeded"`.
/cc @gregsheremeta
> HIVE-1394: Add generic install failing reason ResourceLimitExceeded.

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
In an effort to reduce the storage for nonessential memory-intensive
metrics, rest_client_request_latency_seconds was identified as the
metric that reports and stores the most time series. This metric was
vendored in from sigs.k8s.io/controller-runtime.
However, it has since been deprecated in kube 1.14 and turned off
in kube 1.17. Since upstream still registers this metric, it was
consequently decided to point controller-runtime to a fork that carries
the patch to not report this metric
/cc @gregsheremeta
> Point sigs.k8s.io/controller-runtime to a fork

- apis/hive/v1/clusterclaim_types.go
- config/crds/hive.openshift.io_clusterclaims.yaml
- vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go
This PR adds an "Age" column back to the ClusterClaim output by adding a printcolumn annotation.  In Hive v1.0.19, a number of (very useful) new columns were added but this had the effect of removing the "Age" column, a useful metric when computing how much of a ClusterClaim's `Lifetime` remains or determining which clusters may have been unintentionally leaked or left around without a Lifetime by users/automation.  
```
gbuchana-mac:hive-1 gurnben$ oc get clusterclaim -n default
NAME                       POOL             PENDING   CLUSTERNAMESPACE   CLUSTERRUNNING   AGE
gurnben-hive-deploy-test   canary-aws-470                                                 11m
```
> Add an 'Age' printer column to ClusterClaims

- hack/update-codegen.sh
the code-generator seems to generate/update the deepcopy functions in
the vendor directory where github.com/openshift/hive/apis package exists
from the context of the root package.
the code-generator fails to run from the apis submodule, so the next
best thing is to copy the deepcopy functions from the vendor to apis
submodule.
> hack/update-codegen.sh: make sure deepcopy functions are updated in apis

- pkg/controller/hibernation/aws_actuator.go
- pkg/controller/hibernation/azure_actuator.go
- pkg/controller/hibernation/gcp_actuator.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
x-ref: https://issues.redhat.com/browse/HIVE-1455
Encountered a cluster deployment stuck resuming for several days, and
thus was not powered off after the hibernateAfter interval.
Issue appeared to be because one worker VM was still in stopped state.
The code made the assumption that we must have issued the start command
when transitioning to resuming state, and then never tried to again.
To fix we now will issue StartMachines every time we check if we're
resumed. All three providers are implemented to only issue to VMs that
are stopped / stopping so the change should have no impact normally.
> Fix clusters stuck resuming due to stopped instance.

- contrib/pkg/createcluster/create.go
- pkg/clusterresource/openstack.go
Here I've added the ability to specify the floating IP that users want to utilise for ingress services on an OpenStack based cluster.
> New Floating IP option for Ingress with OpenStack

- hack/fedora33dev/Dockerfile.dev
- hack/fedora33dev/Dockerfile.devbase
- hack/fedora33dev/README.md
- hack/fedora33dev/docker-dev-push.sh
I've been using this for a long time, but ideally it would be nice to see cleaned up and a recommended dev path in the docs.
For now, just publishing to help out Andrew.
> Add a temporary Fedora 33 dev docker build/push setup.

- pkg/awsclient/client.go
the session options always picked default profile for AWS Config. So
when the session was from secret object the AWS Config will be generated
for the default profile. But when the session needed to be created from
environment like in installerpod, the setting of default profile would
skip the environement variables weirdly (this is not how it should be
but tested and it acts like that).
/assign @joelddiaz
> awsclient: fix creating client from env when no config provided

- pkg/installmanager/installmanager.go
Currently, `oc adm must-gather` stores logs inside `logs/must-gather` dir of the
install pod. While uploading we iterate through `logs` dir and only upload files,
ignoring directories.
This fix creates a tar archive file of the `logs/must-gather` dir in the `logs` dir
so that it does not get ignored while uploading to S3.
x-ref: https://issues.redhat.com/browse/HIVE-1462
> Fix issue with the upload when logs are collected using oc adm must-gather

- apis/hive/v1/agent/platform.go
- config/crds/hive.openshift.io_clusterdeployments.yaml
- config/crds/hive.openshift.io_clusterpools.yaml
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/agent/platform.go
This field is not needed according to assisted team, it can be inferred
by cluster name and base domain.
x-ref: https://issues.redhat.com/browse/HIVE-1460
> Drop agent platform apivipdnsname.

- docs/awsassumerolecreds.md
the docs became stale when i moved to hiveconfig field names, bringing them in sync.
xref: https://issues.redhat.com/browse/HIVE-1422
> docs/awsassumerolecreds.md: fix hiveconfig instructions

- config/hiveadmission/clusterdeployment-webhook.yaml
- config/hiveadmission/clusterimageset-webhook.yaml
- config/hiveadmission/clusterprovision-webhook.yaml
- config/hiveadmission/dnszones-webhook.yaml
- config/hiveadmission/machinepool-webhook.yaml
- config/hiveadmission/selectorsyncset-webhook.yaml
- config/hiveadmission/syncset-webhook.yaml
- pkg/operator/assets/bindata.go
Since all of our validation webhooks only validate the resource being
sent in with info in the object and any other global configuration,
these pretty much have no side effects.
so setting the side effects to None allows dry-runs.
xref: https://issues.redhat.com/browse/HIVE-1468
/cc @hongkailiu
> config/hiveadmission: set sideEffects for validating webhooks to None

- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
This was happening previously for most clusters due to an assumption
that if no Unreachable condition exists, then the cluster must not be
installed yet. However an integrating application stumbled into a crash
where they were misusing the Unreachable condition, with status Unknown,
and our code interpreted this as must be installed (it wasn't), and
reachable, leading to the crash as no cluster metadata is defined.
The misused of Unknown condition will be fixed on their end, but we
should have an explicit installed check regardless.
> Skip uninstalled clusters in clustersync controller.

- hack/logextractor.sh
As written, the `logextractor.sh` script fails to authenticate to AWS
with error:
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
This PR exports the secret access key and access key ID so subsequent
AWS calls succeed.
Signed-off-by: Christopher Collins <collins.christopher@gmail.com>
> Exports AWS credentials in logextractor to fix auth bug

- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
When `SyncSet` `resourceApplyMode` is changed from `Sync` to `Upsert`, we remove the `resourcesToDelete` from `ClusterSync` status. Since `resourceApplyMode` defaults to `Upsert` we should check for no `resourceApplyMode` when clearing the `resourcesToDelete`.
> Check for no applyMode set (defaults to Upsert) when clearing resourcesToDelete

- pkg/awsclient/client.go
In one of the rebases it looks like I missed initializing elbv2 client. 🤦🏽 
> awsclient: initialize elbv2 client

- pkg/validating-webhooks/hive/v1/clusterimageset_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterimageset_validating_admission_hook_test.go
Per a conversation with @dgoodwin, this PR removes the immutability check from the `ClusterImageSet` webhook. This permits the `Spec` of CIS objects to be updated, such as the case where the image you wish to use has changed location (different registry, or changing from tag to digest references).
There was some consideration around the fact that this may cause some confusion around which release image was used to generate a particular `ClusterDeployment`, however the CD status contains at least the installer and cli image digests that are retrieved from inside the release bundle image so this may not be strictly necessary.
> Allow updates to ClusterImageSet.Spec

- docs/awsprivatelink.md
just to save the random user a bit of time of copy-paste.
> change aws permissions policy from dot to colon

- pkg/controller/awsprivatelink/cleanup.go
When the provision fails to reach a level that metadata is available,
deleting the clusterdeployment should skip the cleanup of private link
resources.
> awsprivatelink: skip deleting privatelink when no cleanup required

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
There are cases where the cluster's private link will be ready, but the
installation attempt fails for reasons outside it. In this case we need
to reconcile the aws private link to cleanup the prev created resources
and allow for next attempt. since we have created the resources once, we
reconcile but quicker than when the cluster is installed.
setProgress(complete = true) updates already Ready condition with latest
probe time so that we can track the last Ready level time.
Now since we have the last Ready time, we update the shouldSync
function to use the Ready's last probe time to calculate the time passed
since last Ready sync.
should sync now returns when to syncAfter if it returns false. this
allows the caller to RequeueAfter with that duration.
> awsprivatelink: fix shouldSync for Ready leveled and installing clusters

- pkg/controller/metrics/provision_underway_collector.go
- pkg/controller/metrics/provision_underway_collector_test.go
When Provision Underway metric collector fetches conditions and reasons
of clusterdeployment, it should continue fetching if first condition is
false, and report the first condition with status True
xref: https://issues.redhat.com/browse/HIVE-1475
> Provision Underway Metric must report first condition with status=True

- apis/hive/v1/clusterdeprovision_types.go
- go.sum
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
- pkg/controller/clusterprovision/installlogmonitor.go
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/controller/utils/jobs.go
- pkg/install/generate.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
Setting an active deadline seconds for the job limits the time an attempt
can continue to run. This is useful when install/cleanup is stuck for
really long and cannot make progress.
In cases when no progress can be be made it is useful to give up the
attempt as failure and report the failure so that we can reattempt. This
also also reattempt limits to be useful.
/cc @joelddiaz
> install: add active deadline seconds on provision/deprovision jobs

- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/vpcinventory.go
Ensure that when choosing the VPC and subnets from the inventory the
choice only have the supported subnets. This makes sure the the vpc
endpoint is created in correct and supported AZs
> awsprivatelink: fix filtering inventory to correct subnets

- Makefile
Running `IMG=localhost:5000/hive:latest make docker-dev-push` fails with 
make: *** No rule to make target `image-hive-dev', needed by `docker-dev-push'.  Stop.
Looking at the [docs](https://github.com/openshift/hive/blob/master/docs/developing.md#deploying-from-source) and the [deprecation messages](https://github.com/openshift/hive/blob/master/Makefile#L233) in the Makefile, I guess the sub-target should be `image-hive-fedora-dev` rather than `image-hive-dev`. Consequently I sent this PR to update the target to `image-hive-fedora-dev`.
PTAL
> Fix docker-dev-push target

- apis/hive/v1/clusterpool_types.go
- apis/hive/v1/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_clusterpools.yaml
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
- pkg/test/clusterdeployment/clusterdeployment.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
- vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
- Created `clusterpool.spec.annotations` field that can be used to apply fake cluster annotation on the cluster deployments
- Hibernation controller will now skip processing for cluster deployments with fake annotation
x-ref: https://issues.redhat.com/browse/HIVE-1493
> Add option to fake out all the clusterdeployments in the clusterpool

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterprovision/installlogmonitor.go
- pkg/controller/clusterprovision/installlogmonitor_test.go
When the provision fails, we store a piece of the failure in
.spec.installLog for the clusterprovision. When we can't find any match
we known failures, we report the install log as-is as part of the failed
provision condition's message.
This message can now be added to the clusterdeployment, when it
reconciles a failed clusterprovision.
including the logs from failed attempt in the condition when the error
is unknown allows users and sre's to at glance look the failure. this
prevents users not understanding the failure.
> include the installLog from failed provision in clusterdeployment condition

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
install log snippet
```
level=info msg=Creating infrastructure resources...
level=info msg=Waiting up to 20m0s for the Kubernetes API at https://api.osde2e-nci3m.xmbp.p2.openshiftapps.com:6443...
level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.osde2e-nci3m.xmbp.p2.openshiftapps.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp: lookup api.osde2e-nci3m.xmbp.p2.openshiftapps.com on 172.30.0.10:53: no such host
level=info msg=Pulling debug logs from the bootstrap machine
level=info msg=Bootstrap gather logs captured here "/output/log-bundle-20210421123336.tar.gz"
level=error msg=Bootstrap failed to complete: Get "https://api.osde2e-nci3m.xmbp.p2.openshiftapps.com:6443/version?timeout=32s": …
```
> Add regex to detect install failed waiting for kube api

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
ClusterSync object is not created when syncset-paused annotation
is applied to the ClusterDeployment. This is not mentioned in the
status. This commit improves the status message.
x-ref: https://issues.redhat.com/browse/HIVE-1497
> Improve status reporting when syncsets are paused

- go.mod
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
- vendor/modules.txt
when the spec has changes on fields that are not mutable, return the
list of fields that changed (with values) that should not have been
changed.
for example,
```
oc patch cd test-cluster --type='merge' -p $'spec:\n baseDomain:
devcluster.openshift.co#\n clusterName: test-cluste#\n platform:\n
aws:\n   region: us-east-#'
Error from server (BadRequest): admission webhook
"clusterdeploymentvalidators.admission.hive.openshift.io" denied the
request: Attempted to change ClusterDeployment.Spec which is immutable
except for
CertificateBundles,ClusterMetadata,ControlPlaneConfig,Ingress,Installed,PreserveOnDelete,ClusterPoolRef,PowerState,HibernateAfter,InstallAttemptsLimit,MachineManagement
fields. Unsupported change:
ClusterName: (test-cluster => test-cluste#)
BaseDomain: …
```
> validating-webhooks: include diff when immutable fields are changed

- pkg/controller/images/controller_images.go
- pkg/install/generate.go
To mitigate ClusterProvision pods not starting during a container image registry outage change the CusterProvision pod `imagePullPolicy` from `Always` to `IfNotPresent`.
This should allow any ClusterProvision pod to start without entering `ImagePullBackoff` provided the `hive` image pod is cached locally.
This is a temporary mitigation until [HIVE-1504](https://issues.redhat.com/browse/HIVE-1504) is implemented and Hive can take advantage of registry mirrors.
[HIVE-1505](https://issues.redhat.com/browse/HIVE-1505)
> Change ClusterProvision image pull policy

- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
When we receive a watch, and we reconcile for that watch and then use
that cache to get the latest version of the changed object, we can
assume this gurantee.
Currently, due to historical reasons, we have a separate cache for
watching secrets in hive namespace, but then use the reconciler's client
to get the secrets. This means that our assumption of having the latest
update secret is no longer valid.
So in the current setup, we should use the lister from the correct
cache to get secrets. This is now achieved by storing the lister for the
secrets and then using that when required.
> https://github.com/openshift/hive/pull/1350
that change allows reconcile on secret changes that are used in hiveconfig esp the client certificates secret.
but when the secret was updated, the reconcile would …
> operator: use the correct cache to get secrets

- apis/hive/v1/clusterdeployment_types.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
- pkg/controller/utils/conditions.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
As per kube api guidelines, conditions should be placed by the controller as soon as possible, to indicate that it has began processing the resource. If a decision cannot be made regarding the status of the condition at that time, it can be set to Unknown.
This commit Initializes cluster hibernating condition as soon as possible.
It is to False for Unsupported clouds, and to Unknown for others
xref https://issues.redhat.com/browse/HIVE-1509
/cc @dgoodwin
> Initialize Hibernating condition

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
The error messages are important information that ends up in the Failed
condition. But the request IDs in the messages cause the Failed
conditions to change frequently. so filtering out the request IDs should
prevent un necessary updates to the Failed condition
> awsprivatelink: filter our reuest id from error messages

- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/cleanup.go
The discovery for hosted zone cleanup was not required when we have the
hosted zone id in the status. Using the hosted zone id when set.
this helps reduce the VPC Endpoint and route 53 calls that need to be
made to fetch this discovery data.
> awsprivatelink: hosted zone cleanup reuse the status

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
New changes to how we set conditions beforehand led to hibernating
condition status set to unknown for fake cluster. This fix
explicitly sets hibernating condition to false for fake cluster.
> Fix cluster claim for fake clusterpool

- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/utils/conditions.go
- pkg/imageset/updateinstaller.go
Currently we assume all ClusterDeploymentConditions to have negative polarity, consequently we only set them for the first time if their Status=True. Eliminate this assumption and allow all conditions to be set regardless of their status.
/cc @dgoodwin
> Set ClusterDeploymentCondition for all status

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/cleanup.go
x-ref: https://issues.redhat.com/browse/HIVE-1536
In this scenario the controllers are trying to teardown a cluster that
was never fully installed, and failing because aws private link cleanup
requires an admin kubeconfig Secret, which does not seem to exist. (this
fix will be pursued separately)
The hotloop was caused by the fact that we were setting the Ready
condition to indicate we're trying to tear down, and then also setting
it after an error occurs. Each write causes another reconcile, so we're
flapping the condition back and forth between these two states. The
reconciles then fan out to all other controllers watching
ClusterDeployment.
Per latest kube api guidelines:
"Condition type names should describe the current observed state of the
resource, rather than describing the …
> Fix hotloop in awsprivatelink controller in some situations

- pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook_test.go
in addition to allowing zero replicas w/o zones, also allow it when the
machinepool has a list of zones defined.
xref: https://issues.redhat.com/browse/HIVE-1486
> allow to set zero replicas also when zones are set

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/cleanup.go
In some scenarios when an AWS privatelink cluster is deleted prior to
being fully installed, it was possible for the code to jam up in a
situation where no hosted zone ID was recorded in status, and we cannot
discover it because the admin kubeconfig secret is already gone.
To fix we just gracefully exit in this scenario as we have nothing to
cleanup.
x-ref: https://issues.redhat.com/browse/HIVE-1537
/cc @suhanime
> Fix stuck privatelink clusters deleted prior to install.

- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/dnszone_controller_test.go
error message can contain AWS generated username (when doing
AssumeRole/STS). This can cause a loop of Status() followed by
Reconcile().
> do not include error message in status condition

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/clusterinstalls.go
- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/imageset/updateinstaller.go
- pkg/imageset/updateinstaller_test.go
- pkg/remoteclient/remoteclient.go
- pkg/remoteclient/remoteclient_test.go
- pkg/test/assert/assertions.go
As per kube api guidelines, conditions should be placed by the controller as soon as possible, to indicate that it has began processing the resource. If a decision cannot be made regarding the status of the condition at that time, it can be set to Unknown.
xref: https://issues.redhat.com/browse/HIVE-1529
> Initialize all cluster deployment conditions

- cmd/manager/main.go
- cmd/operator/main.go
We currently alert if hive is down for 5 minutes, however our leader
election timeouts can easily blow past this if a pod loses
leader status without a clean exit.
These limits were originally from CCO and requests to avoid the default
writes to etcd every 2s.
Cut the limits in half such that we're writing to etcd every 30s, and we
timeout after 2 minutes, which should work well with our 5 min alert.
> Lower leader election lease durations.

- pkg/controller/remotemachineset/remotemachineset_controller.go
The semver library returns an error if you try to parse a version with
only major.minor. Provide the semver package the full major.minor.patch
to allow properly detecting whether a version of OpenStack can support
autocaling.minReplicas=0.
xref: https://issues.redhat.com/browse/HIVE-1539
> fix support of OpenStack autoscalling.minRep=0

- apis/hive/v1/clusterdeployment_types.go
- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
- pkg/controller/utils/conditions.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
We have always assumed that all cluster deployment conditions have negative polarity, i.e., they are in their undesired state if their status=True.
This PR removes that assumption, and logs `hive_cluster_deployments_conditions` for all conditions in their undesired state.
For cluster deployment conditions in  `PositivePolarityClusterDeploymentConditions`, we assume that their desired state is True, and for all other conditions, the desired state is False..
Conditions with Unknown state are ignored.
xref: https://issues.redhat.com/browse/HIVE-1549
/cc @dgoodwin @abhinavdahiya
> Metrics change to accomodate clusterdeployment conditions cleanup

- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/dnszone_controller_test.go
- pkg/controller/utils/ratelimitedeventhandler.go
- pkg/controller/utils/ratelimitedeventhandler_test.go
Event handlers in controller-runtime add Update events to non-rate limited queues.
In many cases it is desireable that the Update event be rate limited for
preventing excessive reconciles.
One of the main examples of the use case is when controller adds Failure
condition to the objects. This causes Update event to be trigerred and
immediately handled for the object and almost always ending up in the
same Failure state. The effect is increased if the error message in the
condition changes every time error is enconterred like request ids in
error messages returned from cloud providers.
To make sure the controller can backoff these error states, a new event
handler wrapper is added that can force the UPDATE event to be rate
limited when the controller configured function returns true. …
> controller/dnszone: rate limit UPDATE events that are in error state

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/clusterinstalls.go
- pkg/controller/metrics/metrics.go
- pkg/controller/utils/conditions.go
- pkg/controller/utils/conditions_test.go
Now that we have all possible cluster deployment conditions present on
the CR, it can become very difficult to debug.
This commit tries to sort the list of conditions, such that the
conditions in their undesired state are always at the top of the list
xref: https://issues.redhat.com/browse/HIVE-1552
> Sort clusterdeployment conditions

- pkg/operator/hive/hiveadmission.go
x-ref: https://issues.redhat.com/browse/HIVE-1544
> Fix panic when hive admission serving cert secret is missing

- build/build-image/Dockerfile
This reverts commit 82f98f2425c871ea945b253d078adbba48fcdd04.
> Revert "Move to kube 1.20.2 for integration tests."

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/test/assert/assertions.go
TL;DR: When comparing objects coming back from kube, things like ResourceVersion should be ignored (unless asserting that the object has not changed on the server, in which case comparing *only* ResourceVersion should suffice).
We had a couple of tests that were using DeepEquals to compare an object from the (fake) kube server to one we constructed locally. The ResourceVersion returned by the fake server [changed in controller-runtime 0.8.0](https://github.com/kubernetes-sigs/controller-runtime/pull/1306) which broke tests. We [worked around](https://github.com/openshift/hive/pull/1407/commits/c7d60527612c141f58d748b8bf2e25d72f9499d5) that; but the Right Thing To Do™ is to make the comparison ignore ResourceVersion entirely. It is thusly done via this commit.
> Fix clusterdeployment tests for DeepEquals
