- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Not 100% sure the config map is coming out right as the installer doesn't accept it as input yet, but very soon and we can iterate.
> Generate a ConfigMap with an installer InstallConfig and mount in.

- Makefile
- build/build-image/Dockerfile
- build/test-image/Dockerfile
> Change Hive repo to work with ci.

- Makefile
- contrib/cmd/hiveutil/main.go
- contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
first coutil -> hiveutil migration (right now only support aws-tag-deprovision subcommand)
> add initial hiveutil

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Set status when cluster is installed. (still a dummy job that always succeeds)
Add a basic unit tests. Attempts to go further met with problems in the kubebuilder stack I still need to figure out.
> Installed status

- contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
There might be s3buckets in account that attached to different region.
This caused the deprovisioner to fail fataly.
For example:
```
2018/09/24 22:52:43 DEBUG: Request s3/GetBucketTagging Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /?tagging= HTTP/1.1
Host: atectonic-demo-97d9f36d6647e7be86e0ce5baca4e419.s3.amazonaws.com
User-Agent: aws-sdk-go/1.15.41 (go1.10.3; linux; amd64)
Authorization: <redacted>
Accept-Encoding: gzip
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 25 Sep 2018 05:55:26 GMT
Server: AmazonS3
-----------------------------------------------------
2018/09/24 22:55:27 <?xml version="1.0" encoding="UTF-8"?> …
```
> aws_tag_deprovision: continue on s3tag fetch

- contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
@dgoodwin @joelddiaz I noticed if a cluster doesn't complete successfully, there is likely  IAM roles/policies/profiles that are not associated with a running instance (bc they are created in the install process b4 the instance).  The deprovisioner was dependent upon an instance running to delete the IAM resources.  I've added the function of deleting IAM resources for the specific profiles we know to be created with the installer. `${CLUSTER_NAME-master-profile` `${CLUSTER_NAME-worker-profile` and `${CLUSTER_NAME-bootstrap-profile`
have to now pass `--cluster-name mycluster` along with the tags
I've tested different scenerios:  failed launch/successful launch/single/multiple masters  this works well
> Delete IAM resources if associated instance is not running

- Makefile
> Fix make verify for CI.

- README.md
- config/templates/cluster-deployment.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
Separates artifact generation into its own package
Adds necessary environment vars to job to create cluster
> Use new installer to run cluster install job

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
rather than find load balancers by tag, find them by VPC
the cluster can start up its own service load balancer objects, and they are untagged, so locating LBs by VPC association will also find an delete LBs created by the cluster post-install
this means deleting VPCs will now be part of the VPC deletion flow
> delete load balancers by VPC association

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
And document the matching logic.  This makes usage more obvious for folks reading [the godocs][1], who currently have no guidance on what `awsFilter` is.
[1]: https://godoc.org/github.com/openshift/hive/contrib/pkg/awstagdeprovision
> contrib/pkg/awstagdeprovision: Make awsFilter a public AWSFilter

- Makefile
- README.md
> Add make deploy-sd-dev

- contrib/pkg/awstagdeprovision/awstagdeprovision.go
> Fix pointer logging in delete load balancers.

- README.md
- config/overlays/sd-dev/image_patch.yaml
> Update sd-dev image links to the latest images.

- config/rbac/rbac_role.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Fixes issue preventing controller from creating a role for the job service account.
> Add clusterdeployments/status to controller RBAC

- cmd/manager/main.go
Fixes https://github.com/openshift/hive/issues/88
> Remove extra log message warning

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
if we've had a failed install that somehow managed to leave some remnant configmaps or secrets around, the retry will fail. clean up before attempting any installations.
update some comments and logging to reflect non-fatal errors.
> cleanup configmap and secrets before install

- build/build-image/Dockerfile
> Fix go cache error during build 'go: disabling cache ...'

- build/build-image/Dockerfile
older version is causing CI issues
> update kubebuilder version

- Makefile
- cmd/hiveadmission/main.go
- cmd/manager/main.go
- config/default/kustomization.yaml
- config/hiveadmission/hiveadmission.yaml
- config/overlays/sd-dev/image_patch.yaml
- config/rbac/hiveadmission_rbac_role.yaml
- config/rbac/hiveadmission_rbac_role_binding.yaml
- config/samples/hiveadmission-review-failure.json
- config/samples/hiveadmission-review-success.json
- config/samples/hiveadmission-review-update-failure.json
- config/templates/hiveadmission.yaml
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
> Add validation webhooks for hive CRDs.

- README.md
- config/overlays/sd-dev/image_patch.yaml
> Minor fix ups

- pkg/install/generate.go
> Fix renamed release override env var in installer.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
This was erroring when trying to update status, change this to a warning.
> Cleanup errors when admin kubeconfig doesn't yet exist.

- pkg/install/convertconfig.go
- pkg/install/convertconfig_test.go
Matches a change that just went into the installer.
> Add install config version.

- Makefile
- README.md
- hack/federation/deploy_federation.yaml
- hack/federation/federatedirectives/clusterroles.rbac.authorization.k8s.io.yaml
- hack/federation/federatedirectives/configmaps.yaml
- hack/federation/federatedirectives/deployments.apps.yaml
- hack/federation/federatedirectives/ingresses.extensions.yaml
- hack/federation/federatedirectives/jobs.batch.yaml
- hack/federation/federatedirectives/namespaces.yaml
- hack/federation/federatedirectives/replicasets.apps.yaml
- hack/federation/federatedirectives/secrets.yaml
- hack/federation/federatedirectives/serviceaccounts.yaml
- hack/federation/federatedirectives/services.yaml
- hack/install-federation.sh
Adds script and makefile target to install federation
> Script to install federation

- Dockerfile.fedcli
- README.md
- cmd/manager/main.go
- config/crds/hive_v1alpha1_clusterdeployment.yaml
- hack/federation/cluster-registry-crd.yaml
- hack/federation/deploy_federation.yaml
- hack/install-federation.sh
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/add_federation.go
- pkg/controller/federation/clusterdeployment_federation_controller.go
- pkg/federation/config.go
- pkg/federation/generate.go
Updates federation installation script
Adds controller to federate installed clusters
> Federation controller

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
rename ClusterName to ClusterDeploymentName
grab and save the ClusterName (presently named ActualClusterName) and use it where we really want the ClusterName
> don't assume clusterdeploymentname == clustername

- README.md
- config/overlays/sd-dev/image_patch.yaml
- docs/sd_release.md
-[x] Update SD image links to latest release.
-[x] Fix sd_release.md docs to be more correct.
> SD release 20190116

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
> Fix another spec modification.

- .gitignore
- Makefile
- config/overlays/.gitignore
- config/overlays/template/image_patch.yaml
- config/overlays/template/kustomization.yaml
Allows specifying your own image when deploying hive with:
```
make deploy DEPLOY_IMAGE=yourimage:latest
```
> Allow specifying a Hive image when deploying

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
Consider multiple machinepools in clusterdeployment when syncing machinesets.
> Consider multiple machinepools within clusterdeployment for syncing.

- pkg/install/generate.go
- pkg/install/generate_test.go
-- Skips creation of uninstall job if the cluster deployment has PreserveOnDelete set to true
> additional safeguard for PreserveOnDelete

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/crds/hive_v1alpha1_selectorsyncset.yaml
- config/crds/hive_v1alpha1_syncset.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/syncset_types.go
> Add syncset types.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
--> Automatically updates install job when the generation of the cd does not match the cd generation in job's annotations.
> automatically-updating-install-job

- build_deploy.sh
- pr_check.sh
- `build_deploy.sh` will be executed in merge to master. It currently
builds and pushes to quay.
- `pr_check.sh` currently doesn't do anything as the CI is done via
openshift-ci.
> build_deploy.sh and pr_check.sh for AppSRE CI/CD

- contrib/cmd/hiveutil/main.go
- contrib/pkg/testresource/command.go
- pkg/resource/apply.go
- pkg/resource/factory.go
- pkg/resource/helper.go
- pkg/resource/patch.go
Also adds a command to hiveutil to test either apply or patch commands
> Add patch resource helper function

- Makefile
- pkg/resource/apply.go
- pkg/resource/patch.go
- test/integration/clusterdeployment/clusterdeployment_controller_test.go
- test/integration/resource/apply_test.go
- test/integration/resource/patch_test.go
- test/integration/resource/resource_suite_test.go
Fixes existing tests so that they pass
Adds tests for the resource apply/patch functions
Fixes error bug in Patch/Apply
> Add integration tests for apply/patch

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/crds/hive_v1alpha1_selectorsyncset.yaml
- config/crds/hive_v1alpha1_syncset.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/syncset_types.go
- pkg/operator/assets/bindata.go
Update SyncSet API for gvk and update cd status as lists of SyncSets or SelectorSyncSets with status.
> SyncSet api updates

- config/rbac/hive_frontend_role.yaml
> Add pods/log permission to hive-frontend role.

- hack/olm-registry/olm-artifacts-template.yaml
Fixes the default value key for the template
> Fix defaults for olm template

- pkg/controller/metrics/metrics.go
- pkg/install/generate.go
Prometheus metrics for install jobs and uninstall jobs
> Prometheus metrics

- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
Also fixes the count of running install/uninstall jobs to only include those which are actually running.
> Add metrics for total uninstalling clusters in various severities

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
This is to limit cardinality by only reporting the metric to indicate a
problem, if there's a problem.
> Do not report restarts metric for install jobs with 0.

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
run the installer without debug loglevel and capture/redirect the regular console output into a file. save it to a configmap (on error f the generateasset phase, and always in the provisioncluster stage).
pipe out the output of the full installer logs $workdir/.openshift_install.log as the binary/pods output.
add some retry logic around updating the clusterdeployment status (lots of controllers updating the clusterdeployment causing stale object update errors).
update tests to simulate outputing of console output to file, and verify it getting saved to the configmap.
> save installer output to configmap

- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/installmanager/installmanager_test.go
create a regex that can remove any line in the log containing 'password' (case insenstive)
> remove sensitive lines from saved log

- contrib/pkg/installmanager/installmanager.go
build on #324 , and do similar filtering before pushing the contents of the debug log file to stdout
> clean up output to stdout before printing

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
--> Calculates provision job duration metrics
> Provision Job duration metric

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
--> Install job kickstart duration after cd is created
> install job kickstart duration metrics

- contrib/pkg/createcluster/create.go
- pkg/operator/util/apply.go
- pkg/resource/serializer.go
> Fixing "make test"

- Makefile
> Adding "make clean" target to remove built artifacts

- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
If a SyncSet resource was fundamentally broken and will never apply
(target namespace does not exist), the controller would update a
condition if the reason or message changed. The error message was
included in the message and happened to contain a temporary filename,
which is always changing. This would trigger a status update, a new
reconcile, and thus a hotloop.
Switch to using a static error message with a note for how we can
improve in future. Full details will still be in the logs.
This exposed that errors are not being returned from the controller at
all in these cases, so it would be several hours before we tried again.
This is also corrected to return an error to the controller-runtime
framework, which will let us re-try and go into exponential backoff
which tops out around 10 …
> Fix SyncSet controller hotloop.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/federation/clusterdeployment_federation_controller.go
- pkg/controller/federation/clusterdeployment_federation_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/imageset/updateinstaller_test.go
- pkg/install/convertconfig_test.go
> Formatting changes from "make fmt" on go version 1.11.6

- config/manager/service.yaml
- pkg/operator/assets/bindata.go
> Add named port

- README.md
> Updating the deprovisioning steps

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
- pkg/imageset/generate.go
- pkg/install/generate.go
> WIP:imageset job metrics

- README.md
> Adding steps to watch cluster deployment and retrieve password for webconsole

- config/rbac/hive_reader_role.yaml
- config/rbac/hive_reader_role_binding.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
Breakdown hive-admin role into an additional hive-reader role
Fixes: https://jira.coreos.com/browse/CO-380
> Issue CO-380: Add hive-reader role

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
Add histogram for the number of restarts it took to install the cluster.
This is separate from the per-cluster metric we publish while
installing.
Revamp per cluster restarts metric and add a success bool 0/1 metric to
use in addition when alerting. (i.e. if restarts > 4 and success = 0 for
a cluster, alert) We stop reporting both once the cluster is
installed, though it will not be marked stale until Hive is restarted.
Add metrics for deprovisioning clusters and how long they've been in
that state, similar to uninstalled clusters. This will allow us to track
stuck cluster deletions.
Fix bugs in metrics when there are no clusters of a particular type.
> Additional metrics and cleanup.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
A bug has surfaced in stage where a UHC test was creating unmanaged
(PreserveOnDelete) clusters and then immediately deleting them, and
their namespace. The controllers still tried to create service account /
role / rolebinding for the pods, even though we have no pod to run for
these clusters, and we just want to clear the finalizer.
I considered trying to shortcut this but the deletion logic is already
pretty tricky, particularly when you consider a PreserveOnDelete
cluster, with an InfraID, which is not yet fully installed, which is an
edge case where we do actually launch an uninstall job for it. However
this does not appear to be the case in stage as they seem to be deleted
before we can get an InfraID generated.
Instead this PR moves the creation of these objects next to the …
> Fix PreserveOnDelete clusters rapidly deleted after creation.

- config/rbac/manager_role.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/utils/sa.go
- pkg/operator/assets/bindata.go
Also creates job service account on demand
> Fix manager role for clusterdeprovisionrequests

- pkg/controller/syncset/syncset_controller.go
Migrates previous patchType strings to the new short format
> Migrate patch type for SyncSets with patches

- build/build-image/Dockerfile
https://github.com/jenkinsci/docker/issues/519
> Workaround for fixing jenkins git issue

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
Report a metric labelled by cluster name, namespace, and type, for any
cluster that is currently provisioning or deprovisioning. Value is the
number of seconds since it was created/deleted. Once the job completes
we will reset the value to 0 and then stop reporting it which should
limit cardinality.
This should be a better solution to the per-cluster metrics we want to
alert on. This change removes the two metrics we had prior which were
install restarts plus a success boolean metric, which had to be
correlated to know if there was still a problem.
This solution catches situations where no install job gets created, does
not require correlating any metrics against each other, and allows us to
easily alert after any time period we wish.
> Add provisioning underway seconds metrics.

- contrib/cmd/hiveutil/main.go
- contrib/pkg/installmanager/installmanager.go
- contrib/pkg/report/cluster.go
- contrib/pkg/utils/client.go
Fairly simple right now, just iterates all clusters within last X
duration and if they failed, fetches and prints their log summary.
> Add a hiveutil report command for gather info on failed installs.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Add cluster type to the per-cluster restarts metric.
> Add counter metrics for cluster create/delete events.

- pkg/controller/remotemachineset/remotemachineset_controller.go
> Adding error to log for unreachable cluster in machineset controller

- contrib/pkg/createcluster/create.go
Fixes errors in secrets generated by `hiveutil create-cluster`
(This command will be used by the new e2e job to generate a cluster)
> Fix cluster secrets in create-cluster command

- contrib/pkg/createcluster/create.go
Adds a flag to the create-cluster command that points to a URL that contains a pull-spec to a release image to use.
The default is https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest
which should return the latest stable release image for OpenShift 4.
> Add release image source to create-cluster

- pkg/controller/dnszone/zonereconciler.go
- pkg/operator/hive/hive.go
Allows setting a set of DNS servers to perform SOA record checks when determining if a DNS Zone is ready to be used.
You can specify the DNS servers via an environment variable `ZONE_CHECK_DNS_SERVERS`. To specify multiple servers, separate them with a comma.
Example:
```
oc set env -n hive deployment/hive-operator ZONE_CHECK_DNS_SERVERS=8.8.8.8,8.8.4.4
```
> Optional DNS server for DNSZone checks

- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/zonereconciler.go
dnszone controller hotlooping due to an unconditional update call while we're waiting for the zone to be ready. Fixed by checking if status has changed before doing an update, and removing an unconditional timestamp update to only be applied once we're ready.
Added code to cleanup the stuck clusters in stage where the dnszone is unable to remove it's finalizer because it's namespace has been deleted and AWS creds were cleaned up. We give up in this situation just as we do when we detect it for cluster deployments.
We do not yet know how cluster deployments are getting deleted before the dnszones are, the owner ref blockOwnerDeletion does not seem to be working at all, cluster deployment deletion doesn't flag the dnszone for deletion and then UHC deletes the namespace once the cluster is …
> Fix DNSZone hotloop and stuck deletions

- README.md
- contrib/pkg/createcluster/create.go
Makes additional updates to the README file and fixes defaults for pull secret and ssh public key in the create-cluster command.
> Update README and hiveutil create-cluster defaults

- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/add_unreachable.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/controller/utils/utils.go
Adding unreachable = true as cluster deployment condition
if the cluster is unreachable for more than 2 hours
Co-authored-by: Devan Goodwin <dgoodwin@redhat.com>
Co-authored-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Adding unreachable controller

- Makefile
- README.md
- docs/developing.md
- hack/e2e-test.sh
Bypasses a ValidationError regarding unknown field "nullable" when
applying our CRDs.
> Use oc instead of kubectl in Makefile apply commands.

- pkg/controller/unreachable/unreachable_controller.go
> Don't update cd when unreachable cond is absent in reachable cluster

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/metrics/metrics.go
We've seen these get stuck in prod, metric keeps reporting a value, but
the cluster is long gone, and the problem will not correct itself until
hive pod is restarted at which point we no longer report.
Cannot reproduce, or say for sure why, but it's possibly a race
condition between the two places this metric was managed. This change
moves it to one controller, and makes sure we clear it if we process a
deleted cluster deployment that doesn't have our finalizer.
> Attempt at fixing stale deprovision underway metrics.

- Dockerfile
- Dockerfile.hivebase
to allow us to customize the base image, put a new Dockerfile containing the modifications hive wants so that this can be built by CI, and then used as hive's own base image
> add new custom base image

- pkg/controller/installlogmonitor/installlogmonitor_controller.go
This was reconciling on all configmaps and filtering down in the
reconcile loop, and logging a log entry for each. The configmaps used
for HA pod deployments are constantly updated leading to a steady stream
of reconciles and logging.
Reduce by filtering out any configmaps that do not look like hive
install log configmaps.
> Reduce configmap reconcile rate and logging.

- config/hiveadmission/deployment.yaml
- config/manager/deployment.yaml
- config/operator/operator_deployment.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/operator/assets/bindata.go
Drop operator and hiveadmission log levels. This isn't where the problem is but it will help a little.
> Less logging

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Removing the fixup code is causing imageset jobs to fail in updating the clusterdeployment status. Until we can figure out what is causing this, leave the fixup code in the controller.
> Revert ClusterDeployment fixup on clusterdeployment controller

- config/operator/operator_role.yaml
- config/rbac/hive_frontend_serviceaccount.yaml
- hack/generate-operator-bundle.py
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
We suspect bugs in OLM upgrades that are killing the service account.
> Take control of hive-frontend role and service account.

- config/crds/hive_v1alpha1_hiveconfig.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/hiveconfig_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/operator/assets/bindata.go
report a clusterdeployment condition when we are waiting for the dnszone to become ready
retport a metric recording how long we waited for the dnszone to become ready
> Dns condition

- OWNERS
> Adding LalatenduMohanty to owners

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
> CO-455 Send install job duration metric only for the first time install

- pkg/controller/syncset/syncset_controller.go
Fixes existing status entries with duplicate entries
> Remove duplicate syncset status entries

- config/hiveadmission/deployment.yaml
- pkg/controller/metrics/metrics.go
- pkg/operator/assets/bindata.go
- pkg/resource/helper.go
- pkg/resource/kubeconfig_factory.go
- pkg/resource/patch.go
- pkg/resource/restconfig_factory.go
This serves little purpose now that these features are developed and
deployed.
> Reduce metrics and resource apply logging.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
> Trivial changes to make code more readable

- README.md
- docs/FAQs.md
> Expanding the introduction and adding a FAQ doc

- config/clusterimagesets/openshift-4.0-latest.yaml
- hack/update-bindata.sh
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
> CO-458 Stop Deploying openshift-v4.0-latest in Hive operator

- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
Fixes invalid matching of original machine pool
> Fix validation check on machine pool mutation

- Makefile
- contrib/pkg/createcluster/create.go
- hack/e2e-test.sh
- test/e2e/common/clusterdeployment.go
- test/e2e/common/machine.go
- test/e2e/common/machineset.go
- test/e2e/common/node.go
- test/e2e/postinstall/machinesets/infra_test.go
Adds test to ensure we can create/delete additional machinesets
> E2E MachineSet post-install test

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
> Removing deadcode from controllers

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
https://jira.coreos.com/browse/CO-460
> Add regex for no matching route53 zone found.

- Makefile
- golangci.yml
> Adding golangci-lint to Makefile

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/resource/apply.go
> Fixing ineffectual assignment to errors

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
> Simplifying a conditional loop in cluster deployment controller

- docs/developing.md
- docs/install.md
The patch also contains for linting fixes
as per https://github.com/DavidAnson/vscode-markdownlint#rules
> Added steps to enable debug and more small enhancements

- docs/using-hive.md
> Adding documentation for global pull secret

- pkg/controller/remoteingress/remoteingress_controller.go
> Changing retry log to warning for ingress certficate bundle

- contrib/pkg/createcluster/create.go
> Making pull secret file and environment variable optional for hiveutil

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterversion/clusterversion_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/dnszone/test_helpers.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/controller/utils/utils.go
- pkg/imageset/generate_test.go
- pkg/install/convertconfig_test.go
- pkg/installmanager/installmanager_test.go
- pkg/operator/util/apply.go
> Fixing deadcode as per golangci lint issues

- config/crds/hive_v1alpha1_clusterdeployment.yaml
- config/crds/hive_v1alpha1_selectorsyncset.yaml
- config/crds/hive_v1alpha1_syncset.yaml
- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/apis/hive/v1alpha1/dnszone_types.go
- pkg/apis/hive/v1alpha1/machinepools.go
- pkg/apis/hive/v1alpha1/syncset_types.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
- pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
- pkg/controller/metrics/metrics.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/unreachable/unreachable_controller_test.go
- pkg/controller/velerobackup/clusterdeployment_test.go
- pkg/operator/assets/bindata.go
> Fixing spelling mistakes as part for golangci lint fixes

- contrib/cmd/hiveutil/main.go
- contrib/pkg/certificate/command.go
- contrib/pkg/certificate/create.go
- contrib/pkg/certificate/hook.go
- contrib/pkg/createcluster/create.go
- docs/developing.md
- hack/set-additional-ca.sh
- pkg/awsclient/client.go
- pkg/awsclient/mock/client_generated.go
Adds support for serving certs to the create-cluster command
Adds a new command to hiveutil to create a serving certificate through letsencrypt
> Certificate utility

- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
Whenever the serving cert secret is updated (as in renewal), we need
to let the Kube API server on the target cluster know so that the
new certs are applied. This fix uses a hash of all cert secrets
passed to the API server to set the value of the
"forceDeploymentReason" field on the KubeAPIServer resource on the
cluster.
> Force reloading of APIServer on certs change

- config/rbac/hive_frontend_role.yaml
- pkg/operator/assets/bindata.go
This pR allows the hive-frontend ServiceAccount to manage Events.
This is required for https://jira.coreos.com/browse/APPSRE-882
Please let us know if that is the correct way to achieve this.
Thanks!
> hive-frontend add events to role

- pkg/controller/utils/loggingeventhandler.go
I found this helpful when I was verifying some behavior. I though it might be nice to keep in our toolbox.
> wrapping around event handler that adds logging

- README.md
- docs/developing.md
- docs/quick_start.md
> Adding quick start documentation

- cmd/manager/main.go
- cmd/operator/main.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/installlogmonitor/installlogmonitor_controller.go
- pkg/controller/installlogmonitor/installlogmonitor_controller_test.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
> Use the updated global pull secret from hive config

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
> unit test improvments for TestMergePullSecrets

- pkg/controller/velerobackup/helpers_test.go
- pkg/controller/velerobackup/hiveobject.go
- pkg/controller/velerobackup/hiveobject_test.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
- pkg/test/dnszone/dnszone.go
> Create Velero backup object on dnszone change

- README.md
- docs/FAQs.md
- docs/architecture.md
- docs/using-hive.md
> Improve wording around Hive's config management in docs

- docs/using-hive.md
Could put these in separate variables but went with inline. Swapped `-d` for `--decode` for mac compatibility.
> Update using hive examples for grabbing secrets.

- pkg/operator/hive/hive_controller.go
The code to delete the legacy hiveadmission daemonset has been out on stage and production, so those daemonsets should no longer exist.
> remove deletion of legacy hiveadmission daemonset

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
https://jira.coreos.com/browse/CO-440
> Do not use DNS zone if not owned by clusterdeployment

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
This reverts commit 9bebf85494f901a6b5181510f7820c95548d65f3.
> Revert "create dummy clusterprovision for legacy clusterdeployment"

- docs/syncset.md
> Updating diagnosing-syncset-problems and adding an exampple of syncset

- pkg/controller/dnszone/zonereconciler.go
It will help getting more useful information in the controller logs
> Modifying some debug messages to info in dnszone controller

- pkg/installmanager/installmanager.go
Unclear why this is only surfacing now, but ssh-add can fail because the
ssh private key (mounted from a configmap) has insecure permissions. We
cannot chmod in a running pod, nor skip/disable that check.
Instead we'll copy to a file with 0600 permissions and use the copy with
ssh-add.
> Installmanager ssh private key permissions fix.

- pkg/controller/clusterstate/clusterstate_controller.go
> Adding check for unreachable condition

- config/crds/hive_v1alpha1_selectorsyncset.yaml
- config/crds/hive_v1alpha1_syncset.yaml
- config/crds/hive_v1alpha1_syncsetinstance.yaml
- pkg/apis/hive/v1alpha1/syncset_types.go
- pkg/apis/hive/v1alpha1/syncsetinstance_types.go
- pkg/operator/assets/bindata.go
> Adding shortname for syncsetinstance

- hack/e2e-test.sh
I'd like to be able to see exactly what images we were using and how we
generated the cluster deployment.
> Grab some additional yaml artifacts after e2e tests.

- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/remoteingress/remoteingress_controller_test.go
Last PR forgot remove the secret from clusteringress syncset.
> Remove secret from clusteringress syncset

- pkg/install/generate.go
From https://github.com/openshift/hive/pull/556#discussion_r328177056
> fix error message for deprovisioning unsupported platform

- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
SyncSetFailureCondition will be added if any SyncSet failed during application
> Adding SyncSetFailureCondition to cluster deployment

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
> handle nil worker machine platform in remotemachineset controller

- pkg/controller/dnszone/zonereconciler.go
This may be temporary but we have clusters stuck in this state and could
use some additional info.
> Bump to Info loglevel for DNS resolve checks.

- README.md
> Adding azure and gcp to the supported cloud platforms in readme

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
The clusterDeployment controller should not proceed with further reconcilation of a clusterdeployment if the controller finds that the clusterimageset is missing. Instead, the controller was stopping the first time when the condition was set indicating that the imageset is missing but was continuing on subsequent reconciliations since the clusterdeployment did not need to be modified in to set the condition after the first time.
> controller: stop cd reconcile on missing clusterimageset

- pkg/operator/hive/hiveadmission.go
Fixes blocker issue https://jira.coreos.com/browse/CO-595
> Removing outdated ValidatingWebhookConfigurations

- config/hiveadmission/clusterprovision-webhook.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hiveadmission.go
There is a validator for clusterprovisions, but it is not hooked up with an webhook. This adds that webhook.
> webhook for clusterprovision validator

- docs/install.md
updating the pre-reqs to include golang v1.12
> go lang in pre-reqs

- docs/using-hive.md
Fixed #609
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
> Add PersistentVolume in using hive section

- docs/using-hive.md
- use yaml keyword for yaml files
- remove `$` from the cli for easy copy.
/cc @LalatenduMohanty
> docs: consolidate using hive

- pkg/apis/hive/v1alpha1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
ref: https://jira.coreos.com/browse/CO-604
> Add cluster platform label to ClusterDeployment

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/install/generate.go
The legacy install jobs have all been deleted from stage and prod.
> controllers: remove code for deleting legacy install jobs

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
Reduce the severity of some error-level warnings in the syncsetinstance controller.
* When there are errors communicating with the remote cluster, logs those at the warning level.
* When the raw contents of a resource cannot be parsed, log that at the warning level.
* When a referenced secret cannot be found, log that at the info level.
* Remove the second log entry emitted when there is an issue updating the status of a syncsetinstance. The first log entry emitted will have either the error level or the info level depending upon what type of error it is.
> controllers: reduce level of some warnings in syncsetinstance controller

- OWNERS
> Adding staebler to the Owners file

- docs/using-hive.md
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
> Add ClusterImageSet example

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
https://jira.coreos.com/browse/CO-587
> Cleanup syncset secretreference secrets when ResourceApplyMode==Sync

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
Fix resync of Syncsets
@staebler  is this what you had in mind?
/cc @dgoodwin @abutcher
> fix resync

- docs/developing.md
> docs: Corrected aws environment var.

- docs/FAQs.md
> docs: Added syncset and seletorsyncset to FAQ.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
When an installation succeeds for a clusterdeployment, set the status fields in the clusterdeployment first and set the .spec.installed field last. This ensures that things like the kubeconfig are available when the clusterdeployment is marked as installed.
This was not done this way originally because the controller needed to accommodate legacy clusterdeployments that did not have a .spec.installed field. At this point, all clusterdeployments have the field and have it set appropriately.
> controllers: set .spec.installed last

- docs/developing.md
- hack/hiveadmission-dev-cert.sh
> docs: hiveadmission-dev-cert.sh request cfssl and cfssljson.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
save infra ID in Spec instead of Status
> save infra ID in Spec instead of Status

- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
- pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
make Provisioning and InstallConfigSecretRef.Name required
> make Provisioning and InstallConfigSecretRef.Name required

- Makefile
> Updated makefile by adding .PHONY for make target

- Makefile
- docs/syncset.md
- pkg/controller/dnsendpoint/nameserver/gcp.go
- pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
includes changes in (105cae8, a057c9f]
>  merge master into v1

- Makefile
use the latest from the v1 branch as the default deploy image to use
> v1 default deploy image

- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
- pkg/controller/dnsendpoint/nameserverscraper.go
- pkg/controller/dnsendpoint/nameserverscraper_test.go
includes changes in (a057c9f, 6231266]
> merge master into v1

- hack/e2e-test.sh
The e2e tests locally on kind fail because projects cannot be created on kind. Instead of creating a project, the tests need to create a namespace.
> e2e: use namespace instead of project

- config/rbac/hive_frontend_role_binding.yaml
- pkg/operator/assets/bindata.go
> hive-frontend ClusterRoleBinding fix

- config/rbac/hive_frontend_role_binding.yaml
- pkg/operator/assets/bindata.go
> fix hive-frontend ClusterRoleBinding

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
https://jira.coreos.com/browse/CO-660
> clear finalizer on machinepool when clusterdeployment deleted

- hack/scaletest/README.md
- hack/scaletest/syncset-template.yaml
- hack/scaletest/test_setup.sh
Not in perfect state but wanted to get the tooling involved committed so
we can evolve it over time as more tests are run.
> Add scripting and notes from first scale test.

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
https://jira.coreos.com/browse/CO-612
> Requeue successful ssi for resync.

- pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
https://jira.coreos.com/browse/CO-670
> fix machinepool validator so that validation is not skipped

- config/crds/hive_v1_selectorsyncset.yaml
- config/crds/hive_v1_syncset.yaml
- docs/syncset.md
- pkg/apis/hive/v1/syncset_types.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/operator/assets/bindata.go
https://jira.coreos.com/browse/CO-499
> Remove ApplyOnce PatchApplyMode.

- pkg/installmanager/installmanager.go
https://jira.coreos.com/browse/CO-656
The installer output was being redirected to a newly created file each time that the installer was executed via the runOpenShiftInstallCommand method. This changes the installmanager so that the destination file is appended instead of truncated, thus preserving the outputs for every installer execution.
https://jira.coreos.com/browse/CO-589
The full installer logs were being piped to the output of the container every time that the installer was executed via the runOpenShiftInstallCommand method. This changes the installmanager so that the piping is set up once at the start of the process instead of with each installer execution.
> installmanager: fix interactions with installer logs

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
There is currently no deprovision path for baremetal. Skip launching a
job so we don't need to manually remove finalizers for time being.
> Disable deprovision for baremetal clusters.

- contrib/pkg/createcluster/create.go
- pkg/install/generate.go
- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
- pkg/installmanager/testdata/install-config-with-existing-pull-secret.yaml
- pkg/installmanager/testdata/install-config-with-pull-secret.yaml
- pkg/installmanager/testdata/install-config.yaml
- pkg/installmanager/testdata/pull-secret.json
https://jira.coreos.com/browse/CO-678
> install: use merged pull secret in install-config

- docs/developing.md
Hi, some things I noticed trying to compile from scratch...  
The GOPATH one is important, I missed it for a long time because I _thought_ I'm in the right dir :smile:
> Tweaks to docs from trying to compile a fresh checkout

- pkg/controller/dnszone/awsactuator.go
The "id" field refers to the zone ID.
The "zone" field refers to the zone name.
https://jira.coreos.com/browse/CO-629
> make logger field names consistent in dnszone aws actuator

- pkg/hive/apis/hive/hiveconversion/conversion.go
The v1alpha1 HiveConfig only supports a single cloud for managed DNS. If the v1 HiveConfig has multiple entries in its .spec.managedDomains field, then the v1alpha1 update will lose all but one of the entries, even if the update was updating a different field. To prevent this, the v1alpha1 update will fail if the HiveConfig has multiple entries in its .spec.managedDomains field.
> apiserver: block v1alpha1 hiveconfig updates when multiple managed domains

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Adopted clusters do not have a ClusterProvision, but this code was the
only place we set Status.APIURL and Status.WebConsoleURL.
Will now ensure these are set even if the ClusterDeployment is marked
installed.
The ClusterProvision processing still has similar code just to avoid an
extra status update on intial processing of a completed install.
> Extract URLs from kubeconfig for adopted clusters without a provision.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
https://jira.coreos.com/browse/CO-418
> delete imageset job when completed 

- Gopkg.lock
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/controller/utils/utils.go
- pkg/installmanager/installmanager.go
- vendor/k8s.io/kubernetes/pkg/util/labels/doc.go
- vendor/k8s.io/kubernetes/pkg/util/labels/labels.go
> Add labels for syncsetinstance

- pkg/hive/apiserver/registry/clusterdeployment/proxy.go
- pkg/hive/apiserver/registry/clusterdeployment/watch.go
- pkg/hive/apiserver/registry/util/convert.go
Set the resource version of v1alpha1 clusterdeployment to be a hyphen-delimited concatenation of the resource versions from the v1 clusterdeployment, the install-config secret, and the v1 machinepools.
For example,
if the v1 clusterdeployment has a resource version of "cd",
the install-config secret has a resource version of "ic",
the worker machine pool has a resource version of "worker",
and the infra machine pool has a resource version of "infra",
then the resource version of the v1alpha1 clusterdeployment will be "cd-ic-infra-worker".
Note that the machine pool resource versions are ordered alphabetically by the name of the machinepools.
> apiserver: clusterdeployment resource version amalgamation

- contrib/pkg/v1migration/recreateobjects.go
When re-creating a v1alpha1 Hive resource, perform an update after the create so that the status is re-created as well.
> migration: restore status on re-create

- hack/v1migration/delete.sh
Replace uses of "-A" with "--all-namespaces".
Replace "oc delete -A" with a delete in each individual namespace.
> migration: support oc 3.11

- Dockerfile
> Switch to FROM centos:7 and restore libvirt dependencies.

- pkg/controller/remoteingress/remoteingress_controller.go
This was done to force the rollout of ingress config, which should no
longer be needed as of 4.2.0.
The code in question is now causing a problem for hive users who need to
adjust default router tolerations to land them on specific nodes, also
being done by syncsets, and now both syncsets are fighting for the
tolerations causing the pods to restart often, impacting running
services.
With this change, remoteingress will no longer work seamlessly on 4.1
OpenShift clusters, manual restarts may be required. We do not believe
this will impact many users as 4.2 and 4.3 are both available now.
> Remove now obsolete toleration edit in remoteingress controller.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
False when it should have been true.
> Fix missing ClusterImageSet condition.

- README.md
- docs/hiveutil.md
- docs/using-hive.md
docs: update using-hive.md for v1, add hiveutil doc
Fixes: https://github.com/openshift/hive/issues/780
Fixes: https://issues.redhat.com/browse/CO-715
> docs: update using-hive.md for v1, add hiveutil doc

- contrib/cmd/hiveutil/main.go
- contrib/pkg/labelobjects/labelobjects.go
- contrib/pkg/labelobjects/labelobjects_test.go
- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/utils/utils.go
- pkg/controller/velerobackup/velerobackup_controller.go
- pkg/controller/velerobackup/velerobackup_controller_test.go
- pkg/test/generic/generic.go
- pkg/test/job/job.go
- pkg/test/persistentvolumeclaim/persistentvolumeclaim.go
- pkg/test/secret/secret.go
> Migrate hive objects to have expected v1 labels

- docs/using-hive.md
- hack/get-kubeconfig.sh
This is something that I do often enough and that is a long enough command that I thought it would be beneficial to create a script for.
> hack: script for extracting the kubeconfig for a clusterdeployment

- hack/set-additional-ca.sh
address https://issues.redhat.com/browse/CO-797
> set the correct field name when adding additional CAs

- pkg/operator/hive/hive.go
Static list was often out of date and currently missing MachinePool.
Switch to reading all CRD files from the expected directory and applying
each.
> Dynamically apply all hive CRDs from the operator.

- pkg/installmanager/installmanager_test.go
Instead of looking for individual substrings in the cleaned text,
verify that the entire return value matches the expected value. This
makes future tests easier to add and makes the existing tests easier
to read.
> make log redaction tests more robust

- Gopkg.lock
- Gopkg.toml
- pkg/controller/remotemachineset/awsactuator.go
- vendor/github.com/openshift/installer/pkg/asset/machines/aws/machines.go
- vendor/github.com/openshift/installer/pkg/asset/machines/aws/machinesets.go
- vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
- vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
- vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
- vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
> backport Vendor no hosted zone fix

- docs/install.md
Fixes https://github.com/openshift/hive/issues/928
> docs: update install.md to reflect go1.13 requirement

- pkg/apis/hive/v1/machinepool_types.go
- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
For very limited use case and thus not a part of our official API at
this time.
/cc @jeremyeder @derekwaynecarr
> Add an unofficial MachinePool AMI override annotation.

- docs/using-hive.md
Fix `openshift container platform` image tag
> Fix ocp image tag

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Add some jitter to the time when a syncset will be requeued in order to be re-applied. The intention is to spread out the re-apply of syncsets so that there are not spikes in re-apply activity.
https://issues.redhat.com/browse/CO-871
> controller: add jitter to syncset re-apply

- config/crds/hive_v1_syncsetinstance.yaml
- pkg/apis/hive/v1/syncsetinstance_types.go
- pkg/operator/assets/bindata.go
It was setup partially, missing the bits in the CRD.
> Create 'Applied' print column for SSI

- pkg/apis/hive/v1/register.go
- pkg/controller/utils/ownership.go
- pkg/controller/utils/ownership_test.go
- pkg/test/generic/generic.go
> Fix label ownership apiversion bug

- pkg/version/version.go
fix typo in version log (openshfit -> openshift)
/cc @staebler
> fix typo in version log (openshfit -> openshift)

- hack/generate-operator-bundle-operatorhub.py
We removed the 'bundle' directory, so now create a temp directory
to write the bundle to. Also support specifying a bundle directory.
Add support for specifying the previous version in operatorhub mode.
/cc @dgoodwin
> generate-operator-bundle-operatorhub enhancements

- build/olm-registry/Dockerfile
- hack/generate-operator-bundle-operatorhub.py
- hack/olm-registry-deploy.sh
adapt olm-registry-deploy.sh to new generate-operator-bundle-operatorhub script and clean it up a bit.
the first commit is #972
/cc @dgoodwin
> adapt olm-registry-deploy.sh to new generate-operator-bundle-operatorhub script

- Dockerfile
let's get a passing security scan in quay.
/cc @dgoodwin
> Run a yum update during container builds.

- contrib/pkg/createcluster/create.go
- contrib/pkg/deprovision/azure.go
- contrib/pkg/utils/azure/azure.go
- contrib/pkg/utils/gcp/gcp.go
- contrib/pkg/utils/openstack/openstack.go
- docs/hiveutil.md
- pkg/constants/constants.go
Document Azure creds format, and make notes about how deprovisioning works for Azure.
Standardize reading in of Azure creds.
> standardize Azure creds handling

- pkg/controller/clusterprovision/clusterprovision_controller.go
Labelled by result which will allow us to monitor and possibly alert if
the percentage of failing cluster provisions over a window of time
exceeds some threshold.
> Add counter metric for completed cluster provisions.

- hack/app_sre_create_image_catalog.sh
> deploy: change production SHA retrieval to use new location

- docs/developing.md
> Add docs on how to vendor the installer.

- pkg/controller/velerobackup/velerobackup_controller.go
> restore behavior that disables velero by default

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
https://bugzilla.redhat.com/show_bug.cgi?id=1844320
> Add install log regex for unable to find matching route table.

- config/crds/hive.openshift.io_syncsetinstances.yaml
- pkg/apis/hive/v1/syncsetinstance_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
- pkg/operator/assets/bindata.go
Adds metrics `hive_syncset_apply_duration_seconds` and `hive_selectorsyncset_apply_duration_seconds`
> Add time to apply metrics for syncsets and selectorsyncsets

- pkg/controller/syncset/syncset_controller.go
This was (accidentally, we think?) removed via 70c7ae2e6e52ef493d6b6a487ca1d8c1aac6f927 in [#437](https://github.com/openshift/hive/pull/437/files#diff-6f5e4dec9c039eb5be5eed0036fc3604L170-L182)
> syncset controller: Restore reconcile duration metric

- pkg/resource/apply.go
Stop writing to a temp file when doing a resource apply.
> do not use temp file for resource apply

- pkg/controller/syncsetinstance/syncsetinstance_controller.go
- pkg/controller/utils/clientwrapper.go
hive_syncsetinstance_apply_duration_seconds - Histogram for the amount
of time to apply individual resources within all SyncSetInstances.
hive_syncsetinstance_resources_applied_total - Counter for the rate at
which we're applying individual resources.
hive_kube_client_request_seconds - Histogram for the amount of time to
make remote cluster API requests, similar to existing one for the rate
at which we're making them. Can be combined with the apply duration to
determine how much time we're spending CPU bound vs network bound.
> Add new metrics to evaluate syncsetinstance performance.

- go.sum
- pkg/apis/hive/v1/dnszone_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/dnszone/actuator.go
- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/azureactuator.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/dnszone_controller_test.go
- pkg/controller/dnszone/gcpactuator.go
Add AuthenticationFailure condition to dnszone controller
> Add AuthenticationFailure condition to dnszone controller

- pkg/controller/clusterversion/clusterversion_controller.go
In https://github.com/openshift/hive/pull/1041, the clusterversion controller was changed to set labels on the ClusterDeployment for the cluster version. However, the controller was not changed to do a regular update of the ClusterDeployment. The only update remained a Status update. The changes here separate the code to set the labels into a new function in which a regular update of the ClusterDeployment is executed if there are any changes to the labels.
https://issues.redhat.com/browse/CO-626
> fix update to set cluster version labels

- pkg/controller/dnszone/awsactuator.go
- pkg/controller/dnszone/awsactuator_test.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/dnszone/dnszone_controller_test.go
jira: https://issues.redhat.com/browse/CO-1064
> Fix insufficient credentials condition on ClusterDeployment

- hack/olm-registry/olm-artifacts-template.yaml
> add deleteProtection parameter to hiveconfig in olm template

- pkg/install/generate.go
- pkg/install/generate_test.go
> Add memory request to provisioning pod.

- cmd/manager/main.go
- config/controllers/service.yaml
- config/hiveadmission/deployment.yaml
- config/hiveadmission/service.yaml
- config/prometheus/prometheus-deployment-with-pvc.yaml
- contrib/pkg/createcluster/create.go
- docs/developing.md
- hack/create-kind-podman-cluster.sh
- hack/scaletest/README.md
- hack/scaletest/setup-selectorsyncsets.sh
- hack/scaletest/syncset-template.yaml
- hack/scaletest/test_setup.sh
- pkg/clusterresource/builder.go
- pkg/operator/assets/bindata.go
Various improvements for scale testing, updated instructions and observations. Details in individual commits.
> Scale testing improvements

- pkg/apis/hive/v1/clusterdeployment_types.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
Fix failure to set unsupported condition when no condition exists
Fixes https://issues.redhat.com/browse/CO-1095 and https://issues.redhat.com/browse/CO-1096
> Hibernation: set condition when failing to stop/start

- hack/olm-registry/olm-artifacts-template.yaml
Expose hiveAPIEnabled in hiveconfig template so it can be selectively
enabled and disabled.
/cc @staebler
> expose hiveAPIEnabled in hiveconfig template

- pkg/controller/dnszone/awsactuator.go
- pkg/installmanager/dnscleanup.go
- pkg/installmanager/installmanager.go
This reverts commit 65fb4af148ca96acae23681bb6865b2724cca417.
Causes a panic.
/cc @joelddiaz @akhil-rane
> Revert "pick one DNS cleanup codepath and use it everywhere"

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/remoteclient/remoteclient.go
Details in individual commits.
> Small fixes for issues found in the unreachable hotloop investigation

- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
For a new ClusterDeployment, the ClusterSync is created and then immediately updated with the status of applying any syncsets. If there were errors applying syncsets, then the clustersync controller may do its next reconcile using the created version instead of the updated version. When this happens, the update at the end of the reconcile will fail due to a conflict.
With these changes, when there is no ClusterSync, the clustersync controller will create the ClusterSync as the only thing that it does for the reconciliation. The clustersync controller will requeue the ClusterDeployment when the controller sees the new ClusterSync, and the controller will not get any conflicts when doing updates.
> controller: create clustersync as separate reconcile

- pkg/controller/hibernation/gcp_actuator.go
- pkg/controller/hibernation/gcp_actuator_test.go
- pkg/gcpclient/client.go
- pkg/gcpclient/mock/client_generated.go
Adds a GCP actuator to the hibernation controller
> Implement hibernation for GCP

- pkg/operator/hive/hive.go
Use the correct resource version when deleting SyncSetInstances.
> operator: fix cleanup of syncsetinstances

- pkg/controller/clustersync/clustersync_controller.go
With commit 0c17526e1ffc6f562c3b83d6d6e57588f0b245e6, the ClusterSync is created as a separate clustersync reconcile. However, the clustersync controller does not watch for changes to ClusterSync. Consequently, the syncsets are not applied to a new cluster until there is some later change to the ClusterDeployment or one of the syncsets. These changes will queue the ClusterDeployment when the ClusterSync is created.
> controller: fix syncset applies not going immediately after ClusterSync create

- contrib/pkg/deprovision/azure.go
With the latest version of the installer, the Azure destroyer needs to have the resource group set. These changes use the installer's
New function to create the destroyer. This will set the resource group to the default value of "${INFRA_ID}-rg".
https://issues.redhat.com/browse/CO-1142
> fix azure deprovision by implicitly setting resource group

- pkg/client/clientset/versioned/fake/register.go
- pkg/client/listers/hive/v1/checkpoint.go
- pkg/client/listers/hive/v1/clusterclaim.go
- pkg/client/listers/hive/v1/clusterdeployment.go
- pkg/client/listers/hive/v1/clusterdeprovision.go
- pkg/client/listers/hive/v1/clusterimageset.go
- pkg/client/listers/hive/v1/clusterpool.go
- pkg/client/listers/hive/v1/clusterprovision.go
- pkg/client/listers/hive/v1/clusterrelocate.go
- pkg/client/listers/hive/v1/clusterstate.go
- pkg/client/listers/hive/v1/dnszone.go
- pkg/client/listers/hive/v1/hiveconfig.go
- pkg/client/listers/hive/v1/machinepool.go
- pkg/client/listers/hive/v1/machinepoolnamelease.go
- pkg/client/listers/hive/v1/selectorsyncidentityprovider.go
- pkg/client/listers/hive/v1/selectorsyncset.go
- pkg/client/listers/hive/v1/syncidentityprovider.go
- pkg/client/listers/hive/v1/syncset.go
- pkg/client/listers/hiveinternal/v1alpha1/clustersync.go
- pkg/client/listers/hiveinternal/v1alpha1/clustersynclease.go
The generated client code is out-of-sync since the dependencies were updated in cbba83bcdec460352fc90abdfa7226adbdf72b1e.
> client: update generated code

- pkg/operator/hive/hive.go
Also, attempt to delete all SyncSetInstances in a batch regardless of whether there were errors deleting some of them.
> accept gone SyncSetInstance during cleanup

- pkg/installmanager/installmanager.go
As with df024bd7957fc800e363d7f24561ab862b5839cc, the Azure destroy in installmanager needs to include the resource group in the destroyer.
Additionally, the call to the destroyer Run that is repeated for every platform has been brought out of the switch.
https://issues.redhat.com/browse/CO-1142
> install: fix azure failed provision cleanup

- pkg/installmanager/dnscleanup.go
Check error creating azure client in DNS cleanup. Also, add consistent logging for AWS DSN cleanup;
> Check error creating azure client in DNS cleanup

- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
/assign @staebler 
/cc @dgoodwin
> CO-1187: Latest hive doesn't honor syncset-pause annotation

- README.md
- docs/hiveutil.md
- docs/using-hive.md
Jira: https://issues.redhat.com/browse/CO-1090
> Add docs for OpenStack

- pkg/controller/clustersync/clustersync_controller.go
Some SelectorSyncSet time to first apply metrics were abnormally large
as labels can be added to clusters long after they're installed,
resulting in a time to apply metric of install time -> now, which could
be days weeks or months.
Instead use the new "FirstSuccessTimestamp" on ClusterSync.Status. If we
see a first success for a SelectorSyncSet, but the FirstSuccessTimestamp
overall is set, we know this was a new match and thus we don't really
have an accurate start time, and the metric should be skipped.
/cc @staebler
> Stop reporting SelectorSyncSet metrics after initial sync success.

- docs/using-hive.md
update to aws cred section.  I left the yaml reference, but noted base64.
> aws cred update

- Dockerfile
- Dockerfile.dev
- build/build-image/Dockerfile
/assign @staebler 
/cc @dgoodwin
> change osd build to not use dockerhub part 2

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
Previously the hibernation controller would mark a ClusterDeployment with a condition indicating that hibernation was not supported (b/c the clusterversion had not yet become available). It would never clear the Unsupported condition once the ClusterDeployment was deemed to be hibernation-capable.
Detect and update the condition for this case.
> handle switch from unsupported to supported hibernation capability

- pkg/controller/utils/clientwrapper.go
Forgot to include the actual request time when logging the slow requests.
/assign @suhanime
> Include elapsedMillis when logging slow kube client requests.

- pkg/controller/metrics/provision_underway_collector.go
Update the metric to only use conditions if their status is true
indicating an unexpected state.
Add DNSNotReady at the start of the list, so that if this is true it is
the reason we report without checking the others.
Similarly reorder provision launch error as this is likely to surface
before an install failure.
/cc @twiest
> Report DNSNotReady in the cluster provisioning underway metric.

- docs/clusterpools.md
> Add note on what platforms are supported for ClusterPool.

- pkg/controller/metrics/provision_underway_collector.go
> Fix DNSNotReady+Unknown in provisioning delay alert.

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
In the event clusters fail to start (i.e. AWS instance capacity issues
we've seen the last few days), Hive will mark the Hibernation condition
reason FailedToStart, but then would stop all processing, there was no
way to get out of this state, or resume the cluster again.
This change adds the FailedToStart reason to the case where we continue
trying to start machines. If an error is encountered starting the
machines, we also now return this error from the controller, which gives
us the normal reconcile with backoff loop we want in a situation like
this.
In practice with the AWS capacity issues this week, this situation will
actually resolve itself fairly quickly if you keep trying.
/assign @twiest 
/cc @csrwng
> Fix resuming clusters that hit a FailedToStart issue.

- hack/scaletest/README.md
> Update scaletest readme with notes on HiveConfig and fake applies.

- hack/olm-registry/olm-artifacts-template.yaml
This is necessary in order to deploy S3 log uploading.
/assign @gregsheremeta 
/cc @joelddiaz
> Add FAILED_PROVISION_CONFIG param to hivconfig template.

- config/crds/hive.openshift.io_clusterpools.yaml
- contrib/pkg/clusterpool/clusterpool.go
- pkg/apis/hive/v1/clusterpool_types.go
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/controller/clusterpool/clusterpool_controller.go
> Add ClusterPool.Spec.HibernateAfter.

- README.md
> Add note for Office Hours

- config/clustersync/service.yaml
- config/clustersync/statefulset.yaml
- pkg/apis/hive/v1/zz_generated.deepcopy.go
- pkg/operator/assets/bindata.go
> Change hive-clustersync sts labels to match others

- docs/clusterpools.md
jira: https://issues.redhat.com/browse/CO-1280
> Add documentation for time-based scaling of clusterpool

- docs/syncset.md
> [DOC] Replace SyncsetInstance with ClusterSync in troubleshooting

- Dockerfile
- Dockerfile.dev
- Dockerfile.hivebase
- Makefile
- build/build-image/Dockerfile
- config/controllers/deployment.yaml
- config/hiveadmission/deployment.yaml
- config/operator/operator_deployment.yaml
- config/templates/cluster-deployment-customimageset.yaml
- hack/local-e2e-test.sh
- pkg/controller/images/controller_images.go
- pkg/operator/assets/bindata.go
QE reporting problems with the old registry, which appears to at the very least need auth now.
/assign @suhanime
> Move pullspecs to new openshift CI registry.

- pkg/controller/metrics/provision_underway_collector.go
Add InstallImagesNotResolved to provision underway collector
> Add InstallImagesNotResolved condition

- pkg/controller/remotemachineset/openstackactuator.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
> remotemachineset/openstackactuator.go: handle error when creating yamlOpts

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
> Add install log regex for GCPQuotaSSDTotalGBExceeded.

- docs/clusterpools.md
related to https://issues.redhat.com/browse/HIVE-1348
> clarify ClusterPool docs when using installConfigTemplate

- config/crds/hive.openshift.io_clusterclaims.yaml
- pkg/apis/hive/v1/clusterclaim_types.go
Allow oc get clusterclaim to show pending condition reason, cluster
namespace, and clusterrunning condition reason.
/cc @twiest
> Add some display columns for ClusterClaim.

- pkg/controller/utils/statefulset.go
- pkg/operator/hive/clustersync.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
> Delete clustersync sts when spec is changed

- pkg/controller/metrics/metrics.go
The OpenShift Dedicated SRE team would like to be alerted when a production ClusterDeployment has a `hive.openshift.io/syncset-pause="true"` annotation for some threshold duration.
This adds a new Prometheus metric to allow for such an alert.  It's essentially a boolean for each ClusterDeployment.
> metrics: Add metricClusterDeploymentSyncsetPaused

- pkg/installmanager/fake.go
> Add fake-cluster- prefix to fake cluster uid

- hack/regexes/additional-hive-regexes.yaml
Template to reference in app-interface.
> hive-1349: Add blank regex configmap template.

- hack/olm-registry/olm-artifacts-template.yaml
add controllersConfig section to template hiveconfig so the OSD pipeline can clustersync replicas to 3
/assign @twiest 
/cc @dgoodwin
> add controllersConfig section to template hiveconfig

- docs/using-hive.md
/assign @gregsheremeta 
/cc @dgoodwin
> document scaling clustersync controller

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
> HIVE-1387: Add regex for VpcLimitExceeded

- docs/cluster-relocation.md
Built off @staebler's comments in #1011.
Tested and still working. 
Would like to get some feedback from SRE on how they're linking their operators into this process, thus this is still a TODO in the doc.
/cc @abutcher 
@gregsheremeta do you know any names of folks working on this SRE side who you could ping here for feedback?
> Add some documentation around ClusterRelocate.

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
> Add regex definitions for this week's alerts

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
> Fix typo DNSZoneResoucreConflict -> DNSZoneResourceConflict

- pkg/controller/remotemachineset/gcpactuator.go
- pkg/controller/remotemachineset/gcpactuator_test.go
cc: @igoihman  @dgoodwin  @staebler  @gregsheremeta
> Add support for Subnet, and Network for GCP MachinePools

- OWNERS
> OWNERS update.

- docs/install.md
Warning on building your own OLM bundle (nobody uses this afaik, but I don't want to remove the docs on how to do it just incase)
/assign @gregsheremeta
> Update install instructions to point to community operatorhub releases.

- docs/install.md
Fix a sub-list that wasn't rendering properly.
> Tweak formatting in install.md

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
x-ref: https://issues.redhat.com/browse/HIVE-1463
> Add install log regex for invalid aws credentials

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/cleanup.go
> awsprivatelink: support assume role for user aws client

- hack/olm-registry/olm-artifacts-template.yaml
part of https://issues.redhat.com/browse/APPSRE-3165
follows up on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17259
> remove HiveConfig from template

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/machinemanagement/machinemanagement_controller.go
- pkg/controller/machinemanagement/machinemanagement_controller_test.go
https://issues.redhat.com/browse/HIVE-1412
also addresses https://issues.redhat.com/browse/HIVE-1458
/cc @suhanime
> Sync changes to managed secrets in cd namespace to target namespace.

- pkg/awsclient/client.go
Found some unused calls when going through the list of required AWS actions.
> Remove unused awsclient calls.

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/operator/assets/bindata.go
x-ref: https://issues.redhat.com/browse/HIVE-1411
> Add S3 Buckets Limit exceeded to install log regex

- config/configmaps/install-log-regexes-configmap.yaml
- go.sum
- pkg/awsclient/mock/client_generated.go
- pkg/operator/assets/bindata.go
also include some unrelated changes from running a 'make generate'
xref: https://issues.redhat.com/browse/HIVE-1488
> add regex to catch EIP Address limit exceeded

- Makefile
Give the option to build hive with buildah
> Re-add buildah build target for dev

- hack/regexes/additional-hive-regexes.yaml
> Remove configmap metadata.namespace and add eip regex for testing.

- pkg/operator/hive/hive_controller.go
When certain secrets referenced in HiveConfig change, the operator
should trigger the reconcile.
Currently only secrets in `spec.additionalCertificateAuthoritiesSecretRef`
support this behavior.
hive operator maintains an index of secrets referenced in HiveConfig
that can trigger reconcile. When the operator sees an update for these
secrets, it uses the index to trigger reconcile for the specific
HiveConfig.
/assign @dgoodwin @joelddiaz
> hive-operator: resync on changes to secrets in HiveConfig

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook_test.go
for platforms where this is supported
Update Webhook accordingly
Update remotemachineset controller to do more dynamic detection of
supportability.
xref: https://issues.redhat.com/browse/HIVE-1486
> allow setting zero minReplicas for autoscaling

- config/configmaps/install-log-regexes-configmap.yaml
- hack/regexes/additional-hive-regexes.yaml
- pkg/operator/assets/bindata.go
I also added the regex to the additional template which I'm testing in integration.
> HIVE-1498: Add InvalidInstallConfigSubnet install log regex.

- pkg/operator/hive/hiveadmission.go
There are certain contracts and their implementations that we know
are supported always. So we make sure these are allowed without the
discovery from CRDs.
> operator: support already known contracts

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
xref: https://issues.redhat.com/browse/HIVE-1517
/cc @jharrington22
> awsprivatelink: add Name tag to endpoint and endpoint service

- docs/enhancements/cluster-install-apis.md
- docs/enhancements/install-strategy.md
cc @abhinavdahiya @joelddiaz @mhrivnak @avishayt @filanov @romfreiman @jnpacker @csrwng @derekwaynecarr
> Add proposal for breaking out install strategy to separate CRDs.

- pkg/controller/fakeclusterinstall/fakeclusterinstall_controller.go
Per enhancement, the fake cluster install controller will now add an owner reference to itself indicating it is owned by it's ClusterDeployment. Used for cleanup.
> Add owner ref on FakeClusterInstall.

- docs/install.md
Signed-off-by: Mike Ng <ming@redhat.com>
A quick fix for the install doc HiveConfig yaml sample.
> doc fix for install.md - format HiveConfig yaml sample

- apis/hive/v1/hiveconfig_types.go
- pkg/constants/constants.go
- pkg/operator/add_hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/metrics/metrics.go
- vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Currently this controller only reports metrics for conditions
on HiveConfig. We can add more metrics in the future.
> Add metrics controller for hive-operator

- pkg/controller/remotemachineset/remotemachineset_controller.go
since we don't have watches on the remote clusters to trigger on changes
in MachineSets created for MachinePools, we need a way to periodically
sync the status for our objects.
this adds an periodic source for watch to the controller, that adds all
the MachinePools for reconcile every duration(30 minutes) with some
jitter.
xref:  https://issues.redhat.com/browse/HIVE-1511
xref: https://issues.redhat.com/browse/HIVE-1510
> remotemachineset: periodically reconcile MachinePools for update

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
> controller/clusterdeployment: rate limit updates to clusterdeployment because of error

- pkg/controller/dnszone/dnszone_controller.go
When DNS zone ends up in error state, the clusterdeployment controller
copies that error to the clusterdeployment status. This causes update on
the clusterdeployment object, in turn creating an update event for dns
zone created for the clusterdeployment. since watch from
clusterdeployments are not rate limited, this creates exceesive
reconciles.
To make sure the dnszone controller limits updates from dns error, we
must also rate limit dns error from clusterdeployment updates. so now
the controller uses the DNSNotReadyCondition to check if error
transitions is because of dns error and then rate limit it.
xref: https://issues.redhat.com/browse/HIVE-1553
/cc @dgoodwin @staebler
> controller/dnszone: rate limit update events from cd cause by dns error

- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
Often the machineset status does not include the errorReason,
errorMessage that would summarize failures in machines belonging to the
set. So the controller now uses the machineset's specified selector to
get machines and then collect the reason and messages for failed
machines.
xref: https://issues.redhat.com/browse/HIVE-1511
/cc @joelddiaz
> controller/remotemachineset: summarize failures from machines

- apis/hiveinternal/v1alpha1/clustersync_types.go
- config/crds/hiveinternal.openshift.io_clustersyncs.yaml
- docs/developing.md
- go.sum
- vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
Make `oc get clustersync` print the overall status and message.
[HIVE-1456](https://issues.redhat.com/browse/HIVE-1456)
> HIVE-1456: ClusterSync: Status & Message printer columns

- docs/using-hive.md
> add Azure examples to using-hive doc managed dns section

- apis/hive/v1/clusterdeployment_types.go
- config/crds/hive.openshift.io_clusterdeployments.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
x-ref: https://issues.redhat.com/browse/HIVE-1457
> Abandon deprovision for any cluster when preserveOnDelete is true

- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller_test.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/controller/utils/conditions.go
xref: https://issues.redhat.com/browse/HIVE-1556
/cc @dgoodwin
> Initialize clusterpool+clusterclaim conditions

- docs/enhancements/hivev2.md
Lay down the skeleton for an enhancement doc to collect ideas for v2 of the Hive API.
> Skeleton enhancement doc for Hive v2

- docs/awsprivatelink.md
Thank you for writing such awesome docs!
> Fix AWS docs link in privatelink doc

- Dockerfile
See: https://github.com/open-cluster-management/backlog/issues/13183
> Bump to RHEL8 in Dockerfile for libvirt dependencies.

- apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/metrics/metrics_test.go
- pkg/controller/utils/conditions_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Move to RequirementsMet with reason ClusterImageSetMissing.
x-ref: https://issues.redhat.com/browse/HIVE-1481
> Remove ClusterImageSetMissing condition.

- hack/e2e-test.sh
We have to do this in stages: Update this script such that it works for both existing and new prow job config; update prow config; clean up this script as necessary. In this stage:
- Tolerate a missing AWS creds file if the proper environment variables are set. (For now, we have to use those env vars to generate the creds file; left a TODO to fix that up.)
- Tolerate a missing SSH pubkey file, generating a keypair in this case.
- Detect provisioning failures when they happen, rather than timing out after `installed` fails to appear for 90m.
- Remove some unnecessary variable `export`ing. Just because it bothered me, not because it has any effect.
> Update e2e-test.sh for ClusterPools (step 1)

- apis/hive/v1/clusterdeployment_types.go
- apis/hive/v1/hiveconfig_types.go
- cmd/manager/main.go
- config/crds/hive.openshift.io_hiveconfigs.yaml
- pkg/constants/constants.go
- pkg/controller/argocdregister/argocdregister_controller.go
- pkg/controller/argocdregister/argocdregister_controller_test.go
- pkg/controller/argocdregister/argotypes.go
- pkg/operator/hive/hive.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
- vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
> Add argocdregister controller.

- pkg/clusterresource/builder.go
- pkg/clusterresource/builder_test.go
Feel free to close if there's a better solution :) 
fixes #1435
> fix panic when metadata is nil

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
This commit enables hibernating or running fake clusters instead of
skipping them. Hibernating condition and cluster powerstate for fake
clusters can now be toggled based on hibernation controller logic.
xref: https://issues.redhat.com/browse/HIVE-1573
/cc @abhinavdahiya
> Simulate hibernation for fake clusters

- docs/developing.md
- docs/using-hive.md
- pkg/remoteclient/remoteclient.go
x-ref: https://issues.redhat.com/browse/HIVE-1566
> Document cluster adoption

- hack/logextractor.sh
This PR adds an optional `--backplane` argument to the `logextractor.sh` helper script. This option is intended to assist people in using the script in Hive environments where actions such as retrieving the S3 bucket secret are normally restricted.
> Add optional backplane escalation for logextractor.sh

- Dockerfile
- apis/go.mod
- build/build-image/Dockerfile
- go.mod
- vendor/github.com/openshift/hive/apis/go.mod
[HIVE-1579](https://issues.redhat.com/browse/HIVE-1579)
> Build against go 1.16

- README.md
> Remove Office Hours

- pkg/controller/clusterclaim/clusterclaim_controller_test.go
We were skipping some chunks of TestReconcileClusterClaim if the claim was deleted. However, there are still things we should be checking in that case -- like the state of the assigned ClusterDeployment. Tweak the test driver to support this.
> Tighten TestReconcileClusterClaim

- pkg/controller/remotemachineset/awsactuator.go
- pkg/controller/remotemachineset/awsactuator_test.go
Currently the discovery codepath only decides whether a subnet is public
by using the routetables.
There are many network deployments which do not directly attach an igw
to the public subnet, but usage of these subnets is clearly defined by
the user by tagging these subnets with PublicSubnetTagName. So it
would be benefitial if the discovery codepath respect the indication on
the public subnets set by the admins of the cluster.
Similarly the aws-load-balancer-controller [1] now solely depends on
PublicSubnetTagName to discover the public subnets for ELB.
In this change, we update the isSubnetPublic function such that when it
fails to decide that a subnet is public using route table rules, if
checks if the subnet has the PublicSubnetTagName, and if the tag exists
and equal to empty("") and …
> remotemachineset: aws: fallback to using kubernetes.io/role/elb tag for public subnets when route tables are not enough

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
As a part of previous change to support hibernation for fake clusters,
it was found that
- some spec and/or status updates were missing
- code coverage for hibernation due to powerstate change (and not
hibernateafter) was missing
- switching to running condition from initialized hibernation condition
was not covered
This commit rearranges some code to resolve the above stated bugs
xref: https://issues.redhat.com/browse/HIVE-1585
/cc @abhinavdahiya
> Hibernation bug with fake clusters

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Second attempt was still bad if the objects were already deleted, the code path was skipped. :(
/cc @suhanime
> Fix transfer of PreserveOnDelete to DNSZone when deleted.

- docs/using-hive.md
Signed-off-by: Sho Weimer <sweimer@redhat.com>
> MachinePool documentation updates

- hack/e2e-common.sh
We've been intermittently seeing this flake in e2e:
`time="2021-08-26T18:12:59Z" level=fatal msg="error updating HiveConfig" error="Operation cannot be fulfilled on hiveconfigs.hive.openshift.io \"hive\": the object has been modified; please apply your changes to the latest version and try again"`
Add a dumb retry around enabling managed DNS.
> e2e: Add retry for managed DNS

- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
https://issues.redhat.com/browse/HIVE-1636
> HIVE-1636: Make ClusterDeployment metal platform agentSelector field mutable

- go.mod
- go.sum
- vendor/github.com/miekg/dns/.travis.yml
- vendor/github.com/miekg/dns/CODEOWNERS
- vendor/github.com/miekg/dns/acceptfunc.go
- vendor/github.com/miekg/dns/edns.go
- vendor/github.com/miekg/dns/fuzz.go
- vendor/github.com/miekg/dns/generate.go
- vendor/github.com/miekg/dns/labels.go
- vendor/github.com/miekg/dns/msg.go
- vendor/github.com/miekg/dns/scan.go
- vendor/github.com/miekg/dns/version.go
- vendor/modules.txt
CVE-2019-19794 https://github.com/advisories/GHSA-44r7-7p62-q3fr
> Update github.com/miekg/dns dep

- docs/enhancements/cluster_pool_hot_spares.md
At the last minute we decided to change where `ClaimedTimestamp` lived.
Update the RFE doc for posterity.
[HIVE-1576](https://issues.redhat.com/browse/HIVE-1576)
> Update hot spares RFE

- hack/bundle-gen.py
Add some logic to map whatever branch you specify to the right
- commit to build from
- semver prefix
- channel(s) to update
Plus a bit of general cleanup/refactoring.
[HIVE-1604](https://issues.redhat.com/browse/HIVE-1604)
> bundle-gen: smart branch/channel detection

- apis/hive/v1/azure/platform.go
- apis/hive/v1/clusterdeprovision_types.go
- apis/hive/v1/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_clusterdeployments.yaml
- config/crds/hive.openshift.io_clusterdeprovisions.yaml
- config/crds/hive.openshift.io_clusterpools.yaml
- contrib/pkg/deprovision/azure.go
- hack/app-sre/saas-template.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/install/generate.go
- pkg/installmanager/installmanager.go
- vendor/github.com/openshift/hive/apis/hive/v1/azure/platform.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
- vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
https://issues.redhat.com/browse/HIVE-1638
/cc @joelddiaz
> HIVE-1638: Add cd.Spec.Platform.Azure.CloudName and plumb into deprovision.

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
best to review commit by commit
/cc @yithian
> More install log regexps

- hack/bundle-gen.py
With this update, you can specify any commit-ish to `--branch` and we
will go look for `ocm-X.Y` branches on that commit. If we find any,
we'll add them to the list of channels to update. However, we'll error
if there's more than one and you're not tracking master, because then we
wouldn't know what semver prefix to use.
This also fixes a bug whereby we would erroneously update the `alpha`
channel if you specified an ocm branch that was a direct descendant of
`master`.
To summarize, assume the following (contrived) tree:
```
*  efef5656 (ocm-2.6, master)
*  cdcd3434 (ocm-2.4, ocm-2.5)
| * abab1212 (ocm-1.10, ocm-2.3)
| * 0101fafa (ocm-2.2)
|/
*
|
...
```
| `--branch`                               | Version       | Channels         |
| ---------------------------------------- | …
> bundle-gen: Discover ocm-* branches, fix alpha

- hack/bundle-gen.py
...in the package.yaml file.
[HIVE-1604](https://issues.redhat.com/browse/HIVE-1604)
> bundle-gen: Another missing 'v'

- hack/e2e-pool-test.sh
We were frequently flaking because a controller would revert our status update to set ProvisionStopped to True. Do that in the wait loop so it'll be sure to stick at some point.
> e2e-pool: Broken cluster flake

- hack/bundle-gen.py
> bundle-gen: Ensure working in hive clone when generating bundle.

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
Adds 'TooManyRoute53Zones' install error
> Add error when Route53 zone limits are exceeded 

- apis/hive/v1/hiveconfig_types.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
x-ref: https://issues.redhat.com/browse/HIVE-1663
> Remove AlphaAgentInstallStrategy feature gate

- hack/app_sre_build_deploy.sh
...and repair a latent brace snafu
> Fix podman auth file path

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
see https://coreos.slack.com/archives/CCX9DB894/p1639325596354000
> Add install error regex for AWSEC2QuotaExceeded

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
> add install log regexp for bootstrap failed

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
> add install log regexp for route53 timeout

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Our previous test returned a nil value for the error received from validating credentials which made it seem like we would always set an auth failure condition in the code we were testing. We actually just logged the error and returned. The auth condition will now be set and a reconcile error will be returned after (and when) the condition has been set.
> HIVE-1465: VMware x509 error is not reflected in ClusterDeployment

- hack/bundle-gen.py
> Update bundle-gen.py to support docker

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
add the known installation issue for [OSD-9693](https://issues.redhat.com/browse/OSD-9693) [OSD-9695](https://issues.redhat.com/browse/OSD-9695) and [OSD-9694](https://issues.redhat.com/browse/OSD-9694)
> add regex for known installation issues

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
Relates to: [OSD-9818](https://issues.redhat.com/browse/OSD-9818)
> Add regex for AWS NLB creation installation failure

- pkg/controller/clusterpool/clusterpool_controller.go
The clusterpool controller sorts unclaimed clusters when deciding which
to make Running to satisfy `runningCount` and/or pending claims.
Generally we want FIFO behavior, so the primary sort is by
`creationTimestamp`. However, since that has a granularity of 1s, it is
possible for multiple CDs to have the same value, leading to
nondeterministic sorting on each reconcile and potential "thrashing" of
running-ness.
With this commit, we add a secondary sort by CD namespace and name to
force the sort to be deterministic.
[HIVE-1747](https://issues.redhat.com/browse/HIVE-1747)
> ClusterPool: Secondary sort by ns/name for running

- docs/developing.md
Update "developing" documentation to reflect new golang version requirements and the added `mockgen` requirement.
> Update developing documentation

- hack/bundle-gen.py
Last week I needed to work around a temporary upstream problem by using
a different base image in the Dockerfile. However, since bundle-gen
clones the hive repo from GitHub, I would have needed to commit and
merge that Dockerfile change, which would not be appropriate.
With this commit, bundle-gen accepts an optional `--hive-repo` parameter
allowing you to clone from something other than the default
(github/openshift/hive). In this case I used it to clone from a local
directory in which I had made the temporary Dockerfile update.
This has the ancillary benefit of allowing you to save time by pointing
to a local clone (but be careful that it's up to date!).
> bundle-gen: Support overriding hive repo to clone

- hack/bundle-gen.py
Pick up some bundle-gen features from master:
- Create new channel for first push from a new branch
- `--hive-repo` arg
> Backport bundle-gen

- docs/hiveutil.md
Update the docs accordingly
[HIVE-1772](https://issues.redhat.com/browse/HIVE-1772)
> hiveutil is for internal use only

- hack/bundle-gen.py
We've just started a new branch naming scheme for MCE (multi-cluster
engine), handled by the same team and processes as the `ocm-X.Y`
branches. The new branches will be named `ocm-X.Y-mce-M.N`, e.g.
`ocm-2.5-mce-2.0`. These will generate OperatorHub bundles with semver
base `X.Y` for channels named `mce-X.N`.
Note that bundle-gen still needs to understand `ocm-X.Y` branches for
backports.
[HIVE-1775](https://issues.redhat.com/browse/HIVE-1775)
> bundle-gen: Understand MCE branches

- docs/using-hive.md
> Adds a bit more clarity on required permissions

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/ibmcloud_actuator.go
- pkg/controller/hibernation/ibmcloud_actuator_test.go
- pkg/ibmclient/client.go
- pkg/ibmclient/mock/client_generated.go
This change implements hibernation for IBM Cloud.
[HIVE-1623](https://issues.redhat.com/browse/HIVE-1623)
/hold
for testing
> [HIVE-1623] IBMCloud: Hibernation

- test/e2e/postdeploy/hivecontroller/manager_test.go
[HIVE-1788](https://issues.redhat.com/browse/HIVE-1788)
> e2e: Retry on failure to reach metrics endpoint

- apis/hive/v1/aws/machinepool.go
- apis/hive/v1/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_machinepools.yaml
- hack/app-sre/saas-template.yaml
- vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
- vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
[HIVE-1765](https://issues.redhat.com/browse/HIVE-1765)
> Make EC2RootVolume.IOPS an optional field.

- contrib/pkg/deprovision/ovirt.go
- pkg/installmanager/installmanager.go
[HIVE-1786](https://issues.redhat.com/browse/HIVE-1786)
> Set RemoveTemplate=true for oVirt deprovision.

- pkg/constants/constants.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
[HIVE-1792](https://issues.redhat.com/browse/HIVE-1792)
> Set ovirt cd platform label.

- apis/go.mod
- apis/go.sum
- apis/vendor/github.com/gogo/protobuf/proto/text_parser.go
- apis/vendor/modules.txt
> Update gogo/protobuf vendored dep

- pkg/controller/machinepool/awsactuator.go
- pkg/controller/machinepool/awsactuator_test.go
Generate AWS MachineSets with an AMI tag reference (to match the master machine) and no longer error when an AMI ID is not set for master machines.
[HIVE-1770](https://issues.redhat.com//browse/HIVE-1770)
> Detect when master machine references AMI by tag.

- pkg/awsclient/client.go
- pkg/awsclient/mock/client_generated.go
- pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
- pkg/controller/awsprivatelink/vpcinventory.go
xref https://issues.redhat.com/browse/HIVE-1806
> Use proper pagination for VPC endpoint retrieval

- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/machinepool/machinepool_controller.go
- pkg/controller/utils/conditions.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/util/conditions.go
Just like 2c00f88d9 / #1761, but for the other controllers similarly
affected.
[HIVE-1873](https://issues.redhat.com//browse/HIVE-1873)
> Fix condition initialization for other controllers

- pkg/controller/machinepool/machinepool_controller.go
The "normal" machinepool controller flow does all the things, and then
at the end checks whether the machinepool is deleted. If so, it removes
the finalizer and bails.
For fake clusters, we are bailing before "all the things". But we were
not deleting the finalizer in that case.
To make fake clusters behave more like real clusters, this commit adds
finalizer removal to the fake cluster flow.
> machinepool: remove finalizer for fake CD

- pkg/controller/clustersync/clustersync_controller_test.go
In #1541 / ec0ea846 I worked around some floating point weirdness by
hacking together a rounding function for a test assertion. I since
learned about `assert.InDelta`, which is made for this purpose. Replace
hack with real thing.
> clustersync UT: Use assert.InDelta instead of hack

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
xref: https://issues.redhat.com/browse/HIVE-1904
> Add SCACertPullFailed to install log regex search

- pkg/clusterresource/builder.go
This field is not omitempty from upstream and an empty install config object cannot be unmarshalled by the installer in previous versions.
> Patch installconfig generated by clusterresource builder to remove AWS metadataService field.

- build/build-image/Dockerfile
> Trigger CI to update to go 1.18

- pkg/controller/hibernation/hibernation_controller.go
Fetching cluster deployment conditions returns a pointer, and that
pointer is subject to change as other controllers update the CR, and
those conditions get sorted into a different order.
A bug was caught while testing powerstate transitioning metrics, where,
by the time we reported the hibernation transition metric, the ready
condition was pointing to some other condition of cluster deployment.
This commit ensures that before reporting the metric, we re-fetch the
relevant condition
xref: https://issues.redhat.com/browse/HIVE-1630
> Ensure correct time reported for transition metrics

- go.mod
- go.sum
xref https://issues.redhat.com/browse/HIVE-1923
> Exclude old etcd dependency to remove potential security hazard

- hack/bundle-gen.py
Add support to hack/bundle-gen.py for generating bundle files locally,
from an arbitrary commit. The result is *not* a real OLM bundle; this is
explicitly for the case where hive is to be packaged into a larger
deliverable (specifically MCE). Of note, this option does not:
- Try to compute a real `version`. The `name` and `version` fields in
the CSV should be seen as placeholders, to be supplanted by the
consuming packaging.
- Build/push operator images.
- Talk to OperatorHub to a) calculate graph data (e.g. `replaces`), or
b) open PRs.
Example usage below. Note that the argument to `--dummy-bundle` can be
any commit-ish recognized by git, including a raw SHA.
```
[efried@efried hive]$ ./hack/bundle-gen.py --dummy-bundle origin/ocm-2.4
Cloning git@github.com:openshift/hive.git to …
```
> bundle-gen: Add --dummy-bundle COMMIT-ISH (for MCE)

- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
While checking for cluster operators, we always assume we would have
encountered WaitingForNodes, however that is not necessary as we could
have requeued for some other reason after machines were running, and by
the time we check, the nodes could have already been ready.
Allow for the clusteroperator check to proceed for other states as well, 
like StartingMachines or WaitingForMachines.
xref: https://issues.redhat.com/browse/HIVE-1948
> Don't rely on WaitingForNodes

- apis/hive/v1/clusterdeployment_types.go
- config/crds/hive.openshift.io_clusterdeployments.yaml
- hack/app-sre/saas-template.yaml
- pkg/remoteclient/dialer.go
- pkg/remoteclient/dialer_test.go
- pkg/remoteclient/mock/remoteclient_generated.go
- pkg/remoteclient/remoteclient.go
- pkg/remoteclient/remoteclient_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Addresses remaining points from this comment: https://github.com/openshift/hive/pull/1817#pullrequestreview-1043467943
> Azure private endpoint support - follow-up

- apis/hive/v1/clusterdeployment_types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
xref: https://github.com/openshift/hive/pull/1820#discussion_r926123103
> Minor cleanup (in a test) related to generics 

- docs/hiveutil.md
- docs/using-hive.md
[HIVE-1871](https://issues.redhat.com//browse/HIVE-1871)
> Document Azure platform cloudName within usage and hiveutil docs.

- pkg/controller/argocdregister/argocdregister_controller.go
- pkg/controller/awsprivatelink/awsprivatelink_controller.go
- pkg/controller/clusterclaim/clusterclaim_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterstate/clusterstate_controller.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clusterversion/clusterversion_controller.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/dnsendpoint/dnsendpoint_controller.go
- pkg/controller/dnszone/dnszone_controller.go
- pkg/controller/fakeclusterinstall/fakeclusterinstall_controller.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/machinepool/machinepool_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
- pkg/controller/unreachable/unreachable_controller.go
- pkg/controller/utils/delayingreconciler.go
- pkg/controller/velerobackup/velerobackup_controller.go
xref: https://issues.redhat.com/browse/HIVE-1895
> Add DelayingReconciler to delay 403 requeues

- docs/using-hive.md
> Document how to create vSphere CA certificate secret.

- Makefile
- hack/e2e-common.sh
- Make hive-operator use `debug` log level
- Save the HiveConfig
> Couple of e2e FFDC improvements

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
We stopped using a PVC to store install logs via #1189 / cb5142fd. These
functions were left around to clean up PVCs on installs that had used
this mechanism previously. It has been ~20mo, which should be long
enough for that to have happened in any reasonable deployment. Resolve
the TODOs and clean up the functions.
> Tech Debt: Remove install log PVC functions

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/asset/installconfig/gcp/validation.go
- vendor/github.com/openshift/installer/pkg/asset/installconfig/vsphere/validation.go
- vendor/github.com/openshift/installer/pkg/types/nutanix/platform.go
- vendor/modules.txt
Revving for Nutanix `PrismElement.Name` field. 
/hold
> Rev installer vendor to release-4.11@25aa6a4

- contrib/pkg/createcluster/create.go
- pkg/clusterresource/alibabacloud.go
- pkg/clusterresource/builder.go
- pkg/clusterresource/ibmcloud.go
[HIVE-2030](https://issues.redhat.com//browse/HIVE-2030)
> Plumb --credentials-mode-manual into cloud builder.

- config/clustersync/statefulset.yaml
- config/controllers/deployment.yaml
- config/hiveadmission/deployment.yaml
- config/operator/operator_deployment.yaml
- hack/app-sre/saas-template.yaml
- pkg/controller/utils/utils.go
- pkg/imageset/generate.go
- pkg/imageset/generate_test.go
- pkg/install/generate.go
- pkg/install/generate_test.go
- pkg/operator/assets/bindata.go
- pkg/test/assert/assertions.go
Conform to new pod security admission rules.
[HIVE-2023](https://issues.redhat.com//browse/HIVE-2023)
> Explicit pod security

- docs/enhancements/scale-mode.md
Propose a design to teach hive to be able to scale to O(100k) spoke
clusters.
[HIVE-1862](https://issues.redhat.com//browse/HIVE-1862)
> Design doc for "Scale Mode"

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/clusterinstalls.go
[HIVE-1957](https://issues.redhat.com/browse/HIVE-1957)
[HIVE-2010](https://issues.redhat.com/browse/HIVE-2010)
> Fix logic for ClusterInstall/ClusterDeployment condition reconciliation

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
xref: https://issues.redhat.com/browse/HIVE-2036
> Stop provisioning if fatal DNSZone conditions are met

- contrib/pkg/utils/generic.go
- pkg/awsclient/client.go
- pkg/controller/dnsendpoint/nameserverscraper.go
- pkg/operator/hive/configmap.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterdeploymentcustomization_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterimageset_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterpool_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/dnszone_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/selector_syncset_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/syncset_validating_admission_hook.go
[HIVE-2034](https://issues.redhat.com//browse/HIVE-2034)
> Restore some weird formatting done by go fmt due to indentation levels.

- pkg/controller/clustersync/clustersync_controller.go
xref: https://issues.redhat.com/browse/HIVE-2038
> Watch for ClusterSyncLease and renew if it is missing

- hack/e2e-common.sh
- hack/e2e-test.sh
- Add a wait for the target namespace to appear when we change it
- Dump validating webhook configs, service, and apiservice manifests on cleanup
> e2e enhancements

- docs/install.md
To line up with the bullet points the examples live under.
/assign @suhanime
> Indent a few docs/install.md examples.

- OWNERS
> OWNERS: add jstuever

- pkg/controller/clusterrelocate/clusterrelocate_controller.go
- pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
Starting in k8s 1.21, the kube-controller-manager (and presumably OpenShift's fork thereof) creates/reconciles `kube-root-ca.crt` and `openshift-service-ca.crt` ConfigMaps in every namespace. On relocate, as we're copying objects, we'll try to copy these from the source to the destination cluster, fail because the object (with the same name) already exists, try to delete it, and then race with the kcm trying to create it again. If the relocate controller loses the race, it'll fail the relocate and try again. It might succeed eventually if it wins the race, but in at least one case (see associated issue/card) it never won.
With this commit, we ignore these two ConfigMaps, based on their names (hardcoded).
[HIVE-2080](https://issues.redhat.com//browse/HIVE-2080)
closes #1932
> Relocate: Ignore kube-controller-manager .crt ConfigMaps

- docs/scaling-hive.md
- docs/using-hive.md
[HIVE-2091](https://issues.redhat.com//browse/HIVE-2091)
> Document HiveConfig.Spec.DeploymentConfig

- apis/hive/v1/clusterdeployment_types.go
- pkg/controller/hibernation/hibernation_controller.go
- pkg/controller/hibernation/hibernation_controller_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
xref: https://issues.redhat.com/browse/HIVE-2134
> Improve PowerState status for Deprovisioned ClusterDeployments

- cmd/manager/main.go
This reverts commit bccc16d57c1075ad58386f25e074fbf3fb148f8f.
The changes in #1957 have produced several heap artifacts, and as such we can revert these changes.
/cc @abutcher
> Revert #1957

- Makefile
- hack/bundle-gen.py
Potential fix for "too many open files"
> Set ulimit for buildah image build.

- apis/helpers/namer_test.go
I noticed this while working on #1976 and felt it was worth a separate PR. On current latest commit (52f2706d1f70f6bfc1ac13a68b5fb80e544be387), this is quite repeatable with:
```shell
cd ./apis
go test -race -count 50 -run TestGetName ./helpers
```
There was a bug when shortName happened to be generated as a string
of length >= 246 as the test would expect that shortName + "-deploy"
did not exceed 253 characters and was not truncated. However, the 
test previously randomly generated a shortName of length [1, 253),
which causes this test to flake and fail occasionally.
This commit creates a shortBase that at maximum is the longest
possible base that has room for a hash so that it will never be
truncated.
> Fix  flaky `TestGetName`

- pkg/controller/metrics/metrics.go
xref: https://issues.redhat.com/browse/HIVE-2191
> Report time since DeletionTimestamp for deprovision metric

- hack/bundle-gen.py
- hack/version.py
xref: https://issues.redhat.com/browse/HIVE-2145?filter=-1
> Refactor bundlegen script

- docs/hive_metrics.md
Document the metrics that are reported by all Hive Controllers.
Also includes minor updates/corrections.
> Add generic controller metrics

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
In [HIVE-2198](https://issues.redhat.com//browse/HIVE-2198) / #1999 / 253408ed8 we started injecting a ConfigMap containing a CA bundle for better proxy support. Alas, we were only injecting it in the provisioning path. For hives that never had the earlier code, this probably would have been fine, as the ConfigMap would continue to exist until the cluster was deleted, whereupon it could properly be mounted on the deprovisioning pods. But for spokes that existed prior to upgrading to that code, and which were never re-reconciled before they were deleted (or, conceivably, if a user deleted the ConfigMap at some point in there) the ConfigMap would not exist, resulting in mount failures attempting to bring up the deprovisioning pods.
This commit moves the ConfigMap injection earlier in the …
> Ensure hive-trusted-cabundle earlier

- config/configmaps/install-log-regexes-configmap.yaml
- pkg/controller/clusterprovision/installlogmonitor_test.go
- pkg/operator/assets/bindata.go
It can happen that AWS is blocking an account so the installation will fail.
> [OSD-16302] Add new install failure for blocked AWS account.

- config/hiveadmission/deployment.yaml
- pkg/operator/assets/bindata.go
xref: https://issues.redhat.com/browse/HIVE-2212
> Require TLS cipher min version TLSv1.3

- pkg/controller/machinepool/machinepool_controller.go
- pkg/controller/machinepool/machinepool_controller_test.go
This leaves ``ClusterAutoscaler`` with its existing configuration in case it's already defined in the cluster.
Creation of the object with the same defaults will still take place as before, in case cluster still doesn't have it defined.
Closes [HIVE-2220](https://issues.redhat.com//browse/HIVE-2220)
> Skip configuring CA when object already exists

- docs/clusterpools.md
Describe what happens when a ClusterPool is deleted.
[HIVE-1557](https://issues.redhat.com//browse/HIVE-1557)
> ClusterPool: Document deletion behavior

- hack/bundle-gen.py
Validate that the image indicated by `--image-repo` and `--image-tag-override` (both of which may be defaulted/computed) exists in the repo.
- We only validate `quay.io/*` images.
- You may bypass validation by specifying the new `--skip-image-validation` flag.
[HIVE-2202](https://issues.redhat.com//browse/HIVE-2202)
> bundle-gen: Validate image

- config/templates/hive-csv-template.yaml
xref: https://issues.redhat.com/browse/HIVE-2135
> Update OperatorHub CSV

- cmd/manager/main.go
- docs/developing.md
[HIVE-2244](https://issues.redhat.com//browse/HIVE-2244)
> Serve pprof for hive-controllers, hive-clustersync

- hack/bundle-gen.py
xref: https://issues.redhat.com/browse/HIVE-1658
> Change bundle-gen.py to account for new bundle format

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
Deleting a namespace containing a ClusterDeployment and its associated artifacts results in an impossible situation: the deletion of the ClusterDeployment wants to trigger a deprovision, but we cannot create the necessary artifacts (e.g. ClusterDeprovision CR, deprovision Pod) in a namespace that is terminating. We have logic to skip deprovisioning and simply leak the cloud resources in this case.
...but we forgot to incorporate this logic for the hive-trusted-cabundle ConfigMap (introduced by https://github.com/2uasimojo/hive/commit/253408ed8ecdab5a7f3510a7f573db51008d6486 / https://github.com/openshift/hive/pull/1999), and would hot-loop attempting and failing to create it, never reaching the aforementioned "give up" logic, resulting in wedging the namespace. This commit adds the logic, …
> Skip hive-trusted-cabundle ConfigMap creation on deleted ns

- pkg/remoteclient/remoteclient.go
When ClusterDeployment.Spec.ControlPlaneConfig.APIServerIPOverride is in use, we experience the memory leak described by
https://github.com/kubernetes/kubernetes/issues/118703. That issue has not been resolved at the time of this writing, but describes a couple of workarounds. Try the one described in [this comment](https://github.com/kubernetes/kubernetes/issues/118703#issuecomment-1595072383):
> For now, I would probably just set the Proxy func to
> utilnet.NewProxierWithNoProxyCIDR(http.ProxyFromEnvironment) so that
> the TLS cache is skipped for your code. This isn't guaranteed behavior
> and may stop working at any time, but it will at least solve the issue
> for you for now (by restoring the old behavior).
[HIVE-2272](https://issues.redhat.com//browse/HIVE-2272)
> Work around upstream memory leak with APIServerIPOverride

- docs/syncset.md
Add words describing the order in which SyncSets and SelectorSyncSets are applied. I got tired of looking this up in the code.
> syncset.md: Describe ordering

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
When retrofitting cd.spec.clusterMetadata.platform.aws.hostedZoneRole (see #2100), we need to initialize the parent structures only once we know we're going to be setting the hostedZoneRole field. Otherwise, if parsing the install-config fails for some reason, we may end up trying to Update() the cd with that `aws` section empty, which is forbidden by webhook.
Turns out we also made this mistake when setting the azure resourceGroupName as well (see #1997). Fix.
[HIVE-2297](https://issues.redhat.com//browse/HIVE-2297)
> Initialize clusterMetadata as late as possible

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
Continuation of #2100: Add unit tests.
[HIVE-2297](https://issues.redhat.com//browse/HIVE-2297)
> Tests for AWS shared VPC HostedZoneRole

- test/e2e/postinstall/syncsets/syncsets_suite_test.go
We've recently seen more than one occurrence of 409 conflict flakes in this test suite, where a previously-retrieved instance of ClusterDeployment had a stale resourceVersion by the time it was Update()d back to the server.
This commit adds a RetryOnConflict wrapper around both Update()s in this test, which should hopefully reduce errors to "real" ones.
[HIVE-2294](https://issues.redhat.com//browse/HIVE-2294)
> e2e: syncset test: retry on conflict

- pkg/controller/metrics/metrics.go
- pkg/controller/metrics/metrics_test.go
xref: https://issues.redhat.com/browse/HIVE-2313
Add label in order to count number of CDs with a given powerState.
> Add powerState label to metricClusterDeploymentsTotal

- apis/hive/v1/gcp/machinepools.go
- config/crds/hive.openshift.io_machinepools.yaml
- hack/app-sre/saas-template.yaml
- pkg/controller/machinepool/gcpactuator.go
- pkg/controller/machinepool/gcpactuator_test.go
- vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
[HIVE-2261](https://issues.redhat.com//browse/HIVE-2261)
> MachinePool: Add GCP SecureBoot

- pkg/controller/metrics/metrics.go
[HIVE-2313](https://issues.redhat.com/browse/HIVE-2313)
> Ensure stale cluster deployment metrics are not reported

- docs/using-hive.md
Add words to the adoption section of using-hive.md describing the things you can do with an adopted cluster.
[ACM-7498](https://issues.redhat.com//browse/ACM-7498)
[HIVE-2338](https://issues.redhat.com//browse/HIVE-2338)
> Beef up adoption docs

- .snyk
Silence errors in [apis/]vendor and *_test.go
> Snyk Code: Set up some exclusions

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
Followon from #2151/#2153/#2154.
[HIVE-2334](https://issues.redhat.com//browse/HIVE-2334)
> UT for GCP Network Project ID

- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
- pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
This reverts commit a41c8ae0fc558d3d02dddede7ba2fa7997d4b1d3.
> Revert "TEMPORARY! Disable ClusterMetadata mutability webhook"

- apis/hive/v1/hiveconfig_types.go
- apis/hive/v1/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_hiveconfigs.yaml
- hack/app-sre/saas-template.yaml
- pkg/client/applyconfiguration/hive/v1/controllerconfig.go
- pkg/operator/hive/clustersync.go
- pkg/operator/hive/configmap.go
- pkg/operator/hive/hive.go
- vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
- vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
xref: [HIVE-2410](https://issues.redhat.com//browse/HIVE-2410)
> HIVE-2410: Add config for controller memory requests and limits

- pkg/controller/clustersync/clustersync_controller_test.go
- pkg/test/syncset/syncset.go
Address a couple of minor review comments from #2192
[HIVE-1748](https://issues.redhat.com//browse/HIVE-1748)
> Syncset parameters: Review followup

- .tekton/hive-pull-request.yaml
- .tekton/hive-push.yaml
The backslash escaping was wrong.
> HIVE-2509: Add missing backslash escaping

- hack/grafana-dashboards/grafana-dashboard-hive-slo.configmap.yaml
Update the prod datasource from Hive SLO dashboard
> Update prod datasource

- apis/hiveinternal/v1alpha1/clustersync_types.go
- contrib/pkg/adm/managedns/enable.go
- contrib/pkg/testresource/command.go
- contrib/pkg/utils/generic.go
- pkg/controller/clustersync/clustersync_controller.go
- pkg/controller/clustersync/clustersync_controller_test.go
- pkg/controller/controlplanecerts/controlplanecerts_controller.go
- pkg/controller/remoteingress/remoteingress_controller.go
- pkg/operator/hive/hive_controller.go
- pkg/remoteclient/fake.go
- pkg/remoteclient/kubeconfig.go
- pkg/remoteclient/mock/remoteclient_generated.go
- pkg/remoteclient/remoteclient.go
- pkg/resource/helper.go
- pkg/resource/restconfig_factory.go
- vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
This reverts commit 110c817776fa2d3892dabcdfdde6b7d43e36320e. (#2246)
> NOISSUE: Revert "Reuse restConfigClientGetter when creating cmdutil.Factory" (HIVE-2399)

- cmd/manager/main.go
[HIVE-2535](https://issues.redhat.com//browse/HIVE-2535)
> Plumb HiveConfig logLevel into controller manager

- hack/app_sre_build_deploy.sh
In order to be able to pull certain images, we need to have access to the registries that the build nodes are already authenticated to.
> app-sre-build: preserve original regitry creds

- pkg/controller/utils/statefulset.go
- pkg/operator/hive/sharded_controllers.go
- pkg/test/machinepool/machinepool.go
Minor fixups from #2341.
[HIVE-2537](https://issues.redhat.com//browse/HIVE-2537)
> FUP: Minor updates from sharding machinepool controller

- apis/hive/v1/clusterpool_types.go
- apis/hive/v1/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_clusterpools.yaml
- hack/app-sre/saas-template.yaml
- pkg/clusterresource/builder.go
- pkg/controller/clusterpool/clusterpool_controller.go
- pkg/controller/clusterpool/clusterpool_controller_test.go
- pkg/test/clusterpool/clusterpool.go
- vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
- vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Add ClusterPool.Spec.InstallerEnv for passthrough to ClusterDeployment.Spec.Provisioning.InstallerEnv.
[HIVE-2564](https://issues.redhat.com//browse/HIVE-2564)
> ClusterPool: Enable InstallerEnv

- .tekton/hive-mce-26-pull-request.yaml
- .tekton/hive-mce-26-push.yaml
- Dockerfile
- Makefile
This PR backports #2367 and #2348 to finally have a healthy Konflux build for the mce-2.6 branch
> Konflux fix backport 2.6

- apis/hiveinternal/v1alpha1/clustersync_types.go
- config/crds/hiveinternal.openshift.io_clustersyncs.yaml
- hack/app-sre/saas-template.yaml
- vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
Before:
```
$ oc get clustersync -A
NAMESPACE   NAME           STATUS
foo         bar            Success
one         two            Success
```
After:
```
$ oc get clustersync -A
NAMESPACE   NAME           STATUS    CONTROLLERREPLICA
foo         bar            Success   1
one         two            Success   0
```
[HIVE-2556](https://issues.redhat.com//browse/HIVE-2556)
> Add ControllerReplica printColumn to clustersync

- docs/clusterpools.md
- docs/troubleshooting.md
[HIVE-2598](https://issues.redhat.com//browse/HIVE-2598)
> Document ClusterPool troubleshooting

- hack/e2e-common.sh
This is the hive side of [HIVE-2270](https://issues.redhat.com/browse/HIVE-2270), which must be merged prior to its corresponding PR in the release repo. Adds support for vsphere platform in e2e tests, utilizing necessary environment variables gathered from the ci-operator workflow.
> Add e2e support for vsphere

- docs/syncset.md
It was very non-obvious how `[Selector]SyncSet.Spec.ApplyBehavior` affected clustersync behavior. See the attached card for a fun exploration of this rabbit hole.
[HIVE-2577](https://issues.redhat.com//browse/HIVE-2577)
> Document SyncSet ApplyBehavior

- docs/syncset.md
A recent update (#2442 / 0a7edb0c) added some documentation for [Selector]SyncSet `applyBehavior`, but missed some details. Enhance.
[HIVE-2577](https://issues.redhat.com//browse/HIVE-2577)
> Update syncset doc for applyBehavior

- pkg/controller/privatelink/actuator/awsactuator/awshubactuator.go
Prior to this change, the AWS hub actuator used the first VPC in the list of associatedVPCs when creating the DNS hosted zone. However, if that VPC was in a different account, this caused an error due to permissions.
This change modifies the behavior so that it selects the EndPoint VPC when on AWS. Otherwise, it selects the first VPC that is in the same account. It also modifies the deletion behavior to only look for the hosted zone in VPCs that use the same account. As a result, at least one item must be added to the list of associatedVPCs that either has no credentails specified, or uses the same secret as the primary account.
> OCPBUGS-41370: PrivateLink AWS hub actuator to select a vpc in the hub account.

- pkg/azureclient/client.go
Installer accepts azure creds (osServicePrincipal.json) with case-insensitive keys, but previously we were parsing them into a generic map and extracting the values by exact (case-sensitive) keys.
This commit switches from generic map to the installer-provided Credentials struct. This makes the unmarshalling case-insensitive.
[ACM-14248](https://issues.redhat.com//browse/ACM-14248)
> Azure: make creds case-insensitive

- pkg/controller/clusterdeployment/clusterinstalls.go
When reconciling a ClusterInstall, we may need to update both the spec and the status of the ClusterDeployment, and those need to be done in separate operations (because subresource). If both succeed, great. If the first fails, fine -- we'll requeue and try the whole thing again. But if the first succeeds and the second fails, we need to make sure we're in a state where the subsequent reconcile will still retry it.
Prior to this commit, we were doing the spec update first. In a normal sequence, this would set cd.Spec.Installed to true, which would activate a branch on the subsequent reconcile that would skip the routine that would have retried the status update.
This commit swaps the order -- we do the status update first -- based on the fact that the affected fields have no effect on the …
> ACM-13064: ClusterInstall: Idempotence improvements

- pkg/controller/clusterversion/clusterversion_controller.go
We recently (#2467) added a tunable poll interval for the clusterversion controller. However, we were being too nice about unparseable values, ignoring them and reverting to the default behavior. With this change, we'll crash the controller instead. The pod will go into Error (or CrashLoopBackoff eventually) with a message telling you what you did wrong.
[HIVE-2619](https://issues.redhat.com//browse/HIVE-2619)
> clusterversion controller: crash on unparseable poll interval

- pkg/controller/machinepool/machinepool_controller.go
Previously we enqueued all MachinePools every $pollInterval, which would result in a sudden glut of activity.
With this change, we instead use `RequeueAfter: $pollInterval + jitter` (random 0-1s jitter) so these requeues spread out over time.
[HIVE-2542](https://issues.redhat.com//browse/HIVE-2542)
> MachinePool controller: use RequeueAfter for poll interval

- Makefile
In #2481 / 6bb17298 we started getting the controller-gen tool by compiling and installing it from the vendor directory. But the method used there assumed that the resulting binary would end up in the user's `$PATH`, which is not necessarily the case.
With this change, we:
- Use `go list` to discover where the controller-gen binary will be installed; and use this full path when invoking it.
- Treat the controller-gen binary as a proper `make` build target: make it dependent on its source so that it will only be rebuilt if necessary.
[HIVE-2626](https://issues.redhat.com//browse/HIVE-2626)
> controller-gen: proper building and pathing

- pkg/controller/machinepool/machinepool_controller.go
In #2469 / 376de427 we switched to using `requeueAfter` for the poll interval for MachinePools. But we missed the bespoke code path for fake clusters. Fix.
Resolving this involved a refactor which _should_ have no direct impact other than now managing the `"hive.openshift.io/remotemachineset"` finalizer, which was heretofore always absent from fake clusters' MachinePools.
[HIVE-2542](https://issues.redhat.com//browse/HIVE-2542)
> MachinePool poll interval for fake clusters

- docs/scaling-hive.md
Comb through scaling-hive.md and tweak the language/links to reflect the current architecture, where both the clustersync and machinepool controllers are split into their own horizontally-scalable StatefulSets.
[HIVE-2039](https://issues.redhat.com//browse/HIVE-2039)
> Update scaling doc for clustersync/machinepool sharding

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
...for https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOLANGJWTJWTV4-8341242
[HIVE-2654](https://issues.redhat.com//browse/HIVE-2654)
> Bump jwt/v4 to 4.5.1

- apis/hive/v1/openstack/machinepools.go
- apis/hive/v1/openstack/zz_generated.deepcopy.go
- config/crds/hive.openshift.io_machinepools.yaml
- hack/app-sre/saas-template.yaml
- pkg/controller/machinepool/openstackactuator.go
- vendor/github.com/openshift/hive/apis/hive/v1/openstack/machinepools.go
- vendor/github.com/openshift/hive/apis/hive/v1/openstack/zz_generated.deepcopy.go
xref: [HIVE-2637](https://issues.redhat.com//browse/HIVE-2637)
> HIVE-2637: Add new API field AdditionalSecurityGroupIDs for OpenStack machine pools

- go.mod
- go.sum
- vendor/github.com/sirupsen/logrus/README.md
- vendor/github.com/sirupsen/logrus/writer.go
- vendor/modules.txt
For https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSIRUPSENLOGRUS-5564391
[HIVE-2657](https://issues.redhat.com//browse/HIVE-2657)
> Upgrade logrus to 1.9.3

- apis/hive/v1/openstack/machinepools.go
- config/crds/hive.openshift.io_machinepools.yaml
- hack/app-sre/saas-template.yaml
- vendor/github.com/openshift/hive/apis/hive/v1/openstack/machinepools.go
xref: [HIVE-2637](https://issues.redhat.com//browse/HIVE-2637)
> HIVE-2637 followup doc change

- docs/hiveutil.md
> Update hiveutil doc: make build-hiveutil

- .tekton/hive-mce-27-pull-request.yaml
- .tekton/hive-mce-27-push.yaml
- Dockerfile
Make the configs match `master`, mostly.
[HIVE-2780](https://issues.redhat.com//browse/HIVE-2780)
> konflux/mce-2.7: fix konflux configs

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/google/default.go
- vendor/golang.org/x/oauth2/google/externalaccount/aws.go
- vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
- vendor/golang.org/x/oauth2/jws/jws.go
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/modules.txt
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594
> HIVE-2787: CVE-2025-22868 x/oauth2/jws 0.27.0

- pkg/controller/machinepool/machinepool_controller.go
We were checking for OCP versions >=4.7.x to determine whether zero minimum replicas are allowed for autoscaling. That version is long out of service. Remove the obsolete code.
> HIVE-2791: MachinePool/OpenStack: Remove obsolete version check

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
xref: [ACM-18777](https://issues.redhat.com//browse/ACM-18777)
> ACM-18777: Cleanse metadata.json on the ClusterProvision object

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
xref: [ACM-18776](https://issues.redhat.com//browse/ACM-18776)
> ACM-18776: Cleanse metadata.json on the ClusterProvision object

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
xref: [ACM-18784](https://issues.redhat.com//browse/ACM-18784)
> ACM-18784: Cleanse metadata.json on the ClusterProvision object

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
xref: [ACM-18780](https://issues.redhat.com//browse/ACM-18780)
> ACM-18780: Cleanse metadata.json on the ClusterProvision object

- pkg/installmanager/installmanager.go
- pkg/installmanager/installmanager_test.go
xref: [ACM-18787](https://issues.redhat.com//browse/ACM-18787)
> ACM-18787: Cleanse metadata.json on the ClusterProvision object

- renovate.json
...per https://konflux.pages.redhat.com/docs/users/faq/general-questions.html#i-dont-want-konflux-to-update-my-dependencies-i-just-want-the-basics-how-can-i-do-that
> HIVE-2826: Limit konflux bot PRs to tekton

- pkg/controller/awsprivatelink/awsprivatelink_controller.go
**Issue:**
https://issues.redhat.com/browse/HIVE-2838
When there are many VPC endpoints associated with a cluster, AWS may paginate the response to `DescribeVpcEndpoints`. In some cases, AWS returns an empty first page (no `VpcEndpoints`) with a NextToken, which is highly unintuitive.
Example returned data:
```
{
NextToken: "eyJ2IjoiM<snip>="
}
```
Hive currently does not handle pagination in this code path. As a result:
- we falsely assume no VPC endpoint exists
- we create a new endpoint unnecessarily
This results in leaked VPC endpoints. We believe the reason for having so many VPCE in the first place is another bug ([HIVE-2837](https://issues.redhat.com/browse/HIVE-2837)), where rejected connections are leaked by hive.
**Proposed fix:**
This PR adds proper pagination support when …
> fix(HIVE-2838): privatelink-controller: paginate retrieved vpc endpoints

- .tekton/hive-pull-request.yaml
- .tekton/hive-push.yaml
Why doesn't the bot do this for me?
> Migration fixups

- pkg/controller/machinepool/nutanixactuator.go
- pkg/controller/machinepool/nutanixactuator_test.go
When autoscaling was enabled on Nutanix `MachinePools` with failure domains, no `MachineSets` were generated, breaking autoscaling functionality.
**Root Cause**: The [upstream installer's Nutanix code](https://github.com/openshift/installer/blob/184b556d7c4840eb5100c669ca1393532d1ea800/pkg/asset/machines/nutanix/machinesets.go#L37-L39) skips MachineSet generation when `pool.Replicas` is `nil` (which happens with autoscaling pools):
```go
// vendor/github.com/openshift/installer/pkg/asset/machines/nutanix/machinesets.go:36-37
if numOfMachineSets > total {  // e.g., 3 failure domains > 0 replicas
numOfMachineSets = total   // becomes 0, no MachineSets created
}
```
Modified the Nutanix actuator to temporarily set appropriate replica count during MachineSet generation:
- Calculate …
> HIVE-2860: Fix Nutanix generate `MachineSets` for autoscaling `MachinePools`

- pkg/controller/machinepool/machinepool_controller.go
- pkg/controller/machinepool/machinepool_controller_test.go
Fix `NotEnoughReplicas` condition not being cleared when switching from autoscaling to fixed replicas.
The `ensureEnoughReplicas` function wasn't properly clearing the `NotEnoughReplicas` condition when a `MachinePool` transitioned from autoscaling mode to having sufficient fixed replicas. 
This fix ensures the condition is cleared when autoscaling is disabled and replica count meets requirements.
Includes unit tests to verify proper condition management across autoscaling transitions.
/cc @2uasimojo
> HIVE-2860: Fix `ensureEnoughReplicas` to properly clear `NotEnoughReplicas` condition 

- config/controllers/hive_controllers_serviceaccount.yaml
- config/hiveadmission/service-account.yaml
- hack/app-sre/kustomization.yaml
- hack/app-sre/saas-template.yaml
- pkg/operator/assets/bindata.go
Corresponding app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/150878 
Relevant docs: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/make-registry-private.md
> Add quay.io image pull secret to app-sre service account

- config/controllers/hive_controllers_serviceaccount.yaml
- config/hiveadmission/service-account.yaml
- config/operator/operator_deployment.yaml
- hack/app-sre/saas-template.yaml
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
- pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
- pkg/controller/clusterprovision/clusterprovision_controller.go
- pkg/controller/clusterprovision/clusterprovision_controller_test.go
- pkg/controller/utils/podconfig.go
- pkg/controller/utils/utils.go
- pkg/imageset/generate.go
- pkg/imageset/generate_test.go
- pkg/install/generate.go
- pkg/install/generate_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/hive/hive.go
- pkg/operator/hive/hive_controller.go
- pkg/operator/hive/hiveadmission.go
- pkg/operator/hive/sharded_controllers.go
xref: [HIVE-2891](https://issues.redhat.com//browse/HIVE-2891)
(previous PR #2724 referenced wrong branch)
> HIVE-2891: Make hive able to run as a private image
